### ISSUE TITLE
Allow Panel serve and panel.serve to use the same port

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1076]
#### My Pain

I have started using `panel.serve` and its great. But now I wan't to run my apps on a specific port and the way I would have expected it to work causes errors.

I would have expected everything to be served on the one port I specify. Either via `panel serve --port` or `panel.serve(..., port=..)`. But it turns out that two ports are actually involved. Thats confusing and friction.

#### Example 1

```python
import panel as pn

APP_ROUTES = {"app1": pn.pane.Markdown("# App1"), "app2": pn.pane.Markdown("# App2")}

pn.serve(APP_ROUTES, port=14033)
```

usage I try to start the server with `--port 14033` and then open `http://localhost:14033/issue_ports`

```bash
$ panel serve "issue_ports.py" --port 14033
2020-02-06 10:59:38,034 Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
2020-02-06 10:59:38,036 User authentication hooks NOT provided (default user enabled)
2020-02-06 10:59:38,045 Bokeh app running at: http://localhost:14033/issue_ports
2020-02-06 10:59:38,045 Starting Bokeh server with process id: 10672
2020-02-06 10:59:44,162 Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
2020-02-06 10:59:44,175 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x000000B48D1E2E48>: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
File "netutil.py", line 174, in bind_sockets:
sock.bind(sockaddr) Traceback (most recent call last):
  File "c:\users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\Users\masma\source\repos\orsteddcsmarketsanalytics\api\scripts\issue_ports.py", line 5, in <module>
    pn.serve(APP_ROUTES, port=14033)
  File "c:\users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\panel\io\server.py", line 132, in serve
    **kwargs)
  File "c:\users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\panel\io\server.py", line 194, in get_server
    server = Server(apps, port=port, **opts)
  File "c:\users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\bokeh\server\server.py", line 393, in __init__
    sockets, self._port = bind_sockets(self.address, self.port)
  File "c:\users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\bokeh\server\util.py", line 66, in bind_sockets
    ss = netutil.bind_sockets(port=port or 0, address=address)
  File "c:\users\masma\source\repos\orsteddcsmarketsanalytics\api\.venv\lib\site-packages\tornado\netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

2020-02-06 10:59:44,655 WebSocket connection opened
2020-02-06 10:59:44,657 ServerConnection created

Interrupted, shutting down
(.venv)
MASMA@PC70601 MINGW64 /c/Users/masma/source/repos/orsteddcsmarketsanalytics/api/scripts (master)
```
#### Example 2

I start it without a port but then both port 5006 and 14033 are in play.

```bash
$ panel serve "issue_ports.py"
2020-02-06 11:00:00,819 Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
2020-02-06 11:00:00,821 User authentication hooks NOT provided (default user enabled)
2020-02-06 11:00:00,826 Bokeh app running at: http://localhost:5006/issue_ports
2020-02-06 11:00:00,827 Starting Bokeh server with process id: 10024
2020-02-06 11:00:06,085 Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
2020-02-06 11:00:06,087 User authentication hooks NOT provided (default user enabled)
2020-02-06 11:00:07,054 WebSocket connection opened
2020-02-06 11:00:07,055 ServerConnection created
```

![image](https://user-images.githubusercontent.com/42288570/73926857-9ea17400-48d0-11ea-9004-7031e3823d5d.png)

#### Solution

Enable use of one port only. And enable the user to specify the port on the command line or in the file.

#### Additional Context

I can live with the second example. But I spent some time on understanding it. So it's some friction related to using Panel.

**Comment by philippjfr** [comment]
I'm a bit confused here, are you starting a server with `panel serve` which calls `pn.serve` internally, because that's definitely not intended. `pn.serve` already starts a server so there's no need to use `panel serve` to launch that script, you should just run it with `python issue_ports.py`

**Comment by MarcSkovMadsen** [comment]
Ahh. I'm the one whos confused here by `panel serve`, `panel.serve` and `panel.servable`. :-)

I was also wondering why `panel serve` and `panel.serve` where that similar and had to be combined. I was just not able to think that I could/ should run panel without `panel serve` and I thought `panel.serve` was some new functionality added to serve multiple apps via `panel serve`.

Going back to the Reference Guide with what I now know I can see that the `panel serve` command is first mentioned after `panel.serve` and thus implicitly I guess that users would know that `panel.serve` is to be run by a normal `python` command?`

**Can I provide all the arguments of `panel serve` to `panel.serve`. For example `dev` and `num_procs`?** If I can then I can do everything I wan't in python (except [Issue 1075](https://github.com/holoviz/panel/issues/1075))

### Additional Context - My Use Case

- I would expect to have a growing number of apps I would like to serve as independent apps developed by different people/ teams.
- I would like to be able to serve them at an endpoint I specify like `/book` and /book/list`. See [Issue 1075](https://github.com/holoviz/panel/issues/1075)
- I would like to define a custom template for the root url instead of the default one. 
    - It would contain some "welcome" information and a menu system using the same Template as the other apps.
- Ideally I would like to configure the routing and the apps in python. That's why I chose `pn.serve`. And because I expect there to be many later on. (Just like gallery of awesome-panel.org).
- I would like to be able to use the options from the `panel serve` command line including `--dev` and `--num-procs`.

**I guess what is possible is constrained by what is possible in Bokeh?** https://docs.bokeh.org/en/latest/docs/reference/command/subcommands/serve.html

**Comment by MarcSkovMadsen** [comment]
And my requirement is especially to be able to set `--port` to `0.0.0.0` as this will be running in a docker container.

**Comment by MarcSkovMadsen** [comment]
Closing this one as the requirement as it is not very clear that the original request turned into a new request in the post just above.

I've created a new more specific feature request here https://github.com/holoviz/panel/issues/1364

**Comment by mhangaard** [comment]
I am curious what the conclusion was on this issue. Can I run `panel serve` and still configure routes in the python code?
