### ISSUE TITLE
DatePicker widget raises ValueError when date is selected

### ISSUE THREAD

**Issue by Jhoan1970** [holoviz/panel#1173]
Well, like the title says, selecting a date from a DatePicker widget raises a ValueError, previously I hadn't this issue, however I updated panel from 0.8 to 0.9.1 and now i have this problem.

Here is some code:

    >>> import panel as pn
    >>> pn.__version__
    '0.9.1'
    >>> app = pn.widgets.DatePicker()
    >>> app.show()
    Launching server at http://localhost:38785
    WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.36ms

Until this point there are no problems, but as soon as I select any date this error raises:

    ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f6c21de5d90>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py:51> exception=ValueError("time data '-03-20' does not match format '%b %d %Y'")>)
    Traceback (most recent call last):
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 195, in with_document_locked
    return func(*args, **kwargs)
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1164, in wrapper
    return doc._with_self_as_curdoc(invoke)
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1150, in _with_self_as_curdoc
    return f()
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1163, in invoke
    return f(*args, **kwargs)
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 953, in remove_then_invoke
    return callback(*args, **kwargs)
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 794, in _change_event
    self._process_events(events)
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 784, in _process_events
    self.param.set_param(**self._process_property_change(events))
    File "/home/xhoan/anaconda3/lib/python3.7/site-packages/panel/widgets/input.py", line 150, in _process_property_change
    msg['value'] = datetime.date(datetime.strptime(msg['value'][4:], '%b %d %Y'))
    File "/home/xhoan/anaconda3/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    File "/home/xhoan/anaconda3/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
    ValueError: time data '-03-20' does not match format '%b %d %Y'

Is there any way to fix this?

**Comment by hyamanieu** [comment]
Simply replacing line 150  from https://github.com/holoviz/panel/blob/d8c0c20708362978ea39bbe12b811871a0fb9edd/panel/widgets/input.py#L150 by

`msg['value'] = datetime.date(datetime.strptime(msg['value'], '%Y-%m-%d'))`

fixed this issue.

I don't know the whole contact for this ìf`case, but it looks unusual (perhaps a weird date string format from a previous bokeh version?)

**Comment by philippjfr** [comment]
Yes, the format definitely changed.

**Comment by philippjfr** [comment]
Would you consider pushing a PR with the fix?

**Comment by hyamanieu** [comment]
I think I did, can't find it though. Do you need to release it?

**Comment by hyamanieu** [comment]
#1187
