### ISSUE TITLE
Give _repr_html_ higher precedence than _repr_png_

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1191]
#### My Pain

Trying to help with this question https://discourse.holoviz.org/t/panel-and-folium-do-they-mix/342/2.

I can see that a Folium Map has a _repr_html_ method and as such should be supported in Panel.

But when using it in a Column I get an unexpected TypeError

```python
import folium as fm
import panel as pn

in_lat = 20.5936832
in_long = 78.962883
in_map = fm.Map(location=[in_lat, in_long], zoom_start=5)

pn.Column(in_map).servable()
```

```bash
$ python -m panel serve 'examples\folium_issue.py' --dev --show
2020-03-26 04:27:12,561 Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
2020-03-26 04:27:12,591 User authentication hooks NOT provided (default user enabled)
2020-03-26 04:27:12,626 Bokeh app running at: http://localhost:5006/folium_issue
2020-03-26 04:27:12,631 Starting Bokeh server with process id: 20972
2020-03-26 04:27:19,374 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x0000001452A73E08>: argument should be a bytes-like object or ASCII string, not 'NoneType'
File "base64.py", line 46, in _bytes_from_decode_data:
"string, not %r" % s.__class__.__name__) from None Traceback (most recent call last):
  File "C:\repos\private\panel\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel\examples\folium_issue.py", line 8, in <module>
    pn.Column(in_map).servable()
  File "C:\repos\private\panel\panel\viewable.py", line 243, in servable
    self.server_doc(title=title)
  File "C:\repos\private\panel\panel\viewable.py", line 600, in server_doc
    model = self.get_root(doc)
  File "C:\repos\private\panel\panel\viewable.py", line 536, in get_root
    root = self._get_model(doc, comm=comm)
  File "C:\repos\private\panel\panel\layout.py", line 136, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "C:\repos\private\panel\panel\layout.py", line 126, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "C:\repos\private\panel\panel\pane\markup.py", line 43, in _get_model
    model = self._bokeh_model(**self._get_properties())
  File "C:\repos\private\panel\panel\pane\image.py", line 95, in _get_properties
    data = base64.b64decode(data)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

#### Additional Context

This works though

```python
import folium as fm
import panel as pn

in_lat = 20.5936832
in_long = 78.962883
in_map = fm.Map(location=[in_lat, in_long], zoom_start=5)

pn.pane.HTML(in_map, height=400, width=400).servable()
```

![image](https://user-images.githubusercontent.com/42288570/77607728-8b4b7600-6f1b-11ea-982d-4ca773683980.png)

**Comment by MarcSkovMadsen** [comment]
#### Additional Context

I've also added a feature request to support Folium via a Panel pane. See  https://github.com/holoviz/panel/issues/1192

**Comment by philippjfr** [comment]
IMO this is Folium's fault, they define a `_repr_png` but that returns None.

**Comment by MarcSkovMadsen** [comment]
But there is also an _repr_html_ method should that no be prioritized higher than the _repr_png_ ?

**Comment by jbednar** [comment]
The principle in Panel is normally that the richest output is prioritized higher, and I consider HTML to be richer than PNG in capabilities, so I would agree.  Also worth filing as a bug report on Folium, though!

**Comment by philippjfr** [comment]
`_repr_png_` apparently doesn't work unless `png_enabled` is passed to the constructor. For now I've solved this by adding a very basic Folium pane which has higher priority but is just an HTML wrapper.

**Comment by philippjfr** [comment]
Given that this hasn't been a re-occuring issue for other panes and the `Folium` wrapper works well I'll close. Happy to reconsider if we find further problematic cases though.
