### ISSUE TITLE
Dashboard works in notebook but fails in Panel serve

### ISSUE THREAD

**Issue by InsciteAnalytics** [holoviz/panel#1234]
I was following holoviz-examples tutorial 08_Advanced_Dashboards while running this code and have almost followed it exactly to create a dashboard for my own dataset. It works fine when I execute it in the notebook; also works fine when I use .servable() (still within the notebook). But as soon as I use panel serve to run it on the local server, I get the appended error (KeyError). Since it seemed to me to be an indexing issue, I tried several other iterations of indexations of my data but nothing works. 

#### ALL software version info
[requirements.txt](https://github.com/holoviz/panel/files/4435028/requirements.txt)

#### Description of expected behavior and the observed behavior
The dashboard consists of two objects: 
1. A geoviews polygon object (world map created from geopandas dataframe) overlayed by a holoviews points object consisting of central latitude and longitudes of each country. The overlay actually converts to a Dynamic map. The only reason I had to use this overlay was I did not find an option in the holoviz ecosystem that enables direct streaming using clicks on polygons, which is obviously a tricky issue in any case.
2. Holoviews Dynamic map running on supplied stream from Selection1D streaming object. 
#### Complete, minimal, self-contained example code that reproduces the issue

```
# Points plot thru which the stream will run by user's clicks
pointsplot=pointsDf.hvplot.points(x='easting',y='northing',color='black',size=50).opts(marker='d',tools=['tap'])

# Geoviews polygon plot that uses geopandas dataframe
geoplot=gv.Polygons(geodf,vdims=['tempchange','country']).opts(width=700,height=450,colorbar=True,color_index='tempchange'\
                                                       ,tools=[hover,'tap'])

# This is the main pipeline, similar to the earthquake_around_point function in tutorial
def main_pipeline(ds,index):
    if not index:
        return ds.iloc[[]]
    row = pointsplot.data.iloc[index[0]]
    df = ds[ds['iso3']==row.iso3]
    return hv.Dataset(df)

# Again, just like the tutorial
dataset = hv.Dataset(mainDf) # The mainDf here is a (11K,500) shape pandas Df
index_stream = streams.Selection1D(source=pointsplot, index=[0])
filtered_ds = dataset.apply(main_pipeline, index=index_stream.param.index)

# Creating a line plot using the pipeline created above
def temp_scatter(ds):
    countryname=ds.data['country'].iloc[0]
    return ds.data.hvplot.line('date','Temp(C)',title='{}'.format(countryname)) # Need the title of the plot to change based on stream

# Creating dynamic plot object and wrapping up in panel for deployment
dynamic_scatter=pn.panel(filtered_ds.apply(temp_scatter))

# Creating dynamic plot object and wrapping up in panel for deployment
gpplot=pn.panel(geoplot*pointsplot)

pn.Column(gpplot,dynamic_scatter).servable()
```

#### Stack traceback and/or browser JavaScript console output
2020-04-05 18:06:39,521 Starting Bokeh server version 1.4.0 (running on Tornado 6.0.3)
2020-04-05 18:06:39,525 User authentication hooks NOT provided (default user enabled)
2020-04-05 18:06:39,529 Bokeh app running at: http://localhost:5006/Wb-Db-2
2020-04-05 18:06:39,536 Starting Bokeh server with process id: 232
bokeh.application.application - ERROR - Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x0000012C6AD70188>: 0
File "hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item:
 Traceback (most recent call last):
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\Users\AMS\Documents\Machine Learning\World Bank\WB Dash\Wb-Db-2.ipynb", line 156, in <module>
    "    events.on('clear_output.CodeCell', handleClearOutput);\n",
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\panel\pane\base.py", line 51, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\panel\param.py", line 562, in __init__
    self._update_inner(self._eval_function(object))
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\panel\param.py", line 577, in _eval_function
    return function(*args, **kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\param\parameterized.py", line 318, in _depends
    return func(*args,**kw)
  File "C:\Users\AMS\Documents\Machine Learning\World Bank\WB Dash\Wb-Db-2.ipynb", line 153, in ppheader
    "    }\n",
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000012C6DEA5548>>, <Future finished exception=KeyError(112)>)
Traceback (most recent call last):
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\pandas\core\indexes\base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 112

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\tornado\ioloop.py", line 767, in _discard_future_result
    future.result()
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\server\session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\server\session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\document\document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\document\document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\document\document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\bokeh\document\document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 383, in process_on_change
    self.on_msg(msg)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\holoviews\plotting\bokeh\callbacks.py", line 126, in on_msg
    stream.update(**processed_msg)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\holoviews\streams.py", line 408, in update
    self._set_stream_parameters(**kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\holoviews\streams.py", line 390, in _set_stream_parameters
    self.param.set_param(**kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\panel\param.py", line 653, in _replace_pane
    new_object = self._eval_function(self.object)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\panel\param.py", line 577, in _eval_function
    return function(*args, **kwargs)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\param\parameterized.py", line 318, in _depends
    return func(*args,**kw)
  File "C:\Users\AMS\Documents\Machine Learning\World Bank\WB Dash\Wb-Db-2.ipynb", line 153, in ppheader
    "    }\n",
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\pandas\core\frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\AMS\Anaconda3\envs\holoviz\lib\site-packages\pandas\core\indexes\base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 112
#### Screenshots or screencasts of the bug in action
https://wbplot.s3.amazonaws.com/Screen-Capture.mp4

**Comment by InsciteAnalytics** [comment]
Most likely a streams issue

**Comment by InsciteAnalytics** [comment]
knock knock!

**Comment by philippjfr** [comment]
Thanks for the issue, without a fully reproducible example it is very difficult to diagnose what might be going wrong here though.

**Comment by InsciteAnalytics** [comment]
Thanks for the response. Would it suffice if I share the entire project folder?

**Comment by philippjfr** [comment]
That would be helpful yes, if you can share the data that is.

**Comment by philippjfr** [comment]
Oh actually before going any further could you try upgrading to latest releases for everything? Bokeh 2.0.1, HoloViews 1.13.2, Panel 0.9.5.

**Comment by InsciteAnalytics** [comment]
Alright I will try the upgrade first. And its public data so I'll share it if it helps solve the problem.

**Comment by InsciteAnalytics** [comment]
Would upgrading Holoviz take care of everything?

**Comment by philippjfr** [comment]
Sadly no, not yet anyway, we're coming out of a period of very heavy development and updating HoloViz to the latest set of packages will come last.

**Comment by InsciteAnalytics** [comment]
Got it thanks.

**Comment by InsciteAnalytics** [comment]
Updating to latest versions worked! thanks!
