### ISSUE TITLE
param.Date raises error when updated via Panel app

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1264]
I'm on the the Panel `web_component_only` branch (https://github.com/holoviz/panel/pull/1252/commits/498a45c8714c1c1e499e8a7e9de07845ddebc45e).

#### My Pain

I'm trying to contribute the Wired components to Panel. I'm working on the wired DatePicker and cannot get it working because of a `ValueError: Parameter 'value' only takes numeric values`.

I have then created the minimal code example below

If I run the code with `pytest` it works and there is no problem in setting the date to `datetime.date(2020,4,8)`. 

But if I run the file with `panel serve` and click the `update` button I get the error (see long stack trace below).

#### My Hunch

My hypothesis is that the associated widget for param.date is not a valid widget.

![image](https://user-images.githubusercontent.com/42288570/79091998-b9b8b600-7d4f-11ea-9832-997a65638f90.png)

I can also see that with `pytest` the `validation` that takes place is handled by `param.Date._validate` only but with `panel serve` the validation that fails is `param.Number._validate`.

#### Code

```python
import panel as pn
import param
import datetime


class DateTest(param.Parameterized):
    update = param.Action()
    date = param.Date()

    def __init__(self, **params):
        super().__init__(**params)

        self.update = self._update

    def _update(self, event=None):
        self.date = datetime.date(2020, 4, 8)

    def view(self):
        return pn.Param(self)


def test_date_test():
    # Given
    date_test = DateTest()
    # When
    date_test.update()
    # Then:
    assert date_test.date == datetime.date(2020, 4, 8)

if __name__.startswith("bokeh"):
    DateTest().view().servable()
```

#### Stack Trace

```bash
$ python -m panel serve 'scripts\issue_param_date.py' --dev --show
2020-04-13 06:19:54,067 Starting Bokeh server version 2.0.0 (running on Tornado 6.0.3)
2020-04-13 06:19:54,070 User authentication hooks NOT provided (default user enabled)
2020-04-13 06:19:54,079 Bokeh app running at: http://localhost:5006/issue_param_date
2020-04-13 06:19:54,079 Starting Bokeh server with process id: 15012
2020-04-13 06:19:56,391 WebSocket connection opened
2020-04-13 06:19:56,392 ServerConnection created
2020-04-13 06:19:59,733 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000008CB4D59048>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py:51> exception=ValueError("Parameter 'value' only takes numeric values")>)
Traceback (most recent call last):
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 767, in _discard_future_result
    future.result()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py", line 195, in with_document_locked
    return func(*args, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\document\document.py", line 1164, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\document\document.py", line 1150, in _with_self_as_curdoc
    return f()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\document\document.py", line 1163, in invoke
    return f(*args, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\document\document.py", line 953, in remove_then_invoke
    return callback(*args, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 525, in _change_event
    self._process_events(events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 511, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\param.py", line 382, in action
    value(self.object)
  File "C:\repos\private\awesome-panel\scripts\issue_param_date.py", line 16, in _update
    self.date = datetime.date(2020, 4, 8)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 294, in _f
    instance_param.__set__(obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\__init__.py", line 623, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 861, in __set__
    obj.param._call_watcher(watcher, event)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1456, in _call_watcher
    watcher.fn(event)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\param.py", line 433, in link
    widget.param.set_param(**updates)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1358, in set_param
    setattr(self_or_cls, k, v)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\__init__.py", line 623, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 823, in __set__
    self._validate(val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\__init__.py", line 882, in _validate
    raise ValueError("Parameter '%s' only takes numeric values"%(self.name))
ValueError: Parameter 'value' only takes numeric values
```

**Comment by MarcSkovMadsen** [comment]
I experience the same problem if I change `param.Date` to `param.CalendarDate`

**Comment by MarcSkovMadsen** [comment]
If I don't show the `param.Date` and/ or `param.CalendardDate` then everything works fine when I click the button.

![image](https://user-images.githubusercontent.com/42288570/79092535-7f501880-7d51-11ea-8429-b1a0b9b36517.png)


```bash
2020-04-13 06:37:02,000 Starting Bokeh server version 2.0.0 (running on Tornado 6.0.3)
2020-04-13 06:37:02,002 User authentication hooks NOT provided (default user enabled)
2020-04-13 06:37:02,009 Bokeh app running at: http://localhost:5006/issue_param_date
2020-04-13 06:37:02,009 Starting Bokeh server with process id: 6872
2020-04-13 06:37:03,706 404 GET /favicon.ico (127.0.0.1) 1.00ms
2020-04-13 06:37:03,717 WebSocket connection opened
2020-04-13 06:37:03,718 ServerConnection created
2020-04-08
<class 'datetime.date'>
2020-04-08
<class 'datetime.date'>
2020-04-08
<class 'datetime.date'>
2020-04-08
<class 'datetime.date'>
```

```python
import panel as pn
import param
import datetime


class DateTest(param.Parameterized):
    update = param.Action()
    date = param.CalendarDate()

    def __init__(self, **params):
        super().__init__(**params)

        self.update = self._update

    def _update(self, event=None):
        self.date = datetime.date(2020, 4, 8)
        print(self.date)
        print(type(self.date))

    def view(self):
        return pn.Param(self.param.update)


def test_date_test():
    # Given
    date_test = DateTest()
    # When
    date_test.update()
    # Then:
    assert date_test.date == datetime.date(2020, 4, 8)

if __name__.startswith("bokeh"):
    DateTest().view().servable()
```

**Comment by MarcSkovMadsen** [comment]
ARGGHHHHHHHHHH. An hour wasted. :-)

I can see that if I set the `bounds` of the `param.Date` or `param.CalendarDate` everything works fine.

![image](https://user-images.githubusercontent.com/42288570/79092998-06ea5700-7d53-11ea-9c10-e31a62c650e7.png)

```python
import panel as pn
import param
import datetime


class DateTest(param.Parameterized):
    update = param.Action()
    date = param.CalendarDate(bounds=(datetime.date(2017, 1, 1), datetime.date(2022, 2, 1)))

    def __init__(self, **params):
        super().__init__(**params)

        self.update = self._update

    def _update(self, event=None):
        self.date = datetime.date(2020, 4, 8)
        print(self.date)
        print(type(self.date))

    def view(self):
        return pn.Param(self, widgets={
            "date": pn.widgets.DatePicker
        })


def test_date_test():
    # Given
    date_test = DateTest()
    # When
    date_test.update()
    # Then:
    assert date_test.date == datetime.date(2020, 4, 8)

if __name__.startswith("bokeh"):
    DateTest().view().servable()
```

**Comment by MarcSkovMadsen** [comment]
I believe this behaviour is simply not good. A lot of users of Panel could run into this and a lot would give up.

# SOLUTION

- Support using `param.Date`, `param.CalendarDate`, `pn.widgets.DatePicker` without bounds and/ or
- Document this problem very clearly and/ or
- Raise an error if you use without bounds.

**Comment by ceball** [comment]
xref https://github.com/holoviz/param/issues/171

**Comment by kcpevey** [comment]
I recently hit this as well. Very frustrating to debug when all I needed to do was add bounds!
