### ISSUE TITLE
I get can't invoke "wm" command when using Matplotlib/ Seaborn

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1482]
Panel: 0.9.7
Tornado: 6.0.4
Matplotlib: 3.2.1
Seaborn: 0.10.1

OS: Windows 10

#### My Pain

I was trying to answer create an answer (example below) to https://discourse.holoviz.org/t/how-to-create-a-self-contained-custom-panel/985. But it seems matplotlib/ seaborn does not work for me when I run the example below.

Steps
1. python 'scripts\issue_custom_component.py'
2. select the `y` column in the dropdown

```bash
$ python 'scripts\issue_custom_component.py'
Launching server at http://localhost:5007
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x00000181668DD548>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py:51> exception=TclError('can\'t invoke "wm" command: application has been destroyed')>)
Traceback (most recent call last):
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 767, in _discard_future_result
    future.result()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 516, in _change_coroutine
    self._change_event(doc)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 526, in _change_event
    self._process_events(events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 512, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\param.py", line 387, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\param.py", line 668, in update_pane
    self._update_inner(new_object)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\base.py", line 387, in _update_inner
    self._inner_layout[0] = self._pane
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout.py", line 252, in __setitem__
    self.objects = new_objects
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 861, in __set__
    obj.param._call_watcher(watcher, event)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1456, in _call_watcher
    watcher.fn(event)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 794, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout.py", line 70, in _update_model
    msg[self._rename['objects']] = self._get_objects(model, old, doc, root, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout.py", line 110, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\markup.py", line 43, in _get_model
    model = self._bokeh_model(**self._get_properties())
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\image.py", line 93, in _get_properties
    data = self._img()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\plot.py", line 151, in _img
    self.object.set_dpi(self.dpi)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\figure.py", line 984, in set_dpi
    self.dpi = val
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\figure.py", line 478, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\figure.py", line 910, in set_size_inches
    manager.resize(*(size * self.dpi / dpi_ratio).astype(int))
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 463, in resize
    self.canvas._tkcanvas.master.geometry("%dx%d" % (width, height))
  File "C:\program files\python37\lib\tkinter\__init__.py", line 1841, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
_tkinter.TclError: can't invoke "wm" command: application has been destroyed
```

```python
import param
import seaborn as sns
pn.extension("matplotlib")


class MyCustomWidget(param.Parameterized):
    column = param.Selector()

    def __init__(self, data):
        self.param.column.objects = data.columns.values

    @param.depends("column")
    def plot(self):
        if self.column:
            ax = sns.distplot(df[self.column])
            plt.close()
            return pn.pane.Matplotlib(ax.figure, background="blue", width=300, height=300)
        else:
            return pn.Spacer(width=300, height=300, background="yellow")

df = pd.DataFrame(data={"x": [1,2,3,4,5,6,7], "y": [1,2,3,4,5,6,7]})
d = MyCustomWidget(df)
pn.Column(d.param, d.plot).show(port=5007)
```

#### Additional Context

I can see I've previously had the same problem in https://github.com/holoviz/panel/issues/781 which has been solved and closed.

**Comment by MarcSkovMadsen** [comment]
I ran `pip install matplotlib seaborn -U`. And matplotlib is now 3.3.0.

This time I get

```bash
$ c:/repos/private/awesome-panel/.venv/Scripts/python.exe c:/repos/private/awesome-panel/scripts/issue_custom_component.py
Launching server at http://localhost:5007
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000024AC18ED108>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py:51> exception=TclError('invalid command name ".!canvas"')>)
Traceback (most recent call last):
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 767, in _discard_future_result
    future.result()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\gen.py", line 191, in wrapper
    result = func(*args, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 516, in _change_coroutine
    self._change_event(doc)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 526, in _change_event
    self._process_events(events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 512, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\param.py", line 387, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\param.py", line 668, in update_pane
    self._update_inner(new_object)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\base.py", line 387, in _update_inner
    self._inner_layout[0] = self._pane
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout.py", line 252, in __setitem__
    self.objects = new_objects
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 861, in __set__
    obj.param._call_watcher(watcher, event)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\param\parameterized.py", line 1456, in _call_watcher
    watcher.fn(event)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 794, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout.py", line 70, in _update_model
    msg[self._rename['objects']] = self._get_objects(model, old, doc, root, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout.py", line 110, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\markup.py", line 43, in _get_model
    model = self._bokeh_model(**self._get_properties())
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\image.py", line 93, in _get_properties
    data = self._img()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\plot.py", line 151, in _img
    self.object.set_dpi(self.dpi)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\figure.py", line 969, in set_dpi
    self.dpi = val
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\figure.py", line 453, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\figure.py", line 889, in set_size_inches
    manager.resize(*(size * self.dpi / dpi_ratio).astype(int))
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 445, in resize
    self.canvas._tkcanvas.configure(width=width, height=height)
  File "C:\program files\python37\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "C:\program files\python37\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!canvas"
```

**Comment by MarcSkovMadsen** [comment]
I removed the `plt.close()` and now it works

![image](https://user-images.githubusercontent.com/42288570/87743653-b2d78e80-c7e9-11ea-9fb3-d28ab85a254a.png)

```python
import matplotlib.pyplot as plt
import pandas as pd
import panel as pn
import param
import seaborn as sns


class MyCustomWidget(param.Parameterized):
    column = param.Selector()

    def __init__(self, data):
        self.param.column.objects = data.columns.values

    @param.depends("column")
    def plot(self):
        if self.column:
            ax = sns.distplot(df[self.column])
            # plt.close()
            return pn.pane.Matplotlib(ax.figure, background="blue", width=300, height=300)
        else:
            return pn.Spacer(width=300, height=300, background="yellow")


df = pd.DataFrame(data={"x": [1, 2, 3, 4, 5, 6, 7], "y": [1, 2, 3, 4, 5, 6, 7]})
d = MyCustomWidget(df)
pn.Column(d.param, d.plot).show(port=5007)
```

I would really like to know if removing `plt.close()` is correct (I.e. could we get memory issues?)

**Comment by MarcSkovMadsen** [comment]
Actually the above code did not work fully as it did not update the plot when changing the selection. The below code works.

```python
import matplotlib.pyplot as plt
import pandas as pd
import panel as pn
import param
import seaborn as sns


class MyCustomWidget(param.Parameterized):
    column = param.Selector()

    def __init__(self, data):
        super().__init__()

        columns = data.columns.values
        self.param.column.objects = columns
        self.column = columns[0]
        # Note: I need to set self.column to show a plot initially

    @param.depends("column")
    def plot(self):
        plt.close()
        # Note:
        # - I get exception if plt.close is below ax line.
        # - The plot does not change if I remove plot.close()
        ax = sns.distplot(df[self.column])
        plot = pn.pane.Matplotlib(ax.figure, background="blue", width=300, height=300)
        return plot

df = pd.DataFrame(data={"x": [1, 2, 3, 4, 5, 6, 7], "y": [1, 2, 2, 4, 5, 9, 7]})
d = MyCustomWidget(df)
pn.Column(d.param, d.plot).servable()
```
