### ISSUE TITLE
Streaming data with Bokeh ColumnDataSource and using Panel periodic callbacks

### ISSUE THREAD

**Issue by jokteur** [holoviz/panel#1496]
I am not sure if this is a Bokeh issue or a Panel issue. As Panel is the higher level library, I prefer to post it here first.

#### Software version info

- Panel version `0.9.7`
- Bokeh version `2.1.1`
- Python version `3.7.3`
- OS: Linux
- Browser: firefox, chrome

Tested in both notebook form and standalone server.

#### Description of expected behavior and the observed behavior

I am trying to use the streaming capabilities of Bokeh in combination with the Panel library. More specifically, I am trying to use `ColumnDataSource.stream` (from Bokeh) in a callback function that should be periodically called. However, I do not manage to make this work: if I add the periodic callback to the bokeh.io.curdoc, the callback is never called and if I add the periodic callback to any Panel object, then I get a Bokeh Error.

#### Using `panel.add_periodic_callback`

```Python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
import numpy as np
import panel as pn

ds = ColumnDataSource({"x": [0], "y": [0]})
i = 1

def update(event=None):
    global i
    ds.stream({"x": [i], "y": [np.random.rand()]})
    i += 1

p = figure()
p.line(x="x", y="y", source=ds)

pane = pn.panel(p)
pane.add_periodic_callback(update, 200)
```
In this case, the update function is called just fine, but as soon as I try to visualize the plot (i.e. opening the standalone server in a browser tab or showing the pane object in a jupyter cell), then I get the following error from Bokeh: `RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes`.

##### Stack traceback from previous example
```
ERROR:tornado.application:Exception in callback <bound method PeriodicCallback._periodic_callback of PeriodicCallback(callback=<function update at 0x7f428be6b1e0>, count=None, name='PeriodicCallback00006', period=200, timeout=None)>
Traceback (most recent call last):
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/panel/callbacks.py", line 65, in _periodic_callback
    self.callback()
  File "test.py", line 14, in update
    ds.stream({"x": [i], "y": [np.random.rand()]})
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/models/sources.py", line 415, in stream
    self._stream(new_data, rollover)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/models/sources.py", line 527, in _stream
    self.data._stream(self.document, self, new_data, rollover, setter)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/core/property/wrappers.py", line 430, in _stream
    hint=ColumnsStreamedEvent(doc, source, new_data, rollover, setter))
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/core/property/wrappers.py", line 150, in _notify_owners
    descriptor._notify_mutated(owner, old, hint=hint)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 869, in _notify_mutated
    self._real_set(obj, old, value, hint=hint)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 832, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 909, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/model.py", line 661, in trigger
    super().trigger(attr, old, new, hint=hint, setter=setter)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/util/callback_manager.py", line 157, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1042, in _notify_change
    self._trigger_on_change(event)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1137, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1150, in _with_self_as_curdoc
    return f()
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1136, in invoke_callbacks
    cb(event)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 704, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/events.py", line 269, in dispatch
    super().dispatch(receiver)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/document/events.py", line 124, in dispatch
    receiver._document_patched(self)
  File "/home/jokteur/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 218, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```
From what I understand, is that Panel added the periodic callback to the tornadio IOLoop, but Bokeh does not allow for `ColumnDataSource.stream` to be called outside of a normal Bokeh document periodic callback.

#### Using `curdoc().add_periodic_callback`
I tried also to simply add the periodic callback to the curdoc(), but here the problem is that update never gets called, even when I have an active session that is opened:
```Python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
from bokeh.io import curdoc
import numpy as np
import panel as pn

ds = ColumnDataSource({"x": [0], "y": [0]})
i = 1

def update(event=None):
    global i
    ds.stream({"x": [i], "y": [np.random.rand()]})
    i += 1

p = figure()
p.line(x="x", y="y", source=ds)

pane = pn.panel(p)
curdoc().add_periodic_callback(update, 200)
```

**Comment by philippjfr** [comment]
Using the latest recommended API this seems to work okay:

```python
from bokeh.plotting import figure
from bokeh.models import ColumnDataSource
import numpy as np
import panel as pn

ds = ColumnDataSource({"x": [0], "y": [0]})
i = 1

def update(event=None):
    global i
    ds.stream({"x": [i], "y": [np.random.rand()]})
    i += 1

p = figure()
p.line(x="x", y="y", source=ds)

pane = pn.panel(p).servable()
pn.state.add_periodic_callback(update, 200)
```

Please reopen if you still encounter issues.

**Comment by dirtyValera** [comment]
@philippjfr 

I'm new to Bokeh and a little confused about usage of `add_periodic_callback`. Is it mandatory in order to implement streaming? Can I use `update` function from another class/file (i.e. wrap pane creation logic and `update` function in a class and call update whenever a new upstream data point arrives)?

**Comment by philippjfr** [comment]
@dirtyValera Thanks for your question, note that the issue tracker is for reporting bugs and feature requests, not for general usage questions. If you have a usage question please post to: https://discourse.holoviz.org/

As a quick answer, no you can stream data however you like but you probably have to have some mechanism that polls for new data arriving and that's where `add_periodic_callback` comes in.

**Comment by dirtyValera** [comment]
@philippjfr Thanks for you answer and sorry for the wrong place to ask!

My understanding was that calling 'stream' pushes the data upstream and maintains state, hence no polling is necessary

**Comment by philippjfr** [comment]
That is correct but something still has to trigger the call to .stream, however what triggers it is entirely up to the user so from that perspective your understanding is correct.
