### ISSUE TITLE
Slider position doesn't change values for string and input form

### ISSUE THREAD

**Issue by awav** [holoviz/panel#1545]
I'd like to make two widgets, one slider and input form, so that their values belong to one abstract variable meaning that once I changed one parameter another is supposed to change its value via a callback (watch). But either I can't make it work or it is a bug in `param` - there is no link between widgets.

Here is a MWE:

```python
default_variance = 1e-6
default_lengthscale = 1e-6

class UI(param.Parameterized):
    a = param.Number(default=default_variance, bounds=(default_variance, 5.0))
    b = param.Parameter(default=default_variance)
    text = param.String(default="Initial")
    
    @param.depends("a", watch=True)
    def update_a_cb(self):
        # self.param["b"].default = self.a
        self.b = self.a
        self.text = str(self.a)
    
    @param.depends("b", watch=True)
    def update_b_cb(self):
        # self.param["a"].default = self.b
        self.a = self.b
        self.text = str(self.b)
        
    @param.depends("a", "b")
    def view(self):
        x = np.arange(20)
        data = x * self.a + self.b
        return hv.Curve([x, data])

```

Versions:

holoviews==1.12.3
param==1.9.1
panel==0.6.0

**Comment by jbednar** [comment]
Reopened now that this is an issue on Panel.  From Param it does seem to work, in that setting 'a' updates 'b' and vice versa.

**Comment by philippjfr** [comment]
Can't reproduce using current versions (Panel 0.9.7 and param 1.9.3). Please reopen if you can still reproduce.

**Comment by jbednar** [comment]
That's odd; I just tried it too and it all worked fine, but I'm pretty sure it failed to update on @tonyfast's system. For reference, here's the complete code I used just now:

```
import numpy as np, param, panel as pn, holoviews as hv
pn.extension()

default_variance = 1e-6
default_lengthscale = 1e-6

class UI(param.Parameterized):
    a = param.Number(default=default_variance, bounds=(default_variance, 5.0))
    b = param.Parameter(default=default_variance)
    text = param.String(default="Initial")
    
    @param.depends("a", watch=True)
    def update_a_cb(self):
        # self.param["b"].default = self.a
        self.b = self.a
        self.text = str(self.a)
    
    @param.depends("b", watch=True)
    def update_b_cb(self):
        # self.param["a"].default = self.b
        self.a = self.b
        self.text = str(self.b)
        
    @param.depends("a", "b")
    def view(self):
        x = np.arange(20)
        data = x * self.a + self.b
        return hv.Curve([x, data])
    
u=UI()
pn.Row(u.param, u.view)
```

**Comment by MatusGasparik** [comment]
I am also experiencing the same issue that `panel` doesn't update the UI although the underlying updates with `param` work as expected.

Using the above example moving the slider has no effect on the plot or the other widgets. This issue seems only present in the JupyterLab notebook, running the example as a standalone panel app everything works just fine.

Is there a solution for this? @jbednar 

These are the versions I am using:
- panel: 1.0.2
- param: 1.13.0
- JupyterLab: 4.0.0

**Comment by Hoxbro** [comment]
Try to downgrade Jupyterlab <4. 

The example of @jbednar seems to break even on Jupyterlab 3 with this traceback:

``` python-traceback
Traceback (most recent call last):
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/pyviz_comms/__init__.py", line 346, in _handle_msg
    self._on_msg(msg)
  File "/home/shh/Repos/holoviz/panel/panel/viewable.py", line 463, in _on_msg
    patch.apply_to_document(doc, comm.id if comm else None)
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/document/document.py", line 369, in apply_json_patch
    patch: PatchJson = deserializer.deserialize(patch_json)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 501, in deserialize
    return self.decode(obj.content, obj.buffers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 516, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 559, in _decode
    return [self._decode(entry) for entry in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 559, in <listcomp>
    return [self._decode(entry) for entry in obj]
            ^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 555, in _decode
    return self._decode_ref(cast(Ref, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 569, in _decode_ref
    self.error(f"can't resolve reference '{id}'")
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.11/site-packages/bokeh/core/serialization.py", line 717, in error
    raise DeserializationError(message)
bokeh.core.serialization.DeserializationError: can't resolve reference 'a5833f74-3458-49b9-b18c-bd8d965a7685'
```

**Comment by philippjfr** [comment]
@mattpap I thought we were ignoring unresolvable references on the Python side. This really is causing a lot of problems all over the place both on the JS and Python side.

**Comment by mattpap** [comment]
> I thought we were ignoring unresolvable references on the Python side.

We are ignoring known (i.e. duplicated) references. I started PR https://github.com/bokeh/bokeh/pull/13153 for dropping messages involving previously known references.

**Comment by philippjfr** [comment]
Thanks, in this case it seems the old figure sends a message containing its `outer_width` and `outer_height` when it is replaced.

**Comment by MatusGasparik** [comment]
I tried with an older version of `jupyterlab` and it works. Here are the concrete versions:

- jupyterlab: 3.5.2
- panel: 0.14.2
- bokeh: 2.4.3
- param: 1.12.3

**Comment by Hoxbro** [comment]
This seems to have been fixed on the main branch.
