### ISSUE TITLE
ValueError when adding item to empty nested ObjectSelector

### ISSUE THREAD

**Issue by stuart-cls** [holoviz/panel#1568]
#### ALL software version info
panel  0.9.7 conda-forge
param 1.9.3 conda-forge
bokeh 2.1.1 conda-forge
python 3.7.6 conda-forge

OS:  Windows 10 64bit
Env: conda / conda-forge

#### Description of expected behavior and the observed behavior

`ObjectSelector(default=None)` which is shown on the panel page triggers 

    ValueError: expected a value of type str, got <Selection Selection00022> of type Selection

when a new object is added with a button action.

This happens either if the ObjectSelector is directly shown as in the example below, or if the parent ObjectSelector is first expanded in the gui and then the button is pressed. If the parent is shown but collapsed, it works as expected.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel
import param


class Selection(param.Parameterized):
    a = param.Integer()


class Selector(param.Parameterized):
    sel = param.ObjectSelector(default=None)


class Main(param.Parameterized):
    sel = param.ObjectSelector(default=None)

    def __init__(self):
        super().__init__()
        self.sel = Selector()
        self.btn = panel.widgets.Button(name="Add selection")
        self.btn.on_click(self.add_selection)

    def add_selection(self, _):
        self.sel.sel = Selection()

    def panel(self):
        return panel.Column(self.sel.param, self.btn)

panel.extension()
s = Main()
app = panel.Row(s.panel)
app.show()

```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "[...]lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "[...]lib\site-packages\tornado\ioloop.py", line 767, in _discard_future_result
    future.result()
  File "[...]lib\site-packages\bokeh\server\session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "[...]lib\site-packages\bokeh\server\session.py", line 195, in with_document_locked
    return func(*args, **kwargs)
  File "[...]lib\site-packages\bokeh\document\document.py", line 1164, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "[...]lib\site-packages\bokeh\document\document.py", line 1150, in _with_self_as_curdoc
    return f()
  File "[...]lib\site-packages\bokeh\document\document.py", line 1163, in invoke
    return f(*args, **kwargs)
  File "[...]lib\site-packages\bokeh\document\document.py", line 953, in remove_then_invoke
    return callback(*args, **kwargs)
  File "[...]lib\site-packages\panel\viewable.py", line 526, in _change_event
    self._process_events(events)
  File "[...]lib\site-packages\panel\viewable.py", line 512, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "[...]lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "[...]lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "[...]scratch_2.py", line 23, in add_selection
    self.sel.sel = Selection()
  File "[...]lib\site-packages\param\parameterized.py", line 294, in _f
    instance_param.__set__(obj, val)
  File "[...]lib\site-packages\param\parameterized.py", line 296, in _f
    return f(self, obj, val)
  File "[...]lib\site-packages\param\parameterized.py", line 861, in __set__
    obj.param._call_watcher(watcher, event)
  File "[...]lib\site-packages\param\parameterized.py", line 1456, in _call_watcher
    watcher.fn(event)
  File "[...]lib\site-packages\panel\param.py", line 444, in link
    widget.param.set_param(**updates)
  File "[...]lib\site-packages\param\parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "[...]lib\site-packages\param\parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "[...]lib\site-packages\panel\viewable.py", line 794, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "[...]lib\site-packages\panel\viewable.py", line 772, in _update_model
    model.update(**msg)
  File "[...]lib\site-packages\bokeh\core\has_props.py", line 370, in update
    setattr(self, k, v)
  File "[...]lib\site-packages\bokeh\core\has_props.py", line 274, in __setattr__
    super().__setattr__(name, value)
  File "[...]lib\site-packages\bokeh\core\property\descriptors.py", line 539, in __set__
    self._internal_set(obj, value, setter=setter)
  File "[...]lib\site-packages\bokeh\core\property\descriptors.py", line 760, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "[...]lib\site-packages\bokeh\core\property\bases.py", line 331, in prepare_value
    raise e
  File "[...]lib\site-packages\bokeh\core\property\bases.py", line 324, in prepare_value
    self.validate(value)
  File "[...]lib\site-packages\bokeh\core\property\bases.py", line 456, in validate
    raise ValueError(msg)
ValueError: expected a value of type str, got <Selection Selection00022> of type Selection
```

**Comment by philippjfr** [comment]
Sorry for the late response here, I'd suggest using a `ClassSelector` here:

```python
    sel = param.ClassSelector(default=None, class_=Selection)
```

With that this works fine for me. The problem is that an `ObjectSelector` expects a list of objects to select from.

**Comment by stuart-cls** [comment]
@philippjfr Thanks for your reply.

Unless I'm doing something wrong, `ClassSelector` does not have the functionality of `ObjectSelector`: selecting between a list of instances.

My goal is

````
Main --- Selector (1) --- Selection (1)
      |                |- Selection (2)
      |- Selector (2) --- Selection (3)
                       |- Selection (4)
````
so that the user can select an Selector instance and then select a Selection instance (but these are dynamically generated).

This was all working, except for the reported bug above.
