### ISSUE TITLE
Embedding panel app in Flask not working in panel 0.10.0a23.post9+gedb3c44

### ISSUE THREAD

**Issue by nghenzi** [holoviz/panel#1575]
Hi ! 

I am beggining to integrate my app with Flask. For that, I begin with the example in holoviews (holoviews_app.py, flaskApp.py and embed.html in folder templates)

 http://holoviews.org/user_guide/Deploying_Bokeh_Apps.html

When I use panel 0.9.7 the app works as you can see in the image 

![mean_field](https://user-images.githubusercontent.com/46707985/92971141-49c16f80-f456-11ea-8ebd-4dac3df27bdd.gif)

When I switch to another environment with panel 0.10.0a23.post9+gedb3c44, the app runs  in the terminal but in the browser does not work. It appears the following error. 

![image](https://user-images.githubusercontent.com/46707985/92971300-9907a000-f456-11ea-8e41-af082a095897.png)

This is the complete traceback 

```
KeyError
KeyError: "View model name 'panel.models.location.Location' not found"

Traceback (most recent call last)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\InterfazWeb\panel_web_app\flaskApp.py", line 11, in index
with pull_session(url="http://localhost:5006/") as session:
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\client\session.py", line 119, in pull_session
session.pull()
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\client\session.py", line 354, in pull
self._connection.pull_doc(doc)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\client\connection.py", line 171, in pull_doc
reply.push_to_document(document)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\protocol\messages\pull_doc_reply.py", line 83, in push_to_document
doc.replace_with_json(self.content['doc'])
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\document\document.py", line 813, in replace_with_json
replacement = self.from_json(json)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\document\document.py", line 556, in from_json
references = instantiate_references_json(references_json)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\document\util.py", line 105, in instantiate_references_json
cls = get_class(obj_type)
File "C:\Users\54911\anaconda3\envs\panel_dev\lib\site-packages\bokeh\model.py", line 147, in get_class
raise KeyError("View model name '%s' not found" % view_model_name)
KeyError: "View model name 'panel.models.location.Location' not found"
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

I think it is related to the Location model but I don't know how to fix it.

Best regards,
N 

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by MarcSkovMadsen** [comment]
My guess is that this has something todo with the panel javascript moving to a cdn and Can be solved by setting panel use INLINE ressources. Dont know the details.

**Comment by nghenzi** [comment]
I tried to configure the BOKEH_RESOURCES variable with

conda env config vars set BOKEH_RESOURCES=inline 

but the same error appears.

**Comment by nghenzi** [comment]
I continue trying to embed a panel app in Flask. After the error with the location model, I'm using panel 0.9.7 now. I implement the following multi app page in Flask.

In case you want to reproduce this example, it is needed to change the ip of your pc. 

```
#flaskApp.py
from bokeh.client import pull_session
from bokeh.embed import server_session
from flask import Flask, render_template
from flask import send_from_directory
try:
    from flask.ext.cors import CORS
except:
    from flask_cors import CORS


app = Flask(__name__)


# locally creates a page 1
@app.route('/app1')
def app1():
    with pull_session(url="http://192.168.0.173:5999/app1") as session:
        # generate a script to load the customized session
        script = server_session(session_id=session.id, url='http://192.168.0.173:5999/app1')
        # use the script in the rendered page
    return render_template("embed.html", script=script, template="Flask")


# locally creates a page 2
@app.route('/app2')
def app2():
    with pull_session(url="http://192.168.0.173:5999/app2") as session:
        # generate a script to load the customized session
        script = server_session(session_id=session.id, url='http://192.168.0.173:5999/app2')
        # use the script in the rendered page
    return render_template("embed.html", script=script, template="Flask")


# locally creates a page 3
@app.route('/app3')
def app3():
    with pull_session(url="http://192.168.0.173:5999/app3") as session:
        # generate a script to load the customized session
        script = server_session(session_id=session.id, url='http://192.168.0.173:5999/app3')
        # use the script in the rendered page
    return render_template("embed.html", script=script, template="Flask")

# locally creates a page 3
@app.route('/app4')
def app4():
    with pull_session(url="http://192.168.0.173:5999/app4") as session:
        # generate a script to load the customized session
        script = server_session(session_id=session.id, url='http://192.168.0.173:5999/app4')
        # use the script in the rendered page
    return render_template("embed.html", script=script, template="Flask")


if __name__ == '__main__':
    # runs app in debug mode
    CORS(app, resources={r"/mapa": {"origins": "*"}})
    app.config['CORS_HEADERS'] = 'Content-Type'
    app.run(port=5001, host='0.0.0.0', debug=True)
```

the Panel aplication is 

```
#holoviews_app.py
import panel as pn
import holoviews as hv
import numpy as np, pandas as pd

from matplotlib.figure import Figure
from matplotlib import cm

hv.extension('bokeh')

pn.config.sizing_mode = 'stretch_width'
pn.extension()

def sine(frequency, phase, amplitude):
    xs = np.linspace(0, np.pi*4)
    return hv.Curve((xs, np.sin(frequency*xs+phase)*amplitude)).options(width=800)


if __name__ == '__main__':

    # app1
    app1 = hv.element.tiles.CartoDark().opts(shared_axes=False,responsive=True, height = 600)

    # app2
    fig = Figure(figsize=(8, 6))
    ax = fig.subplots()
    im = ax.imshow(np.random.random((1000,14260)),
                    aspect='auto', cmap='jet')
    app2 = pn.pane.Matplotlib(fig, dpi=144)

    #app3
    app3 = pn.pane.DataFrame(pd.DataFrame({'a':[1,2,3],'b':[4,5,6]}))

    #app4 
    ranges = dict(frequency=(1, 5), phase=(-np.pi, np.pi), amplitude=(-2, 2), y=(-2, 2))
    app4 = hv.DynamicMap(sine, kdims=['frequency', 'phase', 'amplitude']).redim.range(**ranges)

    
    # to try it, you have to change the ip of your pc
    pn.serve({'app1':app1,
               'app2':app2,
               'app3':app3,
               'app4':app4
             },
    port=5999,
    address="192.168.0.173", # Ip del servidor donde esta corriendo esto 
    host="0.0.0.0", # aca va  ya que es oara que sea un ip publico
    allow_websocket_origin=["*", 
                        "192.168.0.173:5999",
                        "192.168.0.173:5001"], 
    show=False)
```

and the html page is something like 

```
<!-- embed.html  -->


<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Embedding a Bokeh Server With Flask</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
  .body {    font-family: "Lato", sans-serif;   }
  
  .sidenav { 
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
  }
  
  .sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
  }
  
  .sidenav a:hover {
    color: #f1f1f1;
  }
  
  .sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
  }
  
  @media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
  }

  </style>
</head>

<body>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="app1">App1</a>
    <a href="app2">App2</a>
    <a href="app3">App3</a>
    <a href="app4">App4</a>
  </div>

  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>

  <div  id="bokeh_div"> 
    This Bokeh app below served by a Bokeh server that has been embedded
    in another web app framework. For more information see the section
    <a  target="_blank" href="https://bokeh.pydata.org/en/latest/docs/user_guide/server.html#embedding-bokeh-server-as-a-library">Embedding Bokeh Server as a Library</a>
    in the User's Guide.

    {{ script|safe }}

  </div>


  <script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
    }
    
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
    }
</script>

</body>
</html>
```

I have four apps which I serve with pn.serve(*.py) in port 5999 and I embed them in Flask in port 5001 with pulll_session of bokeh.client.   Some models work ok and some others not.  

In the example you can see hv.Tiles and Hv.dynamic map working (all sliders work too). pn.pane.Matplotlib and pn.pane.DataFrame do not work as you can see in gif below. in the left you have the flask server in port 5001 and in the right you have the bokeh server in port 5999 (in the bokeh server the 4 apps are working as expected)

![pull_session](https://user-images.githubusercontent.com/46707985/93025249-ba8d9680-f5d2-11ea-9c58-cfebb37b73f4.gif)
  

After digging a lot, I think the problem appears when server_session is looking for the panel models in bokeh, and these are not registered in bokeh but in panel.

Best regards, 
N

**Comment by nghenzi** [comment]
After digging the internet with google, I found this talk in gitter 

![image](https://user-images.githubusercontent.com/46707985/93084207-16572e80-f66a-11ea-8dfc-347ca34ce160.png)

It seems you need to need to import panel in FlaskApp.py.  Right, pull_session returns a document that says it has SpecialFooModel but unless you import the code that actually defines SpecialFooModel Bokeh has no idea what to do with that. 

It would be good to point it out in the holoviews example.  Thanks for the help !!!
