### ISSUE TITLE
MaterialTemplate, BootstrapTemplate, GoldenTemplate not working - GET 404 when requesting bundled assets

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1653]
I have installed the latest version of the Panel Master Branch and reinstalled my conda environment following the developer guide. I get an error during the installation https://github.com/holoviz/panel/issues/1652. But I believe Panel, Bokeh etc. is still installed and I can run what I need. I have also successfully run `panel build panel`.

If I replace `VanillaTemplate` with `MaterialTemplate` in the file `panel\tests\template\test_vanilla_manual.py` I get

![image](https://user-images.githubusercontent.com/42288570/96549168-694a8400-12af-11eb-9397-c71a55b0f3a7.png)

```python
$ python -m panel serve 'panel\tests\template\test_vanilla_manual.py' --dev
2020-10-20 08:30:40,156 Starting Bokeh server version 2.2.2 (running on Tornado 6.0.4)
2020-10-20 08:30:40,158 User authentication hooks NOT provided (default user enabled)
2020-10-20 08:30:40,161 Bokeh app running at: http://localhost:5006/test_vanilla_manual
2020-10-20 08:30:40,161 Starting Bokeh server with process id: 26420
2020-10-20 08:30:55,676 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1340', ...)
2020-10-20 08:30:55,676 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1342', ...)
2020-10-20 08:30:55,677 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1344', ...)
2020-10-20 08:30:55,782 404 GET /static/extensions/panel/bundled/materialtemplate/material.css (::1) 1.96ms
2020-10-20 08:30:55,784 404 GET /static/extensions/panel/bundled/materialtemplate/material-components-web@v4.0.0/dist/material-components-web.min.css (::1) 2.04ms
2020-10-20 08:30:55,784 404 GET /static/extensions/panel/bundled/materialtemplate/material-components-web@v4.0.0/dist/material-components-web.min.js (::1) 2.04ms
2020-10-20 08:30:56,006 404 GET /static/extensions/panel/bundled/materialtemplate/default.css (::1) 223.31ms
2020-10-20 08:30:56,106 WebSocket connection opened
2020-10-20 08:30:56,107 ServerConnection created
2020-10-20 08:36:30,527 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='2185', ...)
2020-10-20 08:36:30,528 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='2187', ...)
2020-10-20 08:36:30,528 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='2189', ...)
2020-10-20 08:36:30,559 404 GET /static/extensions/panel/bundled/materialtemplate/material.css (::1) 1.00ms
2020-10-20 08:36:30,561 404 GET /static/extensions/panel/bundled/materialtemplate/default.css (::1) 1.00ms
2020-10-20 08:36:30,563 404 GET /static/extensions/panel/bundled/materialtemplate/material-components-web@v4.0.0/dist/material-components-web.min.css (::1) 1.00ms
2020-10-20 08:36:30,566 404 GET /static/extensions/panel/bundled/materialtemplate/material-components-web@v4.0.0/dist/material-components-web.min.js (::1) 1.00ms
2020-10-20 08:36:30,758 WebSocket connection opened
2020-10-20 08:36:30,758 ServerConnection created
```

**Comment by MarcSkovMadsen** [comment]
It's the same issue with the `BootstrapTemplate`.

```python
$ python -m panel serve 'panel\tests\template\test_vanilla_manual.py' --dev
2020-10-20 08:40:47,177 Starting Bokeh server version 2.2.2 (running on Tornado 6.0.4)
2020-10-20 08:40:47,179 User authentication hooks NOT provided (default user enabled)
2020-10-20 08:40:47,183 Bokeh app running at: http://localhost:5006/test_vanilla_manual
2020-10-20 08:40:47,183 Starting Bokeh server with process id: 21588
2020-10-20 08:40:55,615 404 GET /test_vanilla_manua (::1) 1.00ms
2020-10-20 08:40:55,723 404 GET /favicon.ico (::1) 0.00ms
2020-10-20 08:41:03,625 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1340', ...)
2020-10-20 08:41:03,625 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1342', ...)
2020-10-20 08:41:03,625 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1344', ...)
2020-10-20 08:41:03,725 404 GET /static/extensions/panel/bundled/bootstraptemplate/bootstrap.css (::1) 1.00ms
2020-10-20 08:41:03,726 404 GET /static/extensions/panel/bundled/bootstraptemplate/bootstrap/4.4.1/css/bootstrap.min.css (::1) 0.99ms
2020-10-20 08:41:03,728 404 GET /static/extensions/panel/bundled/bootstraptemplate/jquery-3.4.1.slim.min.js (::1) 2.99ms
2020-10-20 08:41:03,729 404 GET /static/extensions/panel/bundled/bootstraptemplate/bootstrap/4.4.1/js/bootstrap.min.js (::1) 3.01ms
2020-10-20 08:41:03,730 404 GET /static/extensions/panel/bundled/bootstraptemplate/default.css (::1) 4.00ms
2020-10-20 08:41:03,732 404 GET /static/extensions/panel/bundled/bootstraptemplate/bootstrap/4.4.1/js/bootstrap.min.js (::1) 0.00ms
2020-10-20 08:41:03,814 WebSocket connection opened
2020-10-20 08:41:03,814 ServerConnection created
```

**Comment by MarcSkovMadsen** [comment]
It's the same problem with the GoldenTemplate

```python
$ 2020-10-20 08:42:08,266 Starting Bokeh server version 2.2.2 (running on Tornado 6.0.4)
2020-10-20 08:42:08,268 User authentication hooks NOT provided (default user enabled)
2020-10-20 08:42:08,271 Bokeh app running at: http://localhost:5006/test_vanilla_manual
2020-10-20 08:42:08,271 Starting Bokeh server with process id: 19688
2020-10-20 08:42:21,390 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1340', ...)
2020-10-20 08:42:21,390 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1342', ...)
2020-10-20 08:42:21,391 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Button(id='1344', ...)
2020-10-20 08:42:21,513 404 GET /static/extensions/panel/bundled/goldentemplate/golden.css (::1) 1.00ms
2020-10-20 08:42:21,515 404 GET /static/extensions/panel/bundled/goldentemplate/files/latest/css/goldenlayout-base.css (::1) 1.00ms
2020-10-20 08:42:21,516 404 GET /static/extensions/panel/bundled/goldentemplate/jquery-1.11.1.min.js (::1) 2.00ms
2020-10-20 08:42:21,517 404 GET /static/extensions/panel/bundled/goldentemplate/files/latest/js/goldenlayout.js (::1) 2.00ms
2020-10-20 08:42:21,518 404 GET /static/extensions/panel/bundled/goldentemplate/default.css (::1) 1.00ms
2020-10-20 08:42:21,527 404 GET /static/extensions/panel/bundled/goldentemplate/files/latest/js/goldenlayout.js (::1) 3.00m
```

**Comment by philippjfr** [comment]
You have to install them correctly by running `pip install -e .` or `python setup.py develop`. The assets are now bundled and need to be collected before this works.

**Comment by MarcSkovMadsen** [comment]
Ok. But I guess then that this issue is about the Developer Guide needs to be updated?

**Comment by philippjfr** [comment]
Already on it.

**Comment by MarcSkovMadsen** [comment]
Also when I run

```
$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 238, in <module>
    % (js_version, version))
ValueError: panel.js version (0.10.0-a33) does not match panel version (0.10.0a34+g3961571a-dirty). Cannot build release.
```

**Comment by MarcSkovMadsen** [comment]
And

```python
$ pip install -e .
Obtaining file:///C:/repos/private/panel
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for file:///C:/repos/private/panel.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\python.exe' 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\masma\AppData\Local\Temp\tmpf6wgu2b1'
       cwd: C:\repos\private\panel
  Complete output (18 lines):
  Traceback (most recent call last):
    File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\masma\AppData\Local\Temp\pip-build-env-s05aw_c3\overlay\Lib\site-packages\setuptools\build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\masma\AppData\Local\Temp\pip-build-env-s05aw_c3\overlay\Lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "C:\Users\masma\AppData\Local\Temp\pip-build-env-s05aw_c3\overlay\Lib\site-packages\setuptools\build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\masma\AppData\Local\Temp\pip-build-env-s05aw_c3\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 238, in <module>
      % (js_version, version))
  ValueError: panel.js version (0.10.0-a33) does not match panel version (0.10.0a34+g3961571a-dirty). Cannot build release.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\python.exe' 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'C:\Users\masma\AppData\Local\Temp\tmpf6wgu2b1' Check the logs for full command output.
```

**Comment by philippjfr** [comment]
My fault, will fix momentarily. Need a pre-commit hook to make sure I've done that before tagging a dev release.

**Comment by philippjfr** [comment]
If you want to fix it locally for you just bump the number to a34 in `package.json` and `package-lock.json`.

**Comment by MarcSkovMadsen** [comment]
After bumping to a34 there is still a `requests` error.

```bash
$ pip install -e .
Obtaining file:///C:/repos/private/panel
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for file:///C:/repos/private/panel.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pyct>=0.4.4 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (0.4.8)
Requirement already satisfied: markdown in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (3.3.2)
Requirement already satisfied: tqdm in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (4.50.2)
Requirement already satisfied: bokeh>=2.1 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (2.2.2)
Requirement already satisfied: param>=1.9.3 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (1.10.0a6)
Requirement already satisfied: pyviz-comms>=0.7.4 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (0.7.6)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from markdown->panel==0.10.0a34+g3961571a.dirty) (2.0.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (5.3.1)
Requirement already satisfied: packaging>=16.8 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (20.4)
Requirement already satisfied: tornado>=5.1 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (6.0.4)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (2.8.1)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\masma\appdata\roaming\python\python37\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (3.7.4.2)
Requirement already satisfied: numpy>=1.11.3 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (1.19.2)
Requirement already satisfied: pillow>=7.1.0 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (8.0.0)
Requirement already satisfied: Jinja2>=2.7 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (2.11.2)
Requirement already satisfied: zipp>=0.5 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from importlib-metadata; python_version < "3.8"->markdown->panel==0.10.0a34+g3961571a.dirty) (3.3.0)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from packaging>=16.8->bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (2.4.7)
Requirement already satisfied: six in c:\users\masma\appdata\roaming\python\python37\site-packages (from packaging>=16.8->bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (1.14.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from Jinja2>=2.7->bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (1.1.1)
Installing collected packages: panel
  Attempting uninstall: panel
    Found existing installation: panel 0.10.0a33
    Uninstalling panel-0.10.0a33:
      Successfully uninstalled panel-0.10.0a33
  Running setup.py develop for panel
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\repos\\private\\panel\\setup.py'"'"'; __file__='"'"'C:\\repos\\private\\panel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\repos\private\panel\
    Complete output (36 lines):
    running develop
    C:\Users\masma\AppData\Local\Temp\pip-build-env-njbxocjq\overlay\Lib\site-packages\setuptools\dist.py:452: UserWarning: Normalizing '0.10.0a34+g3961571a-dirty' to '0.10.0a34+g3961571a.dirty'
      warnings.warn(tmpl.format(**locals()))
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\repos\private\panel\setup.py", line 240, in <module>
        setup(**setup_args)
      File "C:\Users\masma\AppData\Local\Temp\pip-build-env-njbxocjq\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\repos\private\panel\setup.py", line 50, in run
        _build_paneljs()
      File "C:\repos\private\panel\setup.py", line 38, in _build_paneljs
        from panel.compiler import bundle_resources
      File "C:\repos\private\panel\panel\__init__.py", line 3, in <module>
        from . import layout # noqa
      File "C:\repos\private\panel\panel\layout\__init__.py", line 1, in <module>
        from .accordion import Accordion # noqa
      File "C:\repos\private\panel\panel\layout\accordion.py", line 5, in <module>
        from .base import NamedListPanel
      File "C:\repos\private\panel\panel\layout\base.py", line 13, in <module>
        from ..io.model import hold
      File "C:\repos\private\panel\panel\io\__init__.py", line 8, in <module>
        from ..config import config
      File "C:\repos\private\panel\panel\config.py", line 20, in <module>
        from .io.notebook import load_notebook
      File "C:\repos\private\panel\panel\io\notebook.py", line 38, in <module>
        from ..compiler import require_components
      File "C:\repos\private\panel\panel\compiler.py", line 14, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
  Rolling back uninstall of panel
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\panel
   from c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\~anel
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\panel-0.10.0a33-py3.8.egg-info
   from c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\~anel-0.10.0a33-py3.8.egg-info
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\scripts\panel-script.py
   from C:\Users\masma\AppData\Local\Temp\pip-uninstall-hr633nx0\panel-script.py
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\scripts\panel.exe
   from C:\Users\masma\AppData\Local\Temp\pip-uninstall-hr633nx0\panel.exe
ERROR: Command errored out with exit status 1: 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\repos\\private\\panel\\setup.py'"'"'; __file__='"'"'C:\\repos\\private\\panel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by philippjfr** [comment]
Ah, okay, sorry for being the guinea pig here but glad this is getting caught. Will have to add that dependency to the pyproject.toml.

**Comment by MarcSkovMadsen** [comment]
It's strange. Because it does not help me to add it to `pyproject.toml`. And `requests` is installed in my environment.

![image](https://user-images.githubusercontent.com/42288570/96567635-4e840980-12c7-11eb-8d3f-f952fec8c58f.png)

**Comment by MarcSkovMadsen** [comment]
Ahh. The problem is no longer requests. Its `ipywidgets_bokeh`

```bash
File "C:\repos\private\panel\panel\compilerer.py", line 106, in bundle_resources
        __import__(imp)                        dg
    ModuleNotFoundError: No module named 'ipywidgets_bokeh'
```

**Comment by MarcSkovMadsen** [comment]
Maybe it would be an idea to setup some CI/ CD that replicates the steps of the Developer Guide?

**Comment by MarcSkovMadsen** [comment]
I've added `ipywidgets_bokeh` to the `pyproject.toml` guide. Now the problem is

```bash
$ pip install -e .
Obtaining file:///C:/repos/private/panel
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for file:///C:/repos/private/panel.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: param>=1.9.3 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (1.10.0a6)
Requirement already satisfied: bokeh>=2.1 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (2.2.2)
Requirement already satisfied: pyct>=0.4.4 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (0.4.8)
Requirement already satisfied: pyviz-comms>=0.7.4 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (0.7.6)
Requirement already satisfied: markdown in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (3.3.2)
Requirement already satisfied: tqdm in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from panel==0.10.0a34+g3961571a.dirty) (4.50.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (2.8.1)
Requirement already satisfied: Jinja2>=2.7 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (2.11.2)
Requirement already satisfied: PyYAML>=3.10 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (5.3.1)
Requirement already satisfied: tornado>=5.1 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (6.0.4)
Requirement already satisfied: typing-extensions>=3.7.4 in c:\users\masma\appdata\roaming\python\python37\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (3.7.4.2)
Requirement already satisfied: pillow>=7.1.0 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (8.0.0)
Requirement already satisfied: numpy>=1.11.3 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (1.19.2)
Requirement already satisfied: packaging>=16.8 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (20.4)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from markdown->panel==0.10.0a34+g3961571a.dirty) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\masma\appdata\roaming\python\python37\site-packages (from python-dateutil>=2.1->bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (1.14.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from Jinja2>=2.7->bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty)
(1.1.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from packaging>=16.8->bokeh>=2.1->panel==0.10.0a34+g3961571a.dirty) (2.4.7)
Requirement already satisfied: zipp>=0.5 in c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages (from importlib-metadata; python_version < "3.8"->markdown->panel==0.10.0a34+g3961571a.dirty) (3.3.0)
Installing collected packages: panel
  Attempting uninstall: panel
    Found existing installation: panel 0.10.0a33
    Uninstalling panel-0.10.0a33:
      Successfully uninstalled panel-0.10.0a33
  Running setup.py develop for panel
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\repos\\private\\panel\\setup.py'"'"'; __file__='"'"'C:\\repos\\private\\panel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\repos\private\panel\
    Complete output (34 lines):
    running develop
    Working directory: C:\repos\private\panel\panel
    Using C:\repos\private\panel\panel\tsconfig.json
    Compiling TypeScript (36 files)
    Linking modules
    Output written to C:\repos\private\panel\panel\dist
    All done.
    C:\Users\masma\AppData\Local\Temp\pip-build-env-qxp2nhco\overlay\Lib\site-packages\setuptools\dist.py:452: UserWarning: Normalizing '0.10.0a34+g3961571a-dirty' to '0.10.0a34+g3961571a.dirty'
      warnings.warn(tmpl.format(**locals()))
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\repos\private\panel\setup.py", line 240, in <module>
        setup(**setup_args)
      File "C:\Users\masma\AppData\Local\Temp\pip-build-env-qxp2nhco\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\repos\private\panel\setup.py", line 50, in run
        _build_paneljs()
      File "C:\repos\private\panel\setup.py", line 43, in _build_paneljs
        bundle_resources()
      File "C:\repos\private\panel\panel\compiler.py", line 135, in bundle_resources
        write_bundled_files(name, jsfiles, bundle_dir)
      File "C:\repos\private\panel\panel\compiler.py", line 98, in write_bundled_files
        f.write(response.content.decode('utf-8'))
      File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\ufe15' in position 250276: character maps to <undefined>
    Building custom models:
    Bundling custom model resources:
    ----------------------------------------
  Rolling back uninstall of panel
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\panel
   from c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\~anel
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\panel-0.10.0a33-py3.8.egg-info
   from c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\lib\site-packages\~anel-0.10.0a33-py3.8.egg-info
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\scripts\panel-script.py
   from C:\Users\masma\AppData\Local\Temp\pip-uninstall-bahn87cr\panel-script.py
  Moving to c:\users\masma\appdata\local\continuum\anaconda3\envs\panel_dev2\scripts\panel.exe
   from C:\Users\masma\AppData\Local\Temp\pip-uninstall-bahn87cr\panel.exe
ERROR: Command errored out with exit status 1: 'C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\repos\\private\\panel\\setup.py'"'"'; __file__='"'"'C:\\repos\\private\\panel\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by philippjfr** [comment]
The CI does do that but it's on linux, we need to set up GitHub actions to run it on OSX and Windows too.

**Comment by MarcSkovMadsen** [comment]
![image](https://user-images.githubusercontent.com/42288570/96568841-a8d19a00-12c8-11eb-8d81-2e38e6d9cd24.png)

**Comment by philippjfr** [comment]
Okay, fixed the requirement on `ipywidgets_bokeh`, added the developer docs, added requests to the pyproject.toml. Now just need to track down that encoding problem.

**Comment by philippjfr** [comment]
Okay, pushed a fix for that, could you try out the PR?

**Comment by philippjfr** [comment]
Will merge and get a dev release out but would very much appreciate the testing. I'll test everything on my Windows machine later but might take me a while.

**Comment by xavArtley** [comment]
I have tested python setup.py on the last commit all seems working now
**
![image](https://user-images.githubusercontent.com/18531147/96577044-59449b80-12d3-11eb-8f81-a445b095253f.png)
**

**Comment by philippjfr** [comment]
Thanks @xavArtley, I appreciate it. Overall I'm very happy about the bundling work, by default everything is now loaded from the server itself, which means most things can be run even when there's not internet available. There's also no more inlined CSS and everything can fall back cleanly to CDN resources if requested.

**Comment by MarcSkovMadsen** [comment]
FYI. I did a `git pull holoviz master` and ran `python setup.py develop` with success.

**Comment by philippjfr** [comment]
@naanadr Which version are you running and how did you install it?

**Comment by naanadr** [comment]
> @naanadr Which version are you running and how did you install it?

I'm using `panel==0.10.2` and `bokeh==2.2.3`. I installed with `poetry add panel`.

**Comment by naanadr** [comment]
And folks, in my console I found more warnings (or this is errors?) related to bokeh. 

(maybe is better open a new issue ? I'm really lost haha)

![Captura de Tela 2021-01-12 às 15 05 45](https://user-images.githubusercontent.com/21251472/104354311-c6895680-54e7-11eb-872f-fa8e423c9527.png)
