### ISSUE TITLE
panel.serve with num_procs breaks if importing datashade 

### ISSUE THREAD

**Issue by nritsche** [holoviz/panel#1720]
I was experiencing the same as https://github.com/holoviz/panel/issues/1405 and I found that it only happened when I do `from holoviews.operation.datashader import datashade`. Here’s a minimal example:

```
import panel
import holoviews

# This line breaks things:
from holoviews.operation.datashader import datashade

panel.serve(
    panel.pane.Markdown("#1"),
    num_procs=2
)

```

```
Launching server at http://localhost:8008
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 259, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.8/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '6 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".config/JetBrains/PyCharmCE2020.2/scratches/scratch_1.py", line 12, in <module>
    panel.serve(
  File "/home/rick/.local/lib/python3.8/site-packages/panel/io/server.py", line 208, in serve
    server = get_server(panels, **kwargs)
  File "/home/rick/.local/lib/python3.8/site-packages/panel/io/server.py", line 380, in get_server
    server = Server(apps, port=port, **opts)
  File "/home/rick/.local/lib/python3.8/site-packages/bokeh/server/server.py", line 415, in __init__
    http_server.add_sockets(sockets)
  File "/home/rick/.local/lib/python3.8/site-packages/tornado/tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/home/rick/.local/lib/python3.8/site-packages/tornado/netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/home/rick/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 332, in add_reader
    return self._add_reader(fd, callback, *args)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 261, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/usr/lib/python3.8/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
FileExistsError: [Errno 17] File exists
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 259, in _add_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.8/selectors.py", line 192, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '6 is not registered'

During handling of the above exception, another exception occurred:
```
... the last block keeps repeating indefinitely.

#### software version info
Ubuntu 20.04.1 LTS
Python 3.8.5
panel 0.10.1
param 1.10.0
holoviews 1.13.5

**Comment by philippjfr** [comment]
Thanks for filing! I'm not entirely surprised by this, seems likely that numba isn't happy when the process is forked. I'd be surprised if this can be fixed easily. Does this work if you use `panel serve` with ``--num-procs``?

**Comment by philippjfr** [comment]
Think I have to close this as `wontfix` since there is nothing we can do about this at the Panel level. If you want to support this I think you'll have to start your server using the CLI.
