### ISSUE TITLE
Pipeline is not servable

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1980]
Panel 0.10.3

If I `panel serve` the below code I get AttributeError: 'Pipeline' object has no attribute 'servable'.

```bash
2021-02-16 09:17:43,785 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x000002838C344388>: 'Pipeline' object has no attribute 'servable'
File "pipeline_not_working.py", line 28, in <module>:
pipeline.servable() Traceback (most recent call last):
  File "C:\envs\personal\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\trading_analytics\sandbox\masma\daily\pipeline_not_working.py", line 28, in <module>
    pipeline.servable()
AttributeError: 'Pipeline' object has no attribute 'servable'
```

```python
import webbrowser
import param
import panel as pn

pipeline = pn.pipeline.Pipeline()

class GetPassword(param.Parameterized):
    password = param.String()

    _panel = param.Parameter(precedence=-1)
    _widgets = {
        "password": pn.widgets.PasswordInput
    }

    def __init__(self, **params):
        super().__init__(**params)

        self._panel = pn.Param(
            self, widgets=self._widgets
        )

    @param.output('password', param.String)
    def panel(self):
        return self._panel

get_admin_password_from_pam = GetPassword
pipeline.add_stage("Get Pam Password", get_admin_password_from_pam)
pipeline.servable()
```

**Comment by MarcSkovMadsen** [comment]
A workaround is `pipeline.layout.servable()`

**Comment by MarcSkovMadsen** [comment]
I think the `ParametrizedComponent` is what is needed here https://github.com/holoviz/panel/issues/1979
