### ISSUE TITLE
cannot run test_manual.py on developer version - holoviews.core.options.AbbreviatedException

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#1994]
I've followed the developer guide except for the final command `doit develop_install -c pyviz/label/dev -c conda-forge -c bokeh -o build -o tests -o recommended`.

Instead I've run

```bash
python -m pip install bokeh==2.3.0.dev13
python -m pip install -e .
panel build panel
python -m pip install -e .
python -m panel serve 'panel\tests\template\test_manual.py' --dev --show
```

And I get

```bash
$ python -m panel serve 'panel\tests\template\test_manual.py' --dev --show
2021-02-20 17:54:49,536 Starting Bokeh server version 2.3.0dev13 (running on Tornado 6.1)
2021-02-20 17:54:49,538 User authentication hooks NOT provided (default user enabled)
2021-02-20 17:54:49,542 Bokeh app running at: http://localhost:5006/test_manual
2021-02-20 17:54:49,575 Starting Bokeh server with process id: 16588
2021-02-20 17:54:51,304 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x0000023BED927948>: AttributeError: 'str' object has no attribute 'dataspecs'   

To view the original traceback, catch this exception and call print_traceback() method.
File "options.py", line 227, in __exit__:
raise AbbreviatedException(etype, value, traceback) Traceback (most recent call last):
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1359, in _init_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, source.data)
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1252, in _update_glyph
    dataspecs = glyph.dataspecs()
AttributeError: 'str' object has no attribute 'dataspecs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel_docker\panel\panel\tests\template\test_manual.py", line 207, in <module>
    _get_app().servable()
  File "C:\repos\private\panel_docker\panel\panel\viewable.py", line 313, in servable
    self.server_doc(title=title, location=True)
  File "C:\repos\private\panel_docker\panel\panel\template\base.py", line 291, in server_doc       
    return self._init_doc(doc, title=title, location=location)
  File "C:\repos\private\panel_docker\panel\panel\template\base.py", line 450, in _init_doc        
    doc = super()._init_doc(doc, comm, title, notebook, location)
  File "C:\repos\private\panel_docker\panel\panel\template\base.py", line 156, in _init_doc        
    model = obj.get_root(doc, comm, preprocess=False)
  File "C:\repos\private\panel_docker\panel\panel\viewable.py", line 481, in get_root
    root = self._get_model(doc, comm=comm)
  File "C:\repos\private\panel_docker\panel\panel\layout\base.py", line 113, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "C:\repos\private\panel_docker\panel\panel\layout\base.py", line 103, in _get_objects       
    child = pane._get_model(doc, root, model, comm)
  File "C:\repos\private\panel_docker\panel\panel\layout\base.py", line 113, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "C:\repos\private\panel_docker\panel\panel\layout\card.py", line 91, in _get_objects        
    objects = super()._get_objects(model, old_objects, doc, root, comm)
  File "C:\repos\private\panel_docker\panel\panel\layout\base.py", line 103, in _get_objects       
    child = pane._get_model(doc, root, model, comm)
  File "C:\repos\private\panel_docker\panel\panel\pane\holoviews.py", line 239, in _get_model      
    plot = self._render(doc, comm, root)
  File "C:\repos\private\panel_docker\panel\panel\pane\holoviews.py", line 304, in _render
    return renderer.get_plot(self.object, **kwargs)
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\bokeh\renderer.py", line 73, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, doc, renderer, **kwargs)
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\renderer.py", line 243, in get_plot
    plot.update(init_key)
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\plot.py", line 982, in update
    return self.initialize_plot()
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1389, in initialize_plot
    self._init_glyphs(plot, element, ranges, source)
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1359, in _init_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, source.data)
  File "C:\Users\masma\AppData\Local\Continuum\anaconda3\envs\panel_dev\lib\site-packages\holoviews\core\options.py", line 227, in __exit__
    raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: AttributeError: 'str' object has no attribute 'dataspecs'

To view the original traceback, catch this exception and call print_traceback() method.

2021-02-20 17:54:51,718 WebSocket connection opened
2021-02-20 17:54:51,719 ServerConnection created
```

**Comment by MarcSkovMadsen** [comment]
Closed. I think the problem was on my side. Running python 2.7 miniconda inside docker :-)
