### ISSUE TITLE
Running the IDOM reference notebook from inside Docker Container does not work

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2011]
I'm on the current IDOM branch.

I'm trying to run the notebook. I've started it inside a Docker conainer. But it does not work.

I see the below

![image](https://user-images.githubusercontent.com/42288570/109189014-d4dbbb00-7793-11eb-9a42-d2d2fc490e9c.png)

I see it opening new, random ports when I run cell 2

![image](https://user-images.githubusercontent.com/42288570/109189091-e8872180-7793-11eb-8ae4-5f8baf3b5cd4.png)

I get the error messages below

```python
Traceback (most recent call last):
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 374, in dispatch_queue
    yield self.process_one()
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 358, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 220, in dispatch_shell
    idents, msg = self.session.feed_identities(msg, copy=False)
  File "/opt/conda/envs/panel_dev/lib/python3.7/site-packages/jupyter_client/session.py", line 857, in feed_identities
    raise ValueError("DELIM not in msg_list")
ValueError: DELIM not in msg_list
```

and

```python
Bad pipe message: %s [b'ol: max-age=0\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.']
Bad pipe message: %s [b' (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/5']
Bad pipe message: %s [b'.36 Edg/88.0.705.74\r\nAccept: text/html,application', b'html+xml,application/xml;q=0.9,image/webp,imag']
Bad pipe message: %s [b'apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\nSec-Fetch-Site: none\r\nSec-Fetch-Mode: navigat', b'\nSec-Fetch-User: ?1\r\nSec-Fetch-Dest: document\r\nAccept-Encoding: gzip, deflate, br\r\nAccept-Language: ', b'-US,en;q=0.9,da;q=0.8\r\nCookie: _xsrf=2|5a0e01e9|7b39e7c3209ab4d0c5521a07bf3c8bdc|1612637472; usernam']
```

Right now I'm just confused and trying to understand what is happening.

**Comment by MarcSkovMadsen** [comment]
But if IDOM needs to open random ports it will make deployment scenarios difficult.

**Comment by philippjfr** [comment]
As of right now this is the only real release blocker (although there are bound to be more).

**Comment by philippjfr** [comment]
I'm going to close, I can't reproduce this and it doesn't seem like this is actually an issue with Panel. More likely to be related to some incompatibility between your Jupyter version and IDOM itself.
