### ISSUE TITLE
Panel 0.11.0rc3: wrapping plot in HoloViews Pane gives AttributeError: 'str' object has no attribute 'dataspecs'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2023]
Panel: 0.11.0rc3
Bokeh: 2.3.0
HoloViews: 1.14.1
HvPlot: 0.7

When I Panel serve the below I get an error.

```python
import hvplot.pandas  # pylint: disable=unused-import
import pandas as pd
import panel as pn
COLOR = "#E1477E"

def _get_chart_data() -> pd.DataFrame:
    """## Chart Data

    Returns:
        pd.DataFrame -- A DataFrame with dummy data and columns=["Day", "Orders"]
    """

    chart_data = {
        "Day": [
            "Sunday",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
        ],
        "Orders": [
            15539,
            21345,
            18483,
            24003,
            23489,
            24092,
            12034,
        ],
    }
    return pd.DataFrame(chart_data)

def _holoviews_chart():
    """## Dashboard Orders Chart generated by HoloViews"""
    data = _get_chart_data()
    line_plot = data.hvplot.line(
        x="Day",
        y="Orders",
    )
    fig = line_plot
    return fig

chart = _holoviews_chart()
app = pn.pane.HoloViews(chart)
app.servable()
```

```bash
AbbreviatedException: AttributeError: 'str' object has no attribute 'dataspecs' To view the original traceback, catch this exception and call print_traceback() method.
Traceback (most recent call last):
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1359, in _init_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, source.data)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1252, in _update_glyph
    dataspecs = glyph.dataspecs()
AttributeError: 'str' object has no attribute 'dataspecs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\awesome-panel\scripts\panel_011_0rc3.py", line 47, in <module>
    app.servable()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 314, in servable
    self.server_doc(title=title, location=True)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\viewable.py", line 765, in server_doc
    model = self.get_root(doc)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\base.py", line 254, in get_root
    root = self.layout._get_model(doc, comm=comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout\base.py", line 113, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\layout\base.py", line 103, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\holoviews.py", line 239, in _get_model
    plot = self._render(doc, comm, root)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\panel\pane\holoviews.py", line 304, in _render
    return renderer.get_plot(self.object, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\bokeh\renderer.py", line 73, in get_plot
    plot = super(BokehRenderer, self_or_cls).get_plot(obj, doc, renderer, **kwargs)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\renderer.py", line 243, in get_plot
    plot.update(init_key)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\plot.py", line 982, in update
    return self.initialize_plot()
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1389, in initialize_plot
    self._init_glyphs(plot, element, ranges, source)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\plotting\bokeh\element.py", line 1359, in _init_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, source.data)
  File "C:\repos\private\awesome-panel\.venv\lib\site-packages\holoviews\core\options.py", line 227, in __exit__
    raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: AttributeError: 'str' object has no attribute 'dataspecs'

To view the original traceback, catch this exception and call print_traceback() method.
```

**Comment by MarcSkovMadsen** [comment]
I also saw the problem. But I got confused and thought it had another cause and closed it.

https://github.com/holoviz/panel/issues/1994

**Comment by MarcSkovMadsen** [comment]
I get this error every where I use HoloViews plots at awesome-panel.org. So for me this is a major issue.

**Comment by philippjfr** [comment]
This is a HoloViews issue, upgrade to a HoloViews dev release.

**Comment by MarcSkovMadsen** [comment]
So you will release Holoviews together with Panel @philippjfr ? Otherwise Panel Will not work

**Comment by philippjfr** [comment]
Yes.
