### ISSUE TITLE
ValueError: HoloViews pane does not support objects of type 'annotate'.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2049]
Panel 0.11

```python
import panel as pn
import holoviews as hv
import numpy as np
hv.extension("bokeh")

curve = hv.Curve(np.random.randn(50).cumsum())
curve_annotator = hv.annotate.instance()
curve_annotator(curve.opts(width=800, height=400, responsive=False), annotations={'Label': str})
component2 = pn.pane.HoloViews(curve_annotator, sizing_mode="stretch_both")
component2.servable()
```

```bash
ValueError: HoloViews pane does not support objects of type 'annotate'.

Traceback (most recent call last):
  File "c:\repos\private\panel_011\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel_011\test_me.py", line 9, in <module>
    component2 = pn.pane.HoloViews(curve_annotator, sizing_mode="stretch_both")
  File "c:\repos\private\panel_011\.venv\lib\site-packages\panel\pane\holoviews.py", line 85, in __init__
    super().__init__(object, **params)
  File "c:\repos\private\panel_011\.venv\lib\site-packages\panel\pane\base.py", line 107, in __init__
    self._type_error(object)
  File "c:\repos\private\panel_011\.venv\lib\site-packages\panel\pane\base.py", line 117, in _type_error
    (type(self).__name__, type(object).__name__))
ValueError: HoloViews pane does not support objects of type 'annotate'.
```

**Comment by xavArtley** [comment]
For me it works:
![image](https://user-images.githubusercontent.com/18531147/109809504-a55fff00-7c28-11eb-9893-baa0513f5c69.png)

**Comment by philippjfr** [comment]
It's because @MarcSkovMadsen is trying to render the annotator object, which is an operation rather than the return value when the annotator is applied. I'm closing since this is a usage error. For completeness sake you should do:

```python
curve_annotator = hv.annotate.instance()
annotated = curve_annotator(curve.opts(width=800, height=400, responsive=False), annotations={'Label': str})
component2 = pn.pane.HoloViews(annotated, sizing_mode="stretch_both")
```
