### ISSUE TITLE
Perspective raises difficult to understand ValueError if data column is of type int

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2054]
Panel 0.11

If you run the below with `panel serve` you get a `ValueError`

```python
import panel as pn
pn.extension("perspective")

data = {0: ['1981 01 01 00   161    28 10173   270    21     0     0     0',
  '1981 01 01 01   111    33 10175   270    21     0     0 -9999',
  '1981 01 01 02   111    39 10183   330    26     0     0 -9999',
  '1981 01 01 03    94    39 10192 -9999     0     0     0 -9999',
  '1981 01 01 04    72    39 10196 -9999     0     0     0 -9999'],
 'year': [1981, 1981, 1981, 1981, 1981],
 }

pn.pane.Perspective(data).servable()
```

```bash
ValueError: failed to validate ColumnDataSource(id='1021', ...).data: expected an element of ColumnData(String, Seq(Any)), got {0: ['1981 01 01 00 161 28 10173 270 21 0 0 0', '1981 01 01 01 111 33 10175 270 21 0 0 -9999', '1981 01 01 02 111 39 10183 330 26 0 0 -9999', '1981 01 01 03 94 39 10192 -9999 0 0 0 -9999', '1981 01 01 04 72 39 10196 -9999 0 0 0 -9999'], 'year': [1981, 1981, 1981, 1981, 1981]}

Traceback (most recent call last):
  File "c:\repos\load-forecasts\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\load-forecasts\test_error.py", line 12, in <module>
    pn.pane.Perspective(data).servable()
  File "c:\repos\load-forecasts\.venv\lib\site-packages\panel\viewable.py", line 314, in servable
    self.server_doc(title=title, location=True)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\panel\viewable.py", line 765, in server_doc
    model = self.get_root(doc)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\panel\pane\base.py", line 254, in get_root
    root = self._get_model(doc, comm=comm)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\panel\pane\perspective.py", line 135, in _get_model
    properties = self._process_param_change(self._init_params())
  File "c:\repos\load-forecasts\.venv\lib\site-packages\panel\pane\perspective.py", line 130, in _init_params
    props['source'] = ColumnDataSource(data=self._data)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\bokeh\models\sources.py", line 200, in __init__
    self.data.update(raw_data)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\bokeh\core\property\wrappers.py", line 378, in update
    descriptor._notify_mutated(owner, old, hint=hint)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 884, in _notify_mutated
    value = self.property.prepare_value(obj, self.name, value)
  File "c:\repos\load-forecasts\.venv\lib\site-packages\bokeh\core\property\bases.py", line 350, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate ColumnDataSource(id='1021', ...).data: expected an element of ColumnData(String, Seq(Any)), got {0: ['1981 01 01 00   161    28 10173   270    21     0     0     0', '1981 01 01 01   111    33 10175   270    21     0     0 -9999', '1981 01 01 02   111    39 10183   330    26     0     0 -9999', '1981 01 01 03    94    39 10192 -9999     0     0     0 -9999', '1981 01 01 04    72    39 10196 -9999     0     0     0 -9999'], 'year': [1981, 1981, 1981, 1981, 1981]}
```

#### Solution

Support column names of non-string type or provide better error error message.

**Comment by Hoxbro** [comment]
This error is a consequence of the JSON format only allowing key names to be strings. 

A way to sidestep the problem is by doing something like this 
``` python
 def _get_data(self):
      if self.object is None:
          return None, {}
      elif isinstance(self.object, dict):
          obj = self.object
      else:
          obj = ColumnDataSource.from_df(self.object)

      obj = {str(k): v for k, v in obj.items()}
      return self.object, obj
```

https://github.com/holoviz/panel/blob/85a139293a563f970438e9290fd4929d88fb9eef/panel/pane/perspective.py#L117-L122

**Comment by philippjfr** [comment]
The fix of casting the names to ints makes sense to me. We should then also cast all `columns` to `str` too.
