### ISSUE TITLE
Panel 0.11.0 and 0.11.1 causes jupyter notebook to hang on launch (Windows 10 python 3.8)

### ISSUE THREAD

**Issue by jenshnielsen** [holoviz/panel#2097]
#### ALL software version info
Windows 10 20H2

Tested in Firefox and New edge
with the following packages from Conda forge

This seems to be an issue with python 3.8 but not with 3.7
```
# packages in environment at C:\Users\Jens-work\miniconda3\envs\panel38:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
bokeh                     2.3.0            py38haa244fe_0    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.4.6            py38hd7da0ea_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.7.3            py38haa244fe_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
ipykernel                 5.5.0            py38hc5df569_1    conda-forge
ipython                   7.21.0           py38hc5df569_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
jedi                      0.18.0           py38haa244fe_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py38haa244fe_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
markupsafe                1.1.1            py38h294d835_3    conda-forge
mistune                   0.8.4           py38h294d835_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38haa244fe_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
notebook                  6.2.0            py38haa244fe_0    conda-forge
numpy                     1.20.1           py38h0cc643e_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1j               h8ffe710_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandoc                    2.12                 h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.11.0             pyhd8ed1ab_0    conda-forge
param                     1.10.1             pyhd3deb0d_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py38h9273828_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.17             pyha770c72_0    conda-forge
prompt_toolkit            3.0.17               hd8ed1ab_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.8           h7840368_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pywinpty                  0.5.7            py38h32f6830_1    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.0.3           py38h09162b1_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
terminado                 0.9.2            py38haa244fe_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge
```

#### Description of expected behavior and the observed behavior

launching jupyter notebook should open a webpage that eventually loads the notebook.
This works as expected if panel is not installed however when installing panel 0.11.0 (also tested with 0.11.1 from pypi as 0.11.1 is not yet on conda forge)
the notebook load hangs on the this page should redirect you. Reverting to panel 0.10.3 fixes the issue.

#### Complete, minimal, self-contained example code that reproduces the issue

```
conda create -n panel38
conda activate panel38
conda config --add channels conda-forge --env
conda config --set channel_priority strict --env
conda install python=3.8 jupyter
```
Here launching jupyter notebook works as expected

```
conda install panel
```
Now launching jupyter notebook hangs
```
conda install panel==0.10.3
```
Now launching jupyter notebook works again

#### Stack traceback and/or browser JavaScript console output
No errors are shown in the browser error console or the terminal.

**Comment by jenshnielsen** [comment]
could be related to https://github.com/holoviz/panel/issues/2061

**Comment by philippjfr** [comment]
Will have to test on my Windows machine. Unlikely to be related to #2061 since a kernel crash is very different from the actual notebook server hanging. Suspect it may be down to the server extension.

**Comment by jenshnielsen** [comment]
Indeed it seems likely to be related to the server extension. If you uninstall bokeh a traceback will be thrown from loading the server extension but the notebook loads. 

```
[W 10:34:19.919 NotebookApp] Error loading server extension panel
    Traceback (most recent call last):
      File "C:\Users\Jens-work\miniconda3\envs\panel38\lib\site-packages\notebook\notebookapp.py", line 1988, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\Jens-work\miniconda3\envs\panel38\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\Jens-work\miniconda3\envs\panel38\lib\site-packages\panel\__init__.py", line 1, in <module>
        from . import layout # noqa
      File "C:\Users\Jens-work\miniconda3\envs\panel38\lib\site-packages\panel\layout\__init__.py", line 1, in <module>
        from .accordion import Accordion # noqa
      File "C:\Users\Jens-work\miniconda3\envs\panel38\lib\site-packages\panel\layout\accordion.py", line 3, in <module>
        from bokeh.models import Column as BkColumn, CustomJS
    ModuleNotFoundError: No module named 'bokeh'

```

**Comment by philippjfr** [comment]
Thanks, that helps. It seems odd though, just like the bokeh error it should handle failure to launch the server extension gracefully.

**Comment by wenjuno** [comment]
The problem feels like the jupyter server never accepts the request from browser because the browser shows nothing (no return nor error) and just keeps spinning. I did some tracing and the problem turns out to be complicated and it will be very helpful if I can get some suggestions for how to "fix" or "work around" the problem.

This problem doesn't happen for panel 0.10 so I looked at the imported modules during launching jupyter notebook. I see that panel is imported as extension for panel 0.11 but not for panel 0.10. I looked at the stack when jupyter notebook finishes launching and see that when using panel 0.11 the `SelectorEventLoop` is used but when using panel 0.10 the `ProactorEventLoop` is used. I dug a little deeper and found the import for `bokeh.server.server` and from there I found the function `fixup_windows_event_loop_policy`: https://github.com/bokeh/bokeh/blob/187803263a34c9f2d351578b548e99178cd8f591/bokeh/util/tornado.py#L47-L54. I think the problem is that the `SelectorEventLoop` doesn't call `poll` but I'm not very sure about it.

Currently downgrading panel to 0.10 is one solution but that will prevent people from getting the latest features from panel. I don't have a good idea about what the "correct" solution is (should bokeh stops working around with the hack? should panel be imported as extension in jupyter notebook initialization? should panel do something differently in the import to work around the problem?). I think suggestions from panel developers will be very helpful. Thanks.

**Comment by jbednar** [comment]
What about upgrading to panel 0.11.3?

**Comment by wenjuno** [comment]
Hi @jbednar, it has the same problem.

**Comment by philippjfr** [comment]
So is Panel just broken on Windows right now then? @MarcSkovMadsen You work on Windows right? Are you seeing issues with the Panel 0.12.0 dev releases? If anyone else could check the dev releases as well that would be hugely appreciated. You can get them with:

```
conda install -c pyviz/label/dev panel
```

or 

```
pip install panel --pre --upgrade
```

**Comment by jenshnielsen** [comment]
I  can no longer reproduce the issue with notebook 6.4.0 (but I can reproduce it with notebook 6.2.0 as originally reported and 6.3.0) regardless of the version of panel installed

**Comment by philippjfr** [comment]
Thanks, really appreciate you testing this. Sounds like Jupyter will stick with the old behavior going forward and if they do revert then we have to follow up and fix this in Bokeh.
