### ISSUE TITLE
Streaming to Tabulator table inside Template raises ValueError

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2116]
panel: 0.11.1
os: windows

#### `Tabulator.stream` not working inside Template

If I click the "Stream" button I get a `ValueError` in the console

![image](https://user-images.githubusercontent.com/42288570/112262473-ff734380-8c6d-11eb-8375-0cd67916cc35.png)

```python
import numpy as np
import pandas as pd
import panel as pn
from panel.widgets import Tabulator

pn.config.sizing_mode="stretch_width"

DATA = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))
tabulator = Tabulator(DATA)
stream = pn.widgets.Button(name="Stream")
def stream_data(self, *events):
    tabulator.stream(pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE')))
stream.on_click(stream_data)

template = pn.template.FastListTemplate(title="Tabulator")
template.main[:]=[tabulator]
template.sidebar[:]=[stream]
template.servable()
```

```bash
$ panel serve 'application\pages\tabulator_app\__init__.py' --auto --show
2021-03-24 06:54:32,518 Starting Bokeh server version 2.3.0 (running on Tornado 6.1)
2021-03-24 06:54:32,519 User authentication hooks NOT provided (default user enabled)
2021-03-24 06:54:32,521 Bokeh app running at: http://localhost:5006/__init__
2021-03-24 06:54:32,521 Starting Bokeh server with process id: 27352
2021-03-24 06:54:35,135 404 GET /favicon.ico (::1) 0.00ms
2021-03-24 06:54:35,145 WebSocket connection opened
2021-03-24 06:54:35,146 ServerConnection created   
2021-03-24 06:55:16,886 WebSocket connection closed: code=1001, reason=None
2021-03-24 06:55:19,622 WebSocket connection opened
2021-03-24 06:55:19,623 ServerConnection created
2021-03-24 06:55:36,672 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000001C3914B2288>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at c:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py:51> exception=ValueError('Length of values (30) does not match length of index (20)')>)
Traceback (most recent call last):
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback        
    ret = callback()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\bokeh\server\session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\reactive.py", line 249, in _change_coroutine    
    self._change_event(doc)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\reactive.py", line 259, in _change_event        
    self._process_events(events)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\reactive.py", line 915, in _process_events      
    self._update_column(k, v)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\widgets\tables.py", line 913, in _update_column 
    self.value[column] = array
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pandas\core\frame.py", line 3163, in __setitem__      
    self._set_item(key, value)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pandas\core\frame.py", line 3239, in _set_item        
    value = self._sanitize_column(key, value)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pandas\core\frame.py", line 3896, in _sanitize_column 
    value = sanitize_index(value, self.index)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\pandas\core\internals\construction.py", line 752, in sanitize_index
    "Length of values "
ValueError: Length of values (30) does not match length of index (20)
```

#### No Errors If not using a Template

![image](https://user-images.githubusercontent.com/42288570/112262595-2fbae200-8c6e-11eb-8fc8-26a6b97a6570.png)

```python
import numpy as np
import pandas as pd
import panel as pn
from panel.widgets import Tabulator

pn.config.sizing_mode="stretch_width"

DATA = pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE'))
tabulator = Tabulator(DATA)
stream = pn.widgets.Button(name="Stream")
def stream_data(self, *events):
    tabulator.stream(pd.DataFrame(np.random.randn(10, 5), columns=list('ABCDE')))
stream.on_click(stream_data)

pn.Column(tabulator, stream).servable()
```

**Comment by Hoxbro** [comment]
The error seems to happen because the template triggers the tabulator widget twice each click. This is properly related to the tabulator widget is referenced twice in the `_models` property.

If I add `print(tabulator._models)` I get the following: 

**With template:**
`{'1039': (DataTabulator(id='1039', ...), None), '1003': (DataTabulator(id='1039', ...), None)}`

**Without template:**
`{'1002': (DataTabulator(id='1036', ...), Column(id='1002', ...))}`

I can get it to work without the error by adding the following below the template code. It is a big hack so a better solution is needed.
`del tabulator._models[next(iter(tabulator._models))]`

**Comment by MarcSkovMadsen** [comment]
Thanks @Hoxbro . Your hack makes my application work.

But @philippjfr . This must be a bug in the implementation of `stream`. `patch` is probably also buggy (repeating patch twice).

**Comment by philippjfr** [comment]
Probably a bug in the implementation of templates rather than Tabulator. Will take a look.
