### ISSUE TITLE
Filtered Tabulator failed on cell edit

### ISSUE THREAD

**Issue by EfforiaKnight** [holoviz/panel#2165]
#### ALL software version info
Python 3.7
panel=0.11.2
pandas=1.2.4

#### Description of expected behavior and the observed behavior
This is my first issue :)
When filtering data in Tabulator widget and then editing one of the cells there is exception from Pandas.
I think it can be fixed by changing:
```
    def _update_column(self, column, array):
        if self.pagination != 'remote':
            # self.value[column] = array  -> This line to below two lines
			index = self._processed.index.values
            self.value.loc[index, column] = array
            return
        nrows = self.page_size
        start = (self.page-1)*nrows
        end = start+nrows
        if self.sorters:
            index = self._processed.iloc[start:end].index.values
            self.value[column].loc[index] = array
        else:
            self.value[column].iloc[start:end] = array
```

#### Complete, minimal, self-contained example code that reproduces the issue
I will try to prepare a minimal example.

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "c:\projects\simplenario_panel\venv\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "c:\projects\simplenario_panel\venv\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\projects\simplenario_panel\venv\lib\site-packages\bokeh\server\session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "c:\projects\simplenario_panel\venv\lib\site-packages\tornado\gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\panel\reactive.py", line 252, in _change_coroutine
    self._change_event(doc)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\panel\reactive.py", line 262, in _change_event
    self._process_events(events)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\panel\reactive.py", line 922, in _process_events
    self._update_column(k, v)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\panel\widgets\tables.py", line 910, in _update_column
    self.value[column] = array
  File "c:\projects\simplenario_panel\venv\lib\site-packages\pandas\core\frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\pandas\core\frame.py", line 3242, in _set_item
    value = self._sanitize_column(key, value)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\pandas\core\frame.py", line 3899, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "c:\projects\simplenario_panel\venv\lib\site-packages\pandas\core\internals\construction.py", line 752, in sanitize_index
    "Length of values "
ValueError: Length of values (1) does not match length of index (365)
```

#### Screenshots or screencasts of the bug in action
![panel_table_filter](https://user-images.githubusercontent.com/18498403/114593202-7e1f3780-9c94-11eb-963d-2dfbd4ed08ca.gif)

**Comment by hyamanieu** [comment]
Here a minimal example (the value doesn't update):

```python
import pandas as pd
import panel as pn
pn.extension()

print(pn.__version__)

import numpy as np

df = pd.DataFrame({'cat': np.random.choice(list('ABCD'), 50), 'numb': np.random.randint(0,100,50), 'fl':np.random.rand(50)})

t = pn.widgets.Tabulator(df)

t.remove_filter('cat')

select = pn.widgets.MultiSelect(options=list('ABCD'), name='Cat Filter')

t.add_filter(select, 'cat')
pn.Row(select,t)
```

Up to this point, editing a cell will not update t.value or df.

Removing the filter like here below will change both t.value & df.
```python
t.remove_filter(select.param.value)
t
```

Suggested change from @EfforiaKnight  works, I can submit a PR this afternoon.
