### ISSUE TITLE
VTKSlider.ipynb raises error when dragging slider

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2227]
I'm running on binder with the current master branch of panel. Panel is currently v 0.11.3

When I drag the slider in the upper right corner I get an error

https://user-images.githubusercontent.com/42288570/115661138-4f146000-a33d-11eb-84c3-02991abd17c2.mp4

```bash
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/home/jovyan/panel/viewable.py", line 260, in _on_msg
    patch.apply_to_document(doc, comm.id)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 784, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/bases.py", line 350, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate Range1d(id='1023', ...).start: expected an element of either Float, Datetime or TimeDelta, got None
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyviz_comms/__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "/home/jovyan/panel/viewable.py", line 260, in _on_msg
    patch.apply_to_document(doc, comm.id)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 784, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/bokeh/core/property/bases.py", line 350, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate Range1d(id='1023', ...).start: expected an element of either Float, Datetime or TimeDelta, got None
```

## Additional Context

You can replicate it using the commit 68f193fee7aeed331c87a5faa6fcc5397a051a61 here

https://mybinder.org/v2/gh/holoviz/panel/68f193fee7aeed331c87a5faa6fcc5397a051a61?urlpath=lab/tree/examples/gallery/demos/VTKInteractive.ipynb

You can test it on the latest `binder` branch here

https://mybinder.org/v2/gh/holoviz/panel/binder?urlpath=lab/tree/examples/gallery/demos/VTKInteractive.ipynb

FYI. @xavArtley

**Comment by xavArtley** [comment]
Can you test if datashader is working ?

**Comment by MarcSkovMadsen** [comment]
How would I do that? What would I expect to see?

**Comment by xavArtley** [comment]
Since none of the 3 slices are displayed I suspect it's more a datashader problem than a vtk one.

For the moment I have no really spare time to investigate further.

But I will recommand you to make just a simple notebook example on mybinder just to display an image rasterized by datashader and see if it works.

If it works I'll try to look further why the example does not work. And if it does not then may be like vtk there is something to do with the binder environnement to make datashader works.

Or may be simpler in the vtkslicer notebook just remove the rasterize functions inside dynamic maps to see if the error is still present

**Comment by xavArtley** [comment]
Actually you are not trying to drag a cursor, but a bokeh axis.
It's the dynamic map plot with the reponsive option wich is not working.
It's a layout problem.
you should have something like that displayed:
![image](https://user-images.githubusercontent.com/18531147/115682729-0917c600-a356-11eb-8925-d954bd189984.png)

However I can't make the responsive option works on your mybinder environment

**Comment by xavArtley** [comment]
And the reason of the difference is bokeh version.
It works with bokeh version 2.3.0 but not with 2.3.1

**Comment by xavArtley** [comment]
It seems to me a bug more deep than the VTKSlicer demo, I opened a new issue https://github.com/holoviz/panel/issues/2228

**Comment by MarcSkovMadsen** [comment]
Thanks @xavArtley

**Comment by mattpap** [comment]
> `ValueError: failed to validate Range1d(id='1023', ...).start: expected an element of either Float, Datetime or TimeDelta, got None`

`Range1d.start` is non-nullable. It was accepted before, but it was likely converted to 0 in the runtime.
