### ISSUE TITLE
Acting on widget triggers ValueError: 'value' is not a parameter of RowXXXXX

### ISSUE THREAD

**Issue by olivierverdier** [holoviz/panel#2254]
#### ALL software version info
Current version of param (8725e7187aacfd6d4a623d9fdc8c5d0ad4c66c54), panel version 0.11.3, Jupyter Lab v. 3.0.14, Python 3.8.5 on Windows 10.

Let me add that this occurred after an update of panel/param, the bug was not present before.

#### Description of expected behavior and the observed behavior

Changing a widget in the UI produces an error.

#### Complete, minimal, self-contained example code that reproduces the issue

The example below is as minimal as it can be, any further simplification that I tried makes the bug disappear...

```
import numpy as np

import param

import panel as pn

pn.extension()

class Reg(param.Parameterized):
    pass

class CoeffView(param.Parameterized):
    toggle = param.Boolean(default=True, )

    data = param.Parameter(precedence=-1)
    reg = param.Parameter(precedence=-1)
    
    
    def __init__(self,  *args, **kwargs):
        super(CoeffView, self).__init__(*args, **kwargs)
        self.data = np.array([1])
       
    @param.depends(
                   'data', 
                   'toggle', watch=True)
    def _update_reg(self):
        self.reg = Reg()
        

cview = CoeffView()

pn.Row(cview.param)

```
**Note** I run this in Jupyter lab, and the bug occurs when I click on the check box labelled `toggle`.

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):
  File "C:[.....]\Miniconda3\lib\site-packages\pyviz_comms\__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "C:[.....]\Miniconda3\lib\site-packages\panel\viewable.py", line 261, in _on_msg
    doc.unhold()
  File "C:[.....]\Miniconda3\lib\site-packages\bokeh\document\document.py", line 669, in unhold
    self._trigger_on_change(event)
  File "C:[.....]\Miniconda3\lib\site-packages\bokeh\document\document.py", line 1180, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "C:[.....]\Miniconda3\lib\site-packages\bokeh\document\document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "C:[.....]\Miniconda3\lib\site-packages\bokeh\util\callback_manager.py", line 161, in invoke
    callback(attr, old, new)
  File "C:[.....]\Miniconda3\lib\site-packages\panel\reactive.py", line 273, in _comm_change
    self._process_events({attr: new})
  File "C:[.....]\Miniconda3\lib\site-packages\panel\reactive.py", line 245, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "d:\developer\src\param\param\parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "d:\developer\src\param\param\parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "d:\developer\src\param\param\parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:[.....]\Miniconda3\lib\site-packages\panel\param.py", line 438, in link_widget
    self.object.param.set_param(**{p_name: change.new})
  File "d:\developer\src\param\param\parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "d:\developer\src\param\param\parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "d:\developer\src\param\param\parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "d:\developer\src\param\param\parameterized.py", line 520, in caller
    return function()
  File "d:\developer\src\param\param\parameterized.py", line 351, in _depends
    return func(*args,**kw)
  File "<ipython-input-1-5e6f8be5a8b4>", line 29, in _update_reg
    self.reg = Reg()
  File "d:\developer\src\param\param\parameterized.py", line 316, in _f
    instance_param.__set__(obj, val)
  File "d:\developer\src\param\param\parameterized.py", line 318, in _f
    return f(self, obj, val)
  File "d:\developer\src\param\param\parameterized.py", line 936, in __set__
    obj.param._call_watcher(watcher, event)
  File "d:\developer\src\param\param\parameterized.py", line 1591, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "d:\developer\src\param\param\parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:[.....]\Miniconda3\lib\site-packages\panel\param.py", line 512, in link
    widget.param.set_param(**updates)
  File "d:\developer\src\param\param\parameterized.py", line 1463, in set_param
    raise ValueError("'%s' is not a parameter of %s" % (k, self_or_cls.name))
ValueError: 'value' is not a parameter of Row00110
```

**Comment by olivierverdier** [comment]
This was _fast_! Amazing, thanks a lot! (Thank you also for migrating the issue from `param`)
