### ISSUE TITLE
Streaming perspective example broken

### ISSUE THREAD

**Issue by limx0** [holoviz/panel#2321]
Copying the example from the perspective streaming example and PR, I get the following error: 

`ValueError: Must stream updates to all existing columns (missing: level_0)`

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
`panel==0.11.3`
`bokeh==2.3.2`

#### Description of expected behavior and the observed behavior
Example should run, it does not update

#### Complete, minimal, self-contained example code that reproduces the issue
Use either the gallery example - https://pyviz-dev.github.io/panel/gallery/streaming/streaming_perspective.html#streaming-gallery-streaming-perspective 

Or the PR example code: https://github.com/holoviz/panel/pull/2034

#### Stack traceback and/or browser JavaScript console output
```
2021-05-16 18:22:16,632 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f937a3f9670>>, <Task finished name='Task-225' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at lib/python3.8/site-packages/bokeh/server/session.py:51> exception=ValueError('Must stream updates to all existing columns (missing: level_0)')>)
Traceback (most recent call last):
  File "lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "lib/python3.8/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "lib/python3.8/site-packages/bokeh/server/session.py", line 195, in with_document_locked
    return func(*args, **kwargs)
  File "lib/python3.8/site-packages/bokeh/document/document.py", line 1212, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "lib/python3.8/site-packages/bokeh/document/document.py", line 1211, in invoke
    return f(*args, **kwargs)
  File "lib/python3.8/site-packages/bokeh/document/document.py", line 1001, in remove_then_invoke
    return callback(*args, **kwargs)
  File "lib/python3.8/site-packages/bokeh/models/sources.py", line 419, in stream
    self._stream(new_data, rollover)
  File "lib/python3.8/site-packages/bokeh/models/sources.py", line 498, in _stream
    raise ValueError("Must stream updates to all existing columns (missing: %s)" % ", ".join(sorted(missing)))
ValueError: Must stream updates to all existing columns (missing: level_0)
```

**Comment by philippjfr** [comment]
This appears to be fixed in master, please try upgrading to a Panel dev release (e.g. 0.12.0a15) and if you can still reproduce it reopen the issue.
