### ISSUE TITLE
discreteslider doesn't instantiate without set value

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2394]
pn.widgets.DiscreteSlider()

**Comment by MarcSkovMadsen** [comment]
A minimum reproducible example looks like below

```python
import panel as pn
pn.extension()

pn.widgets.DiscreteSlider().servable()
```

```bash
ValueError: Value None not a valid option, ensure that the supplied value is one of the declared options.
Traceback (most recent call last):
  File "c:\repos\private\panel_docker\panel\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel_docker\panel\panel\test_example.py", line 4, in <module>
    pn.widgets.DiscreteSlider().servable()
  File "c:\repos\private\panel_docker\panel\panel\widgets\slider.py", line 224, in __init__
    raise ValueError('Value %s not a valid option, '
ValueError: Value None not a valid option, ensure that the supplied value is one of the declared options.
```

**Comment by MarcSkovMadsen** [comment]
Hi @andhuang-CLGX 

Could you describe

- the use case for a DiscreteSlider without any value or options
- how this slider should look?

Thanks

**Comment by ahuang11** [comment]
I guess this is mainly for dynamically generating values, e.g. hv.Curve([]) and this works
```
import panel as pn
pn.extension()
pn.widgets.IntSlider()
```
So I expect the IntSlider's cousin, DiscreteSlider should also work.
