### ISSUE TITLE
discreteslider crashes with only a single value

### ISSUE THREAD

**Issue by andhuang-CLGX** [holoviz/panel#2395]
```
pn.widgets.DiscreteSlider(options=["something"])
```

**Comment by andhuang-CLGX** [comment]
Well I guess all sliders are like this, but maybe it'd be good to duplicate the first value or disable it if only one value?

**Comment by MarcSkovMadsen** [comment]
A minimum reproducible example would be

```python
import panel as pn
pn.extension(sizing_mode="stretch_width")

pn.widgets.DiscreteSlider(options=["something else"]).servable()
```

```bash
ValueError: Slider 'start' and 'end' cannot be equal.
Traceback (most recent call last):
  File "c:\repos\private\panel_docker\panel\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel_docker\panel\panel\test_example.py", line 4, in <module>
    pn.widgets.DiscreteSlider(options=["something else"]).servable()
  File "c:\repos\private\panel_docker\panel\panel\viewable.py", line 331, in servable
    self.server_doc(title=title, location=location)
  File "c:\repos\private\panel_docker\panel\panel\viewable.py", line 782, in server_doc
    model = self.get_root(doc)
  File "c:\repos\private\panel_docker\panel\panel\viewable.py", line 500, in get_root
    root = self._get_model(doc, comm=comm)
  File "c:\repos\private\panel_docker\panel\panel\widgets\base.py", line 173, in _get_model
    model = self._composite._get_model(doc, root, parent, comm)
  File "c:\repos\private\panel_docker\panel\panel\layout\base.py", line 113, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "c:\repos\private\panel_docker\panel\panel\layout\base.py", line 103, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "c:\repos\private\panel_docker\panel\panel\widgets\base.py", line 79, in _get_model
    model = self._widget_type(**self._process_param_change(self._init_params()))
  File "c:\repos\private\panel_docker\panel\.venv\lib\site-packages\bokeh\models\widgets\sliders.py", line 71, in __init__
    raise ValueError("Slider 'start' and 'end' cannot be equal.")
ValueError: Slider 'start' and 'end' cannot be equal.
```

**Comment by MarcSkovMadsen** [comment]
Hi @andhuang-CLGX 

- Could you describe the use case for a discreteslider with only one option? 
- And how you would like this to look?

**Comment by ahuang11** [comment]
I imagine:
```
import panel as pn
pn.extension(sizing_mode="stretch_width")

pn.widgets.DiscreteSlider(options=["something else"] * 2).servable()
```

The reason for this is if the options are dynamically generated and there is only one selectable option, it would crash the program.
