### ISSUE TITLE
Panel >= 0.12a12 breaks Jupyter Notebook, prevents startup entirely

### ISSUE THREAD

**Issue by mathrick** [holoviz/panel#2406]
Installing any prerelease of Panel 0.12, up to and including 0.12a18, completely breaks Jupyter Notebook startup.

#### ALL software version info
OS: Ubuntu 20.04
Python: 3.8.5
Jupyter Notebook: 6.4.0 (Classic)
Jupyter kernel installed in user mode from the same virtualenv as Panel is running in
```
$ pip list
Package             Version  
------------------- ---------
argon2-cffi         20.1.0   
async-generator     1.10     
attrs               21.2.0   
backcall            0.2.0    
bleach              3.3.0    
bokeh               2.3.2    
certifi             2021.5.30
cffi                1.14.5   
chardet             4.0.0    
decorator           5.0.9    
defusedxml          0.7.1    
entrypoints         0.3      
idna                2.10     
ipykernel           5.5.5    
ipython             7.24.1   
ipython-genutils    0.2.0    
ipywidgets          7.6.3    
jedi                0.18.0   
Jinja2              3.0.1    
jsonschema          3.2.0    
jupyter             1.0.0    
jupyter-client      6.2.0    
jupyter-console     6.4.0    
jupyter-core        4.7.1    
jupyterlab-pygments 0.1.2    
jupyterlab-widgets  1.0.0    
Markdown            3.3.4    
MarkupSafe          2.0.1    
matplotlib-inline   0.1.2    
mistune             0.8.4    
nbclient            0.5.3    
nbconvert           6.0.7    
nbformat            5.1.3    
nest-asyncio        1.5.1    
notebook            6.4.0    
numpy               1.21.0rc2
packaging           20.9     
pandocfilters       1.4.3    
panel               0.12.0a12
param               1.10.2a13
parso               0.8.2    
pexpect             4.8.0    
pickleshare         0.7.5    
Pillow              8.2.0    
pip                 20.0.2   
pkg-resources       0.0.0    
prometheus-client   0.11.0   
prompt-toolkit      3.0.19   
ptyprocess          0.7.0    
pycparser           2.20     
pyct                0.4.8    
Pygments            2.9.0    
pyparsing           2.4.7    
pyrsistent          0.17.3   
python-dateutil     2.8.1    
pyviz-comms         2.0.2    
PyYAML              5.4.1    
pyzmq               22.1.0   
qtconsole           5.1.0    
QtPy                1.9.0    
requests            2.25.1   
Send2Trash          1.5.0    
setuptools          44.0.0   
six                 1.16.0   
terminado           0.10.1   
testpath            0.5.0    
tornado             6.1      
tqdm                4.61.1   
traitlets           5.0.5    
typing-extensions   3.10.0.0 
urllib3             1.26.5   
wcwidth             0.2.5    
webencodings        0.5.1    
widgetsnbextension  3.5.1    
```
#### Description of expected behavior and the observed behavior
Installing the pre-release package of Panel starting with 0.12a12 breaks Jupyter Notebook startup. Downgrading to 0.12a11 fixes it. It does not seem to matter what directory it is asked to serve.

#### Complete, minimal, self-contained example code that reproduces the issue

I'm not sure how to provide any smaller example, I'm a noob to the Jupyter ecosystem and its installation and inner workings are a complete mystery to me :). However, this is enough to trigger it for me in a fresh virtualenv:

```
$ pip install jupyter
$ pip install ipykernel
$ python -m ipykernel install --user
$ pip install 'panel == 0.12a12' --pre
$ jupyter notebook
```

#### Stack traceback and/or browser JavaScript console output
```
$ pip install --upgrade 'panel == 0.12a12' --pre
Looking in indexes: https://devpi.cerebras.aws/root/pypi/+simple/
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'devpi.cerebras.aws'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting panel==0.12a12
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'devpi.cerebras.aws'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://devpi.cerebras.aws/root/pypi/%2Bf/445/4cea127812464/panel-0.12.0a12-py2.py3-none-any.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 921 kB/s 
Requirement already satisfied, skipping upgrade: bokeh<2.4.0,>=2.3.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (2.3.2)
Requirement already satisfied, skipping upgrade: requests in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (2.25.1)
Requirement already satisfied, skipping upgrade: pyviz-comms>=0.7.4 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (2.0.2)
Requirement already satisfied, skipping upgrade: markdown in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (3.3.4)
Requirement already satisfied, skipping upgrade: tqdm in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (4.61.0)
Requirement already satisfied, skipping upgrade: pyct>=0.4.4 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (0.4.8)
Requirement already satisfied, skipping upgrade: param>=1.10.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (1.10.1)
Requirement already satisfied, skipping upgrade: bleach in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a12) (3.3.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.9 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (3.0.1)
Requirement already satisfied, skipping upgrade: PyYAML>=3.10 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (5.4.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11.3 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (1.20.3)
Requirement already satisfied, skipping upgrade: packaging>=16.8 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (20.9)
Requirement already satisfied, skipping upgrade: pillow>=7.1.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (8.2.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (2.8.1)
Requirement already satisfied, skipping upgrade: tornado>=5.1 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (6.1)
Requirement already satisfied, skipping upgrade: typing_extensions>=3.7.4 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a12) (3.10.0.0)
Requirement already satisfied, skipping upgrade: chardet<5,>=3.0.2 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a12) (4.0.0)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a12) (2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a12) (2021.5.30)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a12) (1.26.5)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bleach->panel==0.12a12) (1.16.0)
Requirement already satisfied, skipping upgrade: webencodings in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bleach->panel==0.12a12) (0.5.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=2.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from Jinja2>=2.9->bokeh<2.4.0,>=2.3.0->panel==0.12a12) (2.0.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from packaging>=16.8->bokeh<2.4.0,>=2.3.0->panel==0.12a12) (2.4.7)
Installing collected packages: panel
  Attempting uninstall: panel
    Found existing installation: panel 0.12.0a11
    Uninstalling panel-0.12.0a11:
      Successfully uninstalled panel-0.12.0a11
Successfully installed panel-0.12.0a12
(yuppie) mathrick@megumi ~/Dev/Cerebras/yuppie $ jupyter notebook
Traceback (most recent call last):
  File "/home/mathrick/.pyenv/versions/yuppie/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/notebook/notebookapp.py", line 2122, in initialize
    self.init_server_extension_config()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/notebook/notebookapp.py", line 2006, in init_server_extension_config
    section = manager.get(self.config_file_name)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/notebook/services/config/manager.py", line 25, in get
    recursive_update(config, cm.get(section_name))
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/notebook/config_manager.py", line 101, in get
    recursive_update(data, json.load(f))
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 1 (char 107)
```
With 0.12a11:
```
$ pip install --upgrade 'panel == 0.12a11' --pre
Looking in indexes: https://devpi.cerebras.aws/root/pypi/+simple/
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'devpi.cerebras.aws'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting panel==0.12a11
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'devpi.cerebras.aws'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  Downloading https://devpi.cerebras.aws/root/pypi/%2Bf/22a/374ef83a0db15/panel-0.12.0a11-py2.py3-none-any.whl (9.0 MB)
     |████████████████████████████████| 9.0 MB 2.5 MB/s 
Requirement already satisfied, skipping upgrade: bokeh<2.4.0,>=2.3.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (2.3.2)
Requirement already satisfied, skipping upgrade: markdown in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (3.3.4)
Requirement already satisfied, skipping upgrade: pyviz-comms>=0.7.4 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (2.0.2)
Requirement already satisfied, skipping upgrade: requests in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (2.25.1)
Requirement already satisfied, skipping upgrade: bleach in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (3.3.0)
Requirement already satisfied, skipping upgrade: param>=1.10.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (1.10.1)
Requirement already satisfied, skipping upgrade: pyct>=0.4.4 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (0.4.8)
Requirement already satisfied, skipping upgrade: tqdm in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from panel==0.12a11) (4.61.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.9 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (3.0.1)
Requirement already satisfied, skipping upgrade: PyYAML>=3.10 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (5.4.1)
Requirement already satisfied, skipping upgrade: numpy>=1.11.3 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (1.20.3)
Requirement already satisfied, skipping upgrade: packaging>=16.8 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (20.9)
Requirement already satisfied, skipping upgrade: pillow>=7.1.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (8.2.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (2.8.1)
Requirement already satisfied, skipping upgrade: tornado>=5.1 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (6.1)
Requirement already satisfied, skipping upgrade: typing_extensions>=3.7.4 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bokeh<2.4.0,>=2.3.0->panel==0.12a11) (3.10.0.0)
Requirement already satisfied, skipping upgrade: chardet<5,>=3.0.2 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a11) (4.0.0)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a11) (1.26.5)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a11) (2021.5.30)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from requests->panel==0.12a11) (2.10)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bleach->panel==0.12a11) (1.16.0)
Requirement already satisfied, skipping upgrade: webencodings in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from bleach->panel==0.12a11) (0.5.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=2.0 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from Jinja2>=2.9->bokeh<2.4.0,>=2.3.0->panel==0.12a11) (2.0.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages (from packaging>=16.8->bokeh<2.4.0,>=2.3.0->panel==0.12a11) (2.4.7)
Installing collected packages: panel
  Attempting uninstall: panel
    Found existing installation: panel 0.12.0a12
    Uninstalling panel-0.12.0a12:
      Successfully uninstalled panel-0.12.0a12
Successfully installed panel-0.12.0a11
(yuppie) mathrick@megumi ~/Dev/Cerebras/yuppie $ jupyter notebook
[I 11:13:02.220 NotebookApp] Serving notebooks from local directory: /home/mathrick/Dev/Cerebras/yuppie
[I 11:13:02.221 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 11:13:02.221 NotebookApp] http://localhost:8888/?token=34e52099904032138c19af24fbb03cc350dee3d37a286544
[I 11:13:02.221 NotebookApp]  or http://127.0.0.1:8888/?token=34e52099904032138c19af24fbb03cc350dee3d37a286544
[I 11:13:02.221 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by mathrick** [comment]
I did some debugging, and it's caused by `etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json`:

```json
{
  "ServerApp": {
    "jpserver_extensions": {
      "panel.io.jupyter_server_extension": true
    }
  }, <-- invalid
}
```

**Comment by philippjfr** [comment]
Wonder why this hasn't affected me locally, but I've fixed it in #2407

**Comment by philippjfr** [comment]
Panel 0.12.0a20 with the fix is now out.

**Comment by mathrick** [comment]
Thanks! Should there a lint step for JSON files in the tests perhaps?

**Comment by philippjfr** [comment]
For sure, is that something you could add?

**Comment by mathrick** [comment]
I'll see if I can figure it out.
