### ISSUE TITLE
pn.bind/pn.depends break when chaining dependencies into keyword args

### ISSUE THREAD

**Issue by mathrick** [holoviz/panel#2409]
#### ALL software version info
Panel 0.12a20

#### Description of expected behavior and the observed behavior
When using `pn.depends` or `pn.bind` with `watch=True`, if the value provided for a keyword argument is itself a bound function, the generated code is wrong and errors out because it tries to call the function with incorrect argument names.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import datetime
import panel as pn

date = pn.widgets.DatePicker()

def foo(date):
    return 42

def bar(foo):
    return 13
    
bound_foo = pn.bind(foo, date=date, watch=True)
pn.bind(bar, foo=bound_foo, watch=True) # breaks
pn.bind(bar, bound_foo, watch=True) # works

date.servable()
date.value = datetime.date.today()
```

#### Stack traceback and/or browser JavaScript console output

```
2021-06-20 20:41:18,700 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f69a5553d60>>, <Task finished name='Task-82' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/bokeh/server/session.py:51> exception=TypeError("bar() got an unexpected keyword argument '__kwarg_foo_date'")>)
Traceback (most recent call last):
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/bokeh/server/session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/reactive.py", line 259, in _change_coroutine
    self._change_event(doc)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/reactive.py", line 269, in _change_event
    self._process_events(events)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/reactive.py", line 252, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 386, in cb
    return func(*args, **dep_kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/depends.py", line 173, in wrapped
    return function(*combined_args, **combined_kwargs)
TypeError: bar() got an unexpected keyword argument '__kwarg_foo_date'
```

This is coming from `panel.depends._param_bind()` and the wrapper it generates.

**Comment by MarcSkovMadsen** [comment]
Wow @mathrick . I think you've invented a new way of using `pn.bind`. But makes totally sense to me. I believe its a feature request and not bug though.

**Comment by mathrick** [comment]
Heh, I wasn't trying to invent anything, I actually spent a good while trying to figure out what the canonical way of feeding data into dependent calculations was, and that was just my best guess :). If that's not it, then what's the current panel way of saying "X depends on Y, and Y depends on Z, and they should all update when Z's inputs change"?
