### ISSUE TITLE
Dicts synced to location get mangled if other URL-synced parameters get changed

### ISSUE THREAD

**Issue by mathrick** [holoviz/panel#2538]
#### ALL software version info
Panel: 0.12.0rc11
Bokeh: 2.3.3
Python: 3.8.10
Tornado: 6.1

#### Description of expected behavior and the observed behavior
If a dict-typed value is synced to `pn.state.location` together with another value, changing the other value will mangle the encoded dict, replacing double quotes for keys with single quotes, which then breaks JSON deserialisation

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
import param

from random import randint

class MyParams(param.Parameterized):
    dict = param.Dict()
    bool = param.Boolean()


myparams = MyParams()
pn.state.location.sync(myparams, {'dict': 'foo', 'bool': 'bar'})

button = pn.widgets.Button(name="Click me")
def cb(*args):
    myparams.dict = {'val': randint(13, 42)}

button.on_click(cb)
pn.Column(button, myparams).servable()
```

Click the button, the URL will have a properly-encoded dict in it (ie. something like http://localhost:5006/test?foo=%7B%22val%22%3A+28%7D). This can be verified by reloading without issues.

Next click the checkbox. Notice the encoding of the dict will have changed in the URL (ie. it's now something like http://localhost:5006/test?foo=%7B%27val%27%3A+28%7D&bar=true). Especially note the double quotes (`%22`) have now been changed to single quotes (`%27`).

Lastly, click the checkbox again, or reload the page. A JSON exception is thrown because single quotes are not valid JSON.

#### Stack traceback and/or browser JavaScript console output
```
2021-07-14 21:29:40,641 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f71aff11ee0>>, <Task finished name='Task-956' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/bokeh/server/session.py:51> exception=JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 2 (char 1)')>)
Traceback (most recent call last):
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/bokeh/server/session.py", line 71, in _needs_document_lock_wrapper
    result = await result
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/tornado/gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/reactive.py", line 259, in _change_coroutine
    self._change_event(doc)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/reactive.py", line 269, in _change_event
    self._process_events(events)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/reactive.py", line 252, in _process_events
    self.param.set_param(**self._process_property_change(events))
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 1472, in set_param
    self_._batch_call_watchers()
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 1611, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/param/parameterized.py", line 1573, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/io/location.py", line 85, in _update_synced
    query_params = self.query_params
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/io/location.py", line 133, in query_params
    return parse_query(self.search)
  File "/home/mathrick/.pyenv/versions/system-3.8.5/envs/yuppie/lib/python3.8/site-packages/panel/util.py", line 296, in parse_query
    query[k] = json.loads(v)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

#### Screenshots or screencasts of the bug in action
Before:
![urlsync-before](https://user-images.githubusercontent.com/179487/125730111-45cd602c-9209-40fe-8766-0c670286cd46.png)

After:
![urlsync-after](https://user-images.githubusercontent.com/179487/125730118-27f11258-97a7-49ae-9478-55f3bd73a270.png)

**Comment by philippjfr** [comment]
The URL still gets mangled now but it now gets decoded okay either way so I'll probably close this. Please reopen if you think the mangling itself is a concern.
