### ISSUE TITLE
Autoreload raises AttributeError: 'NoneType' object has no attribute 'reload'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2570]
After upgrading to Panel 0.12 when I `panel serve script.py --autoreload --show` I sometimes get the below when the app reloads. I've not yet been able to create a minimum reproducible example. It seems random so far.

2021-07-24 05:52:52,826 Exception in callback <bound method PeriodicCallback._periodic_callback of PeriodicCallback(callback=functools.partial(<function _reload_on_update at 0x000002057F80FC18>, {'scripts\\script.py': 1627098714.0517485}), count=None, name='PeriodicCallback00099', period=500, running=False, timeout=None)>
Traceback (most recent call last):
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 905, in _run
    return self.callback()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\callbacks.py", line 70, in _periodic_callback
    self.callback()
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\reload.py", line 153, in _reload_on_update
    _check_file(modify_times, path)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\reload.py", line 132, in _check_file
    _reload(module)
  File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\reload.py", line 119, in _reload
    state.location.reload = True
AttributeError: 'NoneType' object has no attribute 'reload'

**Comment by philippjfr** [comment]
Will just add an explicit guard against this condition.
