### ISSUE TITLE
Memory Leak While Setting default app and index not working behind a Reverse Proxy

### ISSUE THREAD

**Issue by BiswajitTri** [holoviz/panel#2670]
#### ALL software version info
OS : Ubuntu 21.04
Browser : chromium
Panel: 0.11.3
Bokeh:2.3.3
Tornado:6.1

I am serving mutiple panel apps behind a Traefik reverse proxy.

## PROCESS 1 (Running Locally without a proxy)
`panel serve appTwo/app2.py  appOne/app1.py  Home/home.py --port=8080 --address=0.0.0.0  --index=/home.py   --prefix=panels --allow-websocket-origin=localhost 

## OUTPUT
Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
Bokeh app running at: http://0.0.0.0:8080/panel/app1
Bokeh app running at: http://0.0.0.0:8080/panel/app2
Bokeh app running at: http://0.0.0.0:8080/panel/home`

when i run these locally and i visit 'http://0.0.0.0:8080/panel' i am redirected to 'http://0.0.0.0:8080/panel/home'

## PROCESS 2
Running the panel server behind a Traefik reverse proxy

``panel serve appTwo/app2.py  appOne/app1.py  Home/home.py --port=80 --address=0.0.0.0  --index=/home.py   --prefix=panels --allow-websocket-origin=localhost 

## OUTPUT
Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
Bokeh app running at: http://0.0.0.0:80/panel/app1
Bokeh app running at: http://0.0.0.0:80/panel/app2
Bokeh app running at: http://0.0.0.0:80/panel/home``

Now when i visit 'http://localhost/panel'  (using a proxy) i get this error

`2021-08-27 07:55:03,955 Uncaught exception GET /panel (172.x.x.x)

2021-08-27T07:55:03.999540035Z HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/panel', version='HTTP/1.1', remote_ip='172.x.x.x.)

2021-08-27T07:55:03.999550317Z Traceback (most recent call last):

2021-08-27T07:55:03.999556512Z   File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute

2021-08-27T07:55:03.999564787Z     result = await result

2021-08-27T07:55:03.999571100Z   File "/opt/conda/lib/python3.8/site-packages/bokeh/server/views/root_handler.py", line 64, in get

2021-08-27T07:55:03.999577710Z     self.render(index, prefix=prefix, items=sorted(self.applications.keys()))

2021-08-27T07:55:03.999583617Z   File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 863, in render

2021-08-27T07:55:03.999589610Z     html = self.render_string(template_name, **kwargs)

2021-08-27T07:55:03.999595532Z   File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1009, in render_string

2021-08-27T07:55:03.999601493Z     t = loader.load(template_name)

2021-08-27T07:55:03.999608468Z   File "/opt/conda/lib/python3.8/site-packages/tornado/template.py", line 446, in load

2021-08-27T07:55:03.999619015Z     self.templates[name] = self._create_template(name)

2021-08-27T07:55:03.999628881Z   File "/opt/conda/lib/python3.8/site-packages/tornado/template.py", line 477, in _create_template

2021-08-27T07:55:03.999640504Z     with open(path, "rb") as f:

2021-08-27T07:55:03.999647621Z FileNotFoundError: [Errno 2] No such file or directory: '/home.py'`

## PROCESS 3
``
#Running the panel server behind a Traefik reverse proxy with absolute path to default app

P.S I know using absolute path is not the way to set default app (but should i getting such error(mentioned below)?)

``panel serve appTwo/app2.py  appOne/app1.py  Home/home.py --port=80 --address=0.0.0.0  --index={absolute path to /home.py from root directory}   --prefix=panels --allow-websocket-origin=localhost 

Starting Bokeh server version 2.3.3 (running on Tornado 6.1)
Bokeh app running at: http://0.0.0.0:80/panel/app1
Bokeh app running at: http://0.0.0.0:80/panel/app2
Bokeh app running at: http://0.0.0.0:80/panel/home``

Now when i visit 'http://localhost/panel'  i see a memory leak:

I can see the code of home.py in browser in the path ('http://localhost/panel')

Attaching a screenshot of some changed code below( removed actual code for security purpose)

![Screenshot from 2021-08-27 13-54-28](https://user-images.githubusercontent.com/75363869/131098940-8bd55fa5-7e61-4a0a-85d6-12dbd84200d5.png)

How can i set an app as default now ,running behind a reverse proxy?

**Comment by philippjfr** [comment]
Sorry we never replied here, there seem to be quite a few issues at once here. I'd suggest https://discourse.holoviz.org/ as the better place to ask questions like this. For setting an index a lot of the logic was overhauled for 0.13.0 so that should work better now.
