### ISSUE TITLE
Make it easy to have stretch_both for holoviews plot

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#2774]
#### ALL software version info

<details>
  <summary> doit env_capture </summary>

``` yaml
.  env_capture


     active environment : base

    active env location : C:\Users\shh\miniconda3\envs\holoviz

            shell level : 2

       user config file : C:\Users\shh\.condarc

 populated config files : C:\Users\shh\.condarc

          conda version : 4.10.3

    conda-build version : 3.21.4

         python version : 3.7.10.final.0

       virtual packages : __cuda=11.3=0

                          __win=0=0

                          __archspec=1=x86_64

       base environment : C:\Users\shh\miniconda3\envs\holoviz  (writable)

      conda av data dir : C:\Users\shh\miniconda3\envs\holoviz\etc\conda

  conda av metadata url : None

           channel URLs : https://conda.anaconda.org/pyviz/win-64

                          https://conda.anaconda.org/pyviz/noarch

                          https://conda.anaconda.org/conda-forge/win-64

                          https://conda.anaconda.org/conda-forge/noarch

                          https://repo.anaconda.com/pkgs/main/win-64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/win-64

                          https://repo.anaconda.com/pkgs/r/noarch

                          https://repo.anaconda.com/pkgs/msys2/win-64

                          https://repo.anaconda.com/pkgs/msys2/noarch

          package cache : C:\Users\shh\miniconda3\envs\holoviz\pkgs

                          C:\Users\shh\.conda\pkgs

                          C:\Users\shh\AppData\Local\conda\conda\pkgs

       envs directories : C:\Users\shh\miniconda3\envs\holoviz\envs

                          C:\Users\shh\.conda\envs

                          C:\Users\shh\AppData\Local\conda\conda\envs

               platform : win-64

             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.7.10 Windows/10 Windows/10.0.19041

          administrator : False

             netrc file : None

           offline mode : False



# packages in environment at C:\Users\shh\miniconda3\envs\holoviz:

#

# Name                    Version                   Build  Channel

anyio                     3.3.0            py37h03978a9_0    conda-forge

argcomplete               1.12.3             pyhd8ed1ab_2    conda-forge

argon2-cffi               20.1.0           py37hcc03f2d_2    conda-forge

async_generator           1.10                       py_0    conda-forge

atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge

attrs                     21.2.0             pyhd8ed1ab_0    conda-forge

babel                     2.9.1              pyh44b312d_0    conda-forge

backcall                  0.2.0              pyh9f0ad1d_0    conda-forge

backports                 1.0                        py_2    conda-forge

backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge

beautifulsoup4            4.10.0             pyha770c72_0    conda-forge

bleach                    4.1.0              pyhd8ed1ab_0    conda-forge

bokeh                     2.4.0            py37h03978a9_0    conda-forge

branca                    0.4.2              pyhd8ed1ab_0    conda-forge

brotlipy                  0.7.0           py37hcc03f2d_1001    conda-forge

bzip2                     1.0.8                h8ffe710_4    conda-forge

ca-certificates           2021.5.30            h5b45459_0    conda-forge

certifi                   2021.5.30        py37h03978a9_0    conda-forge

cffi                      1.14.6           py37hd8e9650_1    conda-forge

chardet                   4.0.0            py37h03978a9_1    conda-forge

charset-normalizer        2.0.5              pyhd8ed1ab_0    conda-forge

cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge

cmarkgfm                  0.6.0            py37hcc03f2d_0    conda-forge

codecov                   2.1.11             pyhd3deb0d_0    conda-forge

colorama                  0.4.4              pyh9f0ad1d_0    conda-forge

colorcet                  2.0.6                      py_0    pyviz/label/dev

conda                     4.10.3           py37h03978a9_1    conda-forge

conda-build               3.21.4           py37h03978a9_0    conda-forge

conda-package-handling    1.7.3            py37ha54c9ec_0    conda-forge

coverage                  5.5              py37hcc03f2d_0    conda-forge

cryptography              3.4.7            py37h20c650d_0    conda-forge

cycler                    0.10.0                     py_2    conda-forge

debugpy                   1.4.1            py37hf2a7229_0    conda-forge

decorator                 5.1.0              pyhd8ed1ab_0    conda-forge

defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge

docutils                  0.17.1           py37h03978a9_0    conda-forge

doit                      0.33.1           py37hc8dfbb8_1    conda-forge

entrypoints               0.3             py37hc8dfbb8_1002    conda-forge

filelock                  3.0.12             pyh9f0ad1d_0    conda-forge

flake8                    3.9.2              pyhd8ed1ab_0    conda-forge

folium                    0.12.0             pyhd8ed1ab_1    conda-forge

freetype                  2.10.4               h546665d_1    conda-forge

glob2                     0.7                        py_0    conda-forge

holoviews                 1.14.4.post51+g73490cbf6           dev_0    <develop>

hvplot                    0.7.3                      py_0    pyviz

icu                       68.1                 h0e60522_0    conda-forge

idna                      3.1                pyhd3deb0d_0    conda-forge

importlib-metadata        4.8.1            py37h03978a9_0    conda-forge

importlib_metadata        4.8.1                hd8ed1ab_0    conda-forge

iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge

intel-openmp              2021.3.0          h57928b3_3372    conda-forge

ipykernel                 6.4.1            py37h4038f58_0    conda-forge

ipympl                    0.8.0              pyhd8ed1ab_0    conda-forge

ipython                   7.27.0           py37h4038f58_0    conda-forge

ipython_genutils          0.2.0                      py_1    conda-forge

ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge

jbig                      2.1               h8d14728_2003    conda-forge

jedi                      0.18.0           py37h03978a9_2    conda-forge

jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge

jpeg                      9d                   h8ffe710_0    conda-forge

json5                     0.9.5              pyh9f0ad1d_0    conda-forge

jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge

jupyter_client            7.0.3              pyhd8ed1ab_0    conda-forge

jupyter_core              4.8.1            py37h03978a9_0    conda-forge

jupyter_server            1.11.0             pyhd8ed1ab_0    conda-forge

jupyterlab                3.1.13             pyhd8ed1ab_0    conda-forge

jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge

jupyterlab_server         2.8.1              pyhd8ed1ab_0    conda-forge

jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge

keyring                   23.2.1           py37h03978a9_0    conda-forge

kiwisolver                1.3.2            py37h8c56517_0    conda-forge

lcms2                     2.12                 h2a16943_0    conda-forge

lerc                      2.2.1                h0e60522_0    conda-forge

libarchive                3.5.2                hb45042f_0    conda-forge

libblas                   3.9.0              11_win64_mkl    conda-forge

libcblas                  3.9.0              11_win64_mkl    conda-forge

libclang                  11.1.0          default_h5c34c98_1    conda-forge

libdeflate                1.8                  h8ffe710_0    conda-forge

libiconv                  1.16                 he774522_0    conda-forge

liblapack                 3.9.0              11_win64_mkl    conda-forge

liblief                   0.11.5               h0e60522_0    conda-forge

libpng                    1.6.37               h1d00b33_2    conda-forge

libsodium                 1.0.18               h8d14728_1    conda-forge

libtiff                   4.3.0                h0c97f57_0    conda-forge

libxml2                   2.9.12               hf5bbc77_0    conda-forge

lz4-c                     1.9.3                h8ffe710_1    conda-forge

lzo                       2.10              he774522_1000    conda-forge

m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge

m2-patch                  2.7.5                         2    conda-forge

m2w64-gcc-libgfortran     5.3.0                         6    conda-forge

m2w64-gcc-libs            5.3.0                         7    conda-forge

m2w64-gcc-libs-core       5.3.0                         7    conda-forge

m2w64-gmp                 6.1.0                         2    conda-forge

m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge

markdown                  3.3.4              pyhd8ed1ab_0    conda-forge

markupsafe                2.0.1            py37hcc03f2d_0    conda-forge

matplotlib                3.4.3            py37h03978a9_0    conda-forge

matplotlib-base           3.4.3            py37h4a79c79_0    conda-forge

matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge

mccabe                    0.6.1                      py_1    conda-forge

menuinst                  1.4.18           py37h03978a9_0    conda-forge

mistune                   0.8.4           py37hcc03f2d_1004    conda-forge

mkl                       2021.3.0           hb70f87d_564    conda-forge

more-itertools            8.10.0             pyhd8ed1ab_0    conda-forge

msys2-conda-epoch         20160418                      1    conda-forge

nbclassic                 0.3.2              pyhd8ed1ab_0    conda-forge

nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge

nbconvert                 6.1.0            py37h03978a9_1    conda-forge

nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge

nbsmoke                   0.5.0              pyh9f0ad1d_0    pyviz/label/dev

nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge

notebook                  6.4.4              pyha770c72_0    conda-forge

numpy                     1.21.2           py37h940b05c_0    conda-forge

olefile                   0.46               pyh9f0ad1d_1    conda-forge

openjpeg                  2.4.0                hb211442_1    conda-forge

openssl                   1.1.1l               h8ffe710_0    conda-forge

packaging                 21.0               pyhd8ed1ab_0    conda-forge

pandas                    1.3.3            py37h9386db6_0    conda-forge

pandoc                    2.14.2               h8ffe710_0    conda-forge

pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge

panel                     0.13.0a5.post18+gdef70ef8.dirty           dev_0    <develop>

param                     1.11.2a1                   py_0    pyviz/label/dev

parameterized             0.8.1              pyhd3deb0d_0    conda-forge

parso                     0.8.2              pyhd8ed1ab_0    conda-forge

pickleshare               0.7.5           py37hc8dfbb8_1002    conda-forge

pillow                    8.3.2            py37hd7d9ad0_0    conda-forge

pip                       21.2.4             pyhd8ed1ab_0    conda-forge

pkginfo                   1.7.1              pyhd8ed1ab_0    conda-forge

plotly                    5.3.1              pyhd8ed1ab_0    conda-forge

pluggy                    1.0.0            py37h03978a9_1    conda-forge

prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge

prompt-toolkit            3.0.20             pyha770c72_0    conda-forge

psutil                    5.8.0            py37hcc03f2d_1    conda-forge

py                        1.10.0             pyhd3deb0d_0    conda-forge

py-lief                   0.11.5           py37hf2a7229_0    conda-forge

pycodestyle               2.7.0              pyhd8ed1ab_0    conda-forge

pycosat                   0.6.3           py37hcc03f2d_1006    conda-forge

pycparser                 2.20               pyh9f0ad1d_2    conda-forge

pyct                      0.4.8                      py_0    pyviz/label/dev

pyct-core                 0.4.8                      py_0    pyviz/label/dev

pyctdev                   0.6.4                      py_0    pyviz

pyflakes                  2.3.1              pyhd8ed1ab_0    conda-forge

pygments                  2.10.0             pyhd8ed1ab_0    conda-forge

pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge

pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge

pyqt                      5.12.3           py37h03978a9_7    conda-forge

pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge

pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge

pyqtchart                 5.12             py37hf2a7229_7    conda-forge

pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge

pyrsistent                0.17.3           py37hcc03f2d_2    conda-forge

pysocks                   1.7.1            py37h03978a9_3    conda-forge

pytest                    6.2.5            py37h03978a9_0    conda-forge

pytest-cov                2.12.1             pyhd8ed1ab_0    conda-forge

python                    3.7.10          h7840368_101_cpython    conda-forge

python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge

python-libarchive-c       3.1              py37h03978a9_0    conda-forge

python_abi                3.7                     2_cp37m    conda-forge

pytz                      2021.1             pyhd8ed1ab_0    conda-forge

pyviz_comms               2.1.0                      py_0    pyviz/label/dev

pywin32                   301              py37hcc03f2d_0    conda-forge

pywin32-ctypes            0.2.0           py37h03978a9_1003    conda-forge

pywinpty                  1.1.4            py37h7f67f24_0    conda-forge

pyyaml                    5.4.1            py37hcc03f2d_1    conda-forge

pyzmq                     22.3.0           py37hcce574b_0    conda-forge

qt                        5.12.9               h5909a2a_4    conda-forge

readme_renderer           27.0               pyh9f0ad1d_0    conda-forge

requests                  2.26.0             pyhd3eb1b0_0  

requests-toolbelt         0.9.1                      py_0    conda-forge

requests-unixsocket       0.2.0                      py_0    conda-forge

rfc3986                   1.5.0              pyhd8ed1ab_0    conda-forge

ripgrep                   13.0.0               h7f3b576_0    conda-forge

ruamel_yaml               0.15.80         py37hcc03f2d_1004    conda-forge

scipy                     1.7.1            py37hb6553fb_0    conda-forge

send2trash                1.8.0              pyhd8ed1ab_0    conda-forge

setuptools                58.0.4           py37h03978a9_1    conda-forge

six                       1.16.0             pyh6c4a22f_0    conda-forge

sniffio                   1.2.0            py37h03978a9_1    conda-forge

soupsieve                 2.0.1            py37hc8dfbb8_0    conda-forge

sqlite                    3.36.0               h8ffe710_1    conda-forge

tbb                       2021.3.0             h2d74725_0    conda-forge

tenacity                  8.0.1              pyhd8ed1ab_0    conda-forge

terminado                 0.12.1           py37h03978a9_0    conda-forge

testpath                  0.5.0              pyhd8ed1ab_0    conda-forge

tk                        8.6.11               h8ffe710_1    conda-forge

toml                      0.10.2             pyhd8ed1ab_0    conda-forge

tornado                   6.1              py37hcc03f2d_1    conda-forge

tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge

traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge

twine                     3.4.2              pyhd8ed1ab_0    conda-forge

typing_extensions         3.10.0.2           pyha770c72_0    conda-forge

ucrt                      10.0.20348.0         h57928b3_0    conda-forge

urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge

vc                        14.2                 hb210afc_5    conda-forge

vs2015_runtime            14.29.30037          h902a5da_5    conda-forge

wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge

webencodings              0.5.1                      py_1    conda-forge

websocket-client          0.57.0           py37h03978a9_4    conda-forge

wheel                     0.37.0             pyhd8ed1ab_1    conda-forge

widgetsnbextension        3.5.1            py37h03978a9_4    conda-forge

win_inet_pton             1.1.0            py37h03978a9_2    conda-forge

winpty                    0.4.3                         4    conda-forge

xz                        5.2.5                h62dcd97_1    conda-forge

yaml                      0.2.5                he774522_0    conda-forge

zeromq                    4.3.4                h0e60522_1    conda-forge

zipp                      3.5.0              pyhd8ed1ab_0    conda-forge

zlib                      1.2.11            h62dcd97_1010    conda-forge

zstd                      1.5.0                h6255e5f_0    conda-forge

name: holoviz

channels:

  - pyviz

  - conda-forge

  - defaults

prefix: C:\Users\shh\miniconda3\envs\holoviz\envs\holoviz

```
</details>

#### Description of expected behavior and the observed behavior
I have a function which returns a hvplot which I want to be `responsive=True` so it can be used with `stretch_both` or in a template. But when I add it to a panel as a function without calling it or have it inside a template it sets the width and/or height to 0. When I move around the plot it gives an error.

If there is a workaround to this I would love to hear it.  

I'm also not completly sure if this is a panel or hvplot problem. 

#### Complete, minimal, self-contained example code that reproduces the issue
This is the same for all the following examples.
``` python
import hvplot.pandas  # noqa
import panel as pn
import pandas as pd

df = pd.DataFrame(range(100))
f = lambda: df.hvplot(responsive=True)

```

<details>
  <summary> <i>Example 1 </i></summary>

``` python
pn.panel(f, sizing_mode="stretch_both").servable()
```
![image](https://user-images.githubusercontent.com/19758978/134545285-88c4aa2f-f31c-4ff7-b04d-e5d08b313ab5.png)

</details>

<details>
  <summary> <i>Example 2</i></summary>

``` python
pn.panel(f(), sizing_mode="stretch_both").servable()  # This one works
```

![image](https://user-images.githubusercontent.com/19758978/134545981-33bf2482-26f4-4b06-9f1f-fda319639f7a.png)
</details>

<details>
  <summary> <i>Example 3</i></summary>

``` python
pn.template.FastListTemplate(main=f).servable()
```

![image](https://user-images.githubusercontent.com/19758978/134546317-f92b22ac-6fc1-4676-a000-3a314c1cc278.png)
</details>

<details>
  <summary> <i>Example 4</i></summary>

``` python
pn.template.FastListTemplate(main=f()).servable()
```

![image](https://user-images.githubusercontent.com/19758978/134546717-a31152ac-4fe0-43f6-a432-6a03c71adefd.png)

</details>

#### Stack traceback and/or browser JavaScript console output

<details>
  <summary> Stack traceback </summary>

``` python
2021-09-23 18:28:20,542 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '11104'}, 'attr': 'start', 'new': None}, {'kind': 'ModelChanged', 'model': {'id': '11104'}, 'attr': 'end', 'new': None}], 'references': []}
 error: ValueError("failed to validate Range1d(id='11104', ...).start: expected an element of either Float, Datetime or TimeDelta, got None")
Traceback (most recent call last):
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\server\protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\server\session.py", line 93, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\server\session.py", line 287, in _handle_patch
    message.apply_to_document(self.document, self)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_json(self, event_json, references, setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\events.py", line 
259, in handle_json
    handler(doc, event_json, references, setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\events.py", line 
467, in _handle_json
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\core\has_props.py", line 384, in set_from_json
    descriptor.set_from_json(self, json, models=models, setter=setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\core\property\descriptors.py", line 376, in set_from_json
    value = self.property.prepare_value(obj, self.name, self.property.from_json(json, models=models))
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\core\property\bases.py", line 365, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate Range1d(id='11104', ...).start: expected an element of either Float, Datetime or TimeDelta, got None

```

</details>

**Comment by Hoxbro** [comment]
If I add `pn.extension(sizing_mode="stretch_both")` to the start of the script it gives the following result for example 1 (no line but a lot of white space):
![image](https://user-images.githubusercontent.com/19758978/134811159-5d1547c6-2839-4625-b619-c94271d5f827.png)

And the theme show a line, but when I make the plot full screen it gives the same figure as with the simple example 1/2. So maybe it is related to sizing_mode missing when when calling a function somewhere.

**Comment by Hoxbro** [comment]
I can get it to work without a theme and in full screen mode inside a theme by using a combination of `hv.DynamicMaps` and `pn.panel` + `sizing_mode=stretch_mode` for the four examples
``` python
# Example 1
pn.panel(hv.DynamicMap(f), sizing_mode="stretch_both").servable()
```
``` python
# Example 2
pn.panel(f(), sizing_mode="stretch_both").servable()
```
``` python
# Example 3
pn.template.FastListTemplate(main=pn.panel(hv.DynamicMap(f), sizing_mode="stretch_both")).servable()
```
``` python
# Example 4
pn.template.FastListTemplate(main=pn.panel(f(), sizing_mode="stretch_both")).servable()
 ```

But the theme does still not work in "normal mode":
![image](https://user-images.githubusercontent.com/19758978/135137394-938596da-8d09-4e98-8a70-a93ae2ec3781.png)

I have been trying to solve the problem the last couple of days but seem to have hit a wall, so to fix the problem another person is properly needed.

**Comment by Hoxbro** [comment]
Finally, got all the examples to work by setting `responsive=False` for the templates. Which means that this is how to do all the examples.

```python
# Example 1
f = lambda: df.hvplot(responsive=True)
pn.panel(hv.DynamicMap(f), sizing_mode="stretch_both").servable()
```
```python
# Example 2
f = lambda: df.hvplot(responsive=True)
pn.panel(f(), sizing_mode="stretch_both").servable()
```
```python
# Example 3
f = lambda: df.hvplot(responsive=False)
pn.template.FastListTemplate(main=pn.panel(hv.DynamicMap(f), sizing_mode="stretch_both")).servable()
```
```python
# Example 4
f = lambda: df.hvplot(responsive=False)
pn.template.FastListTemplate(main=pn.panel(f(), sizing_mode="stretch_both")).servable()
```

Screenshot of templates working:
![image](https://user-images.githubusercontent.com/19758978/135638522-86a63585-d641-44e9-98da-2f5c9f171c01.png)

**Comment by MarcSkovMadsen** [comment]
+1 for making it easier to get `stretch_both`. It's almost always a challenge.

**Comment by Hoxbro** [comment]
The function can be replaced with `f = lambda: hv.Curve([0, 1, 2]).opts(responsive=True)` or `f = lambda: hv.Curve([0, 1, 2]).opts(responsive=False)`. 

I would like to take a look at this, but I have no idea where to start. Any help?
