### ISSUE TITLE
callback errors from a Trend widget on the Overview admin page

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#2793]
I saw these errors piling up while checking the Overview admin page and refreshing the app page multiple times rapidly.

`panel serve examples/reference/templates/Material.ipynb --admin --show`

```python
...
2021-09-29 15:52:02,405 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f80da07c790>>, <Task finished coro=<PeriodicCallback._periodic_callback() done, defined at /Users/mliquet/work/dev/panel/panel/io/callbacks.py:75> exception=UnsetValueError("TrendIndicator(id='1374', ...).source doesn't have a value set")>)
Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/Users/mliquet/work/dev/panel/panel/io/callbacks.py", line 87, in _periodic_callback
    self.callback()
  File "/Users/mliquet/work/dev/panel/panel/io/admin.py", line 264, in update_memory
    def update_memory(): memory.stream(get_mem())
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 772, in stream
    self.param.trigger(self._data_params[0])
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1595, in trigger
    self_.set_param(**dict(params, **triggers))
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/widgets/indicators.py", line 672, in _update_cds
    super()._update_cds(*events)
  File "/Users/mliquet/work/dev/panel/panel/util.py", line 390, in wrapped
    fn(self, *args, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 657, in _update_cds
    self._apply_update(events, msg, m.source, ref)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 234, in __get__
    raise UnsetValueError(f"{obj}.{self.name} doesn't have a value set")
bokeh.core.property.descriptors.UnsetValueError: TrendIndicator(id='1374', ...).source doesn't have a value set
2021-09-29 15:52:02,410 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f80da07c790>>, <Task finished coro=<PeriodicCallback._periodic_callback() done, defined at /Users/mliquet/work/dev/panel/panel/io/callbacks.py:75> exception=UnsetValueError("TrendIndicator(id='1376', ...).source doesn't have a value set")>)
Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/Users/mliquet/work/dev/panel/panel/io/callbacks.py", line 87, in _periodic_callback
    self.callback()
  File "/Users/mliquet/work/dev/panel/panel/io/admin.py", line 265, in update_cpu
    def update_cpu(): cpu.stream(get_cpu())
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 772, in stream
    self.param.trigger(self._data_params[0])
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1595, in trigger
    self_.set_param(**dict(params, **triggers))
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1526, in set_param
    self_._batch_call_watchers()
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1665, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/param/parameterized.py", line 1627, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/widgets/indicators.py", line 672, in _update_cds
    super()._update_cds(*events)
  File "/Users/mliquet/work/dev/panel/panel/util.py", line 390, in wrapped
    fn(self, *args, **kwargs)
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 657, in _update_cds
    self._apply_update(events, msg, m.source, ref)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/core/property/descriptors.py", line 234, in __get__
    raise UnsetValueError(f"{obj}.{self.name} doesn't have a value set")
bokeh.core.property.descriptors.UnsetValueError: TrendIndicator(id='1376', ...).source doesn't have a value set
```

**Comment by maximlt** [comment]
Just tried to reproduce that and couldn't, I'll leave the issue open for a while anyway and check whether it happens again or not.

**Comment by philippjfr** [comment]
Any luck? I too have seen this before but haven't been able to reproduce.

**Comment by maximlt** [comment]
Didn't happen again!
