### ISSUE TITLE
ReactiveHTML errors when text input only have numbers

### ISSUE THREAD

**Issue by hoxbro** [holoviz/panel#2810]
#### ALL software version info

``` yaml
panel  0.13.0a7
param  1.11.2a1
bokeh  2.4.0   
```

#### Description of expected behavior and the observed behavior
I have the following code, which errors when a number (int or float) is inserted into the text input.  I'm new to ReactiveHTML so it could be an error on my side. The issue is related to https://discourse.holoviz.org/t/how-to-press-enter-on-textinput-to-trigger-a-button/2899/4.

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import panel as pn
import param


class CustomLayout(pn.reactive.ReactiveHTML):

    username = param.String()

    _template = """
    <input id="username" value="${username}"></input>
    """

    _dom_events = {"username": ['change']}


CustomLayout().servable()
```

#### Stack traceback and/or browser JavaScript console output
``` python

 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '1002'}, 'attr': 'username', 'new': 1}], 'references': []}
 error: DeserializationError('String expected str, got 1 of type int')
Traceback (most recent call last):
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\server\protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\server\session.py", line 93, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\server\session.py", line 287, in _handle_patch
    message.apply_to_document(self.document, self)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_json(self, event_json, references, setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\events.py", line 
259, in handle_json
    handler(doc, event_json, references, setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\document\events.py", line 
467, in _handle_json
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\core\has_props.py", line 384, in set_from_json
    descriptor.set_from_json(self, json, models=models, setter=setter)
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\core\property\descriptors.py", line 376, in set_from_json
    value = self.property.prepare_value(obj, self.name, self.property.from_json(json, models=models))
  File "C:\Users\shh\miniconda3\envs\holoviz\lib\site-packages\bokeh\core\property\bases.py", line 535, in from_json
    raise DeserializationError(msg)
bokeh.core.property.bases.DeserializationError: String expected str, got 1 of type int
```

**Comment by philippjfr** [comment]
`ReactiveHTML` is actively recommended against so will no longer be supported. Use a `JSComponent` instead.
