### ISSUE TITLE
ValueError: HoloViews pane does not support objects of type 'Interactive'.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#2868]
Panel: 0.12.4, hvplot  0.7.3, holoviews 1.14.5

After having watched parts of Philipps 2021 Talk I was highly motivated to start using `.interactive` with Panel.

But it seems not to work. When I `panel serve` the script below I get 

```bash
ValueError: HoloViews pane does not support objects of type 'Interactive'.
Traceback (most recent call last):
  File "c:\repos\private\awesome-panel-introduction\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 197, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\awesome-panel-introduction\examples\script.py", line 26, in <module>
    component = pn.pane.HoloViews(pipeline, height=800)
  File "c:\repos\private\awesome-panel-introduction\.venv\lib\site-packages\panel\pane\holoviews.py", line 85, in __init__
    super().__init__(object, **params)
  File "c:\repos\private\awesome-panel-introduction\.venv\lib\site-packages\panel\pane\base.py", line 110, in __init__
    self._type_error(object)
  File "c:\repos\private\awesome-panel-introduction\.venv\lib\site-packages\panel\pane\base.py", line 119, in _type_error
    raise ValueError("%s pane does not support objects of type '%s'." %
ValueError: HoloViews pane does not support objects of type 'Interactive'.
```

![image](https://user-images.githubusercontent.com/42288570/139587768-a55ca65a-d18c-456c-852a-b4458de9bf1a.png)

```python
import pandas as pd
import hvplot.pandas
import panel as pn
pn.extension(sizing_mode="stretch_width")

url="https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD"
file="rows.csv"
try:
    seattle_bikes = pd.read_csv(file, parse_dates=["Date"]).set_index("Date")
except Exception:
    seattle_bikes = pd.read_csv(url, parse_dates=["Date"]).set_index("Date")
    seattle_bikes.to_csv(file)

rolling = pn.widgets.IntSlider(value=50, start=10, end=100)

pipeline = (
    seattle_bikes
    .interactive()
    .resample("D")
    .sum()
    .rolling(rolling, center=True, win_type='gaussian')
    .sum(std=10)
    .hvplot(line_dash=['solid', 'dashed', 'dotdash'])
)

component = pn.pane.HoloViews(pipeline, height=800)
pn.template.FastListTemplate(
    main=[component]
).servable()
```

**Comment by MarcSkovMadsen** [comment]
Ok. I understand now that the `Interactive` object is not a HoloViews objects. But `.holoviews()` is.

This works.

```python
import pandas as pd
import hvplot.pandas
import panel as pn

pn.extension(sizing_mode="stretch_width")

url = "https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD"
file = "rows.csv"
try:
    seattle_bikes = pd.read_csv(file, parse_dates=["Date"]).set_index("Date")
except Exception:
    seattle_bikes = pd.read_csv(url, parse_dates=["Date"]).set_index("Date")
    seattle_bikes.to_csv(file)

rolling = pn.widgets.IntSlider(value=50, start=10, end=100)

pipeline = (
    seattle_bikes.interactive()
    .resample("D")
    .sum()
    .rolling(rolling, center=True, win_type="gaussian")
    .sum(std=10)
    .hvplot(
        line_dash=["solid", "dashed", "dotdash"], responsive=True, height=400, title="Seattle Data"
    )
)

pn.template.FastListTemplate(
    sidebar=[pipeline.widgets()],
    main=[pn.panel(pipeline.holoviews(), sizing_mode="stretch_width")],
).servable()
```

**Comment by jbednar** [comment]
Isn't the issue that it needs a different Pane type, `pn.pane.Interactive` instead of `pn.pane.HoloViews` (see https://github.com/holoviz/panel/pull/1900)? I think this is an error people are likely to encounter the same as you did, so maybe we could add a special error check so that instead of `ValueError: HoloViews pane does not support objects of type 'Interactive'.` it says `ValueError: HoloViews pane does not support objects of type 'Interactive'; use 'pn.pane.Interactive' instead.`.

**Comment by MarcSkovMadsen** [comment]
Or use `pn.panel` instead.

**Comment by jbednar** [comment]
Yes, `pn.panel` works here, especially since the output of `.hvplot()` even without `.interactive` isn't always a HoloViews object; sometimes it's a Panel object (for certain cases not currently expressible in HoloViews, though I forget what those are).  But precisely because it's hard for people to predict what the type is, if they make a wrong but reasonable guess, I'd like us to anticipate that and give them good feedback when it occurs.
