### ISSUE TITLE
`Color` parameter on ReactiveHTML

### ISSUE THREAD

**Issue by Jhsmit** [holoviz/panel#3058]
I'm getting an error with a `param.Color` parameter on a `ReactiveHTML`

code:

```python
import param
from panel.reactive import ReactiveHTML
import panel as pn

class TestReactive(ReactiveHTML):

    bg_color = param.Color(
        default=None,
        doc="Color of the background"
    )

    _template = """
    <div id="container" style="width:100%; height:100%;"><p>test</p></div>
    """

if __name__ == '__main__' or __name__.startswith('bokeh_app'):
    test = TestReactive(
        height=500,
        sizing_mode='stretch_width',
    )

    tmpl = pn.template.FastListTemplate()
    tmpl.main.append(test)

    tmpl.servable()

```

Error:

```
  File "C:\Users\jhsmi\Miniconda3\envs\py38_panel\lib\site-packages\bokeh\core\property\bases.py", line 452, in _validate_type_param
    raise ValueError("setting 'help' on type parameters doesn't make sense")
ValueError: setting 'help' on type parameters doesn't make sense
```

When I change `Color` to, for example, `Number`,  I don't have any problems.

#### ALL software version info
```
panel==0.12.6
bokeh==2.4.2
Windows 10
```

**Comment by Hoxbro** [comment]
As a workaround you can change None to a color like red. 

``` python 
import param
from panel.reactive import ReactiveHTML
import panel as pn


class TestReactive(ReactiveHTML):

    bg_color = param.Color(default="red", doc="Color of the background")

    _template = """
        <div id="container" style="background-color: ${bg_color}; width:100%; height:100%;"><p>${bg_color}</p></div>
    """


if __name__ == "__main__" or __name__.startswith("bokeh_app"):
    test = TestReactive(
        height=500,
        sizing_mode="stretch_width",
    )

    tmpl = pn.template.FastListTemplate()
    tmpl.main.append(test.param.bg_color)
    tmpl.main.append(test)

    tmpl.servable()
```

**Comment by jbednar** [comment]
Thanks, @Hoxbro. Sounds like the title of this issue could be made more specific to focus on the use of None in such a case.

**Comment by maximlt** [comment]
Running this snippet is enough to get the error:
```python
import param
from panel.reactive import ReactiveHTML

class TestReactive(ReactiveHTML):

    bg_color = param.Color(default=None)

    _template = """
    <div id="container" style="width:100%; height:100%;"><p>test</p></div>
    """
```

And here's the full traceback:
```
Traceback (most recent call last):
  File "issue_reactivehtml_color.py", line 5, in <module>
    class TestReactive(ReactiveHTML):
  File "/Users/mliquet/work/dev/panel/panel/reactive.py", line 1154, in __init__
    mcs, name=model_name, ignore=ignored, types=types
  File "/Users/mliquet/work/dev/panel/panel/links.py", line 127, in construct_data_model
    bk_prop = bp.Nullable(bk_prop, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/core/property/nullable.py", line 46, in __init__
    super().__init__(type_param, default=default, help=help, serialized=serialized, readonly=readonly)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/core/property/bases.py", line 471, in __init__
    self.type_param = self._validate_type_param(type_param)
  File "/Users/mliquet/miniconda3/envs/panel-dev37/lib/python3.7/site-packages/bokeh/core/property/bases.py", line 452, in _validate_type_param
    raise ValueError("setting 'help' on type parameters doesn't make sense")
ValueError: setting 'help' on type parameters doesn't make sense
```
