### ISSUE TITLE
DatetimePicker raises CalendarDate parameter 'start' only takes date types

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3107]
Panel 0.12.6

## Issue

```python
import pandas as pd
import panel as pn

start_date = pd.Timestamp('2022-01-17 00:00:00')

pn.widgets.DatetimePicker(
    value=start_date,
    enable_seconds=False,
    name="datetime",
    start=start_date,
    end=start_date,
).servable()
```

```bash
$ python 'script.py'
Traceback (most recent call last):
  File "script.py", line 6, in <module>
    pn.widgets.DatetimePicker(
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\panel\widgets\input.py", line 191, in __init__
    super().__init__(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\panel\widgets\base.py", line 52, in __init__
    super().__init__(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\panel\reactive.py", line 79, in __init__
    super().__init__(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\panel\viewable.py", line 538, in __init__
    super().__init__(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\panel\viewable.py", line 399, in __init__
    super().__init__(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\panel\viewable.py", line 230, in __init__
    super().__init__(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\parameterized.py", line 3146, in __init__
    self.param._setup_params(**params)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\parameterized.py", line 1363, in override_initialization
    fn(parameterized_instance, *args, **kw)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\parameterized.py", line 1616, in _setup_params
    setattr(self, name, val)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\parameterized.py", line 353, in _f
    return f(self, obj, val)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\__init__.py", line 621, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\parameterized.py", line 353, in _f
    return f(self, obj, val)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\parameterized.py", line 1177, in __set__
    self._validate(val)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\__init__.py", line 905, in _validate
    self._validate_value(val, self.allow_None)
  File "C:\repos\trading_analytics\fumo-engine\.venv\lib\site-packages\param\__init__.py", line 1948, in _validate_value
    raise ValueError("CalendarDate parameter %r only takes date types." % self.name)
ValueError: CalendarDate parameter 'start' only takes date types.
```

## Cause

`value` is `Date` parameter. `start` and `end` are `CalendarDate` parameters.

![image](https://user-images.githubusercontent.com/42288570/149721497-631ef614-0076-46f0-8fce-778b3fac9110.png)

![image](https://user-images.githubusercontent.com/42288570/149721529-cb90216c-4dcb-4252-8f35-a7f96b2e6167.png)

## Discussion

Change `start` and `end` parameters to `Date` parameters then no longer raises error. But validation on an hourly level is not respected. Don't know if that is a Panel or Bokeh problem.

```python
import pandas as pd
import panel as pn
import param

start_date = pd.Timestamp('2022-01-17 02:00:00')
end_date = pd.Timestamp('2022-01-18 10:00:00')

class DatetimePickerFix(pn.widgets.DatetimePicker):
    start = param.Date(default=None)
    end = param.Date(default=None)

DatetimePickerFix(
    value=start_date,
    enable_seconds=False,
    name="datetime",
    start=start_date,
    end=end_date,
).servable()
```

I am allow to set the `value` to `2022-01-17 00:00:00` even though its below the `start` bound.

![image](https://user-images.githubusercontent.com/42288570/149722299-c82030a8-3536-4d71-b9d3-d0506876a110.png)

------

The documentation correctly mentions that `start` and `end` are date. So things are working according to the documentation.

![image](https://user-images.githubusercontent.com/42288570/149722927-9f0b8473-5638-4bf5-83e9-00f68ffebc97.png)

**Comment by Hoxbro** [comment]
The problem is that [flatpickr](https://flatpickr.js.org/options/) can only disable on a date basis. Therefore, when I implemented the widget I chose to only make these options available as dates.

**Comment by MarcSkovMadsen** [comment]
Ok. Will close. Thanks for the feedback @Hoxbro
