### ISSUE TITLE
periodic_callback not robust. Raises exceptions when browser tab refreshed or closed.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3113]
Panel 0.12.6, Browser: Edge

I would like to look into performance of streaming data apps.

I noticed that Panel does not seem very robust to the user refreshing or closing the tab. It logs a lot of messages and exceptions

https://user-images.githubusercontent.com/42288570/150005855-13dc5aac-20a3-43b0-b025-66ea90e1f8ff.mp4

```bash
2022-01-18 20:25:10,203 Failed sending message as connection was closed
2022-01-18 20:25:10,206 Failed sending message as connection was closed
2022-01-18 20:25:10,207 Failed sending message as connection was closed
2022-01-18 20:25:10,207 Failed sending message as connection was closed
2022-01-18 20:25:10,210 Failed sending message as connection was closed
2022-01-18 20:25:10,211 Failed sending message as connection was closed
2022-01-18 20:25:10,211 Failed sending message as connection was closed
2022-01-18 20:25:10,212 Failed sending message as connection was closed
2022-01-18 20:25:10,215 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x00000213D60B03D0>>, <Task finished name='Task-25534' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at c:\repos\private\data-app-performance\.venv\lib\site-packages\bokeh\server\session.py:77> exception=WebSocketClosedError()>)
Traceback (most recent call last):
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback  
    ret = callback()
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\bokeh\server\session.py", line 97, in _needs_document_lock_wrapper
    result = await result
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\tornado\gen.py", line 216, in wrapper
    result = ctx_run(func, *args, **kwargs)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\reactive.py", line 279, in _change_coroutine
    self._change_event(doc)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\reactive.py", line 289, in _change_event  
    self._process_events(events)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\reactive.py", line 258, in _process_events
    state.busy = True
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 353, in _f        
    return f(self, obj, val)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 1228, in __set__  
    obj.param._call_watcher(watcher, event)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 2018, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 2000, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 649, in caller    
    return function()
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 387, in _depends  
    return func(*args, **kw)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\io\state.py", line 119, in _update_busy   
    indicator.value = self.busy
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 351, in _f        
    instance_param.__set__(obj, val)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 353, in _f        
    return f(self, obj, val)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 1228, in __set__  
    obj.param._call_watcher(watcher, event)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 2018, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\param\parameterized.py", line 2000, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\reactive.py", line 253, in _param_change  
    self._apply_update(events, msg, model, ref)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\reactive.py", line 207, in _apply_update  
    self._update_model(events, msg, root, model, doc, comm)
  File "C:\Program Files\Python39\lib\contextlib.py", line 124, in __exit__
    next(self.gen)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\panel\io\server.py", line 452, in unlocked      
    WebSocketHandler.write_message(socket, msg.header_json)
  File "c:\repos\private\data-app-performance\.venv\lib\site-packages\tornado\websocket.py", line 337, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2022-01-18 20:25:10,266 Failed sending message as connection was closed
2022-01-18 20:25:10,267 Failed sending message as connection was closed
2022-01-18 20:25:10,268 Failed sending message as connection was closed
2022-01-18 20:25:10,269 Failed sending message as connection was closed
2022-01-18 20:25:10,270 Failed sending message as connection was closed
2022-01-18 20:25:10,270 Failed sending message as connection was closed
2022-01-18 20:25:10,271 Failed sending message as connection was closed
2022-01-18 20:25:10,272 Failed sending message as connection was closed
2022-01-18 20:25:10,273 Failed sending message as connection was closed
2022-01-18 20:25:10,273 Failed sending message as connection was closed
2022-01-18 20:25:10,274 Failed sending message as connection was closed
2022-01-18 20:25:10,275 Failed sending message as connection was closed
2022-01-18 20:25:10,276 Failed sending message as connection was closed
2022-01-18 20:25:10,276 Failed sending message as connection was closed
2022-01-18 20:25:10,277 Failed sending message as connection was closed
2022-01-18 20:25:10,278 Failed sending message as connection was closed
2022-01-18 20:25:10,278 Failed sending message as connection was closed
2022-01-18 20:25:10,279 Failed sending message as connection was closed
2022-01-18 20:25:10,280 Failed sending message as connection was closed
2022-01-18 20:25:10,280 Failed sending message as connection was closed
2022-01-18 20:25:10,281 Failed sending message as connection was closed
2022-01-18 20:25:10,282 Failed sending message as connection was closed
2022-01-18 20:25:10,282 Failed sending message as connection was closed
2022-01-18 20:25:10,283 Failed sending message as connection was closed
2022-01-18 20:25:10,284 Failed sending message as connection was closed
2022-01-18 20:25:10,285 Failed sending message as connection was closed
2022-01-18 20:25:10,286 Failed sending message as connection was closed
2022-01-18 20:25:10,286 Failed sending message as connection was closed
2022-01-18 20:25:10,287 Failed sending message as connection was closed
2022-01-18 20:25:10,287 Failed sending message as connection was closed
2022-01-18 20:25:10,288 Failed sending message as connection was closed
2022-01-18 20:25:10,289 Failed sending message as connection was closed
2022-01-18 20:25:10,290 Failed sending message as connection was closed
2022-01-18 20:25:10,290 Failed sending message as connection was closed
2022-01-18 20:25:10,291 Failed sending message as connection was closed
2022-01-18 20:25:10,291 Failed sending message as connection was closed
2022-01-18 20:25:10,292 Failed sending message as connection was closed
2022-01-18 20:25:10,293 Failed sending message as connection was closed
2022-01-18 20:25:10,293 Failed sending message as connection was closed
2022-01-18 20:25:10,294 Failed sending message as connection was closed
2022-01-18 20:25:10,295 Failed sending message as connection was closed
2022-01-18 20:25:10,295 Failed sending message as connection was closed
2022-01-18 20:25:10,296 Failed sending message as connection was closed
2022-01-18 20:25:10,297 Failed sending message as connection was closed
2022-01-18 20:25:10,298 Failed sending message as connection was closed
2022-01-18 20:25:10,299 Failed sending message as connection was closed
2022-01-18 20:25:10,299 Failed sending message as connection was closed
2022-01-18 20:25:10,300 Failed sending message as connection was closed
2022-01-18 20:25:10,301 Failed sending message as connection was closed
2022-01-18 20:25:10,302 Failed sending message as connection was closed
2022-01-18 20:25:10,303 Failed sending message as connection was closed
2022-01-18 20:25:10,487 Failed sending message as connection was closed
2022-01-18 20:25:10,490 Failed sending message as connection was closed
2022-01-18 20:25:10,536 Failed sending message as connection was closed
2022-01-18 20:25:10,540 Failed sending message as connection was closed
2022-01-18 20:25:10,540 Failed sending message as connection was closed
2022-01-18 20:25:10,540 Failed sending message as connection was closed
2022-01-18 20:25:10,541 WebSocket connection closed: code=None, reason=None
c:\repos\private\data-app-performance\.venv\lib\site-packages\bokeh\util\tornado.py:199: RuntimeWarning:

coroutine 'WSHandler.send_message' was never awaited
````

## Discussion

My hypothesis is that this puts additional strain on the server. I believe its just a matter of better error handling.

Additionally its also a matter of trust in the server. If it raises a lot of errors just because the user refreshes or closes the tab then it makes you wonder if the server is ready for production. Or using Panel for streaming is a good idea.

## Code

```python
import datetime
import random

import plotly.express as px

x = [datetime.datetime.now()]
y = [random.randint(0, 100)]
plot_count = 3


def update_data(x=x, y=y, window=50):
    next_x = datetime.datetime.now()
    next_y = random.randint(0, 100)
    x.append(next_x)
    y.append(next_y)

    if len(x) > window:
        x[:]=x[len(x)-window:]
        y[:]=y[len(y)-window:]

def get_plot(x, y):
    return px.line(x=x, y=y, height=300)


import panel as pn

pn.extension("plotly", sizing_mode="stretch_width", template="fast")

window = pn.widgets.IntSlider(value=50, start=10, end=100, name="Window").servable(area="sidebar")

plot1 = pn.pane.Plotly(get_plot(x, y))
plot2 = pn.pane.Plotly(get_plot(x, y))
plot3 = pn.pane.Plotly(get_plot(x, y))
update_stat = pn.widgets.IntInput(disabled=True, name="Realized Update Frequency")

def update():
    update_data(window=window.value)
    plot = get_plot(x, y)
    plot1.object = plot
    plot2.object = plot
    plot3.object = plot
    update_stat.value = int((x[-1]-x[0]).total_seconds()*1000/len(x))


periodic_callback = pn.state.add_periodic_callback(update, 500)
period = pn.widgets.IntInput.from_param(periodic_callback.param.period, name="Update Frequency")
period.servable(area="sidebar")
update_stat.servable(area="sidebar")
plot1.servable(title="Panel - Slider with Plot Performance Test")
plot2.servable(title="Panel - Slider with Plot Performance Test")
plot3.servable(title="Panel - Slider with Plot Performance Test")
```

**Comment by philippjfr** [comment]
I think for now we should just handle the error appropriately and/or check if the socket is closed before sending anything on it. I think bokeh folks have long discussed having some mechanism by which a client (be it a browser or some other client) can reconnect to a session after it has been closed. Therefore we should continue to have sessions process updates to the models until they are formally marked for cleanup.
