### ISSUE TITLE
Tabulator sort by index raise Error when pagination="remote"

### ISSUE THREAD

**Issue by xavArtley** [holoviz/panel#3125]
MRE:
```python
import panel as pn
import numpy as np
import pandas as pd
pn.extension("tabulator")

df = pd.DataFrame(np.random.rand(10,2), columns=["X1","X2"])
pn.widgets.Tabulator(df, pagination="remote")
```
![tabulator_bug_sort_index](https://user-images.githubusercontent.com/18531147/150348245-ed50137b-f215-42ed-adc2-92d010a8aed1.gif)

traceback:
```
Traceback (most recent call last):
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\pyviz_comms\__init__.py", line 325, in _handle_msg
    self._on_msg(msg)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\viewable.py", line 273, in _on_msg
    doc.unhold()
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\document.py", line 799, in unhold
    self.callbacks.unhold()
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\document\callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\bokeh\util\callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\reactive.py", line 316, in _comm_change
    self._schedule_change(doc, comm)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\reactive.py", line 303, in _schedule_change
    self._change_event(doc)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\reactive.py", line 297, in _change_event
    self._process_events(events)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\reactive.py", line 1041, in _process_events
    super(ReactiveData, self)._process_events(events)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\reactive.py", line 263, in _process_events
    self.param.update(**self_events)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 1877, in update
    self_._batch_call_watchers()
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 2038, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\param\parameterized.py", line 2000, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\widgets\tables.py", line 1168, in _update_cds
    super()._update_cds(*events)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\util.py", line 368, in wrapped
    fn(self, *args, **kwargs)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\widgets\tables.py", line 198, in _update_cds
    self._processed, data = self._get_data()
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\widgets\tables.py", line 998, in _get_data
    df = self._sort_df(df)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\panel\widgets\tables.py", line 988, in _sort_df
    return df.sort_values(
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\pandas\core\frame.py", line 5294, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "D:\CIVA_RP\CIVA_B_2021\civa-rep\ProjetCIVA\ceaComponents\dev\python\lib\site-packages\pandas\core\generic.py", line 1563, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'index'
```

**Comment by maximlt** [comment]
I can no longer reproduce this issue so I will close it. It has very likely been fixed by the recent fixes and changes made to the widget.
