### ISSUE TITLE
jinja2 Markup import has changed

### ISSUE THREAD

**Issue by IainHammond** [holoviz/panel#3257]
#### ALL software version info
Python 3.7.11 and panel 0.12.1

#### Description of expected behavior and the observed behavior
jinja2 updated on 24th March 2022 and the Markup import must be imported from markupmafe

#### Complete, minimal, self-contained example code that reproduces the issue
io/resources.py line 24
```
from jinja2 import Environment, Markup, FileSystemLoader
```
Suggest changing this to: 
`from jinja2 import Environment, FileSystemLoader`
`from markupsafe import Markup`

#### Screenshots or screencasts of the bug in action
<img width="1388" alt="Screen Shot 2022-03-25 at 11 38 12 am" src="https://user-images.githubusercontent.com/63645203/160058676-d28f6e05-a764-408b-a387-8243f6e42422.png">

**Comment by akaszynski** [comment]
Just noticed this issue as well in `pyvista` builds, which use on `panel` for documentation.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pv/lib/python3.8/site-packages/panel/__init__.py", line 1, in <module>
    from . import layout # noqa
  File "/tmp/pv/lib/python3.8/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/tmp/pv/lib/python3.8/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/tmp/pv/lib/python3.8/site-packages/panel/layout/base.py", line 11, in <module>
    from ..io.model import hold
  File "/tmp/pv/lib/python3.8/site-packages/panel/io/__init__.py", line 9, in <module>
    from ..config import config
  File "/tmp/pv/lib/python3.8/site-packages/panel/config.py", line 21, in <module>
    from .io.notebook import load_notebook
  File "/tmp/pv/lib/python3.8/site-packages/panel/io/notebook.py", line 39, in <module>
    from .resources import Bundle, Resources, _env, bundle_resources
  File "/tmp/pv/lib/python3.8/site-packages/panel/io/resources.py", line 24, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (/tmp/pv/lib/python3.8/site-packages/jinja2/__init__.py)
```

Pertinent packages:
```
$ pip list
panel                         0.12.6
Jinja2                        3.1.0
```

**Comment by celliern** [comment]
Same error on an internal project : current workaround was to explicitely pin the Jinja2 requirements

**Comment by MarcSkovMadsen** [comment]
Just experienced this too. My site awesome-panel.org failed deployment

![image](https://user-images.githubusercontent.com/42288570/160230334-17bdb732-9672-4995-8c6b-d93ad91fe944.png)

![image](https://user-images.githubusercontent.com/42288570/160230344-2a2a403b-14a9-4fdd-8b97-bb96aaed8971.png)

**Comment by philippjfr** [comment]
Yeah may just have to push out a 0.12.7 release before the 0.13 release next week.
