### ISSUE TITLE
KeyError when sorting Tabulator

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/panel#3315]
When sorting the tabulator widget, a KeyError is raised.

``` python
import pandas as pd
import panel as pn

pn.extension("tabulator")

df = pd.DataFrame(range(10))
table = pn.widgets.Tabulator(df)
pn.panel(table).servable()

``` 

https://user-images.githubusercontent.com/19758978/161609012-4edf50a5-3f91-445c-8e58-5865714ea6b0.mp4

Error message

``` log
2022-04-04 20:29:46,160 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7fcd05bbdf70>>, <Task finished name='Task-1681' coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/bokeh/server/session.py:77> exception=KeyError('index')>)
Traceback (most recent call last):
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/bokeh/server/session.py", line 97, in _needs_document_lock_wrapper
    result = await result
  File "/home/shh/Development/holoviz/panel/panel/reactive.py", line 284, in _change_coroutine
    self._change_event(doc)
  File "/home/shh/Development/holoviz/panel/panel/reactive.py", line 298, in _change_event
    self._process_events(events)
  File "/home/shh/Development/holoviz/panel/panel/reactive.py", line 1010, in _process_events
    super(ReactiveData, self)._process_events(events)
  File "/home/shh/Development/holoviz/panel/panel/reactive.py", line 264, in _process_events
    self.param.update(**self_events)
  File "/home/shh/Development/holoviz/param/param/parameterized.py", line 1898, in update
    self_._batch_call_watchers()
  File "/home/shh/Development/holoviz/param/param/parameterized.py", line 2059, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/shh/Development/holoviz/param/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/shh/Development/holoviz/panel/panel/widgets/tables.py", line 1248, in _update_cds
    super()._update_cds(*events)
  File "/home/shh/Development/holoviz/panel/panel/util.py", line 379, in wrapped
    fn(self, *args, **kwargs)
  File "/home/shh/Development/holoviz/panel/panel/widgets/tables.py", line 204, in _update_cds
    self._processed, data = self._get_data()
  File "/home/shh/Development/holoviz/panel/panel/widgets/tables.py", line 1070, in _get_data
    return super()._get_data()
  File "/home/shh/Development/holoviz/panel/panel/widgets/tables.py", line 438, in _get_data
    df = self._sort_df(df)
  File "/home/shh/Development/holoviz/panel/panel/widgets/tables.py", line 257, in _sort_df
    return df.sort_values(
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/pandas/core/frame.py", line 6307, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "/home/shh/miniconda3/envs/holoviz/lib/python3.8/site-packages/pandas/core/generic.py", line 1848, in _get_label_or_level_values
    raise KeyError(key)
```

**Comment by Hoxbro** [comment]
The PR only fixes the sorting of the index, not when the column name is not a string.
