### ISSUE TITLE
allow pd.Series/pd.DataFrame (with one column) in pn.widgets.Select

### ISSUE THREAD

**Issue by raybellwaves** [holoviz/panel#3453]
#### Is your feature request related to a problem? Please describe.

Moving from a streamlit dashboard to a panel dashboard. In streamlit one can do:
```
value = st.selectbox("name", PandasLike)
```
where `PandasLike` is a `pandas.core.frame.DataFrame` or a `pandas.core.series.Series`

In `panel` with `pn.widgets.Select(name="name", options=PandasLike)` one gets a `ValueError: ClassSelector parameter 'options' value must be an instance of (dict, list), not ...`

#### Describe the solution you'd like
One seemlessly passes these types into `pn.widgets.Select` and it convert the values to a list internally.

#### Describe alternatives you've considered
Currently have to pass `list(s)` or `list(df["COL"])` to `options`

#### To reproduce

st.py:
```
import pandas as pd
import streamlit as st

s = pd.Series([1, 2])
value = st.selectbox("value s:", s)

df = s.to_frame()
value = st.selectbox("value df:", df)
```

```
streamlit run st.py
```
![Screen Shot 2022-04-25 at 4 29 22 PM](https://user-images.githubusercontent.com/17162724/165169686-fba38154-2c9d-4e0d-a79f-165780b999de.png)

pn.py:
```
import pandas as pd
import panel as pn

s = pd.Series([1, 2])
value = pn.widgets.Select("value s:", s).serveable()
```

```
ValueError: ClassSelector parameter 'options' value must be an instance of (dict, list), not 0 1 1 2 dtype: int64.
Traceback (most recent call last):
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/Users/ray/Documents/Projects/shipping_backtrack/norm_dashboard/test.py", line 5, in <module>
    value = pn.widgets.Select(name="value s:", options=s).serveable()
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/widgets/select.py", line 140, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/widgets/select.py", line 58, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/widgets/base.py", line 52, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/reactive.py", line 79, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/viewable.py", line 538, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/viewable.py", line 399, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/panel/viewable.py", line 230, in __init__
    super().__init__(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/parameterized.py", line 3146, in __init__
    self.param._setup_params(**params)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/parameterized.py", line 1363, in override_initialization
    fn(parameterized_instance, *args, **kw)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/parameterized.py", line 1616, in _setup_params
    setattr(self, name, val)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/parameterized.py", line 353, in _f
    return f(self, obj, val)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/parameterized.py", line 1177, in __set__
    self._validate(val)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/__init__.py", line 1327, in _validate
    self._validate_class_(val, self.class_, self.is_instance)
  File "/Users/ray/miniconda3/envs/main/lib/python3.9/site-packages/param/__init__.py", line 1339, in _validate_class_
    raise ValueError(
ValueError: ClassSelector parameter 'options' value must be an instance of (dict, list), not 0    1
1    2
dtype: int64.
```

**Comment by maximlt** [comment]
According to [streamlit's docs](https://docs.streamlit.io/library/api-reference/widgets/st.selectbox), if the options is a Pandas DataFrame then the first column is selected. I'm not convinced by this, it doesn't feel really intuitive. I'd prefer just supporting Pandas Series and Indexes, and Numpy Arrays.

**Comment by MarcSkovMadsen** [comment]
+1. This would be a really great UX improvement. I agree with @maximlt comment.

For me I would like the below to work

```python
import panel as pn
import pandas as pd
import numpy as np

pn.extension()

data1 = pd.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})

pn.widgets.Select(options=np.array([1, 2, 3]))
pn.widgets.Select(options=data1["x"].unique())
pn.widgets.Select(options=data1["x"])
```
