### ISSUE TITLE
RuntimeError("Patched curdoc has been previously destroyed")

### ISSUE THREAD

**Issue by Julien76** [holoviz/panel#3552]
As mentioned in the discussion https://github.com/holoviz/panel/pull/3228, the `RuntimeError("Patched curdoc has been previously destroyed")` is still occurring in Panel 0.13.x.

As mentioned in #3225, this issue is difficult to reproduce so I'm pasting the same error log as in #3225 

```
2022-03-04 09:04:02,108;INFO;Request URL: '[https://<REMOVED BY ME>.blob.core.windows.net/runs?restype=REDACTED&comp=REDACTED&marker=REDACTED&include=REDACTED'/nRequest](https://<REMOVED BY ME>.blob.core.windows.net/runs?restype=REDACTED&comp=REDACTED&marker=REDACTED&include=REDACTED%27/nRequest) method: 'GET'/nRequest headers:/n    'x-ms-version': 'REDACTED'/n    'Accept': 'application/xml'/n    'User-Agent': 'azsdk-python-storage-blob/12.9.0 Python/3.7.2 (Linux-5.4.0-1070-azure-x86_64-with-debian-9.8)'/n    'x-ms-date': 'REDACTED'/n    'x-ms-client-request-id': '0911dc44-9b9a-11ec-89ae-028d771633e0'/n    'Authorization': 'REDACTED'/nNo body was attached to the request
2022-03-04 09:04:02,338 Failed to run session creation hooks RuntimeError('Patched curdoc has been previously destroyed')

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/bokeh/server/contexts.py", line 239, in create_session_if_needed

    await self._application.on_session_created(session_context)

  File "/usr/local/lib/python3.7/site-packages/panel/io/server.py", line 169, in on_session_created

    cb(session_context)

  File "/usr/local/lib/python3.7/site-packages/panel/io/server.py", line 118, in _initialize_session_info

    if config.session_history == 0 or session_id in sessions:

  File "/usr/local/lib/python3.7/site-packages/panel/config.py", line 237, in __getattribute__

    params = super().__getattribute__('param')

  File "/usr/local/lib/python3.7/site-packages/param/parameterized.py", line 2623, in param

    return Parameters(self.__class__, self=self)

  File "/usr/local/lib/python3.7/site-packages/panel/config.py", line 241, in __getattribute__

    if state.curdoc and state.curdoc not in session_config:

  File "/usr/local/lib/python3.7/site-packages/panel/io/state.py", line 348, in curdoc

    elif _curdoc().session_context:

  File "/usr/local/lib/python3.7/site-packages/bokeh/io/doc.py", line 62, in curdoc

    raise RuntimeError("Patched curdoc has been previously destroyed")

RuntimeError: Patched curdoc has been previously destroyed
```

**Comment by philippjfr** [comment]
>RuntimeError("Patched curdoc has been previously destroyed") is still occurring in Panel 0.13.x.

Thanks for the report. What exact version have you tested with? The only version that has actually been released is 0.13.0 and I was about to tag 0.13.1 with the fix. I'll hold off on releasing until you confirm whether you've tried dev releases or not.

**Comment by Julien76** [comment]
I have tested with 0.13.0.
As it seems very random, I cannot reproduce it. It happens once or twice a week currently.

**Comment by philippjfr** [comment]
Okay, thank you. I'll release 0.13.1 with a fix shortly then.

**Comment by epifanio** [comment]
I am having the same error with a panel application - the log says: 

```
seaice_bokeh.1.skz790e9i1a1@swarm    | 2022-11-30 09:55:53,227 Failed to run session creation hooks RuntimeError('Patched curdoc has been previously destroyed')
seaice_bokeh.1.skz790e9i1a1@swarm    | Traceback (most recent call last):
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/bokeh/server/contexts.py", line 239, in create_session_if_needed
seaice_bokeh.1.skz790e9i1a1@swarm    |     await self._application.on_session_created(session_context)
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/panel/io/server.py", line 275, in on_session_created
seaice_bokeh.1.skz790e9i1a1@swarm    |     cb(session_context)
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/panel/io/server.py", line 161, in _initialize_session_info
seaice_bokeh.1.skz790e9i1a1@swarm    |     history = -1 if config._admin else config.session_history
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/panel/config.py", line 339, in __getattribute__
seaice_bokeh.1.skz790e9i1a1@swarm    |     params = super().__getattribute__('param')
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/param/parameterized.py", line 3178, in param
seaice_bokeh.1.skz790e9i1a1@swarm    |     return Parameters(self.__class__, self=self)
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/panel/config.py", line 343, in __getattribute__
seaice_bokeh.1.skz790e9i1a1@swarm    |     curdoc = state.curdoc
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/panel/io/state.py", line 835, in curdoc
seaice_bokeh.1.skz790e9i1a1@swarm    |     doc = curdoc_locked()
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/panel/io/state.py", line 70, in curdoc_locked
seaice_bokeh.1.skz790e9i1a1@swarm    |     doc = _curdoc()
seaice_bokeh.1.skz790e9i1a1@swarm    |   File "/opt/venv/lib/python3.10/site-packages/bokeh/io/doc.py", line 62, in curdoc
seaice_bokeh.1.skz790e9i1a1@swarm    |     raise RuntimeError("Patched curdoc has been previously destroyed")
seaice_bokeh.1.skz790e9i1a1@swarm    | RuntimeError: Patched curdoc has been previously destroyed
```

full log:  https://gist.github.com/epifanio/3570a484095ea49fd4f0c5ac70e74d32

```python
Python 3.10.5 (main, Aug  2 2022, 11:04:27) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import panel
>>> panel.__version__
'0.14.0'
>>> import bokeh
>>> bokeh.__version__
'2.4.3'
>>> 

```

**Comment by philippjfr** [comment]
Can you try 0.14.1 @epifanio?

**Comment by philippjfr** [comment]
This was patched in https://github.com/holoviz/panel/commit/a7f880f02f65d576656c17e9d0fa9f451dc7bc1a

**Comment by epifanio** [comment]
I am rebuilding the docker image for this app, making sure newer version are used, and I will test it - however, the crash was happening on a (maybe) random base - after one month of crash-free runtime
