### ISSUE TITLE
Echarts not work for maps

### ISSUE THREAD

**Issue by wybert** [holoviz/panel#3742]
The code,
```python
import panel as pn
pn.extension('echarts')
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.faker import Faker
from pyecharts.globals import ChartType

c = (
    Geo()
    .add_schema(maptype="china")
    .add(
        "geo",
        [list(z) for z in zip(Faker.provinces, Faker.values())],
        type_=ChartType.HEATMAP,
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(),
        title_opts=opts.TitleOpts(title="Geo-HeatMap"),
    )
)
print(type(c))
echart_pane = pn.pane.ECharts(c, height=480, width=640)
echart_pane
```
I got,

> <class 'pyecharts.charts.basic_charts.geo.Geo'>
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/site-packages/IPython/core/formatters.py:973, in MimeBundleFormatter.__call__(self, obj, include, exclude)
    970     method = get_real_method(obj, self.print_method)
    972     if method is not None:
--> 973         return method(include=include, exclude=exclude)
    974     return None
    975 else:

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/site-packages/panel/viewable.py:661, in Viewable._repr_mimebundle_(self, include, exclude)
    659 doc = Document()
    660 comm = state._comm_manager.get_server_comm()
--> 661 model = self._render_model(doc, comm)
    662 ref = model.ref['id']
    663 manager = CommManager(comm_id=comm.id, plot_id=ref)

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/site-packages/panel/viewable.py:507, in Renderable._render_model(self, doc, comm)
    505 if comm is None:
    506     comm = state._comm_manager.get_server_comm()
--> 507 model = self.get_root(doc, comm)
    509 if config.embed:
    510     embed_state(self, model, doc,
    511                 json=config.embed_json,
    512                 json_prefix=config.embed_json_prefix,
    513                 save_path=config.embed_save_path,
    514                 load_path=config.embed_load_path,
    515                 progress=False)

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/site-packages/panel/pane/base.py:312, in PaneBase.get_root(self, doc, comm, preprocess)
    310 doc = init_doc(doc)
    311 if self._updates:
--> 312     root = self._get_model(doc, comm=comm)
    313 else:
    314     root = self.layout._get_model(doc, comm=comm)

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/site-packages/panel/pane/echarts.py:61, in ECharts._get_model(self, doc, root, parent, comm)
     59 def _get_model(self, doc, root=None, parent=None, comm=None):
     60     ECharts = lazy_load('panel.models.echarts', 'ECharts', isinstance(comm, JupyterComm), root)
---> 61     props = self._get_echart_dict(self.object)
     62     props.update(self._process_param_change(self._init_params()))
     63     self._get_dimensions(props)

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/site-packages/panel/pane/echarts.py:83, in ECharts._get_echart_dict(self, object)
     81 if isinstance(object, pyecharts.charts.chart.Chart):
     82     w, h = object.width, object.height
---> 83     params = {'data': json.loads(object.dump_options())}
     84     if not self.height and h:
     85         params['height'] = int(h.replace('px', ''))

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File /opt/homebrew/Caskroom/mambaforge/base/envs/py39_app/lib/python3.9/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end
JSONDecodeError: Expecting value: line 140 column 22 (char 3505)

When `c` is a `pyecharts.charts.basic_charts.bar.Bar` object, it works fine, such as 
```python 
from pyecharts.charts import Bar
c = Bar()
c.add_xaxis(["c1", "w1", "x", "k", "g", "wz"])
c.add_yaxis("na", [5, 20, 36, 10, 75, 90])
c.render_notebook()
```

**Comment by shuo-Liu** [comment]
I also encountered this problem when using bmap function of pyecharts to draw maps. How can I fix this problem?

**Comment by pierrotsmnrd** [comment]
I also encounter the problem.

The original description seems related to pyecharts but I encounter a similar issue with a raw Echarts pane.

Here's a reproduction snippet :

```
import panel as pn
import json
pn.extension('echarts')

class PanelEChartsMap(pn.viewable.Viewer):
    def __init__(self, **params):
        super().__init__(**params)

    def __panel__(self):

        with open("test.json") as f:
            config = json.load(f)  
        
        # This config taken from the docs works
        # config = {
        #     'title': {
        #         'text': 'ECharts entry example'
        #     },
        #     'tooltip': {},
        #     'legend': {
        #         'data':['Sales']
        #     },
        #     'xAxis': {
        #         'data': ["shirt","cardign","chiffon shirt","pants","heels","socks"]
        #     },
        #     'yAxis': {},
        #     'series': [{
        #         'name': 'Sales',
        #         'type': 'bar',
        #         'data': [5, 20, 36, 10, 10, 20]
        #     }],
        # }
        
        echart_pane = pn.pane.ECharts(config, height=480, width=640)
        return echart_pane
```
Use this [test.json](https://github.com/user-attachments/files/17605461/test.json) file attached. Its content comes from [this Apache ECharts example](https://echarts.apache.org/examples/en/editor.html?c=map-usa-projection). 


I get the following error : 
```
Error rendering Bokeh items: TypeError: Cannot read properties of undefined (reading 'regions')
    at e.getInitialData (echarts.min.js:45:453208)
    at e.init (echarts.min.js:45:158927)
    at e.<anonymous> (echarts.min.js:45:113722)
    at Array.forEach (<anonymous>)
    at E (echarts.min.js:35:5064)
    at e.<anonymous> (echarts.min.js:45:113355)
    at t.topologicalTravel (echarts.min.js:45:106595)
    at e._mergeOption (echarts.min.js:45:112849)
    at rd (echarts.min.js:45:118019)
    at e._resetOption (echarts.min.js:45:112118)
```

Note that the issue also occurs with other examples I have tested, like [this one](https://echarts.apache.org/examples/en/editor.html?c=effectScatter-bmap).

**Comment by pierrotsmnrd** [comment]
In an attempt to find a solution, I thought of creating a custom `JSComponent` liked explained [in the docs](https://panel.holoviz.org/reference/custom_components/JSComponent.html), to have more flexibility with the Echarts code, and eventually be able to show maps.

First step was to have a working wrapper, displaying an example bar graph. Here is the code : 
```python
import param
from panel.custom import JSComponent
import panel as pn
import json
pn.extension('echarts')

from pprint import pprint

class EchartsWrapper(JSComponent, param.Parameterized):

    container_id = param.String(default="echarts_container")
    options_ = param.Dict(default={})

    def __init__(self, options, **params):
        super().__init__(**params)

        self.options_ = options
        
        self.on_msg(lambda msg: pprint(msg))
        


    _esm = """
    import * as echarts from "https://cdn.jsdelivr.net/npm/echarts@5.5.1/+esm";
    import "https://code.jquery.com/jquery-3.5.1.js";

    export function render({ model }) {
        console.log("Model options:", model.options_);

        // Create container for the chart
        const container = document.createElement('div');
        container.id = model.container_id;
        container.width = "800px";
        container.height = "400px";
        container.style.width = "800px";
        container.style.height = "400px";
        console.log("Container created:", container);

        let chart = null;

        // Function to update chart options
        const update = () => {
            if (!chart) {
                console.log("Chart is not initialized yet.");
                return;
            }
            console.log("Updating chart with options:", model.options_);
            chart.resize();
            chart.setOption(model.options_);
        };

        // Function to build the chart
        const buildChart = () => {
            console.log("DEBUG", container.clientWidth, container.clientHeight);
            /*chart = echarts.init(container, null, { renderer: 'canvas' });*/
            chart = echarts.init(container);
            console.log("Chart initialized:", chart);
            update();  // Initial update after chart initialization         
        };

        // Event listeners
        model.on('change:options_', update);
        model.on('lifecycle:after_layout', () =>  buildChart() );
        
        model.on('lifecycle:resize', () => chart && chart.resize());
        model.on('lifecycle:remove', () => chart && chart.dispose());

        return container;
    }"""

    
class DemoPlot(pn.viewable.Viewer):
    def __init__(self, **params):
        super().__init__(**params)

    def __panel__(self):
        
        options = {
            'title': {
                'text': 'ECharts entry example'
            },
            'tooltip': {},
            'legend': {
                'data':['Sales']
            },
            'xAxis': {
                'data': ["shirt","cardign","chiffon shirt","pants","heels","socks"]
            },
            'yAxis': {},
            'series': [{
                'name': 'Sales',
                'type': 'bar',
                'data': [5, 20, 36, 10, 10, 20]
            }],
        }


        return EchartsWrapper(options)


if __name__ == "__main__":

    pn.serve(
        {"/":lambda : DemoPlot()},
        port=8080,
        start=True,
        location=True,
        show=False,
        autoreload=True,
        allow_websocket_origin=[
            "localhost:8080",
        ],
    )
```


Unfortunately, the plot is not fully rendered. I have the tooltips, I can see them when I hover over the page, but the actual demo bar graph is not shown.
If I can make this work, I think we can make Echarts maps work.
