### ISSUE TITLE
Custom ReactiveHTML widget fails to perform iterative param.List manipulation in served page, but not in Jupyter Notebook.

### ISSUE THREAD

**Issue by inuyasha10121** [holoviz/panel#3796]
I've noticed some differential behavior between a ReactiveHTML file upload widget I'm developing with regards to editing a param.List object.  The end goal is to allow the user to upload a set of files, have those files be compressed to speed up transfer, then do more on the Python side of things to process the data.

#### Software Version Info
Python 3.9.11
notebook 6.4.8
panel 0.13.1
param 1.12.1
Chrome for the browser

#### Expected Behavior
The expected behavior here is that, for each file that is uploaded, "test_data" will be set as the list element (resulting in len 9 for the test here), which will eventually be replaced by a compressed FileReader ArrayBuffer -> Uint8Array from pako.  

#### Observed Behavior
When ran through a jupyter notebook, this works fine it seems.  However, when I serve the notebook via command line (panel serve Sandbox.ipynb --port 8889) things seem to break, and the List object is not modified by the script except by the initial array initialization with nulls for each file.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn #0.13.1
from panel.reactive import ReactiveHTML
import param #1.12.2
pn.extension()

class MultiUploadFast(ReactiveHTML, param.Parameterized):
    
    file_contents = param.List([])
    load_data_flag = param.Boolean(False)
    
    _template = """
        <div id="drop-area">
            <form class="my-form">
                <p>Upload multiple files with the file dialog or by dragging and dropping images onto the dashed region</p>
                <input type="file" id="fileElem" multiple onchange="${script('handleFiles')}"></input>
                <label class="button" for="fileElem">Select some files</label>
            </form>
        </div>
    """
    
    _scripts = {
        "handleFiles":"""
            var files = document.querySelectorAll('[id^=fileElem]')[0].files;
            var nfiles = files.length;
            data.file_contents = new Array(nfiles).fill(null);
            
            for(let i = 0; i < nfiles; i++){
                data.file_contents[i] = "test_data";
            }
            data.load_data_flag = !data.load_data_flag
        """, 
    }
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.param.watch(self._data_loading,  ['load_data_flag'], onlychanged=False)
    
    def _data_loading(self, event):
        test_text.value = "PING:%s\n"%(len(self.file_contents))
        for i in range(len(self.file_contents)):
            test_text.value += "Ind %s: %s\n"%(i, len(self.file_contents[i]))

up_module = MultiUploadFast()
test_button = pn.widgets.Button(name='Test')
test_text = pn.widgets.TextAreaInput(width=500, height=300)

ui = pn.Column(
    test_text,
    up_module, 
)
ui.servable()

```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/bokeh/server/session.py", line 97, in _needs_document_lock_wrapper
    result = await result
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/panel/reactive.py", line 356, in _change_coroutine
    self._change_event(doc)
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/panel/reactive.py", line 370, in _change_event
    self._process_events(events)
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/panel/reactive.py", line 315, in _process_events
    self.param.update(**self_events)
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/param/parameterized.py", line 1898, in update
    self_._batch_call_watchers()
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/param/parameterized.py", line 2059, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/jon/anaconda3/envs/SUMSDev2/lib/python3.9/site-packages/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jon/PythonDev/SIPS-Dev/Sandbox.ipynb", line 47, in _data_loading
    "    if (root._bokeh_is_loading > 0) {\n",
TypeError: object of type 'NoneType' has no len()

```
The JS console shows no errors or reports beyond what is normally observed

#### Screenshots or screencasts of the bug in action
Working visualization from the Jupyter notebook instance
![image](https://user-images.githubusercontent.com/6994958/187323953-7dfbaee7-b8d9-4d23-bed8-039ef0133175.png)
Failing visualization from the served webpage
![image](https://user-images.githubusercontent.com/6994958/187324044-3a68787d-4460-42e0-b458-aa4a745377dd.png)

#### Additional notes
My pervious iteration of the file uploader first stores all the information from the files in a dummy JS variable, then sets the List element to that dummy variable.  This seems to work, but precludes a progress update to the user of the status of the upload.  So, its not that you CAN'T update the list, its that it appears that you can't upload individual list elements one by one and have to do everything all at once when the page is being served.

**Comment by inuyasha10121** [comment]
Update: So this appears to be an even more fundamental problem beyond Panel, or is a problem interfacing between Bokeh and Panel (I'm not well versed enough in Bokeh alone to know which it is or how to best test this).  I tried to write a Bokeh implementation of the Panel code above, and the same behavior as above is observed.  It appears that List objects only update to callbacks if the List elements are changed all at once, and not piecewise.  My apologies if there is an obvious error or bad implementation here, I'm new to TypeScript and direct Bokeh coding in general.  Here is the Bokeh implementation code I used (I'm on 2.4.3 for Bokeh):

main.ipynb
```
import panel as pn
from bokeh.core.properties import List, String, Dict, Int, Bool
from bokeh.layouts import column
from bokeh.models import HTMLBox, LayoutDOM

pn.extension()

class CustomFileInput(LayoutDOM):

    __implementation__ = "custom_file_input.ts"
    
    accept = String()
    file_names = List(item_type=String, default=[])
    loaded = Bool()
    value = String()
    #data = List(Dict(keys_type=String, values_type=Int), default=[])
        
def _data_loading(attr, old, new):
    rep = "BEP\n"
    for name in custom_file.file_names:
        rep += f"{name}: \n"
    text_output.value = rep
    
    
custom_file = CustomFileInput()
custom_file.on_change("loaded", _data_loading)
layout = column(custom_file)


bokeh_pane = pn.pane.Bokeh(layout)
text_output = pn.widgets.TextAreaInput(width=500, height=500)

app = pn.Column(bokeh_pane, text_output)
app.servable()
```

custom_file_input.ts
```
import { HTMLBox, HTMLBoxView } from "models/layouts/html_box"

import { div } from "core/dom"
import * as p from "core/properties"

export class CustomFileInputView extends HTMLBoxView {
    model: CustomFileInput

    render(): void {
        console.info("render");
        super.render()
        var input
        input = document.createElement("input")
        input.type = "file"
        input.accept = this.model.accept
        input.id = "input-" + this.model.id
        input.multiple = true
        input.onchange = () => {
            let files = (<HTMLInputElement>document.getElementById("input-" + this.model.id)).files
            if (files != null) {
                let nfiles = files.length
                //Does not work
                this.model.file_names = new Array(nfiles).fill(null);
                for(let i = 0; i < nfiles; i++) {
                    this.model.file_names[i] = files[i].name
                }
                this.model.loaded = !this.model.loaded
                
                //Works fine
                //var dummy = new Array(nfiles).fill(null);
                //for(let i = 0; i < nfiles; i++) {
                //    dummy[i] = files[i].name
                //}
                //this.model.file_names = dummy
                //this.model.loaded = !this.model.loaded
            }
        };
        
        this.el.appendChild(div(input))
    }
}

export namespace CustomFileInput {
    export type Attrs = p.AttrsOf<Props>
    export type Props = HTMLBox.Props & {
        accept: p.Property<string>
        file_names: p.Property<Array<string>>
        loaded: p.Property<boolean>
        value: p.Property<string>
    }
}

export interface CustomFileInput extends CustomFileInput.Attrs { }

export class CustomFileInput extends HTMLBox {
    properties: CustomFileInput.Props

    constructor(attrs?: Partial<CustomFileInput.Attrs>) {
        super(attrs)
    }

    static init_CustomFileInput(): void {
        this.prototype.default_view = CustomFileInputView;

        this.define<CustomFileInput.Props>({
            accept: [p.String],
            file_names: [p.Array],
            loaded: [p.Boolean],
            value: [p.String]
        })
    }
}
```
