### ISSUE TITLE
Param docs fails when running clicking the run pyodide button

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#3968]
https://panel.holoviz.org/user_guide/Param.html

![image](https://user-images.githubusercontent.com/42288570/194381853-8c743822-ea14-486d-9f4d-f4e7b843336f.png)

```bash
2022-10-06 19:36:34,943 ERROR: panel.reactive - Callback failed for object named "Num int" changing property {'value': 50360} 
pyodide.asm.js:10 Traceback (most recent call last):
pyodide.asm.js:10   File "/lib/python3.10/site-packages/panel/reactive.py", line 319, in _process_events
pyodide.asm.js:10     self.param.update(**self_events)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 1898, in update
pyodide.asm.js:10     self_._batch_call_watchers()
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 2059, in _batch_call_watchers
pyodide.asm.js:10     self_._execute_watcher(watcher, events)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 2021, in _execute_watcher
pyodide.asm.js:10     watcher.fn(*args, **kwargs)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/panel/param.py", line 496, in link_widget
pyodide.asm.js:10     self.object.param.update(**{p_name: change.new})
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 1891, in update
pyodide.asm.js:10     setattr(self_or_cls, k, v)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 2776, in __setattr__
pyodide.asm.js:10     parameter = copy.copy(parameter)
pyodide.asm.js:10   File "/lib/python3.10/copy.py", line 102, in copy
pyodide.asm.js:10     return _reconstruct(x, None, *rv)
pyodide.asm.js:10   File "/lib/python3.10/copy.py", line 273, in _reconstruct
pyodide.asm.js:10     y.__setstate__(state)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/__init__.py", line 920, in __setstate__
pyodide.asm.js:10     super(Number, self).__setstate__(state)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 1304, in __setstate__
pyodide.asm.js:10     setattr(self,k,v)
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 1127, in __setattr__
pyodide.asm.js:10     raise e
pyodide.asm.js:10   File "/lib/python3.10/site-packages/param/parameterized.py", line 1118, in __setattr__
pyodide.asm.js:10     old = getattr(self, attribute) if implemented else NotImplemented
pyodide.asm.js:10 AttributeError: 'Integer' object has no attribute 'bounds'
```

## Wish

I wish the "button" turned into a red cross to if the page fails. That would make it clear to the users that something is wrong. If there was even a notification that something went wrong and they can report the issue on Github it would be amazing.

**Comment by philippjfr** [comment]
Can't reproduce. Also the button should already turn into a red cross when it fails.

**Comment by MarcSkovMadsen** [comment]
Now I cannot reproduce. But instead I see this one consistently.

```bash
PyodideServiceWorker.js:51 
        
       Uncaught (in promise) Error: [Service Worker] Fetching resource https://panel.holoviz.org/user_guide/static/extensions/panel/bundled/datatabulator/tabulator-tables@5.3.2/dist/css/tabulator_simple.min.css failed with response: 404
    at PyodideServiceWorker.js:51:13
```

Is a resource missing?

**Comment by philippjfr** [comment]
See https://github.com/holoviz/panel/pull/3967 Will release that with a few other fixes next week.
