### ISSUE TITLE
TypeError: Read-only parameter 'event' cannot be modified when moving mouse fast

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4008]
I and a user of the `panel-highcharts` package independently found the same issue today.

```bash
TypeError: Read-only parameter 'event' cannot be modified
```

I've investigated and cannot find an issue in the `panel-highcharts` package. It might be there though.

## Reproducible Steps

```bash
pip install panel==0.14.0 panel-highcharts==20221015.3
```

`script.py`

```python
import json

import requests

import panel_highcharts as ph

ph.config.theme("auto")

import panel as pn

pn.extension("highstock")

data = requests.get(
    "https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/new-intraday.json"
).json()
configuration = {
    "title": {"text": "AAPL stock price by minute"},
    "series": [
        {
            "name": "AAPL",
            "type": "candlestick",
            "data": data,
            "tooltip": {"valueDecimals": 2},
            "allowPointSelect": "true",
            "point": {
                "events": {
                    "mouseOver": "@mouseOverFun",
                }
            },
        }
    ],
}
plot_pane = ph.HighStock(object=configuration, sizing_mode="stretch_both", min_height=600)
pn.Column(plot_pane, plot_pane.param.event).servable()
```

```bash
panel serve script.py
```

Open the application in the browser.

- If you hover with the mouse slowly there is no error
- If you hover with the mouse fast you see the error
- If you remove the `plot_pane.param.event` from the app you cannot trigger the error.

https://user-images.githubusercontent.com/42288570/195974313-4662e16e-6ea0-444a-9811-9eb4bfc32bd8.mp4

```bash
2022-10-15 07:07:54,006 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7ff968bec610>>, <Task finished name='Task-1195' coro=<ServerSession.with_document_locked() done, defined at /home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/bokeh/server/session.py:78> exception=TypeError("Read-only parameter 'event' cannot be modified")>)
Traceback (most recent call last):
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/bokeh/server/session.py", line 99, in _needs_document_lock_wrapper
    result = await result
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/panel/reactive.py", line 365, in _change_coroutine
    state._handle_exception(e)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/panel/io/state.py", line 391, in _handle_exception
    raise exception
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/panel/reactive.py", line 363, in _change_coroutine
    self._change_event(doc)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/panel/reactive.py", line 381, in _change_event
    self._process_events(events)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/panel/reactive.py", line 319, in _process_events
    self.param.update(**self_events)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 1898, in update
    self_._batch_call_watchers()
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 2059, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/panel/param.py", line 496, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 1891, in update
    setattr(self_or_cls, k, v)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/home/jovyan/conda-envs/panel-highcharts/lib/python3.9/site-packages/param/parameterized.py", line 1203, in __set__
    raise TypeError("Read-only parameter '%s' cannot be modified" % self.name)
TypeError: Read-only parameter 'event' cannot be modified
```

## Additional Context

- I've also tried with combinations of `panel==0.13.1` and `panel-highcharts==20220428.1` and I also see the issue there.
- The `constant` event parameter can be found here https://github.com/awesome-panel/panel-highcharts/blob/dcd3ab4683519857fe885434fc8a8389395fb5fb/panel_highcharts/charts.py#L24
- You can find a guide for installing for development here https://github.com/awesome-panel/panel-highcharts/blob/main/DEVELOPER_GUIDE.md

**Comment by MarcSkovMadsen** [comment]
## Workaround

For now I've removed the `readonly` setting and released `panel-highcharts==20221015.4`. This works around the issue.

But I believe there is an issue with Panel. Why would the fact that I add a widget from my parameter to my Panel app try to update the parameter if I don't change anything in the widget? I only change the parameter.

**Comment by philippjfr** [comment]
Sounds like the value is making a round-trip to the frontend. Indeed seems like an issue.
