### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4010]
Panel ==0.14.0

## Reproduce

```python
"""This example shows a streaming dashboard with Panel.
Panel runs on top of the Tornado server. Tornado is a fast, asynchronous web server built to
support streaming use cases.

You can run `some_function` periodically via
`pn.state.add_periodic_callback(some_function, period=1000, count=200)`.
"""
import numpy as np
import panel as pn

pn.extension(sizing_mode="stretch_width")

layout = pn.layout.FlexBox(
    *(
        pn.indicators.Trend(
            data={"x": list(range(10)), "y": np.random.randn(10).cumsum()},
            width=150,
            height=100,
            plot_type=pn.indicators.Trend.param.plot_type.objects[i % 4],
        )
        for i in range(32)
    )
)


def stream():
    for trend in layout:
        trend.stream(
            {"x": [trend.data["x"][-1] + 1], "y": [trend.data["y"][-1] + np.random.randn()]},
            rollover=20,
        )


periodic_callback = pn.state.add_periodic_callback(stream, 1000)

period_input = pn.widgets.IntInput.from_param(periodic_callback.param.period, sizing_mode="fixed")
checkbox_input = pn.widgets.Checkbox.from_param(
    periodic_callback.param.running, align="end", sizing_mode="fixed"
)
controls = pn.Row(period_input, checkbox_input)

pn.template.FastListTemplate(
    site="Awesome Panel",
    title="Streaming Indicators",
    favicon="https://raw.githubusercontent.com/MarcSkovMadsen/awesome-panel-assets/320297ccb92773da099f6b97d267cc0433b67c23/favicon/ap-1f77b4.ico",
    main=[
        pn.Column(
            __doc__,
            controls,
        ),
        layout,
    ],
).servable()
```

```bash
panel serve --port 5007 --num-threads 4 app.py
```

Open the app in the browser and change the frequency to 200.

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/io/state.py", line 382, in _handle_future_exception
    self._handle_exception(exception)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/io/state.py", line 391, in _handle_exception
    raise exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/reactive.py", line 381, in _change_event
    self._process_events(events)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/reactive.py", line 319, in _process_events
    self.param.update(**self_events)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 1898, in update
    self_._batch_call_watchers()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2059, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/param.py", line 496, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 1898, in update
    self_._batch_call_watchers()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2059, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 669, in caller
    return function()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/param/parameterized.py", line 407, in _depends
    return func(*args, **kw)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/io/callbacks.py", line 75, in _update_period
    self.start()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/panel/io/callbacks.py", line 175, in start
    self._cb = self._doc.add_periodic_callback(self._periodic_callback, self.period)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/document.py", line 299, in add_periodic_callback
    return self.callbacks.add_session_callback(cb, callback, one_shot=False)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 188, in add_session_callback
    self.trigger_on_change(SessionCallbackAdded(doc, callback_obj))
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 378, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 377, in invoke_callbacks
    cb(event)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 263, in <lambda>
    self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/document/events.py", line 1034, in dispatch
    cast(SessionCallbackAddedMixin, receiver)._session_callback_added(self)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/server/session.py", line 264, in _session_callback_added
    self._callbacks.add_session_callback(wrapped)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/server/callbacks.py", line 197, in add_session_callback
    self._group.add_periodic_callback(callback_obj.callback, callback_obj.period, callback_obj.id)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/util/tornado.py", line 285, in add_periodic_callback
    cb.start()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/util/tornado.py", line 141, in start
    self._loop.add_future(self.sleep(), on_done)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel-cli/.venv/lib/python3.9/site-packages/bokeh/util/tornado.py", line 110, in sleep
    f: gen.Future[None] = gen.Future()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

**Comment by MarcSkovMadsen** [comment]
https://user-images.githubusercontent.com/42288570/196024060-b605bd31-f10e-404c-90bf-14c43b0fac3e.mp4

**Comment by philippjfr** [comment]
Thanks, I can reproduce.
