### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4086]
I just updated awesome-panel.org to panel 0.14.1. I also added `--num-threads 4` for the first time.

I see the below in my logs

```bash
2022-11-05 20:01:31,086 exception calling callback for <Future at 0x7f2499758ca0 state=finished raised RuntimeError>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/io/state.py", line 392, in _handle_future_exception
    self._handle_exception(exception)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/io/state.py", line 399, in _handle_exception
    raise exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/reactive.py", line 381, in _change_event
    self._process_events(events)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/reactive.py", line 341, in _process_events
    state.busy = busy
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 1248, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2039, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 669, in caller
    return function()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 407, in _depends
    return func(*args, **kw)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/io/state.py", line 236, in _update_busy
    indicator.value = self.busy
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 1248, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2039, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/param/parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/reactive.py", line 308, in _param_change
    self._apply_update(named_events, msg, model, ref)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/panel/reactive.py", line 245, in _apply_update
    doc.add_next_tick_callback(cb)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/bokeh/document/document.py", line 276, in add_next_tick_callback
    return self.callbacks.add_session_callback(cb, callback, one_shot=True)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 188, in add_session_callback
    self.trigger_on_change(SessionCallbackAdded(doc, callback_obj))
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 378, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/home/jovyan/repos/private/awesome-panel/awesome-panel/.venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 376, in invoke_callbacks
    for cb in self._change_callbacks.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by philippjfr** [comment]
Looks like the error originates in bokeh. It's not clear to me why the change callbacks on the busy indicator would change after initialization. If this is something you can reproduce easily is there a chance you could `print(self._change_callbacks)`?

**Comment by philippjfr** [comment]
Submitted a fix upstream in Bokeh.
