### ISSUE TITLE
panel convert reports success but is failing

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4089]
I'm trying to use `convert_app` and `panel convert` for Panel Sharing.

It is really difficult to catch and report errors because `convert_app` can fail without raising exceptions. 

The problem for me is that I am using `convert_app` and can only get to the things printed and raised by Panel not the true underlying issues that Bokeh reports in the terminal.

## Example 1

Here is an example the real issue is printed by bokeh but not catched and handled by Panel and convert_app.

In the end `panel convert` reports the wrong cause.

```python
import panel as pn
import textblob

pn.panel("hello").servable()
```

```bash
panel convert script.py
ERROR:bokeh.application.application:Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7fefccb4cc70>: No module named 'textblob'
File 'script.py', line 2, in <module>:
import textblob Traceback (most recent call last):
  File "/home/jovyan/repos/private/awesome-panel/panel-sharing/.venv/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/private/awesome-panel/panel-sharing/script.py", line 2, in <module>
    import textblob
ModuleNotFoundError: No module named 'textblob'
 
Failed to convert script.py to pyodide target: The file script.py does not publish any Panel contents. Ensure you have marked items as servable or added models to the bokeh document manually.
```

## Example 2

Here is an example where it states a combination of success and failure.

```python
import panel as pn

pn.panel("hello").servable()

import textblob
```

```bash
panel convert script.py
ERROR:bokeh.application.application:Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7f15f557bca0>: No module named 'textblob'
File 'script.py', line 5, in <module>:
import textblob Traceback (most recent call last):
  File "/home/jovyan/repos/private/awesome-panel/panel-sharing/.venv/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/private/awesome-panel/panel-sharing/script.py", line 5, in <module>
    import textblob
ModuleNotFoundError: No module named 'textblob'
 
Successfully converted script.py to pyodide target and wrote output to script.html.
```

**Comment by MarcSkovMadsen** [comment]
I will close this one in favor of https://github.com/holoviz/panel/issues/4090. They are not exactly the same. But the other one is much more important to solve.

**Comment by MarcSkovMadsen** [comment]
The problem is that Bokeh just logs errors instead of raising them here

![image](https://user-images.githubusercontent.com/42288570/200487172-f2766896-719a-47b8-a1ea-4fbcd89c42cc.png)

Panel convert needs to catch these errors and handle them.

**Comment by MarcSkovMadsen** [comment]
A solution would be to *mock* the `bokeh.application.application` logger.

**script2.py**

```python
from panel.io.convert import convert_app
from pathlib import Path
from bokeh.application import application
from logging import Logger


class MockLogger(Logger):
    def error(self, *args, **kwargs):
        error_message = args[3]
        raise Exception(error_message)

original_log = application.log
application.log=MockLogger("bokeh.application.application")

convert_app("script.py", dest_path=Path())

application.log=original_log
```

**script.py**

```python
import panel as pn

import textblob
pn.panel("hello").servable()
```

```bash
python script2.py
Failed to convert script.py to pyodide-worker target: Traceback (most recent call last):
  File "/home/jovyan/conda-envs/panel_dev/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/private/panel/script.py", line 3, in <module>
    import textblob
ModuleNotFoundError: No module named 'textblob'
```
