### ISSUE TITLE
Document how to request data from urls when using panel convert

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4111]
When you `panel convert` you need to make your code work both on the (linux) server and in pyodide.

An example of this is @ahuang11 who wants to do http get requests in https://discourse.holoviz.org/t/try-out-panel-sharing/4549/7.

This complicates things as `requests`, `httpx` etc does not work in pyodide.

I.e. we should finalize and document an example like the below.

`app.py`

```python
import panel as pn
import sys
import httpx

pn.extension()

def get(url):
    if sys.platform == 'emscripten':
        raise NotImplementedError()
    else:
        return httpx.get(url=url)

response = get(url="https://jsonplaceholder.typicode.com/todos/1")
pn.panel(response.json()).servable()
```

```bash
panel convert app.py --to pyodide-worker
```

**Comment by MarcSkovMadsen** [comment]
This code might be improved. But at least it works

```python
import panel as pn
import sys
import json

pn.extension()

def get_json(url):
    if sys.platform == 'emscripten':
        from pyodide.http import open_url
        response = open_url(url)   
        return json.loads(response.getvalue())
    else:
        import requests
        return requests.get(url=url).json()

response = get_json(url="https://jsonplaceholder.typicode.com/todos/1")
pn.panel(response).servable()
```

Check out the code and live ap [here](https://www.awesome-panel.org/sharing?project=eyJzb3VyY2UiOnsiY29kZSI6ImltcG9ydCBwYW5lbCBhcyBwblxuaW1wb3J0IHN5c1xuaW1wb3J0IGpzb25cblxucG4uZXh0ZW5zaW9uKClcblxuZGVmIGdldF9qc29uKHVybCk6XG4gICAgaWYgc3lzLnBsYXRmb3JtID09ICdlbXNjcmlwdGVuJzpcbiAgICAgICAgZnJvbSBweW9kaWRlLmh0dHAgaW1wb3J0IG9wZW5fdXJsXG4gICAgICAgIHJlc3BvbnNlID0gb3Blbl91cmwodXJsKSAgIFxuICAgICAgICByZXR1cm4ganNvbi5sb2FkcyhyZXNwb25zZS5nZXR2YWx1ZSgpKVxuICAgIGVsc2U6XG4gICAgICAgIGltcG9ydCByZXF1ZXN0c1xuICAgICAgICByZXR1cm4gcmVxdWVzdHMuZ2V0KHVybD11cmwpLmpzb24oKVxuXG5yZXNwb25zZSA9IGdldF9qc29uKHVybD1cImh0dHBzOi8vanNvbnBsYWNlaG9sZGVyLnR5cGljb2RlLmNvbS90b2Rvcy8xXCIpXG5wbi5wYW5lbChyZXNwb25zZSkuc2VydmFibGUoKSIsInJlcXVpcmVtZW50cyI6IiJ9fQ%3D%3D)

**Comment by MarcSkovMadsen** [comment]
This might be even more useful

```python
import panel as pn
import sys
import json

pn.extension()

def requests_get(url, type="json"):
    if sys.platform == 'emscripten':
        from pyodide.http import open_url
        response = open_url(url)   
        if type=="json":
            return json.loads(response.getvalue())
        return response.getvalue()
    else:
        import requests
        response = requests.get(url=url)
        if type=="json":
            return response.json()
        return response.text

response = get_json(url="https://jsonplaceholder.typicode.com/todos/1", type="text")
pn.panel(response).servable()
```

**Comment by philippjfr** [comment]
Since panel 0.14.1 we automatically [pyodide-http](https://github.com/koenvo/pyodide-http) by default so using requests should work just fine.

**Comment by MarcSkovMadsen** [comment]
Thanks. I can see requests works

![image](https://user-images.githubusercontent.com/42288570/201527602-013284b9-7348-488d-b316-d6125ccb806a.png)

**Comment by ahuang11** [comment]
Any ideas about this traceback?
![image](https://user-images.githubusercontent.com/15331990/201552952-103841eb-7680-4815-a937-ebda235ab0e9.png)
```
pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 506, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 359, in run_async
    await coroutine
  File "<exec>", line 209, in <module>
  File "<exec>", line 169, in initialize_widgets
  File "/lib/python3.10/site-packages/panel/io/cache.py", line 375, in wrapped_func
    ret = func(*args, **kwargs)
  File "<exec>", line 69, in get_stats
  File "/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/lib/python3.10/site-packages/pyodide_http/_requests.py", line 42, in send
    resp = send(pyodide_request, stream)
  File "/lib/python3.10/site-packages/pyodide_http/_core.py", line 112, in send
    xhr.send(request.body)
pyodide.JsException: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://pypistats.org/api/packages/prefect/recent?period=month'.

    at new_error (pyodide.asm.js:10:218123)
    at pyodide.asm.wasm:0xdef7c
    at pyodide.asm.wasm:0xe37ae
    at method_call_trampoline (pyodide.asm.js:10:218037)
    at pyodide.asm.wasm:0x126317
    at pyodide.asm.wasm:0x1f6f2e
    at pyodide.asm.wasm:0x161a32
    at pyodide.asm.wasm:0x126827
    at pyodide.asm.wasm:0x126921
    at pyodide.asm.wasm:0x1269c4
    at pyodide.asm.wasm:0x1e0697
    at pyodide.asm.wasm:0x1da6a5
    at pyodide.asm.wasm:0x126a07
    at pyodide.asm.wasm:0x1e248c
    at pyodide.asm.wasm:0x1e00d9
    at pyodide.asm.wasm:0x1da6a5
    at pyodide.asm.wasm:0x126a07
    at pyodide.asm.wasm:0xe347a
    at Module.callPyObjectKwargs (pyodide.asm.js:10:119064)
    at Module.callPyObject (pyodide.asm.js:10:119442)
    at wrapper (pyodide.asm.js:10:183746)
new_error @ pyodide.asm.js:10
$wrap_exception @ pyodide.asm.wasm:0xdef7c
$FutureDoneCallback_call @ pyodide.asm.wasm:0xe37ae
method_call_trampoline @ pyodide.asm.js:10
$_PyObject_MakeTpCall @ pyodide.asm.wasm:0x126317
$func3192 @ pyodide.asm.wasm:0x1f6f2e
$func1855 @ pyodide.asm.wasm:0x161a32
$PyVectorcall_Call @ pyodide.asm.wasm:0x126827
$_PyObject_Call @ pyodide.asm.wasm:0x126921
$PyObject_Call @ pyodide.asm.wasm:0x1269c4
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1e0697
$func3015 @ pyodide.asm.wasm:0x1da6a5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x126a07
$func3027 @ pyodide.asm.wasm:0x1e248c
$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x1e00d9
$func3015 @ pyodide.asm.wasm:0x1da6a5
$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x126a07
$_pyproxy_apply @ pyodide.asm.wasm:0xe347a
Module.callPyObjectKwargs @ pyodide.asm.js:10
Module.callPyObject @ pyodide.asm.js:10
wrapper @ pyodide.asm.js:10
await in wrapper (async)
(anonymous) @ main.html:563
```

**Comment by ahuang11** [comment]
I was able to make `panel convert` work by hardcoding a few things:
https://github.com/ahuang11/panel-prefect-stats/pull/1

**Comment by joelostblom** [comment]
It took me some time to figure this out too, so I think an explicit mention in the docs that the pyodide-http library is included which means that external files can be read as usual from URLs with `read_csv` etc, especially since the docs currently have this section which made me try the approach recommended there first:

![image](https://user-images.githubusercontent.com/4560057/222501086-1685c290-a60a-4a04-a4af-9c8f200063d3.png)
