### ISSUE TITLE
Async method not working: AttributeError: 'App' object has no attribute '_depends'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4261]
I'm on the current `main` branch.

```python
import asyncio

import param

import panel as pn

class App(param.Parameterized):
    run = param.Event()
    clicks = param.Integer(-1)

    @pn.depends("run")
    async def click_view(self):
        self.clicks+=1
        await asyncio.sleep(0.5)
        return f"Clicked {self.clicks} times"

app=App()
pn.Column(app.param.run, app.click_view).servable()
```

![image](https://user-images.githubusercontent.com/42288570/211199299-0b12697e-8fbf-4882-9e59-7872a556432b.png)

```bash
AttributeError: 'App' object has no attribute '_depends'
Traceback (most recent call last):
  File "C:\repos\private\panel\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel\script.py", line 18, in <module>
    pn.Column(app.param.run, app.click_view).servable()
  File "c:\repos\private\panel\panel\layout\base.py", line 630, in __init__
    params['objects'] = [panel(pane) for pane in objects]
  File "c:\repos\private\panel\panel\layout\base.py", line 630, in <listcomp>
    params['objects'] = [panel(pane) for pane in objects]
  File "c:\repos\private\panel\panel\pane\base.py", line 80, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
  File "c:\repos\private\panel\panel\param.py", line 786, in __init__
    self._link_object_params()
  File "c:\repos\private\panel\panel\param.py", line 864, in _link_object_params
    params = parameterized.param.method_dependencies(self.object.__name__)
  File "C:\repos\private\panel\.venv\lib\site-packages\param\parameterized.py", line 2271, in method_dependencies
    method = getattr(self_.self_or_cls, name)
AttributeError: 'App' object has no attribute '_depends'
```

**Comment by MarcSkovMadsen** [comment]
If I change the `click_view` method to a function It does not raise an exception, BUT it does not display the value either.

```python
import param

import panel as pn

class App(param.Parameterized):
    run = param.Event()
    clicks = param.Integer(-1)

app=App()

@pn.depends(app.param.run)
async def click_view(self):
    app.clicks+=1
    return f"Clicked {app.clicks} times"

pn.Column(app.param.run, click_view).servable()
```

![image](https://user-images.githubusercontent.com/42288570/211199732-a8f2aa22-e279-4aec-b68e-f1854fa9ac99.png)

**Comment by philippjfr** [comment]
Duplicate of https://github.com/holoviz/panel/issues/4237
