### ISSUE TITLE
RuntimeError: _pending_writes after triggering async callback

### ISSUE THREAD

**Issue by geronimogoemon** [holoviz/panel#4324]
#### ALL software version info
Python 3.9.14
panel 0.14.2

#### Description of expected behavior and the observed behavior
I have a small app that contains two panels, "a" and "b". Panel "b" contains only Markdown text. Panel "a" contains a button which upon being clicked will add Markdown text to the webpage. Most crucially, the button calls an async function. I am not doing any await inside the async function for presentation purposes given that this is enough to replicate the problem.

Here is an expected normal use scenario:
- Enter Panel "a"
- Press button
- See Markdown text "a" added
- Enter Panel "b"
- See Markdown text "b" already present

What actually happens:
- Enter Panel "a"
- Press button
- See Markdown text "a" added
- Enter Panel "b"
- The server crashes with the following error

```
Traceback (most recent call last):
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/panel/io/server.py", line 338, in get
    session = await self.get_session()
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/server/views/session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/server/contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/panel/io/server.py", line 297, in initialize_document
    super().initialize_document(doc)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/application/application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/panel/io/server.py", line 128, in _eval_panel
    panel = panel()
  File "/home/user/projects/external/panel_issues/broken_main.py", line 19, in view_b
    return pn.pane.Markdown("B").servable()
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/panel/viewable.py", line 379, in servable
    self.server_doc(title=title, location=location) # type: ignore
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/panel/viewable.py", line 875, in server_doc
    add_to_doc(model, doc)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/panel/io/model.py", line 106, in add_to_doc
    doc.add_root(obj)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/document/document.py", line 330, in add_root
    self.callbacks.trigger_on_change(RootAddedEvent(self, model, setter))
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 378, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 377, in invoke_callbacks
    cb(event)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/document/callbacks.py", line 263, in <lambda>
    self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/document/events.py", line 223, in dispatch
    cast(DocumentPatchedMixin, receiver)._document_patched(self)
  File "/home/user/projects/external/panel_issues/venv/lib/python3.9/site-packages/bokeh/server/session.py", line 247, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```

Most surprisingly, this exact order of entering websites has to happen for this error to show up. I can visit Panel "b" if it's the first Panel I visit.

#### Complete, minimal, self-contained example code that reproduces the issue

This code can be used to replicate the problem
```
import panel as pn
from panel.io.server import serve

from functools import partial

def view_a():
    root = pn.Column()

    button = pn.widgets.Button(name="test")
    button.on_click(partial(update_root, root=root))
    root.append(button)

    return root.servable()

async def update_root(event, root):
    root.append(pn.pane.Markdown("A"))

def view_b():
    return pn.pane.Markdown("B").servable()

serve(
    panels={
        "/a": view_a,
        "/b": view_b,
    },
)
```

The problem seems to be gone if I schedule the async function as a `periodic_callback`
```
import panel as pn
from panel.io.server import serve

from functools import partial

def view_a():
    root = pn.Column()

    button = pn.widgets.Button(name="test")
    button.on_click(partial(update_root, root=root))
    root.append(button)

    return root.servable()

def update_root(event, root):
    pn.state.add_periodic_callback(partial(_update_root, root=root), count=1)

async def _update_root(root):
    root.append(pn.pane.Markdown("A"))

def view_b():
    return pn.pane.Markdown("B").servable()

serve(
    panels={
        "/a": view_a,
        "/b": view_b,
    },
)
```

**Comment by Hoxbro** [comment]
It seems to work if I remove the `.servable()` for both views.

**Comment by philippjfr** [comment]
Will close. If you have suggestions for clarifying this in the docs that would still be helpful, although we are currently reorganizing the docs entirely anyway.
