### ISSUE TITLE
IntRangeSlider raises 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4402]
Panelite=0.14.3

I'm trying the example notebook reference/widgets/IntRangeSlider.ipynb. When I drag the `IntRangeSlider` below it raises an exception.

![image](https://user-images.githubusercontent.com/42288570/216833869-ddd40e96-9e1e-4c55-b233-653b0af5c558.png)

```bash
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 346, in _handle_msg
    self._on_msg(msg)
  File "/lib/python3.10/site-packages/panel/viewable.py", line 298, in _on_msg
    doc.unhold()
  File "/lib/python3.10/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 403, in _comm_change
    state._handle_exception(e)
  File "/lib/python3.10/site-packages/panel/io/state.py", line 408, in _handle_exception
    raise exception
  File "/lib/python3.10/site-packages/panel/reactive.py", line 401, in _comm_change
    self._schedule_change(doc, comm)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 383, in _schedule_change
    self._change_event(doc)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 379, in _change_event
    self._process_events(events)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 318, in _process_events
    self.param.update(**self_events)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/lib/python3.10/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/lib/python3.10/site-packages/panel/param.py", line 496, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1895, in update
    setattr(self_or_cls, k, v)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1201, in __set__
    self._validate(val)
  File "/lib/python3.10/site-packages/param/__init__.py", line 2083, in _validate
    super(Range, self)._validate(val)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1019, in _validate
    self._validate_value(val, self.allow_None)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1039, in _validate_value
    super(NumericTuple, self)._validate_value(val, allow_None)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1006, in _validate_value
    raise ValueError("Tuple parameter %r only takes a tuple value, "
ValueError: Tuple parameter 'value' only takes a tuple value, not <class 'list'>.
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 346, in _handle_msg
    self._on_msg(msg)
  File "/lib/python3.10/site-packages/panel/viewable.py", line 298, in _on_msg
    doc.unhold()
  File "/lib/python3.10/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 403, in _comm_change
    state._handle_exception(e)
  File "/lib/python3.10/site-packages/panel/io/state.py", line 408, in _handle_exception
    raise exception
  File "/lib/python3.10/site-packages/panel/reactive.py", line 401, in _comm_change
    self._schedule_change(doc, comm)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 383, in _schedule_change
    self._change_event(doc)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 379, in _change_event
    self._process_events(events)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 318, in _process_events
    self.param.update(**self_events)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/lib/python3.10/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/lib/python3.10/site-packages/panel/param.py", line 496, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1895, in update
    setattr(self_or_cls, k, v)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1201, in __set__
    self._validate(val)
  File "/lib/python3.10/site-packages/param/__init__.py", line 2083, in _validate
    super(Range, self)._validate(val)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1019, in _validate
    self._validate_value(val, self.allow_None)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1039, in _validate_value
    super(NumericTuple, self)._validate_value(val, allow_None)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1006, in _validate_value
    raise ValueError("Tuple parameter %r only takes a tuple value, "
ValueError: Tuple parameter 'value' only takes a tuple value, not <class 'list'>.
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 346, in _handle_msg
    self._on_msg(msg)
  File "/lib/python3.10/site-packages/panel/viewable.py", line 298, in _on_msg
    doc.unhold()
  File "/lib/python3.10/site-packages/bokeh/document/document.py", line 799, in unhold
    self.callbacks.unhold()
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 396, in unhold
    self.trigger_on_change(event)
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 373, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 191, in invoke
    callback(attr, old, new)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 403, in _comm_change
    state._handle_exception(e)
  File "/lib/python3.10/site-packages/panel/io/state.py", line 408, in _handle_exception
    raise exception
  File "/lib/python3.10/site-packages/panel/reactive.py", line 401, in _comm_change
    self._schedule_change(doc, comm)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 383, in _schedule_change
    self._change_event(doc)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 379, in _change_event
    self._process_events(events)
  File "/lib/python3.10/site-packages/panel/reactive.py", line 318, in _process_events
    self.param.update(**self_events)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/lib/python3.10/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/lib/python3.10/site-packages/panel/param.py", line 496, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1895, in update
    setattr(self_or_cls, k, v)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/lib/python3.10/site-packages/param/parameterized.py", line 1201, in __set__
    self._validate(val)
  File "/lib/python3.10/site-packages/param/__init__.py", line 2083, in _validate
    super(Range, self)._validate(val)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1019, in _validate
    self._validate_value(val, self.allow_None)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1039, in _validate_value
    super(NumericTuple, self)._validate_value(val, allow_None)
  File "/lib/python3.10/site-packages/param/__init__.py", line 1006, in _validate_value
    raise ValueError("Tuple parameter %r only takes a tuple value, "
ValueError: Tuple parameter 'value_throttled' only takes a tuple value, not <class 'list'>.
```

https://user-images.githubusercontent.com/42288570/216833925-40d5cf02-ff1d-47de-8455-45d6f68106ff.mp4

**Comment by MarcSkovMadsen** [comment]
The `RangeSlider` has the same issue

![image](https://user-images.githubusercontent.com/42288570/216838251-8301f1a2-2963-4776-bc78-5258171a592c.png)

**Comment by dalthviz** [comment]
Hi there, while checking https://github.com/holoviz/panel/issues/8098 I stumbled with this. Could it be that the [fix idea](https://github.com/holoviz/panel/issues/8098#issuecomment-3215151715) that I left there can also help with the similar `ValueError` exception that is described here? From a quick test, patching `Reactive.controls` with the proposed fix over panellite seems like helps/prevents the `ValueError` for the `IntRangeSlider` too:

![Image](https://github.com/user-attachments/assets/98d13a5e-23e6-477d-a09d-44e82e3a6eba)

Maybe #8098 is a duplicate of this? 🤔
