### ISSUE TITLE
Ipyleaflet not working with Panel Convert

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4500]
xgomez is trying to convert a Panel app based on Ipyleaflet to Pyodide. But it fails. See https://discourse.holoviz.org/t/ipyleaflet-not-found-in-wasm-pyodide-worker/5028.

I see a lot of *can't find pure python wheel for* ... in the browser console.

## Reproduce

**script.py**

```python
import panel as pn
from ipyleaflet import Map, Marker

pn.extension("ipywidgets", sizing_mode="stretch_width")

ACCENT_BASE_COLOR = "#DAA520"


def get_marker_and_map():
    center = (52.204793, 360.121558)

    lmap = Map(center=center, zoom=15, height=500)

    marker = Marker(location=center, draggable=True)
    lmap.add_layer(marker)
    lmap.layout.height="100%"
    lmap.layout.width="100%"
    return marker, lmap

marker, lmap = get_marker_and_map()

json_widget = pn.pane.JSON({}, height=75)

def on_location_changed(event):
    new = event["new"]
    json_widget.object = {"x": new[0], "y": new[1]}
marker.observe(on_location_changed, 'location')

component = pn.Column(
    pn.panel(lmap, sizing_mode="stretch_both", min_height=500),
    json_widget
)

template = pn.template.FastListTemplate(
    site="Awesome Panel",
    title="IPyLeaflet",
    logo="https://panel.holoviz.org/_static/logo_stacked.png",
    header_background=ACCENT_BASE_COLOR,
    accent_base_color=ACCENT_BASE_COLOR,
    main=[component],
).servable()
```

**requirements.txt**

```bash
ipywidgets
ipyleaflet
ipywidgets_bokeh
jupyter_bokeh<3.0
panel<1.0
```

```bash
panel convert script.py --to pyodide-worker --out out --requirements ./requirements.txt
python -m http.server
```

Open http://localhost:8000/out/script.html

## Screenshot

![image](https://user-images.githubusercontent.com/42288570/222880400-57fa546b-7c22-4d9c-9940-3db0e64793bc.png)

## Logs

```bash
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 435, in add_requirement_inner
    wheel = find_wheel(metadata, req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 303, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'psutil'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.

    at new_error (pyodide.asm.js:10:180819)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xee969
    at method_call_trampoline (pyodide.asm.js:10:230214)
    at pyodide.asm.wasm:0x131392
    at pyodide.asm.wasm:0x20245a
    at pyodide.asm.wasm:0x16ca8f
    at pyodide.asm.wasm:0x1318a6
    at pyodide.asm.wasm:0x1319a0
    at pyodide.asm.wasm:0x131a43
    at pyodide.asm.wasm:0x1eb761
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0x1ed543
    at pyodide.asm.wasm:0x1eb1a3
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0xee1a0
    at pyodide.asm.wasm:0xee041
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:220254)
script.js:33 PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 448, in add_requirement_inner
    await self.add_wheel(wheel, req.extras)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 463, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 337, in add_requirement
    return await self.add_requirement_inner(req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 435, in add_requirement_inner
    wheel = find_wheel(metadata, req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 303, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'tornado>=6.1'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.

    at new_error (pyodide.asm.js:10:180819)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xee969
    at method_call_trampoline (pyodide.asm.js:10:230214)
    at pyodide.asm.wasm:0x131392
    at pyodide.asm.wasm:0x20245a
    at pyodide.asm.wasm:0x16ca8f
    at pyodide.asm.wasm:0x1318a6
    at pyodide.asm.wasm:0x1319a0
    at pyodide.asm.wasm:0x131a43
    at pyodide.asm.wasm:0x1eb761
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0x1ed543
    at pyodide.asm.wasm:0x1eb1a3
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0xee1a0
    at pyodide.asm.wasm:0xee041
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:220254)
script.js:33 PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 435, in add_requirement_inner
    wheel = find_wheel(metadata, req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 303, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'ipywidgets-bokeh'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.

    at new_error (pyodide.asm.js:10:180819)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xee969
    at method_call_trampoline (pyodide.asm.js:10:230214)
    at pyodide.asm.wasm:0x131392
    at pyodide.asm.wasm:0x20245a
    at pyodide.asm.wasm:0x16ca8f
    at pyodide.asm.wasm:0x1318a6
    at pyodide.asm.wasm:0x1319a0
    at pyodide.asm.wasm:0x131a43
    at pyodide.asm.wasm:0x1eb761
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0x1ed543
    at pyodide.asm.wasm:0x1eb1a3
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0xee1a0
    at pyodide.asm.wasm:0xee041
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:220254)
script.js:33 PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 573, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 333, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 340, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 435, in add_requirement_inner
    wheel = find_wheel(metadata, req)
  File "/lib/python3.10/site-packages/micropip/_micropip.py", line 303, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'jupyter-bokeh<3.0'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.

    at new_error (pyodide.asm.js:10:180819)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xee969
    at method_call_trampoline (pyodide.asm.js:10:230214)
    at pyodide.asm.wasm:0x131392
    at pyodide.asm.wasm:0x20245a
    at pyodide.asm.wasm:0x16ca8f
    at pyodide.asm.wasm:0x1318a6
    at pyodide.asm.wasm:0x1319a0
    at pyodide.asm.wasm:0x131a43
    at pyodide.asm.wasm:0x1eb761
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0x1ed543
    at pyodide.asm.wasm:0x1eb1a3
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0xee1a0
    at pyodide.asm.wasm:0xee041
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:220254)
script.js:40 Packages loaded!
pyodide.asm.js:10 
        
       Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    await coroutine
  File "<exec>", line 10, in <module>
ModuleNotFoundError: No module named 'ipyleaflet'

    at new_error (pyodide.asm.js:10:180819)
    at pyodide.asm.wasm:0xe78a8
    at pyodide.asm.wasm:0xee969
    at method_call_trampoline (pyodide.asm.js:10:230214)
    at pyodide.asm.wasm:0x131392
    at pyodide.asm.wasm:0x20245a
    at pyodide.asm.wasm:0x16ca8f
    at pyodide.asm.wasm:0x1318a6
    at pyodide.asm.wasm:0x1319a0
    at pyodide.asm.wasm:0x131a43
    at pyodide.asm.wasm:0x1eb761
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0x1ed543
    at pyodide.asm.wasm:0x1eb1a3
    at pyodide.asm.wasm:0x1e5790
    at pyodide.asm.wasm:0x131a86
    at pyodide.asm.wasm:0xee1a0
    at pyodide.asm.wasm:0xee041
    at Module.callPyObjectKwargs (pyodide.asm.js:10:123403)
    at Module.callPyObject (pyodide.asm.js:10:123781)
    at wrapper (pyodide.asm.js:10:220254)
```

**Comment by philippjfr** [comment]
Should be upstreamed into `ipywidgets_bokeh`, I think we simply need to unpin ipykernel there so it doesn't attempt to pull in tornado.
