### ISSUE TITLE
Terminal reports OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by analog-cbarber** [holoviz/panel#4524]
#### ALL software version info

Python 3.10.9
MacOS 12.6 (M1)
Panel 0.14.4
Bokeh 2.4.3
Chrome 110.0.5481.177

#### Description of expected behavior and the observed behavior

In using the Terminal, I am seeing console spew like this:

```
OSError: [Errno 25] Inappropriate ioctl for device
Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x136835000>>, <Task finished name='Task-217' coro=<ServerSession.with_document_locked() done, defined at /Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/bokeh/server/session.py:78> exception=OSError(25, 'Inappropriate ioctl for device')>)
Traceback (most recent call last):
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/tornado/ioloop.py", line 740, in _run_callback
    ret = callback()
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/tornado/ioloop.py", line 764, in _discard_future_result
    future.result()
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/bokeh/server/session.py", line 99, in _needs_document_lock_wrapper
    result = await result
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/panel/reactive.py", line 363, in _change_coroutine
    state._handle_exception(e)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/panel/io/state.py", line 408, in _handle_exception
    raise exception
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/panel/reactive.py", line 361, in _change_coroutine
    self._change_event(doc)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/panel/reactive.py", line 379, in _change_event
    self._process_events(events)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/panel/reactive.py", line 318, in _process_events
    self.param.update(**self_events)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/param/parameterized.py", line 669, in caller
    return function()
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/param/parameterized.py", line 407, in _depends
    return func(*args, **kw)
  File "/Users/Christopher.Barber/miniconda3/envs/eisviz/lib/python3.10/site-packages/panel/widgets/terminal.py", line 145, in _set_winsize
    fcntl.ioctl(self._fd, termios.TIOCSWINSZ, winsize)
OSError: [Errno 25] Inappropriate ioctl for device
```

I am able to work around by subclassing TerminalSubprocess and overriding
`_set_winsize` to ignore the exception.

It looks like the size is being set, but perhaps I don't understand what this is doing...

**Comment by analog-cbarber** [comment]
This looks like it has been fixed by b0214fc51863bdf1bad2d31c589fbff971f41646
