### ISSUE TITLE
Make it easier to use pn.state.as_cached by supporting unnamed arguments

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4564]
When trying to cache (via `as_cached`)  a function that you normally use with unnamed arguments its friction you have to spend time on looking up the name of the argument.

## Example:

Normally I do `pd.read_csv("my_file.csv")` and similar. Thus i would expect to be able to do
```bash
pn.state.as_cached("data", pd.read_csv, "my_file.csv")
```

But this raises

```bash
TypeError: unsupported operand type(s) for +: 'float' and 'str'
Traceback (most recent call last):
  File "C:\repos\private\panel\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "C:\repos\private\panel\script.py", line 6, in <module>
    data = pn.state.as_cached("data", pd.read_csv, "tabulator.csv")
  File "c:\repos\private\panel\panel\io\state.py", line 453, in as_cached
    new_expiry = time.monotonic() + ttl if ttl else None
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

**Comment by Hoxbro** [comment]
This will probably need a transition period. What you suggest breaks backward compatibility. 

Function signature during the transition period could require `ttl` to be a keyword:
`def as_cached(self, key: str, fn: Callable[[], T], *, ttl: int = None, **kwargs) -> T:`

**Comment by MarcSkovMadsen** [comment]
## Reference

https://awesome-panel.org/tabulator

![image](https://user-images.githubusercontent.com/42288570/227876892-4112d6d2-ac14-4580-b9d6-810e0651fefc.png)

![image](https://user-images.githubusercontent.com/42288570/227876719-6a363e97-7cd1-46c0-a228-6da5afc2f65e.png)

**Comment by MarcSkovMadsen** [comment]
I would suggest making the change in connecting with 1.0. There we can fix anything that should have been different.

**Comment by MarcSkovMadsen** [comment]
You are probably right @Hoxbro and I'm too hasty 👍

**Comment by philippjfr** [comment]
We really should review the API and use keyword only args where possible.

**Comment by MarcSkovMadsen** [comment]
Yes. This is such a time waster. Everything I want to use `pd.read_csv` and `as_cached` I have to look up that the argument is called `filepath_or_buffer`. No body writes that. No body remembers that. I just makes the code harder to read.

**Comment by OSuwaidi** [comment]
I was also confused by this, because according to the [docs](https://panel.holoviz.org/how_to/caching/manual.html):
"_If provided, the `args` and `kwargs` will also be hashed making it easy to cache (or memoize) on the arguments to the function:_"
```
def load_data(*args, **kwargs):
    return ... # Load some data

data = pn.state.as_cached('data', load_data, *args, **kwargs)
```
Which seems to imply that you can pass positional arguments or `*args` and `**kwargs` directly after the function, but in reality, everything has to be passed as keyword arguments (named parameters).

**Comment by jurriaanpro** [comment]
Also, currently `fn` requires a `Callable[[], T]` which is a function that accepts no arg/kwargs. I believe it should be updated to `Callable[..., T]` (ellipsis literal) to allow any arbitrary args/kwargs to be passed to the given function.

Didn't think this was worth creating a new issue, but let me know if I should.
