### ISSUE TITLE
Errors in Dev docs when executing cells via pyodide on iphone

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4636]
When navigating to https://pyviz-dev.github.io/panel/getting_started/build_app.html and executing the first cell I get an error: gzip.BadGzipFile: Not a gzipped file (b'da')

![image](https://user-images.githubusercontent.com/42288570/231638257-b3861fb8-ddac-4852-a2f9-3f9133e3c92c.jpeg)

```python
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/panel/io/mime_render.py", line 178, in exec_with_return
    exec(compile(init_ast, "<ast>", "exec"), global_context)
  File "<ast>", line 4, in <module>
  File "/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1753, in _make_engine
    return mapping[engine](f, **self.options)
  File "/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 79, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 547, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 636, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1965, in pandas._libs.parsers.raise_parser_error
  File "/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'da')
```

**This was from safari on my iPhone. Its the same when using Chrome on my iphone**

**Comment by MarcSkovMadsen** [comment]
It works fine in Edge on my windows laptop

![image](https://user-images.githubusercontent.com/42288570/231639013-958f7716-2aa1-46d4-8e8e-e498de20c24b.png)

**Comment by philippjfr** [comment]
Closing as I wasn't able to reproduce and there's no action we can take on our end to fix this.

**Comment by MarcSkovMadsen** [comment]
Ok. I can still reproduce the issue.
