### ISSUE TITLE
ModuleNotFoundError: No module named 'myst_nb.parser'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4677]
I'm working with current `main` branch on a new virtual environment. I believe the all the extras in the setup.py are installed except python-graphviz which cannot be installed on windows via pip.

I'm trying to build the docs locally. As this is not described any where I'm trying to use ´sphinx-build` as below. But it fails.

How do I solve?

```bash
$ sphinx-build -b html doc build/doc
Running Sphinx v5.3.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\repos\private\panel\.venv\lib\site-packages\sphinx\config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "C:\repos\private\panel\doc\conf.py", line 10, in <module>
    from nbsite.shared_conf import *
  File "C:\repos\private\panel\.venv\lib\site-packages\nbsite\shared_conf.py", line 5, in <module>
    from nbsite import nbbuild
  File "C:\repos\private\panel\.venv\lib\site-packages\nbsite\nbbuild.py", line 37, in <module>
    from myst_nb.parser import nb_to_tokens, nb_output_to_disc, tokens_to_docutils
ModuleNotFoundError: No module named 'myst_nb.parser'
```

**Comment by MarcSkovMadsen** [comment]
Seems I need to `pip install nbsite==0.8.0rc24`
