### ISSUE TITLE
Sphinx Pyodide runs out of memory in Firefox on Windows

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4719]
If I go to https://pyviz-dev.github.io/panel/getting_started/build_app.html and run the download of pyodide I get

```bash
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/panel/io/mime_render.py", line 178, in exec_with_return
    exec(compile(init_ast, "<ast>", "exec"), global_context)
  File "<ast>", line 1, in <module>
  File "/lib/python3.11/site-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/lib/python3.11/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/lib/python3.11/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/lib/python3.11/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/lib/python3.11/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/lib/python3.11/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: Could not load dynamic lib: /lib/python3.11/site-packages/matplotlib/_path.cpython-311-wasm32-emscripten.so
out of memory
```

![image](https://user-images.githubusercontent.com/42288570/234924827-925db58d-8f7e-42d1-aeae-fbe84d62019a.png)

OS: Windows 10
Browser: Firefox 102.10.0esr (32-bit)

It works for me in Chrome.

**Comment by philippjfr** [comment]
I cannot reproduce, but separately, there's no action we can take on our side to resolve this.

**Comment by philippjfr** [comment]
Indeed, how did you end up with a 32-bit browser on Windows 10 in 2023?

**Comment by philippjfr** [comment]
I'm very happy to explicitly state that 32-bit browsers are not supported and we will make no effort to support them.

**Comment by jbednar** [comment]
Can you _please_ support my 8-bit browser that runs on a PDP?

**Comment by philippjfr** [comment]
Just read some of the internal WASM documentation and while WASM itself is 32-bit it has to compete with the system and other browser tabs to allocate a contiguous block in memory. This means that in a 32-bit system it will frequently fail to allocate anything larger than about 256 MB, so yeah it's basically unusable for our purposes.
