### ISSUE TITLE
Dev Vizzu Reference Docs: ModuleNotFoundError: No module named 'IPython'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4728]
If I run the Vizzu dev docs at https://pyviz-dev.github.io/panel/reference/panes/Vizzu.html%20https://pyviz-dev.github.io/panel/reference/panes/Vizzu.html there is an error

```bash
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/panel/io/mime_render.py", line 182, in exec_with_return
    out = eval(compile(_convert_expr(last_ast.body[0]), "<ast>", "eval"), global_context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ast>", line 25, in <module>
  File "/lib/python3.11/site-packages/panel/viewable.py", line 907, in embed
    show_embed(
  File "/lib/python3.11/site-packages/panel/io/notebook.py", line 438, in show_embed
    from IPython.display import publish_display_data
ModuleNotFoundError: No module named 'IPython'
```

![image](https://user-images.githubusercontent.com/42288570/235155011-e9c92c69-91f2-4fb1-81ce-0e2b5f53fbc6.png)

**Comment by MarcSkovMadsen** [comment]
Migrated to #4735
