### ISSUE TITLE
DeserializationError serving HoloViews objects

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#4777]
Serving this app and moving the sliders around I get the traceback reported below. There's no error when `sine` and `cosine` are wrapped in a DynamicMap.

```python
import panel as pn
import numpy as np
import holoviews as hv

pn.extension()

xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)

@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
    return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
        responsive=True, min_height=400)

@pn.depends(freq=freq, phase=phase)
def cosine(freq, phase):
    return hv.Curve((xs, np.cos(xs*freq+phase))).opts(
        responsive=True, min_height=400)

pn.Column(
    freq,
    phase,
    pn.Row(
        # hv.DynamicMap(sine),
        # hv.DynamicMap(cosine),
        sine,
        cosine,
    )
).servable()
```

Traceback:
```
message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': 'p4931'}, 'attr': 'inner_width', 'new': 765}, {'kind': 'ModelChanged', 'model': {'id': 'p4931'}, 'attr': 'inner_height', 'new': 803}, {'kind': 'ModelChanged', 'model': {'id': 'p4931'}, 'attr': 'outer_width', 'new': 854}, {'kind': 'ModelChanged', 'model': {'id': 'p4931'}, 'attr': 'outer_height', 'new': 858}]} 
 error: DeserializationError("can't resolve reference 'p4931'")
Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/document/document.py", line 369, in apply_json_patch
    patch: PatchJson = deserializer.deserialize(patch_json)
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 499, in deserialize
    return self.decode(obj.content, obj.buffers)
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 514, in decode
    return self._decode(obj)
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 555, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 555, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 557, in _decode
    return [self._decode(entry) for entry in obj]
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 557, in <listcomp>
    return [self._decode(entry) for entry in obj]
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 555, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 555, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 553, in _decode
    return self._decode_ref(cast(Ref, obj))
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 567, in _decode_ref
    self.error(f"can't resolve reference '{id}'")
  File "/Users/mliquet/miniconda3/envs/panel38/lib/python3.8/site-packages/bokeh/core/serialization.py", line 715, in error
    raise DeserializationError(message)
bokeh.core.serialization.DeserializationError: can't resolve reference 'p4931'
```

**Comment by philippjfr** [comment]
Also resolved in 3.1.1rc1 (but please confirm).
