### ISSUE TITLE
.clone bug: Should determine readonly parameters from new instance. Not existing instance

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4829]
panel==1.0.0rc8

I am trying to create a UI for the Hugging Face Transformer Agent :-)

![image](https://github.com/holoviz/panel/assets/42288570/962bc061-422a-4e27-947d-709be5f2776a)

I experienced a subtle bug when using the terminal.

## Reproduce

```python
import panel as pn
import time
import param

pn.extension("terminal", design="bootstrap")


class App(param.Parameterized):
    submit = param.Event()
    running = param.Boolean()

    def __init__(self, **params):
        super().__init__(**params)

        self._terminal = pn.widgets.Terminal(name="Logs")
        self._result = pn.panel("Some result")

    @pn.depends("submit", watch=True)
    def _submit(self):
        self.running = True
        time.sleep(1)
        self.running = False

    @pn.depends("running")
    def view(self):
        if self.running:
            return self._terminal
        return self._result


app = App()

pn.Tabs(pn.Column(app.param.submit, app.view), app._terminal).servable()
```

Serve the app and click submit

https://github.com/holoviz/panel/assets/42288570/c90b4855-60ea-4e5a-aa08-e87165fa3822

```bash
$ panel serve script.py --autoreload
2023-05-13 08:54:44,017 Starting Bokeh server version 3.1.1 (running on Tornado 6.3.1)
2023-05-13 08:54:44,019 User authentication hooks NOT provided (default user enabled)
2023-05-13 08:54:44,021 Bokeh app running at: http://localhost:5006/script
2023-05-13 08:54:44,021 Starting Bokeh server with process id: 62566
2023-05-13 08:54:50,013 WebSocket connection opened
2023-05-13 08:54:50,014 ServerConnection created
2023-05-13 08:55:10,208 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1036'}]]}}}]} 
 error: TypeError("Read-only parameter 'ncols' cannot be modified")
Traceback (most recent call last):
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/reactive.py", line 487, in _server_event
    self._comm_event(doc, event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/reactive.py", line 474, in _comm_event
    state._handle_exception(e)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/io/state.py", line 431, in _handle_exception
    raise exception
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/reactive.py", line 472, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/reactive.py", line 409, in _process_bokeh_event
    self._process_event(event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/widgets/button.py", line 233, in _process_event
    self.clicks += 1
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 380, in _f
    instance_param.__set__(obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 382, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 382, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1379, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2225, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2203, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/param.py", line 498, in event
    self.object.param.trigger(p_name)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2164, in trigger
    self_.set_param(**dict(params, **triggers))
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2093, in set_param
    return self_.update(kwargs)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2066, in update
    self_._batch_call_watchers()
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2256, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2203, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 739, in caller
    return function()
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 423, in _depends
    return func(*args, **kw)
  File "/home/jovyan/repos/private/tmp/script.py", line 20, in _submit
    self.running = True
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 380, in _f
    instance_param.__set__(obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 382, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1379, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2225, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2203, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/param.py", line 864, in update_pane
    self._replace_pane()
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/param.py", line 819, in _replace_pane
    self._update_inner(new_object)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/pane/base.py", line 674, in _update_inner
    new_pane, internal = self._update_from_object(
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/pane/base.py", line 663, in _update_from_object
    pane = object.clone()
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/viewable.py", line 994, in clone
    return type(self)(**dict(inherited, **params))
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/widgets/terminal.py", line 269, in __init__
    super().__init__(output=output, **params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/widgets/base.py", line 73, in __init__
    super().__init__(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/reactive.py", line 538, in __init__
    super().__init__(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/reactive.py", line 115, in __init__
    super().__init__(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/viewable.py", line 806, in __init__
    super().__init__(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/viewable.py", line 640, in __init__
    super().__init__(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/panel/viewable.py", line 391, in __init__
    super().__init__(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 3458, in __init__
    self.param._setup_params(**params)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1522, in override_initialization
    fn(parameterized_instance, *args, **kw)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1788, in _setup_params
    setattr(self, name, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 382, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 382, in _f
    return f(self, obj, val)
  File "/home/jovyan/repos/private/tmp/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1322, in __set__
    raise TypeError(
TypeError: Read-only parameter 'ncols' cannot be modified
```

## Discussion

My understanding of the issue is that

- When the terminal is display on the second tab the readonly parameter `ncols` is set to 10 in the frontend.
- For some reason this changes the setting of the parameters `readonly` value to `False`
- When `submit` is clicked I try to display the `terminal` in a second place. To do that Panel runs the `Viewable.clone` method. The 

![image](https://github.com/holoviz/panel/assets/42288570/c32fe655-f693-4208-bf6b-667bc9717d50)

Here it uses the `readonly` setting of the existing instance. Not the new one. Since they differ it results in an exception.

**Comment by MarcSkovMadsen** [comment]
The example below can be used for pytest

```python
import panel as pn
import param

terminal = pn.widgets.Terminal()
with param.edit_constant(terminal):
    terminal.param.ncols.readonly = False
    terminal.ncols = 10

terminal.clone()
```

Currently it raises the `TypeError`. When fixed it should not.

**Comment by philippjfr** [comment]
Seems like an issue with resetting the readonly attribute to False.
