### ISSUE TITLE
Developer Guide instructions unsuccessful for me

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#4833]
https://panel.holoviz.org/developer_guide/index.html does not seem to work for me from a forked repo.

Debugging a bit starting in setup.py
```

    if version is not None:
        return version.Version.setup_version(basepath, reponame, archive_commit="$Format:%h$")
```

That returns None so I dig into version.py in param:
```
print(info['version_string'])
```

Also returns None so I look at `get_setup_version`
```

        fpath = os.path.join(setup_path, pkgname, "__init__.py")
        version = Version(fpath=fpath, reponame=reponame, archive_commit=archive_commit)
```

`verison is None` here too, and that is where I stopped.

Maybe my panel fork only cloned the main branch? I also didn't just use `git clone https://github.com/holoviz/panel.git` because I don't have permission to push to repo, but when I do clone and `pip install -e .` it works.

Traceback:
```
Obtaining file:///Users/airbook/Applications/Developer/python/repos/panel
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      /Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/dist.py:520: SetuptoolsDeprecationWarning: Invalid version: 'None'.
      !!

              ********************************************************************************
              The version specified is not a valid version according to PEP 440.
              This may not work as expected with newer versions of
              setuptools, pip, and PyPI.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        self._validate_version(self.metadata.version)
      /Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running dist_info
      /Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/command/egg_info.py:131: SetuptoolsDeprecationWarning: Invalid version: 'None'.
      !!

              ********************************************************************************
              Version 'None' is not valid according to PEP 440.

              Please make sure to specify a valid version for your package.
              Also note that future releases of setuptools may halt the build process
              if an invalid version is given.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://peps.python.org/pep-0440/ for details.
              ********************************************************************************

      !!
        return _normalization.best_effort_version(tagged)
      Traceback (most recent call last):
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 454, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 317, in <module>
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.ensure_finalized()
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/command/dist_info.py", line 75, in finalize_options
          egg_info.finalize_options()
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
          parsed_version = packaging.version.Version(self.egg_version)
        File "/Users/airbook/miniforge3/envs/panel_dev/lib/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'None'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
TaskFailed - taskid:develop_install
Command failed: 'python -m pip install --no-deps --no-build-isolation -e .' returned 1
```

**Comment by analog-cbarber** [comment]
I see the same thing on a MacBook M1 running Ventura 13.3.1.

Can someone at least suggest a workaround? I cannot really contribute any fixes if I can't get my environment set up correctly....

**Comment by Hoxbro** [comment]
Can you check if you have any `git tags` in the forked repo?

**Comment by analog-cbarber** [comment]
Indeed there are no tags in my fork. I guess the github fork button does not copy tags. I guess I have to do that manually...

**Comment by analog-cbarber** [comment]
That did the trick.

The developer guide should be updated to tell people to copy the tags. I did:

```
git remote add upstream https://github.com/holoviz/panel.git
git fetch --tags upstream
git push --tags
```
