### ISSUE TITLE
Audio pane does not support numpy arrays

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#4837]
panel==1.0.0rc8

According to Panel reference documentation for Audio, then Numpy arrays are supported. But if I try I get `ValueError: Audio pane does not support objects of type 'ndarray'.`

```python
import numpy
import panel as pn

sr = 22050  # sample rate
T = 2.0  # seconds
t = numpy.linspace(0, T, int(T * sr), endpoint=False)  # time variable
x = 0.5 * numpy.sin(2 * numpy.pi * 440 * t)  # pure sine wave at 440 Hz

pn.pane.Audio(object=x, sample_rate=sr).servable()
```

```bash
$ python script.py
Traceback (most recent call last):
  File "/home/jovyan/repos/private/transformers-agent-ui/script.py", line 9, in <module>
    pn.pane.Audio(object=x, sample_rate=sr).servable()
  File "/home/jovyan/repos/private/transformers-agent-ui/.venv/lib/python3.10/site-packages/panel/pane/base.py", line 151, in __init__
    self._type_error(self.object)
  File "/home/jovyan/repos/private/transformers-agent-ui/.venv/lib/python3.10/site-packages/panel/pane/base.py", line 200, in _type_error
    raise ValueError("%s pane does not support objects of type '%s'." %
ValueError: Audio pane does not support objects of type 'ndarray'.
```

**Comment by MarcSkovMadsen** [comment]
The problem with example is that the object is `dtype('float64')`.

![image](https://github.com/holoviz/panel/assets/42288570/5dce41e6-5b08-4fb6-84c0-cb27fbb67aef)

**Comment by MarcSkovMadsen** [comment]
Now I remember that I have tried before combining the Audio Pane and Numpy. And the numpy audio examples I've found never works with the Audio pane.

**Comment by MarcSkovMadsen** [comment]
If we convert to `numpy.int16` as below it works

import numpy
import panel as pn

sr = 22050  # sample rate
T = 2.0  # seconds
t = numpy.linspace(0, T, int(T * sr), endpoint=False)  # time variable
x = 0.5 * numpy.sin(2 * numpy.pi * 440 * t)  # pure sine wave at 440 Hz

print(type(x), isinstance(x, numpy.ndarray))
x = (x * 32768.0).astype(numpy.int16)
pn.pane.Audio(object=x, sample_rate=sr).servable()

**Comment by MarcSkovMadsen** [comment]
Studying https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html I can see that there is no reason to restrict us to numpy.int16. We can either convert as I've done above to make smaller wavfile. Or we can just let scipy determine the wavfile format

![image](https://github.com/holoviz/panel/assets/42288570/e9fbad0f-4e31-4336-87b6-3599dcf36886)

**Comment by MarcSkovMadsen** [comment]
I can see Hugging Face uses `soundfile` for conversion. Might help us get rid of scipy dependency.

```
import IPython
import soundfile as sf

def play_audio(audio):
    sf.write("speech_converted.wav", audio.numpy(), samplerate=16000)
    return IPython.display.Audio("speech_converted.wav")
```
