### ISSUE TITLE
FastGridTemplate example in documentation generate error. Panel Version: 1.0.3 (same error for FastListTemplate)

### ISSUE THREAD

**Issue by federalSoftware** [holoviz/panel#4982]
#### ALL software version info
```
pip list
Package            Version
------------------ --------
bleach             6.0.0
bokeh              3.1.1
certifi            2023.5.7
charset-normalizer 3.1.0
colorama           0.4.6
colorcet           3.0.1
contourpy          1.0.7
holoviews          1.16.0
hvplot             0.8.3
idna               3.4
importlib-metadata 6.6.0
Jinja2             3.1.2
linkify-it-py      2.0.2
Markdown           3.4.3
markdown-it-py     2.2.0
MarkupSafe         2.1.2
mdit-py-plugins    0.3.5
mdurl              0.1.2
numpy              1.24.3
packaging          23.1
pandas             2.0.2
panel              1.0.3
param              1.13.0
Pillow             9.5.0
pip                20.2.3
pyct               0.5.0
python-dateutil    2.8.2
pytz               2023.3
pyviz-comms        2.3.0
PyYAML             6.0
requests           2.31.0
setuptools         49.2.1
six                1.16.0
tornado            6.3.2
tqdm               4.65.0
typing-extensions  4.6.2
tzdata             2023.3
uc-micro-py        1.0.2
urllib3            2.0.2
webencodings       0.5.1
xyzservices        2023.5.0
zipp               3.15.0
```
Code to reproduce the error
```

import hvplot.pandas
import numpy as np
import panel as pn
import pandas as pd

xs = np.linspace(0, np.pi)

freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)

def sine(freq, phase):
    return pd.DataFrame(dict(y=np.sin(xs*freq+phase)), index=xs)

def cosine(freq, phase):
    return pd.DataFrame(dict(y=np.cos(xs*freq+phase)), index=xs)

dfi_sine = hvplot.bind(sine, freq, phase).interactive()
dfi_cosine = hvplot.bind(cosine, freq, phase).interactive()

plot_opts = dict(
    responsive=True, min_height=400,
    # Align the curves' color with the template's color
    color=pn.template.FastListTemplate.accent_base_color
)

# Instantiate the template with widgets displayed in the sidebar
template = pn.template.FastListTemplate(
    title="FastListTemplate",
    sidebar=[freq, phase],
)
# Append a layout to the main area, to demonstrate the list-like API
template.main.append(
    pn.Row(
        dfi_sine.hvplot(title='Sine', **plot_opts).output(),
        dfi_cosine.hvplot(title='Cosine', **plot_opts).output(),
    )
)
template.servable();
```

#### browser Error
```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'c:\desarrollo\python\panel\venv\lib\site-packages\panel\dist\bundled\https:\[fonts.googleapis.com](http://fonts.googleapis.com/)\css?family=Open+Sans'

Traceback (most recent call last):
  File "c:\desarrollo\python\panel\venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "C:\desarrollo\python\panel\fastGridTemp.py", line 38, in <module>
    template.servable();
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\template\base.py", line 388, in servable
    return super().servable(title, location, area, target)
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\viewable.py", line 391, in servable
    self.server_doc(title=title, location=location) # type: ignore
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\template\base.py", line 351, in server_doc
    return self._init_doc(doc, title=title, location=location)
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\template\base.py", line 609, in _init_doc
    self._update_vars()
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\template\fast\base.py", line 94, in _update_vars
    super()._update_vars()
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\template\base.py", line 742, in _update_vars
    self._render_variables['template_resources'] = self.resolve_resources()
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\template\base.py", line 644, in resolve_resources
    for rname, res in self._design.resolve_resources(cdn).items():
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\theme\base.py", line 339, in resolve_resources
    resource_types = super().resolve_resources(cdn)
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\io\resources.py", line 496, in resolve_resources
    resolved_resource = self._resolve_resource(
  File "c:\desarrollo\python\panel\venv\lib\site-packages\panel\io\resources.py", line 443, in _resolve_resource
    if bundlepath.is_file():
  File "C:\Python39\lib\pathlib.py", line 1439, in is_file
    return S_ISREG(self.stat().st_mode)
  File "C:\Python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'c:\\desarrollo\\python\\panel\\venv\\lib\\site-packages\\panel\\dist\\bundled\\https:\\fonts.googleapis.com\\css?family=Open+Sans'

**Comment by Hoxbro** [comment]
It looks like a bug, but I can't recreate it. Can you describe what you are doing in more detail? Do you have any environment variables, and how do you launch the script?

**Comment by federalSoftware** [comment]
Hello.

At this moment I am just testing the features of the version 1.0.3, following the documentation.
I think I don't have any strange environment variables. do you need to see them?

I am using VSC. I launch the script with the following syntax:

panel serve fastGridTemp.py --show --autoreload

After starting the server, the log is:

2023-05-30 16:29:03,788 Starting Bokeh server version 3.1.1 (running on Tornado 6.3.2)
2023-05-30 16:29:03,788 User authentication hooks NOT provided (default user enabled)
2023-05-30 16:29:03,793 Bokeh app running at: http://localhost:5006/fastGridTemp
2023-05-30 16:29:03,793 Starting Bokeh server with process id: 20608
2023-05-30 16:29:04,311 WebSocket connection opened
2023-05-30 16:29:04,313 ServerConnection created

After opening the browser it shows the error that I posted

**Comment by federalSoftware** [comment]
I am testing the code on a laptop with Windows 11 Version 22H2 (OS Build 22621.1702)

These are the steps I did, creating a new clean project.

1) Create a new clean project, using a virtual environment: python -m venv venv
2) After activating the virtual environment, install the panel with:
pip install panel
3) then install the hvplot with: pip install hvplot
4) Create a new file, and copy the code that is in the url:
  https://panel.holoviz.org/reference/templates/FastGridTemplate.html
5) run the code with the following statement:
panel serve FastGridTemp.py --show --autoreload

I am using windows powershell as terminal.

The error comes out with 3 different browsers that I have tried:

Chrome: Version 113.0.5672.127 (Official Build) (64-bit)
Chrome: Version 114.0.5735.45 (Official Build) beta (64-bit)
Microsoft Edge: Version 113.0.1774.57 (Official build) (64-bit)

I'm going to create a video with all these steps, creating a new project, and try to run the code again.

**Comment by federalSoftware** [comment]
I just created a video with all the steps I did to show the error.
I did it by creating a new project.
The video weighs 14 MB so I'll give you a link to google drive

https://drive.google.com/file/d/1sVWZntsro0nrHcym440WDHMH-aDDONKC/view?usp=sharing

**Comment by federalSoftware** [comment]
I tested all the other templates that are in the official panel 1.0.3 documentation, copying exactly the code that is on the page.
Here is a detail of those that work well and those that do not work.

They work fine:

BootStrap
GoldenLayout
react
vanilla

They do not work:

FastGridTemplate
FastListTemplate

Material, with the following error:

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'c:\development\python\testpanel\venv\lib\site-packages\panel\dist\bundled\https:\fonts.googleapis. com\css?family=Roboto:300,400,500'

Slides: with the following Error:
2023-05-30 19:08:37,814 Uncaught exception GET /app (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/app', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
   File "c:\development\python\testpanel\venv\lib\site-packages\tornado\web.py", line 1786, in _execute
     result = await result
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\io\server.py", line 503, in get
     page = server_html_page_for_session(
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\io\server.py", line 312, in server_html_page_for_session
     bundle = bundle_resources(doc.roots, resources)
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\io\resources.py", line 364, in bundle_resources
     js_files.extend(js_resources.js_files)
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\io\resources.py", line 683, in js_files
     design_js = config.design().resolve_resources(
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\theme\base.py", line 339, in resolve_resources
     resource_types = super().resolve_resources(cdn)
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\io\resources.py", line 496, in resolve_resources
     resolved_resource = self._resolve_resource(
   File "c:\development\python\testpanel\venv\lib\site-packages\panel\io\resources.py", line 443, in _resolve_resource
     if bundlepath.is_file():
   File "C:\Python39\lib\pathlib.py", line 1439, in is_file
     return S_ISREG(self.stat().st_mode)
   File "C:\Python39\lib\pathlib.py", line 1221, in stat
     return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'c:\\development\\python\\testpanel\\venv\\lib\\site-packages\\panel\\dist\\ bundled\\https:\\fonts.googleapis.com\\css?family=Roboto:300,400,500'
2023-05-30 19:08:37,820 500 GET /app (::1) 695.45ms
2023-05-30 19:08:37,827 WebSocket connection closed: code=1001, reason=None

**Comment by philippjfr** [comment]
Seems like checking whether a path is a string triggers an error in your case which is quite strange. We can easily put a guard around that though. Thanks for the detailed report.
