### ISSUE TITLE
Running pipeline tutorial and getting warning `WARNING:param.LaTeX00990: ...` and error `'str' object has no attribute 'param'`

### ISSUE THREAD

**Issue by xareelee** [holoviz/panel#4990]
#### ALL software version info
panel 1.0.3
bokeh 3.1.1

python 3.10.11
macOS 13.3.1
VSCode 1.78.2

Jupyter core packages...
IPython          : 8.13.2
ipykernel        : 6.23.1
ipywidgets       : 8.0.6
jupyter_client   : 8.2.0
jupyter_core     : 5.3.0
jupyter_server   : 2.6.0
jupyterlab       : 3.6.3
nbclient         : 0.8.0
nbconvert        : 7.4.0
nbformat         : 5.8.0
notebook         : 6.5.4
qtconsole        : not installed
traitlets        : 5.9.0

#### Description of expected behavior and the observed behavior
I'm trying to follow this tutorial in Jupyter Notebook: https://panel.holoviz.org/how_to/pipeline/simple_pipeline.html

#### Complete, minimal, self-contained example code that reproduces the issue

Just execute the first 3 code blocks in the tutorial:

```py
import param
import panel as pn
pn.extension('katex')

pipeline = pn.pipeline.Pipeline()

class Stage1(param.Parameterized):

    a = param.Integer(default=2, bounds=(0, 10))
    b = param.Integer(default=3, bounds=(0, 10))

    @param.output(('c', param.Integer), ('d', param.Integer))
    def output(self):
        return self.a * self.b, self.a ** self.b

    @param.depends('a', 'b')
    def view(self):
        c, d = self.output()
        c_out = pn.pane.LaTeX('${a} * {b} = {c}$'.format(
            a=self.a, b=self.b, c=c), style={'font-size': '2em'})
        d_out = pn.pane.LaTeX('${a}^{{{b}}} = {d}$'.format(
            a=self.a, b=self.b, d=d), style={'font-size': '2em'})
        return pn.Column(
		    c_out, d_out,  margin=(40, 10), styles={'background': '#f0f0f0'}
		)

    def panel(self):
        return pn.Row(self.param, self.view,)

stage1 = Stage1()
stage1.panel()
```

#### Screenshots or screencasts of the bug in action

It shows warnings when running: `WARNING:param.LaTeX00990: Setting non-parameter attribute style={'font-size': '2em'} using a mechanism intended only for parameters `

![Screenshot 2023-05-31 at 18 58 46](https://github.com/holoviz/panel/assets/804308/dbb65cd6-dcd2-4403-8699-976cf54fcba0)

#### Stack traceback and/or browser JavaScript console output

It shows errors when changing the value o f the slider:

```
Traceback (most recent call last):
  File "{path_to_packages}/panel/reactive.py", line 379, in _process_events
    self.param.update(**self_events)
  File "{path_to_packages}/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "{path_to_packages}/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "{path_to_packages}/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "{path_to_packages}/panel/param.py", line 498, in link_widget
    self.object.param.update(**{p_name: change.new})
  File "{path_to_packages}/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "{path_to_packages}/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "{path_to_packages}/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "{path_to_packages}/panel/param.py", line 872, in update_pane
    self._replace_pane()
  File "{path_to_packages}/panel/param.py", line 827, in _replace_pane
    self._update_inner(new_object)
  File "{path_to_packages}/panel/pane/base.py", line 700, in _update_inner
    new_pane, internal = self._update_from_object(
  File "{path_to_packages}/panel/pane/base.py", line 655, in _update_from_object
    cls._recursive_update(old_object, i, old, new)
  File "{path_to_packages}/panel/pane/base.py", line 629, in _recursive_update
    old.param.update(**new_params)
AttributeError: 'str' object has no attribute 'param'
```

**Comment by philippjfr** [comment]
Thanks, will be fixed by the 1.0.4 release later today.
