### ISSUE TITLE
Deserialization error when updating layout with Holoviews and threading enabled

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#5072]
#### ALL software version info
Panel 1.1.0
Bokeh 3.1.1
Holoviews 1.16.0
Server mode

#### Description of expected behavior and the observed behavior
With threading enabled, when updating an app layout with an Holoviews plot, I get a deserialization error thrown at me more often than not. It does not seem to affect the behavior of the app though.

#### Complete, minimal, self-contained example code that reproduces the issue

`panel serve app.py --num-threads 2` with `app.py`:

```python
import panel as pn
import holoviews as hv
import numpy as np
pn.extension()


def callback(_):
    column.clear()
    column.append(hv.Scatter(np.random.rand(100, 2)))


button = pn.widgets.Button(name='Click')
button.on_click(callback)
column = pn.Column()
pn.Row(button, column).servable()
```

#### Stack traceback and/or browser JavaScript console output
```
2023-06-08 14:57:42,630 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': 'p1387'}, 'attr': 'inner_width', 'new': 217}, {'kind': 'ModelChanged', 'model': {'id': 'p1387'}, 'attr': 'inner_height', 'new': 244}, {'kind': 'ModelChanged', 'model': {'id': 'p1387'}, 'attr': 'outer_width', 'new': 300}, {'kind': 'ModelChanged', 'model': {'id': 'p1387'}, 'attr': 'outer_height', 'new': 300}]} 
 error: DeserializationError("can't resolve reference 'p1387'")
Traceback (most recent call last):
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/document/document.py", line 369, in apply_json_patch
    patch: PatchJson = deserializer.deserialize(patch_json)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 501, in deserialize
    return self.decode(obj.content, obj.buffers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 516, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 559, in _decode
    return [self._decode(entry) for entry in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 559, in <listcomp>
    return [self._decode(entry) for entry in obj]
            ^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 557, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 555, in _decode
    return self._decode_ref(cast(Ref, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 569, in _decode_ref
    self.error(f"can't resolve reference '{id}'")
  File "/home/mathurin/miniconda3/envs/panel/lib/python3.11/site-packages/bokeh/core/serialization.py", line 717, in error
    raise DeserializationError(message)
bokeh.core.serialization.DeserializationError: can't resolve reference 'p1387'
```

**Comment by philippjfr** [comment]
Thanks @TheoMathurin. We're aware of the issue and I'll close for three reasons:

1. The error indeed has no effective at all
2. There is absolutely nothing we can do in Panel to avoid this
3. This is already fixed in Bokeh 3.2.0 dev releases

I've assigned to 1.2.0 milestone which will be the Bokeh 3.2 compatible release once it's out some time next week or the week after next.

**Comment by TheoMathurin** [comment]
Alright thanks for the quick response, it's good that this will be fixed for the sake of clarity in log files.

**Comment by MarcSkovMadsen** [comment]
I came searching for this issue. I know it does not affect anything. But we see this in a key component of our trading application. A lot of people without Panel knowledge work around this application across the business and if they see a long scary log like that they believe that is the cause of the other issue they are trying to solve or just that there is an issue in general with the application. 

You then have to explain and try to convince them you know what you are doing.

Thus is a quite costly piece of log.
