### ISSUE TITLE
pn.state.notifications is None inside functions in Pyodide

### ISSUE THREAD

**Issue by mroleksul** [holoviz/panel#5090]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)
Panel 1.1.0
Bokeh 3.1.1
Ubuntu 20.04.6 LTS (WSL2/VSCode)
No difference in different browsers

#### Description of expected behavior and the observed behavior
I would expect pn.state.notifications.warning("Warning!") to send and display a notification toast, even when inside a function. No issues when running the Bokeh server locally.

After converting the app to Pyodide, whenever pn.state.notifications.warning("Warning!") (or any other notification) is called, an error appears in the console.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn

pn.extension(notifications=True)

# Create a button
button = pn.widgets.Button(name='Click me', button_type='primary')

# Callback function to be executed when the button is clicked
def button_click(event):
    pn.state.notifications.warning("Warning!")

# Attach the callback function to button's click event
button.on_click(button_click)

# Create a Panel to show the button
panel = pn.Row(button)

# Serve the Panel
panel.servable()

```
I convert it with:
`panel convert minimal.py --to pyodide-worker --out minimal --watch`

Or run the Bokeh server with:
`panel serve minimal.py --show --autoreload`
#### Stack traceback and/or browser JavaScript console output

```Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 2, in <module>
  File "/lib/python3.11/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/lib/python3.11/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/lib/python3.11/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 492, in _server_event
    self._comm_event(doc, event)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 479, in _comm_event
    state._handle_exception(e)
  File "/lib/python3.11/site-packages/panel/io/state.py", line 432, in _handle_exception
    raise exception
  File "/lib/python3.11/site-packages/panel/reactive.py", line 477, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 414, in _process_bokeh_event
    self._process_event(event)
  File "/lib/python3.11/site-packages/panel/widgets/button.py", line 243, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "<exec>", line 18, in button_click
AttributeError: 'NoneType' object has no attribute 'warning'

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d63
    at pyodide.asm.wasm:0x159d18
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:126959)
    at pyodide.asm.wasm:0x19f6c2
    at pyodide.asm.wasm:0x286507
    at pyodide.asm.wasm:0x1e0613
    at pyodide.asm.wasm:0x19fba9
    at pyodide.asm.wasm:0x19fe6a
    at pyodide.asm.wasm:0x19ff0c
    at pyodide.asm.wasm:0x264a0c
    at pyodide.asm.wasm:0x26a9f1
    at pyodide.asm.wasm:0x1a0034
    at pyodide.asm.wasm:0x19fcc4
    at pyodide.asm.wasm:0x15952e
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75551)
    at Module.callPyObject (pyodide.asm.js:9:75996)
    at wrapper (pyodide.asm.js:9:57850)

#### Screenshots or screencasts of the bug in action

Pyodide:
https://github.com/holoviz/panel/assets/63408297/cc40f910-b494-4dbf-9282-d699e6ec57cb

Local bokeh server:
https://github.com/holoviz/panel/assets/63408297/76ab7442-6429-483a-921f-b84064c18d23

**Comment by oleksulkowski** [comment]
Hi @philippjfr! I wanted to ask about the progress on this issue as I need it for publication of my app. I might implement other ways to display warning messages in the meantime.

**Comment by oleksulkowski** [comment]
Thank you @philippjfr, your workaround in #5488 worked in this case too.

**Comment by cdeil** [comment]
Currently notifications in the docs are broken here:

https://panel.holoviz.org/reference/global/Notifications.html

<img width="1725" alt="Screenshot 2023-10-11 at 22 41 34" src="https://github.com/holoviz/panel/assets/852409/2138a5fe-825d-45ed-9c6c-14f1d9011138">
