### ISSUE TITLE
Panel 1.1.1 throws an exception in PyScript when setting DatetimePicker widget value to None from a callback

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5155]
#### ALL software version info
Browser: Vivaldi 6.0.2979.22 (Stable channel) (64-bit)
Bokeh 3.1.1
Panel 1.1.0
Pyodide 0.23.3
Pyscript 2023.03.01

#### Description of expected behavior and the observed behavior

In Panel 0.14.4 with PyScript I could reset a DatetimePicker value back to None inside a button callback and that works fine. If I try this in Panel 1.1.0 in PyScript it throws a _pyodide.ffi.JsException: Error: panel.models.datetime_picker.DatetimePicker(p1006).value given invalid value:_  exception.

See attached code example and click the _Clear Datetime_ button

#### Complete, minimal, self-contained example code that reproduces the issue

**index.html**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Panel 1.1.0 Layout Tests</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.03.1/pyscript.css" />
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/@holoviz/panel@1.1.0/dist/panel.min.js"
    ></script>
    <script defer src="https://pyscript.net/releases/2023.03.1/pyscript.js"></script>
</head>
<body>
    <py-config src="./pyscript.toml"></py-config>
    <py-script src="./main.py"></py-script>
    <div id="plot"></div>
</body>
</html>
```

**main.py**
```python
import panel as pn
from datetime import datetime

datetime_picker = pn.widgets.DatetimePicker(
    name="Height Change Time (UTC)", width=160, value=datetime(2021, 3, 2, 12, 10)
)
reset_button = pn.widgets.Button(name="Clear Datetime")
def b(event):
    datetime_picker.value = None
reset_button.on_click(b)
pn.Column(datetime_picker, reset_button).servable(target='plot')
```

**pyscript.toml**
```toml
packages = [
    "https://cdn.holoviz.org/panel/1.1.0/dist/wheels/bokeh-3.1.1-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.1.0/dist/wheels/panel-1.1.0-py3-none-any.whl",
]
name = "Panel 1_1_0 Tests"
[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.23.2/full/pyodide.js"
name = "pyodide-0.23.3"
lang = "python"
```

#### Stack traceback and/or browser JavaScript console output

```
pyodide.asm.js:9 Uncaught PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/panel/io/pyodide.py", line 243, in jssync
    pydoc.apply_json_patch(json_patch.to_py(), setter='js')
  File "/lib/python3.11/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/lib/python3.11/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/lib/python3.11/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/lib/python311.zip/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.11/site-packages/bokeh/io/doc.py", line 82, in patch_curdoc
    yield
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 492, in _server_event
    self._comm_event(doc, event)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 479, in _comm_event
    state._handle_exception(e)
  File "/lib/python3.11/site-packages/panel/io/state.py", line 432, in _handle_exception
    raise exception
  File "/lib/python3.11/site-packages/panel/reactive.py", line 477, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/lib/python311.zip/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.11/site-packages/panel/io/state.py", line 69, in set_curdoc
    yield
  File "/lib/python3.11/site-packages/panel/reactive.py", line 414, in _process_bokeh_event
    self._process_event(event)
  File "/lib/python3.11/site-packages/panel/widgets/button.py", line 243, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/lib/python311.zip/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 131, in _batch_call_watchers
    yield
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "<exec>", line 9, in b
  File "/lib/python3.11/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/lib/python311.zip/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 131, in _batch_call_watchers
    yield
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 374, in _param_change
    self._apply_update(named_events, properties, model, ref)
  File "/lib/python311.zip/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.11/site-packages/panel/io/document.py", line 224, in unlocked
    yield
  File "/lib/python3.11/site-packages/panel/reactive.py", line 302, in _apply_update
    self._update_model(events, msg, root, model, doc, comm)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 753, in _update_model
    super()._update_model(events, msg, root, model, doc, comm)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 330, in _update_model
    model.update(**msg)
  File "/lib/python3.11/site-packages/bokeh/core/has_props.py", line 474, in update
    setattr(self, k, v)
  File "/lib/python3.11/site-packages/bokeh/core/has_props.py", line 327, in __setattr__
    return super().__setattr__(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 334, in __set__
    self._set(obj, old, value, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 619, in _set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 697, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/lib/python3.11/site-packages/bokeh/model/model.py", line 562, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 188, in trigger
    self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 249, in notify_change
    self.trigger_on_change(event)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 413, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/lib/python311.zip/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/lib/python3.11/site-packages/bokeh/io/doc.py", line 82, in patch_curdoc
    yield
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 412, in invoke_callbacks
    cb(event)
  File "/lib/python3.11/site-packages/panel/io/pyodide.py", line 254, in pysync
    jsdoc.apply_json_patch(json_patch, buffer_map)
  File "https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js", line 1093, in Document.apply_json_patch
  File "https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js", line 2533, in f.setv
  File "https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js", line 2488, in f._setv
  File "https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js", line 2996, in PrimitiveProperty.set_value
  File "https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js", line 3026, in PrimitiveProperty._update
  File "https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js", line 3045, in PrimitiveProperty.validate
pyodide.ffi.JsException: Error: panel.models.datetime_picker.DatetimePicker(p1006).value given invalid value: undefined

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x152e6c
    at Module._pythonexc2js (pyodide.asm.js:9:654999)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75811)
    at Module.callPyObject (pyodide.asm.js:9:76020)
    at PyProxy.apply (pyodide.asm.js:9:89271)
    at Object.apply (pyodide.asm.js:9:88049)
    at Document._trigger_on_change (bokeh-3.1.1.js:977:21)
    at EventManager.send_event (bokeh-3.1.1.js:721:31)
    at r._process_event (bokeh-3.1.1.js:7088:45)
    at EventManager.trigger (bokeh-3.1.1.js:729:23)
    at r.trigger_event (bokeh-3.1.1.js:7093:45)
    at _.click (bokeh-widgets-3.1.1.min.js:56:117)
    at HTMLButtonElement.<anonymous> (bokeh-widgets-3.1.1.min.js:46:898)
```

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/12672027/47589c1d-e341-495f-af76-773d5623dc53)

**Comment by owenlamont** [comment]
Note if I directly set the DatetimePicker value to None that works fine, this only happens when setting it inside a callback

**Comment by owenlamont** [comment]
I tried the equivalent code in Jupyter lab 4 - which also doesn't work - but it gives quite different errors in the console:

![image](https://github.com/holoviz/panel/assets/12672027/ea621366-dbda-497a-ab7e-2f336b1b968e)

**Comment by Hoxbro** [comment]
Jupyterlab 4 should work after the release of 1.1.1, which should be released today.

I ran the code in jupyterlab 3, and worked as expected. 

It seems like something is changing the `None` to `undefined`. I can recreate the issue on pyscript.

**Comment by owenlamont** [comment]
Checked again with:

- Panel 1.1.1
- PyScript 2023.05.01
- Pyodide 0.23.3

and this is still occurring.

**Comment by philippjfr** [comment]
The issue was that pyodide converts Python `None` values to JS `undefined` values. I've added a workaround in #5191 and filed an issue with pyodide to simplify this in future.

**Comment by owenlamont** [comment]
Thanks @philippjfr ! Really appreciate you working on this so soon.
