### ISSUE TITLE
Resizing a Plotly Box selection throws an exception

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5193]
#### ALL software version info

**PyScript**
Browser: Vivaldi 6.1.3035.111 (Stable channel) (64-bit) 
Panel 1.1.1
Plotly 5.15.0
Pyscript 2023.05.01
Pyodide 0.23.3
Bokeh 3.1.1

**Conda-forge**
OS: Windows 11 Pro 10.0.22621
Panel 1.1.1
Plotly 5.15.0
Bokeh 3.1.1
Jupyterlab 4.0.2

#### Description of expected behavior and the observed behavior

Render a Plotly plot in a plotly pane, select a region with the Box Select tool - then attempted to drag one of the edges of the selection box to resize it.  This throws exception:

ValueError: Invalid property path 'selections[0].x0' for layout

For my use case I want to capture the selected points in the Box using a selected_data watch so I expect the Rectangle to adjust size without error and any newly covered points to be returned in the callback.

I've tested this both in PyScript and Jupyter and received the same exception.

#### Complete, minimal, self-contained example code that reproduces the issue

**PyScript Code**

**index.thml**
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Panel Plotly</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-3.1.1.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.1.1.min.js"
    ></script>
    <script
            type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/@holoviz/panel@1.1.1/dist/panel.min.js"
    ></script>
    <script src='https://cdn.plot.ly/plotly-2.24.1.min.js'></script>
    <link rel="stylesheet" href="https://pyscript.net/releases/2023.05.1/pyscript.css"/>
    <script defer src="https://pyscript.net/releases/2023.05.1/pyscript.js"></script>
</head>
<body>
    <py-config src="./pyscript.toml"></py-config>
    <py-script src="./main.py"></py-script>
    <div id="plot"></div>
</body>
</html>
```

**main.py**
```python
from datetime import UTC
import panel as pn
import plotly.express as px
import pandas as pd

start = pd.Timestamp('2022-05-11 10:00:00', tz=UTC)
date_range = pd.date_range(start=start, periods=10, freq='h')

df = pd.DataFrame({
    "x": date_range,
    "y": list(range(len(date_range)))
})

plotly_figure = px.scatter(df, x="x", y="y", title="Interactive Plot")
plotly_pane = pn.pane.Plotly(plotly_figure)
json_pane = pn.pane.JSON()
pn.Column(plotly_pane, json_pane).servable(target='plot')

def plotly_pane_callback(selected_data):
    json_pane.object = selected_data.new["points"]

plotly_pane_watcher = plotly_pane.param.watch(
    plotly_pane_callback, "selected_data"
)
```

**pyscript.toml**
```toml
packages = [
    "https://cdn.holoviz.org/panel/1.1.1/dist/wheels/bokeh-3.1.1-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.1.1/dist/wheels/panel-1.1.1-py3-none-any.whl", 
    "pandas",
    "plotly==5.15.0"
]
name = "Panel Plotly Pane Test"
[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.23.3/full/pyodide.js"
name = "pyodide-0.23.3"
lang = "python"
```

**Jupyter Code**

```python
from datetime import UTC
import panel as pn
import plotly.express as px
import pandas as pd

pn.extension("plotly")
```

```python
start = pd.Timestamp('2022-05-11 10:00:00', tz=UTC)
date_range = pd.date_range(start=start, periods=10, freq='h')

df = pd.DataFrame({
    "x": date_range,
    "y": list(range(len(date_range)))
})

plotly_figure = px.scatter(df, x="x", y="y", title="Interactive Plot")
plotly_pane = pn.pane.Plotly(plotly_figure)
json_pane = pn.pane.JSON()

pn.Column(plotly_pane, json_pane)
```

```python
def plotly_pane_callback(selected_data):
    json_pane.object = selected_data.new["points"]

plotly_pane_watcher = plotly_pane.param.watch(
    plotly_pane_callback, "selected_data"
)
```

#### Stack traceback and/or browser JavaScript console output

**PyScript Browser Console**

```
ncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.11/site-packages/panel/io/pyodide.py", line 243, in jssync
    pydoc.apply_json_patch(json_patch.to_py(), setter='js')
  File "/lib/python3.11/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/lib/python3.11/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/lib/python3.11/site-packages/bokeh/document/events.py", line 378, in _handle_event
    model.set_from_json(attr, value, setter=event.setter)
  File "/lib/python3.11/site-packages/bokeh/core/has_props.py", line 445, in set_from_json
    descriptor.set_from_json(self, value, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 428, in set_from_json
    self._set(obj, old, value, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 619, in _set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 697, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/lib/python3.11/site-packages/bokeh/model/model.py", line 562, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 188, in trigger
    self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 249, in notify_change
    self.trigger_on_change(event)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 408, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 185, in invoke
    callback(attr, old, new)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 519, in _server_change
    state._handle_exception(e)
  File "/lib/python3.11/site-packages/panel/io/state.py", line 436, in _handle_exception
    raise exception
  File "/lib/python3.11/site-packages/panel/reactive.py", line 517, in _server_change
    self._change_event(doc)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 445, in _change_event
    self._process_events(events)
  File "/lib/python3.11/site-packages/panel/reactive.py", line 384, in _process_events
    self.param.update(**self_events)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 669, in caller
    return function()
           ^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 407, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/pane/plotly.py", line 188, in _update_figure_layout
    self._figure.plotly_relayout(relayout_data)
  File "/lib/python3.11/site-packages/plotly/basedatatypes.py", line 2612, in plotly_relayout
    relayout_changes = self._perform_plotly_relayout(relayout_data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/plotly/basedatatypes.py", line 2648, in _perform_plotly_relayout
    raise ValueError(
ValueError: 
Invalid property path 'selections[0].x0' for layout


    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x152e6c
    at Module._pythonexc2js (pyodide.asm.js:9:654797)
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75609)
    at Module.callPyObject (pyodide.asm.js:9:75818)
    at PyProxy.apply (pyodide.asm.js:9:89069)
    at Object.apply (pyodide.asm.js:9:87847)
    at Document._trigger_on_change (bokeh-3.1.1.js:977:21)
    at w._push_changes (bokeh-3.1.1.js:2649:26)
    at w.setv (bokeh-3.1.1.js:2548:26)
    at w.set [as relayout_data] (bokeh-3.1.1.js:2254:30)
    at a.<anonymous> (panel.min.js:131:3452)
    at a.emit (plotly-2.24.1.min.js:8:2410259)
    at t.emit (plotly-2.24.1.min.js:8:331739)
    at plotly-2.24.1.min.js:8:408880
```

**Jupyter**

```
Traceback (most recent call last):
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\pyviz_comms\__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\viewable.py", line 471, in _on_msg
    doc.unhold()
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\bokeh\document\document.py", line 758, in unhold
    self.callbacks.unhold()
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\bokeh\document\callbacks.py", line 431, in unhold
    self.trigger_on_change(event)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\bokeh\document\callbacks.py", line 408, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\bokeh\document\callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\bokeh\util\callback_manager.py", line 185, in invoke
    callback(attr, old, new)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\reactive.py", line 469, in _comm_change
    state._handle_exception(e)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\io\state.py", line 436, in _handle_exception
    raise exception
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\reactive.py", line 467, in _comm_change
    self._schedule_change(doc, comm)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\reactive.py", line 449, in _schedule_change
    self._change_event(doc)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\reactive.py", line 445, in _change_event
    self._process_events(events)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\reactive.py", line 384, in _process_events
    self.param.update(**self_events)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\param\parameterized.py", line 1902, in update
    self_._batch_call_watchers()
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\param\parameterized.py", line 2063, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\param\parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\param\parameterized.py", line 669, in caller
    return function()
           ^^^^^^^^^^
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\param\parameterized.py", line 407, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\panel\pane\plotly.py", line 188, in _update_figure_layout
    self._figure.plotly_relayout(relayout_data)
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\plotly\basedatatypes.py", line 2612, in plotly_relayout
    relayout_changes = self._perform_plotly_relayout(relayout_data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owen\miniconda3\envs\jupyter_lab\Lib\site-packages\plotly\basedatatypes.py", line 2648, in _perform_plotly_relayout
    raise ValueError(
ValueError: 
Invalid property path 'selections[0].x0' for layout
```

#### Screenshots or screencasts of the bug in action

**PyScript**

![image](https://github.com/holoviz/panel/assets/12672027/0bf0a801-b8e0-48ec-9962-0ad38ac93373)
![image](https://github.com/holoviz/panel/assets/12672027/084040f3-cf32-4322-9fbb-2dda0542d25a)

**Jupyter**

![image](https://github.com/holoviz/panel/assets/12672027/75f213ff-f4eb-477b-b00e-6a47f96e2be8)

**Comment by owenlamont** [comment]
I also noticed in my Jupyter example the plotly pane selected_data callback function definitely got hit (I added a print inside of it) - but it wouldn't update the json pane contents of the selected points on the Plotly plot whereas in the PyScript example the json pane updated with the selected points no problem when first dragging the initial box select (before attempting to resize it).

Not sure if that is a second issue I should raise or whether it is just a mistake in my Jupyter example code... although it is almost character for character identical with the PyScript example.

**Comment by owenlamont** [comment]
In case anyone is wondering this exception gets thrown even when not attaching a watcher and callback to the plotly plane - I just included that to illustrate my use case better.
