### ISSUE TITLE
Failure to deploy pyodide worker. ModuleNotFoundError.

### ISSUE THREAD

**Issue by LinuxIsCool** [holoviz/panel#5222]
The code is here: https://github.com/bonding-curves/conding/blob/main/nbs/sandbox/TEC.ipynb 

#### ALL software version info
bokeh==2.4.3
panel==0.14.4
Python 3.10.6
Firfox, PopOS Linux

#### Description of expected behavior and the observed behavior
App is deployed at TEC.html

#### Complete, minimal, self-contained example code that reproduces the issue

```
panel convert nbs/sandbox/TEC.ipynb --to pyodide-worker --out docs/app --requirements conding
python3 -m http.server --directory docs/app/

```

#### Stack traceback and/or browser JavaScript console output
```
PythonError: Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/_pyodide/_base.py", line 532, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/_pyodide/_base.py", line 357, in run_async
    await coroutine
  File "<exec>", line 27, in <module>
ModuleNotFoundError: No module named 'conding'
```

#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/panel/assets/31582215/6362ddb3-66a1-4ec9-b41c-bd3a799f5087)

**Comment by LinuxIsCool** [comment]
I updated my libraries, but still having the same issue. 

```
bokeh==3.1.1
panel==1.0.4
```

As the app is loading it says "Installing conding". But still has the ModuleNotFoundError.

**Comment by MarcSkovMadsen** [comment]
Is Vinding some file/ module you have created @LinuxIsCool ?

**Comment by LinuxIsCool** [comment]
Hi @MarcSkovMadsen i'm not sure what Vinding is. Do you mean conding? It's a library I created. Published here: https://pypi.org/project/conding/0.1.3/

**Comment by LinuxIsCool** [comment]
Successfully deployed here by removing the import and putting the code directly in the app. 

https://bonding-curves.github.io/conding/app/02_abc.html

**Comment by MarcSkovMadsen** [comment]
Yes. My autospell changed conding.

To use your own modulets with panel convert they need to be hosted somewhere or available as a Python package.

**Comment by LinuxIsCool** [comment]
conding is available on pypi as I linked to above. Will this work?

**Comment by philippjfr** [comment]
That should work yes, as long as it's available on PyPI.

**Comment by LinuxIsCool** [comment]
Hi, the issue was not solved. I could not get it working. Now I'm working on another app and am unable to use the openai package. 

![image](https://github.com/holoviz/panel/assets/31582215/224ff087-9d98-4ef5-9352-481742aa97d0)


Converter with:

```
panel convert Notebooks/InterviewData/11-dashboard.ipynb --to pyodide-worker --out docs/app --requirements openai
```

**Comment by LinuxIsCool** [comment]
Can anyone provide tips on how to go about debugging this? I am presenting this work at a conference next week and would love to have a live deployment.

**Comment by ahuang11** [comment]
Do you need to demo it using pyodide? If not, you can either host it on Anaconda Notebook or HuggingFace.

**Comment by Hoxbro** [comment]
Do you have the packages installed in the environment you are using for `panel convert`?

**Comment by philippjfr** [comment]
Here's the likely issue in your case:

<img width="1122" alt="Screen Shot 2023-07-14 at 11 04 17" src="https://github.com/holoviz/panel/assets/1550771/bc39c0dc-2e65-4410-a432-9efc01369a64">

Might be good to guide people to test whether their dependencies can be installed from Pyodide on the REPL: https://pyodide.org/en/stable/console.html

**Comment by ahuang11** [comment]
This issue can be tracked here:
https://github.com/pyodide/pyodide/issues/3588

**Comment by firobeid** [comment]
![image](https://github.com/holoviz/panel/assets/44253341/0d5a110b-67cc-4e04-baa6-b7b406c49d6e)
My deployed apps where running perfectly until I just realized that they are not
