### ISSUE TITLE
FastGridTemplate with Debugger raises AttributeError: 'NoneType' object has no attribute 'document'

### ISSUE THREAD

**Issue by bsdz** [holoviz/panel#5235]
#### ALL software version info

```bash
$ panel --version
1.2.0
$ python -V
Python 3.10.6
$ python -mplatform
Linux-5.15.0-73-generic-x86_64-with-glibc2.35
$ uname -a
Linux mlrig 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ /opt/google/chrome/chrome --version
Google Chrome 114.0.5735.198 unknown
```

#### Description of expected behavior and the observed behavior

When using FastGridTemplate with the Debugger widget, a call to the logger raises  an AttributeError. This should behave like FastListTemplate and log the message to the debugger widget without the AttributeError.

#### Complete, minimal, self-contained example code that reproduces the issue

By changing `use_fast_grid`  in the code below to True and pressing the "write log" button then the exception will occur. Keeping `use_fast_grid` to False shows the button/debugger working as expected.

```
import logging
logger = logging.getLogger("foo")
logging.root.setLevel(logging.INFO)

import panel as pn
pn.extension('terminal')

debug = pn.widgets.Debugger(
    name='Logging',
    level=logging.INFO,
    logger_names=["foo"],
)

def do_logging(event):
    logger.info("foo")
    
button = pn.widgets.Button(name="write log", button_type="default")
button.on_click(do_logging)

use_fast_grid = False
if use_fast_grid:
    template = pn.template.FastGridTemplate(
        title="title",
        sidebar_width=200,
    )
    template.main[:1,:1] = button
    template.main[1:5, :6] = debug
else:
    template = pn.template.FastListTemplate(
        title="title",
        sidebar_width=200,
    )
    template.main.append(pn.Column(button, debug))

template.show()

```

#### Stack traceback and/or browser JavaScript console output

```
$ panel serve ~/some/path/to/Untitled.ipynb 
2023-07-08 23:39:57,091 Starting Bokeh server version 3.1.1 (running on Tornado 6.3.2)
2023-07-08 23:39:57,092 User authentication hooks NOT provided (default user enabled)
2023-07-08 23:39:57,095 Bokeh app running at: http://localhost:5006/Untitled
2023-07-08 23:39:57,095 Starting Bokeh server with process id: 4066022
2023-07-08 23:40:01,702 Starting Bokeh server version 3.1.1 (running on Tornado 6.3.2)
2023-07-08 23:40:01,703 User authentication hooks NOT provided (default user enabled)
Launching server at http://localhost:32991
2023-07-08 23:40:01,720 200 GET /Untitled (::1) 126.24ms
2023-07-08 23:40:02,113 101 GET /Untitled/ws (::1) 1.33ms
2023-07-08 23:40:02,113 WebSocket connection opened
2023-07-08 23:40:02,115 ServerConnection created
2023-07-08 23:40:02,275 200 GET / (::1) 160.85ms
2023-07-08 23:40:02,317 200 GET /static/extensions/panel/bundled/react@17/umd/react.production.min.js (::1) 1.22ms
2023-07-08 23:40:02,322 200 GET /static/extensions/panel/bundled/react-dom@17/umd/react-dom.production.min.js (::1) 3.40ms
2023-07-08 23:40:02,326 200 GET /static/extensions/panel/bundled/babel-standalone@latest/babel.min.js (::1) 6.11ms
2023-07-08 23:40:02,326 200 GET /static/extensions/panel/bundled/react-grid-layout@1.3.4/dist/react-grid-layout.min.js (::1) 6.61ms
2023-07-08 23:40:02,327 200 GET /static/extensions/panel/bundled/fastbasetemplate/fast_template.js (::1) 7.08ms
2023-07-08 23:40:02,331 200 GET /static/extensions/panel/bundled/@microsoft/fast-components@2.30.6/dist/fast-components.js (::1) 10.86ms
2023-07-08 23:40:02,334 200 GET /static/extensions/panel/bundled/theme/default.css (::1) 1.17ms
2023-07-08 23:40:02,334 200 GET /static/extensions/panel/bundled/terminal/xterm@4.11.0/css/xterm.css (::1) 0.68ms
2023-07-08 23:40:02,336 200 GET /static/extensions/panel/bundled/fastbasetemplate/fast.css (::1) 0.58ms
2023-07-08 23:40:02,340 200 GET /static/extensions/panel/bundled/fastgridtemplate/fast_grid_template.css (::1) 0.95ms
2023-07-08 23:40:02,342 200 GET /static/extensions/panel/bundled/fast/js/fast_design.js (::1) 0.72ms
2023-07-08 23:40:02,344 200 GET /static/extensions/panel/bundled/terminal/xterm@4.14.1/lib/xterm.js (::1) 1.78ms
2023-07-08 23:40:02,344 200 GET /static/extensions/panel/bundled/terminal/xterm-addon-web-links@0.4.0/lib/xterm-addon-web-links.js (::1) 2.09ms
2023-07-08 23:40:02,347 200 GET /static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465 (::1) 1.57ms
2023-07-08 23:40:02,349 200 GET /static/js/bokeh-gl.min.js?v=9cc8ec1abc75f3359ae423cc92f1ecf9bfd2904423483737fe69e904335557ed44a5fa594abe1191df1b1d2d00ff5d6aad56d745a9f263ad64abd5e8c176ffd5 (::1) 1.00ms
2023-07-08 23:40:02,350 200 GET /static/js/bokeh-widgets.min.js?v=2c2c4d41bc34e1cebbb6bcbfc6b44cbb5a542c5e354ec67226a8de57389f41d7067d1863bb0bc8f0bdd1b01fb0bc85c48145a15efb16dec77077e09f2e626449 (::1) 0.79ms
2023-07-08 23:40:02,354 200 GET /static/js/bokeh-tables.min.js?v=d83e9590cfc01b6d99aece15dc11779953d8cfce1b6707f211ecf53c1c9f5e2219f56e0c8ba71495e189e34bc02e3734cb42dfecc7a37b24ad7e2bc297036702 (::1) 1.04ms
2023-07-08 23:40:02,356 200 GET /static/extensions/panel/panel.min.js?v=9f77034b1eb57d24f21ac7deb65c9cc99f63b72775e311f1f280ab2b6c2e06a2 (::1) 1.80ms
2023-07-08 23:40:02,863 101 GET /ws (::1) 0.67ms
2023-07-08 23:40:02,863 WebSocket connection opened
2023-07-08 23:40:02,863 ServerConnection created
2023-07-08 23:40:02,908 200 GET /static/extensions/panel/images/favicon.ico (::1) 1.68ms
2023-07-08 23:40:02,967 200 GET /static/extensions/panel/css/loading.css (::1) 1.18ms
2023-07-08 23:40:02,968 200 GET /static/extensions/panel/bundled/theme/fast.css (::1) 1.36ms
2023-07-08 23:40:02,977 200 GET /static/extensions/panel/css/loadingspinner.css (::1) 1.38ms
2023-07-08 23:40:02,980 200 GET /static/extensions/panel/css/button.css (::1) 1.06ms
2023-07-08 23:40:03,028 200 GET /static/extensions/panel/css/debugger.css (::1) 0.98ms
2023-07-08 23:40:03,029 200 GET /static/extensions/panel/css/listpanel.css (::1) 1.16ms
2023-07-08 23:40:04,896 200 GET /static/extensions/panel/css/markdown.css (::1) 0.99ms
2023-07-08 23:40:06,112 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1021'}]]}}}]} 
 error: AttributeError("'NoneType' object has no attribute 'document'")
Traceback (most recent call last):
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "~/panel/.venv/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "~/panel/.venv/lib/python3.10/site-packages/panel/reactive.py", line 492, in _server_event
    self._comm_event(doc, event)
  File "~/panel/.venv/lib/python3.10/site-packages/panel/reactive.py", line 479, in _comm_event
    state._handle_exception(e)
  File "~/panel/.venv/lib/python3.10/site-packages/panel/io/state.py", line 436, in _handle_exception
    raise exception
  File "~/panel/.venv/lib/python3.10/site-packages/panel/reactive.py", line 477, in _comm_event
    self._process_bokeh_event(doc, event)
  File "~/panel/.venv/lib/python3.10/site-packages/panel/reactive.py", line 414, in _process_bokeh_event
    self._process_event(event)
  File "~/panel/.venv/lib/python3.10/site-packages/panel/widgets/button.py", line 243, in _process_event
    self.clicks += 1
  File "~/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "~/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "~/panel/.venv/lib/python3.10/site-packages/param/__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "~/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "~/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "~/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "~/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "~/some/path/to/Untitled.ipynb ", line 21, in do_logging
    "(function(root) {\n",
  File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 964, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 821, in filter
    result = f.filter(record)
  File "~/panel/.venv/lib/python3.10/site-packages/panel/widgets/debugger.py", line 99, in filter
    widget_session_ids = set(m.document.session_context.id
  File "~/panel/.venv/lib/python3.10/site-packages/panel/widgets/debugger.py", line 101, in <genexpr>
    tuple()) if m.document.session_context)
AttributeError: 'NoneType' object has no attribute 'document'
```

**Comment by bsdz** [comment]
I've found a workaround and that's to wrap my Debugger widget in a Row or Column; this appears to resolve the issue, i.e. replace

```
    template.main[1:5, :6] = debug
```

with

```
    template.main[1:5, :6] = pn.Row(debug)
```

**Comment by j-carson** [comment]
I just hit this -- but trying to put the debugger in the MaterialTemplate sidebar
It sure would be nice if the Debugger documentation specified that it needs to be wrapped in a Row somewhere until this bug gets fixed because the error message is very cryptic

**Comment by philippjfr** [comment]
Appears to be fixed on main.
