### ISSUE TITLE
reactive_html.DOMEvent not serializable

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5267]
I'm on the current Panel `main` branch trying to help [rsdenijs](https://discourse.holoviz.org/u/rsdenijs) in https://discourse.holoviz.org/t/bootstrap-styling-on-panel-reactivehtml/5705 create ReactiveHTML components using Bootstrap.

During the exploration I get the exception `bokeh.core.serialization.SerializationError: can't serialize <class 'panel.models.reactive_html.DOMEvent'>`.

## Reproduce

```python
import panel as pn
import param
from panel.reactive import ReactiveHTML

class CustomComponent(ReactiveHTML):
    event = param.Parameter()

    _template = """
<div id="container">
<button id="button" onclick="${click_handler}" type="button" class="btn btn-primary" >Primary</button>

<button id="popover_button" onclick="${click_handler}" type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>
</div>
"""
    __css__=["https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"]
    __javascript__=["https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"]

    _scripts = {
        "render": """
new bootstrap.Popover(popover_button)
"""
    }
    
    def click_handler(self, event):
        self.event = event

pn.extension(sizing_mode="stretch_width")
component = CustomComponent(height=100)
pn.Column(component, pn.panel(component.param.event, height=100)).servable()
```

When you click a button you see the issue

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/server/session.py", line 288, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/opt/conda/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/document.py", line 376, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 246, in handle_event
    event_cls._handle_event(doc, event)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 281, in _handle_event
    cb(event.msg_data)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/opt/conda/lib/python3.10/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 492, in _server_event
    self._comm_event(doc, event)
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 479, in _comm_event
    state._handle_exception(e)
  File "/opt/conda/lib/python3.10/site-packages/panel/io/state.py", line 436, in _handle_exception
    raise exception
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 477, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 414, in _process_bokeh_event
    self._process_event(event)
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 2031, in _process_event
    cb(event)
  File "/home/jovyan/repos/private/panel/script.py", line 25, in click_handler
    self.event = event
  File "/opt/conda/lib/python3.10/site-packages/param/parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "/opt/conda/lib/python3.10/site-packages/param/parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "/opt/conda/lib/python3.10/site-packages/param/parameterized.py", line 1252, in __set__
    obj.param._call_watcher(watcher, event)
  File "/opt/conda/lib/python3.10/site-packages/param/parameterized.py", line 2043, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/opt/conda/lib/python3.10/site-packages/param/parameterized.py", line 2025, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 374, in _param_change
    self._apply_update(named_events, properties, model, ref)
  File "/opt/conda/lib/python3.10/site-packages/panel/reactive.py", line 301, in _apply_update
    with unlocked():
  File "/opt/conda/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.10/site-packages/panel/io/document.py", line 293, in unlocked
    curdoc.unhold()
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/document.py", line 758, in unhold
    self.callbacks.unhold()
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 431, in unhold
    self.trigger_on_change(event)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 413, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 412, in invoke_callbacks
    cb(event)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/callbacks.py", line 276, in <lambda>
    self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 354, in dispatch
    super().dispatch(receiver)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 220, in dispatch
    cast(DocumentPatchedMixin, receiver)._document_patched(self)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/server/session.py", line 254, in _document_patched
    self._pending_writes.append(connection.send_patch_document(event))
  File "/opt/conda/lib/python3.10/site-packages/bokeh/server/connection.py", line 88, in send_patch_document
    msg = self.protocol.create('PATCH-DOC', [event])
  File "/opt/conda/lib/python3.10/site-packages/bokeh/protocol/__init__.py", line 131, in create
    return self._messages[msgtype].create(*args, **kwargs)  # type: ignore [attr-defined]
  File "/opt/conda/lib/python3.10/site-packages/bokeh/protocol/messages/patch_doc.py", line 90, in create
    patch_json = PatchJson(events=serializer.encode(events))
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 252, in encode
    return self._encode(obj)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 277, in _encode
    return self._encode_list(obj)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 323, in _encode_list
    return [self.encode(item) for item in obj]
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 323, in <listcomp>
    return [self.encode(item) for item in obj]
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 252, in encode
    return self._encode(obj)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 261, in _encode
    return obj.to_serializable(self)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/document/events.py", line 370, in to_serializable
    new   = serializer.encode(self.new),
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 252, in encode
    return self._encode(obj)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 296, in _encode
    return self._encode_other(obj)
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 466, in _encode_other
    self.error(f"can't serialize {type(obj)}")
  File "/opt/conda/lib/python3.10/site-packages/bokeh/core/serialization.py", line 469, in error
    raise SerializationError(message)
bokeh.core.serialization.SerializationError: can't serialize <class 'panel.models.reactive_html.DOMEvent'>
```

## Discussion

I think its natural to want to save the `event` in a Parameter.

## Workaround

Use `self.event=event.__dict__` instead of `self.event=event`.

**Comment by philippjfr** [comment]
Appears to serialize correctly now.
