### ISSUE TITLE
'labels' is not a parameter of

### ISSUE THREAD

**Issue by ahuang11** [holoviz/panel#531]
Don't know what causes this when doing a `panel serve` but I think philippjfr knows

```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2b4b6e044598>, <Future finished exception=ValueError("'labels' is not a parameter of ")>)
Traceback (most recent call last):
  File "/users/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/users/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/users/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
    future.result()
  File "/users/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/users/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/users/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/users/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/users/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/users/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/users/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/users/anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/users/anaconda3/lib/python3.7/site-packages/param/parameterized.py", line 1219, in inner
    return fn(*args, **kwargs)
  File "/users/anaconda3/lib/python3.7/site-packages/param/parameterized.py", line 2572, in set_param
    return self_or_cls.param.set_param(*args,**kwargs)
  File "/users/anaconda3/lib/python3.7/site-packages/param/parameterized.py", line 1356, in set_param
    raise ValueError("'%s' is not a parameter of %s" % (k, self_or_cls.name))
ValueError: 'labels' is not a parameter of
```

**Comment by philippjfr** [comment]
Seems like this was fixed along the way.
