### ISSUE TITLE
Can't seem to get pyodide example to run

### ISSUE THREAD

**Issue by brentgunderson** [holoviz/panel#5371]
Attempted this https://panel.holoviz.org/how_to/wasm/convert.html#example, on Mac OS, panel version 1.2.1

I saw this issue: https://github.com/holoviz/panel/issues/4907

I seem to become stuck with a 'Module not found' error for panel itself.

<img width="1159" alt="image" src="https://github.com/holoviz/panel/assets/42783590/565d3915-1d7e-4d87-9e08-0fe259ac8fdd">

**Comment by ahuang11** [comment]
It may need the requirements flag
`panel convert script.py --to pyodide-worker --out pyodide --requirements panel xgboost scikit-learn`

**Comment by brentgunderson** [comment]
Thanks @ahuang11.  Interestingly, when I tried including the requirements flag, I seem to encounter exact same issue.

**Comment by philippjfr** [comment]
This should now be resolved. If it reoccurs please report it.

**Comment by brentgunderson** [comment]
I just tried with panel 1.3.6 and seem to encounter exact same error.

This from the web browser console

```
[Log] PythonError: Traceback (most recent call last): (script.js, line 33)
  File "micropip/_micropip.py", line 160, in _fetch_bytes
  File "micropip/_compat_in_pyodide.py", line 29, in fetch_bytes
  File "pyodide/http.py", line 201, in bytes
  File "pyodide/http.py", line 125, in _raise_if_failed
OSError: Request for https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.1.1-py3-none-any.whl failed with status 403: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_pyodide/_base.py", line 540, in eval_code_async
  File "_pyodide/_base.py", line 365, in run_async
  File "<exec>", line 3, in <module>
  File "micropip/_micropip.py", line 576, in install
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 355, in add_requirement
  File "micropip/_micropip.py", line 470, in add_wheel
  File "micropip/_micropip.py", line 176, in download
  File "micropip/_micropip.py", line 168, in _fetch_bytes
ValueError: Can't fetch wheel from 'https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.1.1-py3-none-any.whl'. One common reason for this is when the server blocks Cross-Origin Resource Sharing (CORS). Check if the server is sending the correct 'Access-Control-Allow-Origin' header.

[Log] PythonError: Traceback (most recent call last): (script.js, line 33)
  File "_pyodide/_base.py", line 540, in eval_code_async
  File "_pyodide/_base.py", line 365, in run_async
  File "<exec>", line 3, in <module>
  File "micropip/_micropip.py", line 576, in install
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 355, in add_requirement
  File "micropip/_micropip.py", line 472, in add_wheel
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 346, in add_requirement
  File "micropip/_micropip.py", line 457, in add_requirement_inner
  File "micropip/_micropip.py", line 472, in add_wheel
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 346, in add_requirement
  File "micropip/_micropip.py", line 444, in add_requirement_inner
  File "micropip/_micropip.py", line 312, in find_wheel
ValueError: Can't find a pure Python 3 wheel for 'contourpy>=1'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.

[Log] PythonError: Traceback (most recent call last): (script.js, line 33)
  File "_pyodide/_base.py", line 540, in eval_code_async
  File "_pyodide/_base.py", line 365, in run_async
  File "<exec>", line 3, in <module>
  File "micropip/_micropip.py", line 576, in install
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 349, in add_requirement
  File "micropip/_micropip.py", line 457, in add_requirement_inner
  File "micropip/_micropip.py", line 472, in add_wheel
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 346, in add_requirement
  File "micropip/_micropip.py", line 457, in add_requirement_inner
  File "micropip/_micropip.py", line 472, in add_wheel
  File "micropip/_micropip.py", line 342, in gather_requirements
  File "micropip/_micropip.py", line 346, in add_requirement
  File "micropip/_micropip.py", line 444, in add_requirement_inner
  File "micropip/_micropip.py", line 312, in find_wheel
ValueError: Can't find a pure Python 3 wheel for 'contourpy>=1'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
You can use `micropip.install(..., keep_going=True)`to get a list of all packages with missing wheels.
```
