### ISSUE TITLE
pn.Param raises TypeError: unbound method type.__subclasses__() needs an argument

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5389]
I'm on the latest `main` branch working on the chat components. I would like to use `pn.Param` on a `ChatEntry`. But it fails.

## Minimum Reproducible Example

```python
import panel as pn
import param

class ChatEntry(param.Parameterized):
    value = param.ClassSelector(class_=object)

entry=ChatEntry()
pn.Param(entry)
```

```bash
$ python script.py
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/script.py", line 8, in <module>
    pn.Param(entry)
  File "/home/jovyan/repos/private/panel/panel/param.py", line 254, in __init__
    self._update_widgets()
  File "/home/jovyan/repos/private/panel/panel/param.py", line 325, in _update_widgets
    self._widgets = self._get_widgets()
  File "/home/jovyan/repos/private/panel/panel/param.py", line 688, in _get_widgets
    widgets += [(pname, self.widget(pname)) for pname in self._ordered_params]
  File "/home/jovyan/repos/private/panel/panel/param.py", line 688, in <listcomp>
    widgets += [(pname, self.widget(pname)) for pname in self._ordered_params]
  File "/home/jovyan/repos/private/panel/panel/param.py", line 436, in widget
    options = p_obj.get_range()
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.10/site-packages/param/__init__.py", line 1405, in get_range
    all_classes.update(concrete_descendents(cls))
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.10/site-packages/param/__init__.py", line 1136, in concrete_descendents
    return dict((c.__name__,c) for c in descendents(parentclass)
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.10/site-packages/param/parameterized.py", line 224, in descendents
    for b in x.__subclasses__():
```

## Additional Context

Maybe the `class_` on the `ChatEntry` should be set to something more specific? But I think `pn.Param` should be able to handle this or provide a more meaningful exception.

**Comment by MarcSkovMadsen** [comment]
I can see in `test_chat` contains examples where the value is `1` or the `_FileInputMessage` data class.

So its not straightforward for me to change `class_` to something else than `object`.

I will change the parameter type to `Parameter` instead.

**Comment by philippjfr** [comment]
I'd be okay with re-opening this as a Param issue but tbh, if you're just going to set `class_=object`. Just use a `param.Parameter`.
