### ISSUE TITLE
*pyscript* converted html file cannot fetch required packages (bokeh, panel etc.)  

### ISSUE THREAD

**Issue by AnselmJeong** [holoviz/panel#5449]
I am testing the convert function of the panel app to pyscript. While the conversion process itself is going smoothly, the resulting html file does not operate as expected. 

#### ALL software version info
python = "^3.11"
numpy = "^1.25.2"
pandas = "^2.0.3"
matplotlib = "^3.7.2"
bokeh = "^3.2.2"
ipykernel = "^6.25.1"
jupyter-bokeh = "^3.0.7"
panel = "^1.2.1"
hvplot = "^0.8.4"
jupyterlab = "^4.0.5"

#### Description of expected behavior and the observed behavior
Expected behavior: When serving the converted html file using `python -m http.server`, Accessing `http://localhost:8000/test.html` should display "Hello World!" on the screen.

Observed behavior: Actually, `Hello World!` appears on the screen. But the screen is unresponsive with a giant spinner. The error message tells that the required package whl cannot be accessed. (access denied with error code 403)

The reason why pyscript can't load the necessary package whl could be due to CORS restriction, or it might be because there's no available version of the required whl. However, if it doesn't work even in such a simple example, further app development could not be expected.

#### Complete, minimal, self-contained example code that reproduces the issue
```
import panel as pn

pn.extension()

pn.panel(
    "Hello World!"
).servable()
```

#### Stack traceback and/or browser JavaScript console output
* Javascript console output

```
OSError: Request for https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.2.2-py3-none-any.whl failed with status 403: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 365, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 576, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 342, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 355, in add_requirement
    await self.add_wheel(wheel, extras=set())
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 470, in add_wheel
    await wheel.download(self.fetch_kwargs)
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 176, in download
    data = await self._fetch_bytes(fetch_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/_micropip.py", line 168, in _fetch_bytes
    raise ValueError(
ValueError: Can't fetch wheel from 'https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.2.2-py3-none-any.whl'. One common reason for this is when the server blocks Cross-Origin Resource Sharing (CORS). Check if the server is sending the correct 'Access-Control-Allow-Origin' header.
```

#### Screenshots or screencasts of the bug in action

<img width="1141" alt="image" src="https://github.com/holoviz/panel/assets/1776524/4a10b2f9-3c70-45f3-855c-43b9a02e956c">

**Comment by amarouane-ABDELHAK** [comment]
Same problem here, and this requested link https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.2.2-py3-none-any.whl gives 403 error

**Comment by Hoxbro** [comment]
This is because Bokeh 3.2.2 was not released when Panel 1.2.1 was built. 

This should work: https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.2.1-py3-none-any.whl

**Comment by AnselmJeong** [comment]
I downgraded bokeh to 3.2.1 and tested again. This time the status 403 error is gone. But other errors prevent the normal functioning.

the javascript console spits out the following error message.

```
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 365, in run_async
    await coroutine
  File "<exec>", line 72, in <module>
  File "/lib/python3.11/site-packages/panel/io/pyodide.py", line 519, in write_doc
    views = await Bokeh.embed.embed_items(JSON.parse(docs_json), JSON.parse(render_items))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodide.ffi.JsException: Error: panel.models.browser.BrowserInfo(8b983322-dc4a-42a3-b548-532e4476df10).timezone given invalid value: undefined

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x159d1c
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:128013)
    at pyodide.asm.wasm:0x19f6c6
    at pyodide.asm.wasm:0x28650b
    at pyodide.asm.wasm:0x1e0617
    at pyodide.asm.wasm:0x19fbad
    at pyodide.asm.wasm:0x19fe6e
    at pyodide.asm.wasm:0x19ff10
    at pyodide.asm.wasm:0x264a10
    at pyodide.asm.wasm:0x26a9f5
    at pyodide.asm.wasm:0x1a0038
    at pyodide.asm.wasm:0x19fcc8
    at pyodide.asm.wasm:0x159532
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75497)
    at Module.callPyObject (pyodide.asm.js:9:75942)
    at wrapper (pyodide.asm.js:9:57697)
```
But strangely, the app works well without error when launched on the Safari browser.
