### ISSUE TITLE
pn.state.notifications is None in threading

### ISSUE THREAD

**Issue by monodera** [holoviz/panel#5488]
I have a similar issue on the Notification component to #5090 when using the component with `threading` package. I'm not sure if it's the same origin, so I'm filing the issue as a separate one.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

- Panel 1.2.2
- Bokeh 3.1.1
- Python 3.11.1
- macOS 13.5.1
- Firefox 117.0

##### Expected behavior
Notification shows up.

##### Observed behavior
Notification does not show up with an error `AttributeError: 'NoneType' object has no attribute 'warning'`.

##### Code (app.py)

```
import threading

import panel as pn

pn.extension(notifications=True)

# Create a button
button = pn.widgets.Button(name="Click me", button_type="primary")

# setup threading
cb_exec = threading.Condition()

queue_exec = []


def callback_exec():
    while True:
        cb_exec.acquire()
        for _ in queue_exec:
            pn.state.notifications.warning("Warning!")
        queue_exec.clear()
        cb_exec.release()


thread_exec = threading.Thread(target=callback_exec, daemon=True)
thread_exec.start()


def on_click_exec(event):
    queue_exec.append(event)


# Define an action on click
button.on_click(on_click_exec)

# Create a Panel to show the button
panel = pn.Row(button)

# Serve the Panel
panel.servable()

```

##### Usage
```
panel serve ./app.py --log-level=trace
```

Then, open `http://localhost:5006/app` and click the button.

#### Stack traceback and/or browser JavaScript console output

```
2023-09-07 17:31:02,447 Starting Bokeh server version 3.1.1 (running on Tornado 6.2)
2023-09-07 17:31:02,448 User authentication hooks NOT provided (default user enabled)
2023-09-07 17:31:02,448 These host origins can connect to the websocket: ['localhost:5006']
2023-09-07 17:31:02,448 Patterns are:
2023-09-07 17:31:02,448   [('/favicon.ico',
2023-09-07 17:31:02,448     <class 'bokeh.server.views.ico_handler.IcoHandler'>,
2023-09-07 17:31:02,448     {'app': <bokeh.server.tornado.BokehTornado object at 0x123397390>}),
2023-09-07 17:31:02,448    ('/app/?',
2023-09-07 17:31:02,448     <class 'panel.io.server.DocHandler'>,
2023-09-07 17:31:02,448     {'application_context': <bokeh.server.contexts.ApplicationContext object at 0x12340a710>,
2023-09-07 17:31:02,448      'bokeh_websocket_path': '/app/ws'}),
2023-09-07 17:31:02,448    ('/app/ws',
2023-09-07 17:31:02,448     <class 'bokeh.server.views.ws.WSHandler'>,
2023-09-07 17:31:02,448     {'application_context': <bokeh.server.contexts.ApplicationContext object at 0x12340a710>,
2023-09-07 17:31:02,449      'bokeh_websocket_path': '/app/ws',
2023-09-07 17:31:02,449      'compression_level': None,
2023-09-07 17:31:02,449      'mem_level': None}),
2023-09-07 17:31:02,449    ('/app/metadata',
2023-09-07 17:31:02,449     <class 'bokeh.server.views.metadata_handler.MetadataHandler'>,
2023-09-07 17:31:02,449     {'application_context': <bokeh.server.contexts.ApplicationContext object at 0x12340a710>,
2023-09-07 17:31:02,449      'bokeh_websocket_path': '/app/ws'}),
2023-09-07 17:31:02,449    ('/app/autoload.js',
2023-09-07 17:31:02,449     <class 'panel.io.server.AutoloadJsHandler'>,
2023-09-07 17:31:02,449     {'application_context': <bokeh.server.contexts.ApplicationContext object at 0x12340a710>,
2023-09-07 17:31:02,449      'bokeh_websocket_path': '/app/ws'}),
2023-09-07 17:31:02,449    ('/app/static/(.*)',
2023-09-07 17:31:02,449     <class 'bokeh.server.views.static_handler.StaticHandler'>,
2023-09-07 17:31:02,449     {}),
2023-09-07 17:31:02,449    ('/components/(.*)',
2023-09-07 17:31:02,449     <class 'panel.io.server.ComponentResourceHandler'>,
2023-09-07 17:31:02,449     {}),
2023-09-07 17:31:02,449    ('/?',
2023-09-07 17:31:02,449     <class 'panel.io.server.RootHandler'>,
2023-09-07 17:31:02,449     {'applications': {'/app': <bokeh.server.contexts.ApplicationContext object at 0x12340a710>},
2023-09-07 17:31:02,449      'index': '/Users/monodera/.pyenv/versions/3.11.1/envs/py311/lib/python3.11/site-packages/panel/io/../_templates/index.html',
2023-09-07 17:31:02,449      'prefix': '',
2023-09-07 17:31:02,449      'use_redirect': True}),
2023-09-07 17:31:02,449    ('/static/extensions/(.*)',
2023-09-07 17:31:02,449     <class 'bokeh.server.views.multi_root_static_handler.MultiRootStaticHandler'>,
2023-09-07 17:31:02,449     {'root': {'panel': '/Users/monodera/.pyenv/versions/3.11.1/envs/py311/lib/python3.11/site-packages/panel/dist'}}),
2023-09-07 17:31:02,449    ('/static/(.*)',
2023-09-07 17:31:02,449     <class 'bokeh.server.views.static_handler.StaticHandler'>)]
2023-09-07 17:31:02,450 Bokeh app running at: http://localhost:5006/app
2023-09-07 17:31:02,450 Starting Bokeh server with process id: 32878
2023-09-07 17:31:07,533 Subprotocol header received
2023-09-07 17:31:07,533 Supplied subprotocol headers: ['bokeh', 'eyJzZXNzaW9uX2lkIjogIkFNWkc3R3p5N1YzSlhMSmF4UTBBMnFIc2JTUWNnTTZUdmVQdVBacmZSRWJkIiwgInNlc3Npb25fZXhwaXJ5IjogMTY5NDE0NDE2NiwgIl9fYmtfX3psaWJfIjogImVOcGRrV3RMd3pBVWh2OUs2Q2N2dlNTYnJYWkRSTlRwd0NFNEJMOUptcDYyY1ZuU3Bka3NjX3Z2SnBuZ0JmTGg1RHd2ZVVfZTh4azBRRXZRWFRCQ244R0Q2b3d0QXFFWUZZMjlqRktNc3lCRXdVc0hPcnF1UVhvLVUxc3VCRTNTR0tPakdXVmNHdFUxWXpTVkJnU3lEZlEwUjYtSTRKaWtZNlEzSTRMekdCLWplMkFMbFF3d3dmWVFOT0VhS3RVbmhKekgyTGxjTXdhdGR6RFFtNlF4U3hIU3RoV2NVY09WVEhyWE9lM19kNWRpdkxyRWNSN3lKYTBob1J0ZWZaY2ZVTFRoU1hMaS1jV1BSZlJJWmIyMkN1ZjFUa09RWHBILVV0eEpwa291YTZlb3Q3d05VUW1Wb0FaQ1ZHaW51MUZTQW5NVE9Na0NvSTJvNEJ2d2NiVzF0ckZHVTlrQlcydUlubUcxaHM2NG1BUGlGSE5nMFFRTWE2SmJPSVJlS3JaZXVvRF8wSmtxX1pEU19xcTI3bl9wbkpzRFZmSWZjUXR6NUlvRWV3dVlVZ3NPaHkyXzlaMnVIQnZzZ0dURGpORjhaOWVjRGpKeUFXeVladlM4eU9pd1NuTmNETTZxQXNvY2RpVEx5VEN6b2pQX0h0VzFIOWFfdU45X0FYY2hzOG8ifQ']
2023-09-07 17:31:07,540 WebSocket connection opened
2023-09-07 17:31:07,552 Receiver created for Protocol()
2023-09-07 17:31:07,553 ProtocolHandler created for Protocol()
2023-09-07 17:31:07,553 ServerConnection created
2023-09-07 17:31:07,622 Sending pull-doc-reply from session 'AMZG7Gzy7V3JXLJaxQ0A2qHsbSQcgM6TvePuPZrfREbd'
2023-09-07 17:31:07,706 Patching attribute 'pathname' of Location(id='p1010', ...) with '/app'
2023-09-07 17:31:07,788 Patching attribute 'href' of Location(id='p1010', ...) with 'http://localhost:5006/app'
2023-09-07 17:31:07,870 Patching attribute 'hostname' of Location(id='p1010', ...) with 'localhost'
2023-09-07 17:31:07,952 Patching attribute 'protocol' of Location(id='p1010', ...) with 'http:'
2023-09-07 17:31:08,021 Patching attribute 'port' of Location(id='p1010', ...) with '5006'
2023-09-07 17:31:08,097 Patching attribute 'dark_mode' of BrowserInfo(id='p1016', ...) with False
2023-09-07 17:31:08,177 Patching attribute 'device_pixel_ratio' of BrowserInfo(id='p1016', ...) with 2
2023-09-07 17:31:08,253 Patching attribute 'language' of BrowserInfo(id='p1016', ...) with 'ja'
2023-09-07 17:31:08,329 Patching attribute 'webdriver' of BrowserInfo(id='p1016', ...) with False
2023-09-07 17:31:08,403 Patching attribute 'timezone' of BrowserInfo(id='p1016', ...) with 'Pacific/Honolulu'
2023-09-07 17:31:08,485 Patching attribute 'timezone_offset' of BrowserInfo(id='p1016', ...) with 600
Exception in thread Thread-1 (callback_exec):
Traceback (most recent call last):
  File "/Users/monodera/.pyenv/versions/3.11.1/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/monodera/.pyenv/versions/3.11.1/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/monodera/tmp/test_panel/app.py", line 20, in callback_exec
    pn.state.notifications.warning("Warning!")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'warning'
```

#### Screenshots or screencasts of the bug in action
N/A

#### Additional comment
I also confirm that `minimu.py` posted in #5090 works without any problem.

**Comment by philippjfr** [comment]
So the issue here is that `pn.state` (and to some extent `pn.config`) depend on detecting the current session that is handling a request. When you create a thread this executes outside the context of the session handling and you have to tell Panel manually which session a particular action is meant for. One way of doing this would be this:

```python
from panel.io.state import set_curdoc
curdoc = pn.state.curdoc

def callback_exec():
    while True:
        cb_exec.acquire()
        for _ in queue_exec:
            with set_curdoc(curdoc):
                pn.state.notifications.warning("Warning!")
        queue_exec.clear()
        cb_exec.release()
```

**Comment by monodera** [comment]
Thanks for the comment. I confirm that both worked for me.

**Comment by cdeil** [comment]
With latest `panel 1.3.0a8` and `bokeh 3.3.0` also this simple example:

```
import panel as pn
pn.extension(design="material")
pn.state.notifications.info("Spam!", duration=3000)
```

now results in this error:
```
$ panel serve examples/notifications_none.py --show 
2023-10-11 22:40:57,964 Starting Bokeh server version 3.3.0 (running on Tornado 6.3.3)
2023-10-11 22:40:57,968 Cannot start Bokeh server, port 5006 is already in use
(hm-panel) hm-panel-training-2023 $ panel serve examples/notifications_none.py --show
2023-10-11 22:43:11,763 Starting Bokeh server version 3.3.0 (running on Tornado 6.3.3)
2023-10-11 22:43:11,764 User authentication hooks NOT provided (default user enabled)
2023-10-11 22:43:11,806 Bokeh app running at: http://localhost:5006/notifications_none
2023-10-11 22:43:11,806 Starting Bokeh server with process id: 24719
2023-10-11 22:43:12,402 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x1412d6a90>: 'NoneType' object has no attribute 'info'
File 'notifications_none.py', line 4, in <module>:
pn.state.notifications.info("Spam!", duration=3000) Traceback (most recent call last):
  File "/Users/cdeil/anaconda3/envs/hm-panel/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/Users/cdeil/code/hc/hm-panel-training-2023/examples/notifications_none.py", line 4, in <module>
    pn.state.notifications.info("Spam!", duration=3000)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'info'
 
2023-10-11 22:43:12,787 WebSocket connection opened
2023-10-11 22:43:12,788 ServerConnection created
```

@philippjfr - would you say this is a bug? Or is it usage error to use notifications in such a simple manner?

**Comment by philippjfr** [comment]
Looks like a separate bug

**Comment by cdeil** [comment]
@philippjfr - add "bug" label here? Or should I file a separate ticket?

**Comment by alexespencer** [comment]
I'm getting a similar issue, minimal code to reproduce is hard - but the behaviour is this: even with `pn.extension(notifications=True)` at the top of the code any call to `pn.state.notifications` fail with the same `NoneType` error above until you change + save a part of the code that causes autoreload. Then from that point on, notifications work.

**Comment by AMD-wangjason** [comment]
+1, I also run into same issue. It's not consistently failing but occasionally fails to instantiate a notification object.
