### ISSUE TITLE
Broken App Gallery Examples (Pyodide/WASM)

### ISSUE THREAD

**Issue by michaelweinold** [holoviz/panel#5521]
#### ALL software version info

N/A (depends on the specific example)

#### Description of expected behavior and the observed behavior

I checked some of the examples from [the App Gallery](https://panel.holoviz.org/gallery/index.html). Unfortunately, some fail to load in Pyodide. According to the JavaScript console, this is for different reasons (see below).

#### Complete, minimal, self-contained example code that reproduces the issue

N/A (launch examples in Pyodide)

#### Stack traceback and/or browser JavaScript console output

- [Portfolio Analyzer (Pyodide)](https://panel.holoviz.org/pyodide/portfolio_analyzer)

Does not load.

```
portfolio_analyzer:1705 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'roots')
    at pyodideWorker.onmessage (portfolio_analyzer:1705:36)
pyodideWorker.onmessage @ portfolio_analyzer:1705
2plotly-2.18.0.min.js:8 Uncaught (in promise) Error: Resize must be passed a displayed plot div element.
    at plotly-2.18.0.min.js:8:693036
    at new Promise (<anonymous>)
    at _.resize (plotly-2.18.0.min.js:8:692988)
    at y.after_layout (panel.min.js:132:2994)
    at y.compute_layout (bokeh-3.2.2.min.js:554:5540)
    at y._after_resize (bokeh-3.2.2.min.js:554:732)
    at y.after_resize (bokeh-3.2.2.min.js:433:2547)
    at ResizeObserver.<anonymous> (bokeh-3.2.2.min.js:433:2043)
```

- [Gapminders Example (Pyodide)](https://panel.holoviz.org/pyodide/gapminders)

Does not load.

```
pyodide.asm.js:9 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "_pyodide/_base.py", line 540, in eval_code_async
  File "_pyodide/_base.py", line 365, in run_async
  File "<exec>", line 23, in <module>
ModuleNotFoundError: The module 'matplotlib' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("matplotlib") in Python, or
  await pyodide.loadPackage("matplotlib") in JavaScript
See https://pyodide.org/en/stable/usage/loading-packages.html for more details.

    at new_error (pyodide.asm.js:9:14992)
    at pyodide.asm.wasm:0x152d67
    at pyodide.asm.wasm:0x159d1c
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:128013)
    at pyodide.asm.wasm:0x19f6c6
    at pyodide.asm.wasm:0x28650b
    at pyodide.asm.wasm:0x1e0617
    at pyodide.asm.wasm:0x19fbad
    at pyodide.asm.wasm:0x19fe6e
    at pyodide.asm.wasm:0x19ff10
    at pyodide.asm.wasm:0x264a10
    at pyodide.asm.wasm:0x26a9f5
    at pyodide.asm.wasm:0x1a0038
    at pyodide.asm.wasm:0x19fcc8
    at pyodide.asm.wasm:0x159532
    at Module.callPyObjectKwargs (pyodide.asm.js:9:75497)
    at Module.callPyObject (pyodide.asm.js:9:75942)
    at wrapper (pyodide.asm.js:9:57697)
```

- [Altair Brushing (Pyodide)](https://panel.holoviz.org/pyodide/altair_brushing)

Loads, but does not work.

```
bokeh-3.2.2.min.js:211 Uncaught (in promise) Error: reference 29544cce-0da3-4046-841b-3af90aba5deb isn't known
    at p.error (bokeh-3.2.2.min.js:211:4951)
    at p._decode_ref (bokeh-3.2.2.min.js:211:4572)
    at p._decode (bokeh-3.2.2.min.js:211:1046)
    at p._decode_plain_object (bokeh-3.2.2.min.js:211:2340)
    at p._decode (bokeh-3.2.2.min.js:211:1066)
    at bokeh-3.2.2.min.js:211:2249
    at f (bokeh-3.2.2.min.js:178:450)
    at p._decode_plain_array (bokeh-3.2.2.min.js:211:2237)
    at p._decode (bokeh-3.2.2.min.js:211:928)
    at bokeh-3.2.2.min.js:211:614
```

#### Screenshots or screencasts of the bug in action

![ezgif-1-be8bee0f0f](https://github.com/holoviz/panel/assets/23102087/0480edc1-9844-41fe-b65a-9f04289d26eb)

- [x] I may be interested in making a pull request to address this

**Comment by MarcSkovMadsen** [comment]
I see the same issue in my server based apps using Panel 1.4.4.

![image](https://github.com/holoviz/panel/assets/42288570/3d28329e-5753-4098-a6fd-1db9c61ebda3)


![image](https://github.com/holoviz/panel/assets/42288570/b574ebc0-0977-4ba8-a934-229ce78e6e96)

**Comment by MarcSkovMadsen** [comment]
I still see the resize issue in all my Panel apps with Panel 1.4.5.
