### ISSUE TITLE
Pasting text in the `TextEditor` no longer works

### ISSUE THREAD

**Issue by maximlt** [holoviz/panel#5545]
Pasting text in the `TextEditor` no longer works. That's the error logged in the browser console when you try to paste in the widget:

```
quill.js:3065 Uncaught TypeError: Cannot read properties of null (reading 'offset')
    at quill.js:3065:26
    at Array.map (<anonymous>)
    at Selection.normalizedToRange (quill.js:3059:31)
    at Selection.getRange (quill.js:3042:24)
    at Selection.update (quill.js:3229:28)
    at HTMLDocument.<anonymous> (panel.min.js?v=c47f5b18b8a430e698b9fe15e51f6119984e78334bcf3f45e210d30c37ef2f9e:135:2379)
```

**Comment by maximlt** [comment]
The `TextEditor` widget is implemented based on QuillJS, which hasn't been updated in a while and doesn't yet support the shadow DOM. A good summary of this can be found in:
- https://github.com/quilljs/quill/issues/2961
- https://github.com/robrez/quill/pull/1

After Panel moved to Bokeh 3, the `TextEditor` widget was patched twice to improve its support in the shadow DOM:
- https://github.com/holoviz/panel/pull/4467
- https://github.com/holoviz/panel/pull/5511

Both patches were inspired from https://stackoverflow.com/questions/67914657/quill-editor-inside-shadow-dom/67944380#67944380, the author of this answer can also be found on Quill's Github https://github.com/quilljs/quill/issues/2961#issuecomment-859955012.

The copy/paste issue has also been reported on Quill's issue tracker a few times:
- https://github.com/quilljs/quill/issues/2021#issuecomment-1479055139
- https://github.com/quilljs/quill/issues/2961#issuecomment-1195538461

I haven't yet seen a solution that fixes the issue, I haven't tried them all though and I could easily miss it 🙃 
---

I've tried a few things to fix the issue, without luck so far. It seems the issue doesn't occur on Firefox.

**Comment by maximlt** [comment]
In my quest for finding a fix for this, I found this interesting PR https://github.com/nuxeo/quill/pull/2 where they are patching Quill directly and replacing the [shadow-selection-polyfill](https://github.com/GoogleChromeLabs/shadow-selection-polyfill) with an alternative. This branch https://github.com/quilljs/quill/compare/develop...nuxeo:quill:2.0.0-NX, apparently built on top of the 2.0dev branch of Quill (that is a few years old) has a few commits to add support to the Shadow DOM. It's been last published two years ago https://www.npmjs.com/package/@nuxeo/quill.

I'm pretty sure we'll get hit back by some of these Shadow DOM issues with Quill, when that happens, trying out `@nuxeo/quill` might be an option.
