### ISSUE TITLE
Pyodide ImportError on Windturbines docs page

### ISSUE THREAD

**Issue by cdeil** [holoviz/panel#5559]
At https://panel.holoviz.org/gallery/windturbines.html I see the following error if I execute the example via the green play button.

```
ImportError: Geographic projection support requires: cartopy, geoviews, pyproj.
```

Traceback:

```
Traceback (most recent call last):
  File "/lib/python3.11/site-packages/panel/io/mime_render.py", line 176, in exec_with_return
    exec(compile(init_ast, "<ast>", "exec"), global_context)
  File "<ast>", line 33, in <module>
  File "/lib/python3.11/site-packages/hvplot/plotting/core.py", line 1626, in points
    return self(x, y, kind="points", **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/hvplot/plotting/core.py", line 92, in __call__
    return self._get_converter(x, y, kind, **kwds)(kind, x, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/hvplot/plotting/core.py", line 99, in _get_converter
    return HoloViewsConverter(self._data, x, y, kind=kind, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/hvplot/converter.py", line 401, in __init__
    self.crs = self._process_crs(data, crs) if self.geo else None
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/hvplot/converter.py", line 662, in _process_crs
    return process_crs(_crs)
           ^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/hvplot/util.py", line 248, in process_crs
    raise ImportError(f'Geographic projection support requires: {", ".join(missing)}.')
ImportError: Geographic projection support requires: cartopy, geoviews, pyproj.
```

Screenshot:

<img width="1624" alt="Screenshot 2023-09-29 at 22 18 29" src="https://github.com/holoviz/panel/assets/852409/1a5f39e8-8eb2-491c-84dc-e91a2d046e11">

**Comment by philippjfr** [comment]
Thanks, this is a regression in hvplot which will be resolved in the hvplot 0.9 release.

**Comment by cdeil** [comment]
@philippjfr - it looks like hvplot 0.9 was released two weeks ago.

I now get this different error for https://panel.holoviz.org/gallery/windturbines.html
<img width="987" alt="Screenshot 2023-11-01 at 13 35 13" src="https://github.com/holoviz/panel/assets/852409/3b705d08-3f3e-479b-9463-db0812d23f80">

**Comment by cdeil** [comment]
And for https://panel.holoviz.org/reference/templates/Material.html I see this error:

<img width="999" alt="Screenshot 2023-11-01 at 13 35 50" src="https://github.com/holoviz/panel/assets/852409/e7b185f5-24ea-4acc-a403-c1be613788ce">

**Comment by cdeil** [comment]
This is fixed by now: https://panel.holoviz.org/reference/templates/Material.html

This still shows an error: https://panel.holoviz.org/gallery/windturbines.html

ImportError: In order to use datashading features the Datashader library must be available. It can be installed with:
  conda install datashader

**Comment by Hoxbro** [comment]
Datashader is not available to be installed with Pyodide.
