### ISSUE TITLE
Suspect Panel < 1.3 is incompatible with Param 2

### ISSUE THREAD

**Issue by owenlamont** [holoviz/panel#5745]
#### ALL software version info

Browser: Vivaldi 6.2.3105.58 (Stable channel) (64-bit) 
OS: Windows 11

- Panel 1.2.1
- pyodide 0.23.4
- PyScript 2023.05.1

#### Description of expected behavior and the observed behavior

I got a recursion overflow error when using Panel 1.2.1 in PyScript, I suspect it is incompatible with Param 2. I think you may need to pin older versions of Panel to be Param version < 2. Upgrading Panel to 1.3 resolved the problem with my code (I previously had Panel and Pyscript versions pinned but my code broke just recently (without any changes in my own logic) - which I strongly suspect corresponds with the Param 2 release).

#### Complete, minimal, self-contained example code that reproduces the issue

I believe this happened just during import... 

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):
  File "/home/pyodide/pyscript/_internal.py", line 104, in run_pyscript
    result = eval_code(code, globals=__main__.__dict__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 468, in eval_code
    .run(globals, locals)
     ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python311.zip/_pyodide/_base.py", line 310, in run
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 1, in <module>
  File "/home/pyodide/hydrograph_panel.py", line 42, in <module>
    import panel as pn
  File "/lib/python3.11/site-packages/panel/__init__.py", line 48, in <module>
    from . import layout  # noqa
    ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/layout/__init__.py", line 31, in <module>
    from .accordion import Accordion  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/layout/accordion.py", line 11, in <module>
    from ..reactive import Reactive
  File "/lib/python3.11/site-packages/panel/reactive.py", line 36, in <module>
    from .io.document import unlocked
  File "/lib/python3.11/site-packages/panel/io/__init__.py", line 9, in <module>
    from .document import init_doc, unlocked, with_lock  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/io/document.py", line 25, in <module>
    from ..config import config
  File "/lib/python3.11/site-packages/panel/config.py", line 575, in <module>
    config = _config(**{k: None if p.allow_None else getattr(_config, k)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 315, in __init__
    super().__init__(**params)
  File "/lib/python3.11/site-packages/param/parameterized.py", line 4153, in __init__
    self.param._setup_refs(deps)
    ^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 437, in __getattribute__
    elif f'_{attr}' in params and getattr(self, f'_{attr}_') is not None:
         ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1869, in __contains__
    return param in list(self_)
                    ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1866, in __iter__
    yield from self_.objects(instance=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2367, in objects
    if self_.self is not None and not self_.self._param__private.initialized and instance is True:
```

.
.
.

```
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2367, in objects
    if self_.self is not None and not self_.self._param__private.initialized and instance is True:
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 437, in __getattribute__
    elif f'_{attr}' in params and getattr(self, f'_{attr}_') is not None:
         ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1869, in __contains__
    return param in list(self_)
                    ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1866, in __iter__
    yield from self_.objects(instance=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2367, in objects
    if self_.self is not None and not self_.self._param__private.initialized and instance is True:
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 437, in __getattribute__
    elif f'_{attr}' in params and getattr(self, f'_{attr}_') is not None:
         ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1869, in __contains__
    return param in list(self_)
                    ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1866, in __iter__
    yield from self_.objects(instance=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2367, in objects
    if self_.self is not None and not self_.self._param__private.initialized and instance is True:
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 437, in __getattribute__
    elif f'_{attr}' in params and getattr(self, f'_{attr}_') is not None:
         ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1869, in __contains__
    return param in list(self_)
                    ^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 1866, in __iter__
    yield from self_.objects(instance=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 2367, in objects
    if self_.self is not None and not self_.self._param__private.initialized and instance is True:
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 422, in __getattribute__
    params = super().__getattribute__('param')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/param/parameterized.py", line 4159, in param
    return Parameters(self.__class__, self=self)
                      ^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/panel/config.py", line 413, in __getattribute__
    from .io.state import state
  File "<frozen importlib._bootstrap>", line 409, in parent
RecursionError: maximum recursion depth exceeded while calling a Python object
```

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/12672027/ad5793af-b691-4061-b203-cf84990bcd90)

- [x] I may be interested in making a pull request to address this

**Comment by maximlt** [comment]
Yes indeed older versions aren't compatible with Param 2.0. Could you share how you define your dependencies?

**Comment by MarcSkovMadsen** [comment]
I saw a colleague get hit by this as well in a presentation yesterday.

**Comment by philippjfr** [comment]
That's really unfortunate. For pyodide apps there is in theory a fix, which is to download all the wheels from the CDN, patch them with the updated param pin and then re-upload them.

**Comment by philippjfr** [comment]
I'll start writing a script to do that now.

**Comment by owenlamont** [comment]
Sounds like you've already reproduced this (I can easily on Pyscript.com). If it helps I was importing via pyscript.toml like this:

```toml
packages = [
    "https://cdn.holoviz.org/panel/1.2.1/dist/wheels/bokeh-3.2.1-py3-none-any.whl",
    "https://cdn.holoviz.org/panel/1.2.1/dist/wheels/panel-1.2.1-py3-none-any.whl", 
    "pandas",
    "plotly==5.15.0"
]
name = "Panel Plotly Pane Test"
[[interpreters]]
src = "https://cdn.jsdelivr.net/pyodide/v0.23.4/full/pyodide.js"
name = "pyodide-0.23.4"
lang = "python"
```

**Comment by philippjfr** [comment]
My hacky script:

```python
import pathlib
import boto3

s3_client = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY, aws_secret_access_key=AWS_SECRET_KEY)
s3_paginator = client.get_paginator('list_objects_v2')

def keys(bucket_name, prefix='/', delimiter='/', start_after=''):
    prefix = prefix.lstrip(delimiter)
    start_after = (start_after or prefix) if prefix.endswith(delimiter) else start_after
    for page in s3_paginator.paginate(Bucket=bucket_name, Prefix=prefix, StartAfter=start_after):
        for content in page.get('Contents', ()):
            if content['Key'].endswith('.whl'): 
                yield content['Key']

wheels = list(keys('cdn.holoviz.org'))

for whl in wheels:
    if 'panel-' in whl:
        pathlib.Path(whl).parent.mkdir(exist_ok=True, parents=True) 
        s3_client.download_file(Bucket='cdn.holoviz.org', Key=whl, Filename=whl)
        
def update_wheel(wheel):
    zin = zipfile.ZipFile (wheel, 'r')
    ('rewrite' / pathlib.Path(wheel)).parent.mkdir(parents=True, exist_ok=True)
    zout = zipfile.ZipFile('rewrite' / pathlib.Path(wheel), 'w')
    for item in zin.infolist():
        filename = item.filename
        buffer = zin.read(filename)
        if filename.endswith('METADATA'):
            # remove tornado dependency
            lines = []
            for line in buffer.decode('utf-8').split('\n'):
                if line.startswith('Requires-Dist:') and 'param (' in line:
                    line = line.replace(')', ',<2)')
                    print(line)
                lines.append(line)
            buffer = '\n'.join(lines).encode('utf-8')
        zout.writestr(item, buffer)

    zout.close()
    zin.close()

for whl in glob.glob('./panel/*/*/*/*.whl'):
    update_wheel(whl)
```

Will upload now.

**Comment by philippjfr** [comment]
Uploaded and CDN cache invalidation issued. In theory we should be good now.

**Comment by philippjfr** [comment]
If you could test that would be appreciated. My testing suggests this worked.

**Comment by MarcSkovMadsen** [comment]
This one is not working. But its a Panel 0.x to Panel 1.x issue https://sharing.awesome-panel.org/ahuang11/weather-retro/app.html. Seems apps need to be converted regularly to keep working.

**Comment by philippjfr** [comment]
>This one is not working. But its a Panel 0.x to Panel 1.x issue https://sharing.awesome-panel.org/ahuang11/weather-retro/app.html. Seems apps need to be converted regularly to keep working.

This is a really annoying behavior in pyodide, where it will only install a single version of a package and if a different version is requested it'll error out. We should document that for pyodide you really should pin everything very explicitly.

**Comment by MarcSkovMadsen** [comment]
> > This one is not working. But its a Panel 0.x to Panel 1.x issue https://sharing.awesome-panel.org/ahuang11/weather-retro/app.html. Seems apps need to be converted regularly to keep working.
> 
> This is a really annoying behavior in pyodide, where it will only install a single version of a package and if a different version is requested it'll error out. We should document that for pyodide you really should pin everything very explicitly.

Could `panel convert` help do this automatically?

**Comment by philippjfr** [comment]
Good point, at least for auto-generated requirements it totally should just snapshot the user environment.

**Comment by MarcSkovMadsen** [comment]
Here is another example of the issue https://github.com/pyscript/pyscript/issues/1821
