### ISSUE TITLE
Cannot pass raw interactive dataframe to tabulator

### ISSUE THREAD

**Issue by Stubatiger** [holoviz/panel#5834]
Hey using the interactive tutorial at https://panel.holoviz.org/how_to/interactivity/hvplot_interactive.html i can pass  an interactive dataframe to a widget like this.

(Breaked down version)
```python
import pandas as pd
import panel as pn
import hvplot.pandas  # Enable interactive

pn.extension('tabulator')
df = pd.read_csv('https://datasets.holoviz.org/penguins/v1/penguins.csv')

some_filter = pn.widgets.IntSlider(name="year", start=2007, end=2009)
idf = df.interactive()

filtered_df = idf[idf["year"] >= some_filter]

layout = pn.Row(
    filtered_df.widgets(),
    pn.widgets.Tabulator(filtered_df, page_size=10, pagination='remote'),
)

layout.servable()
```
and it correctly renders the table.

but if i want to show an unmodified version like this
```python
import pandas as pd
import panel as pn
import hvplot.pandas  # Enable interactive

pn.extension('tabulator')
df = pd.read_csv('https://datasets.holoviz.org/penguins/v1/penguins.csv')

idf = df.interactive()

layout = pn.Row(
    pn.widgets.Tabulator(idf, page_size=10, pagination='remote'),
)

layout.servable()

```

the error looks like this
```pytb
KeyError: 1

Traceback (most recent call last):
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\pandas\core\indexes\base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\bokeh\application\handlers\code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "C:\Users\R2D2\PycharmProjects\playground\paneltest.py", line 12, in <module>
    pn.widgets.Tabulator(idf, page_size=10, pagination='remote'),
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\widgets\tables.py", line 1161, in __init__
    super().__init__(value=value, **params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\widgets\tables.py", line 116, in __init__
    super().__init__(value=value, **params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\reactive.py", line 1210, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\reactive.py", line 861, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\widgets\base.py", line 75, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\reactive.py", line 556, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\reactive.py", line 118, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\viewable.py", line 694, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\viewable.py", line 532, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\viewable.py", line 298, in __init__
    super().__init__(**params)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\param\parameterized.py", line 4154, in __init__
    self.param._update_deps(init=True)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\param\parameterized.py", line 2120, in _update_deps
    m()
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\param\depends.py", line 41, in _depends
    return func(*args, **kw)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\widgets\tables.py", line 127, in _compute_renamed_cols
    str(col) if str(col) != col else col: col for col in self._get_fields()
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\panel\widgets\tables.py", line 144, in _get_fields
    col_names = list(self.value.columns)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\hvplot\interactive.py", line 653, in __getitem__
    return self._apply_operator(operator.getitem, other)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\hvplot\interactive.py", line 539, in _apply_operator
    return new._clone(transform)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\hvplot\interactive.py", line 388, in _clone
    return type(self)(self._obj, fn=self._fn, transform=transform, plot=plot, depth=depth,
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\hvplot\interactive.py", line 282, in __init__
    self._current_ = self._transform.apply(ds, keep_index=True, compute=False)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\holoviews\util\transform.py", line 773, in apply
    data = self._apply_fn(dataset, data, fn, fn_name, args,
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\holoviews\util\transform.py", line 672, in _apply_fn
    data = fn(*args, **kwargs)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\pandas\core\frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\R2D2\PycharmProjects\playground\venv39\lib\site-packages\pandas\core\indexes\base.py", line 3797, in get_loc
    raise KeyError(key) from err
KeyError: 1

```

I would expect that i can use an interactive dataframe just like a normal one? 
I cant even use methods like .head() or so and then pass it to the tabulator widget.

**Comment by philippjfr** [comment]
This seems like a bug in `Interactive` itself rather than Panel. The good news is that since Param 2.0 and Panel 1.3 you no longer need to rely on `Interactive` to get this functionality. Specifically we have massively improved and generalized the concepts behind `Interactive` as part of the work on reactive expressions:

```
import pandas as pd
import panel as pn
import hvplot.pandas  # Enable interactive

pn.extension('tabulator')
df = pd.read_csv('https://datasets.holoviz.org/penguins/v1/penguins.csv')

some_filter = pn.widgets.IntSlider(name="year", start=2007, end=2009)
idf = pn.rx(df)

filtered_df = idf[idf["year"] >= some_filter]

layout = pn.Row(
    pn.ReactiveExpr(filtered_df).widgets,
    pn.widgets.Tabulator(filtered_df, page_size=10, pagination='remote'),
)

layout.servable()
```

See [Param docs](https://param.holoviz.org/user_guide/Reactive_Expressions.html) and [corresponding Panel docs](https://holoviz-dev.github.io/panel/reference/panes/ReactiveExpr.html) for reference.

**Comment by philippjfr** [comment]
Actually I just realized this IS probably a Panel bug. Panel should resolve `Interactive` correctly.

**Comment by philippjfr** [comment]
Worse yet, it's a Param issue. Since the expression has no dependencies Param does not treat the `Interactive` object as a reference. Will have to think about a proper fix.
