### ISSUE TITLE
DeserializationError when trying out Deploying_Bokeh_Apps examples

### ISSUE THREAD

**Issue by sflis** [holoviz/panel#5916]
#### ALL software version info
Ubuntu 20.04.5
python 3.11.5
```
asttokens          2.0.5
backcall           0.2.0
bleach             6.1.0
blinker            1.7.0
bokeh              3.3.1
certifi            2023.11.17
charset-normalizer 3.3.2
click              8.1.7
colorcet           3.0.1
contourpy          1.0.5
cycler             0.11.0
decorator          5.1.1
executing          0.8.3
Flask              3.0.0
fonttools          4.25.0
holoviews          1.18.1
idna               3.4
ipython            8.15.0
itsdangerous       2.1.2
jedi               0.18.1
Jinja2             3.1.2
kiwisolver         1.4.4
linkify-it-py      2.0.2
Markdown           3.5.1
markdown-it-py     3.0.0
MarkupSafe         2.1.3
matplotlib         3.8.0
matplotlib-inline  0.1.6
mdit-py-plugins    0.4.0
mdurl              0.1.2
mkl-fft            1.3.8
mkl-random         1.2.4
mkl-service        2.4.0
munkres            1.1.4
numpy              1.26.0
packaging          23.1
pandas             2.1.3
panel              1.3.2
param              2.0.1
parso              0.8.3
pexpect            4.8.0
pickleshare        0.7.5
Pillow             10.0.1
pip                23.3
ply                3.11
prompt-toolkit     3.0.36
ptyprocess         0.7.0
pure-eval          0.2.2
pyct               0.5.0
Pygments           2.15.1
pyparsing          3.0.9
PyQt5              5.15.10
PyQt5-sip          12.13.0
python-dateutil    2.8.2
pytz               2023.3.post1
pyviz_comms        3.0.0
PyYAML             6.0.1
requests           2.31.0
setuptools         68.0.0
sip                6.7.12
six                1.16.0
stack-data         0.2.0
tornado            6.3.3
tqdm               4.66.1
traitlets          5.7.1
typing_extensions  4.8.0
tzdata             2023.3
uc-micro-py        1.0.2
urllib3            2.1.0
wcwidth            0.2.5
webencodings       0.5.1
Werkzeug           3.0.1
wheel              0.41.2
xyzservices        2023.10.1
```

#### Description of expected behavior and the observed behavior
I'm trying examples how to embed a bokeh app in a flask application and no matter what versions of bokeh-panel-holoviews I try I cannot get the example to work. In the following I'm using the latest versions of the packages with python 3.11 and I'm still getting 
 `bokeh.core.serialization.DeserializationError: can't resolve type 'panel.models.browser.BrowserInfo'`

#### Complete, minimal, self-contained example code that reproduces the issue
I'm using the code example from https://holoviews.org/user_guide/Deploying_Bokeh_Apps.html#combining-bokeh-application-and-flask-application only modification I've done is to add `import panel as pn` in the flaskApp.py file as suggested [here](https://discourse.holoviz.org/t/error-when-running-the-example-to-embed-plot-in-flask-application/2785/4).

#### Stack traceback and/or browser JavaScript console output
```127.0.0.1 - - [24/Nov/2023 12:17:40] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/projects/eacl-page/eacl-page/holowiz-test/flaskApp.py", line 14, in index
    with pull_session(url="http://localhost:5006/") as session:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/client/session.py", line 142, in pull_session
    session.pull()
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/client/session.py", line 430, in pull
    self._connection.pull_doc(doc)
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/client/connection.py", line 217, in pull_doc
    reply.push_to_document(document)
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/protocol/messages/pull_doc_reply.py", line 90, in push_to_document
    doc.replace_with_json(self.content['doc'])
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/document/document.py", line 672, in replace_with_json
    replacement = self.from_json(json)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/document/document.py", line 438, in from_json
    doc_struct = deserializer.deserialize(doc_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 512, in deserialize
    return self.decode(obj)
           ^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 525, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 566, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 566, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 568, in _decode
    return [self._decode(entry) for entry in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 568, in <listcomp>
    return [self._decode(entry) for entry in obj]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 558, in _decode
    return self._decode_object_ref(cast(ObjectRefRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 688, in _decode_object_ref
    cls = self._resolve_type(name)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 723, in _resolve_type
    self.error(f"can't resolve type '{type}'")
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 727, in error
    raise DeserializationError(error)
bokeh.core.serialization.DeserializationError: can't resolve type 'panel.models.browser.BrowserInfo'
127.0.0.1 - - [24/Nov/2023 12:17:40] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [24/Nov/2023 12:17:40] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [24/Nov/2023 12:17:40] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [24/Nov/2023 12:17:41] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/projects/eacl-page/eacl-page/holowiz-test/flaskApp.py", line 14, in index
    with pull_session(url="http://localhost:5006/") as session:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/client/session.py", line 142, in pull_session
    session.pull()
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/client/session.py", line 430, in pull
    self._connection.pull_doc(doc)
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/client/connection.py", line 217, in pull_doc
    reply.push_to_document(document)
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/protocol/messages/pull_doc_reply.py", line 90, in push_to_document
    doc.replace_with_json(self.content['doc'])
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/document/document.py", line 672, in replace_with_json
    replacement = self.from_json(json)
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/document/document.py", line 438, in from_json
    doc_struct = deserializer.deserialize(doc_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 512, in deserialize
    return self.decode(obj)
           ^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 525, in decode
    return self._decode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 566, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 566, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 568, in _decode
    return [self._decode(entry) for entry in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 568, in <listcomp>
    return [self._decode(entry) for entry in obj]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 558, in _decode
    return self._decode_object_ref(cast(ObjectRefRep, obj))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 688, in _decode_object_ref
    cls = self._resolve_type(name)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 723, in _resolve_type
    self.error(f"can't resolve type '{type}'")
  File "/home/vagrant/miniconda3/envs/fpoc/lib/python3.11/site-packages/bokeh/core/serialization.py", line 727, in error
    raise DeserializationError(error)
bokeh.core.serialization.DeserializationError: can't resolve type 'panel.models.browser.BrowserInfo'
```
#### Screenshots or screencasts of the bug in action
![image](https://github.com/holoviz/panel/assets/7725618/89c5757d-b9f3-4029-b4dd-6f34e6de7784)

- [ ] I may be interested in making a pull request to address this

**Comment by philippjfr** [comment]
Appreciate the detailed bug report. As an open source project we cannot guarantee any specific turnaround time on issue triaging although I try my best. This is definitely the right place for this issue. I have some guesses on what's wrong here but will have to investigate.

**Comment by philippjfr** [comment]
Okay, the fix for now is to add these imports to the flask app so that these models can be resolved:

```python
import panel
import panel.models.browser
```

There's two fixes we'll have to make on our side:

1. `panel.models.browser` should be imported by default in Panel
2. The HoloViews docs should be updated to include `import panel`
