### ISSUE TITLE
Can't hv.save html file when threading is enabled

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#5957]
Panel 1.3.4
HoloViews 1.18.1
Bokeh 3.3.1

Tried on Fedora 39 and Ubuntu 22.04

Saving a plot using `hv.save` is not possible when threading is enabled. From what I've seen, this issue seems to have been introduced with Panel 1.2.1.

You can for instance `panel serve` the following script with and without `--num-threads` set.

```python
import holoviews as hv
import numpy as np
import panel as pn


def save_curve(event):
    print('Saving...')
    hv.save(curve, 'curve.html')
    print('Saved')


curve = hv.Curve(np.random.randn(100).cumsum())
button = pn.widgets.Button(name='Save Curve', on_click=save_curve)

pn.Column(curve, button).servable()
```

Presumably there is an attempt to create a `ThreadPool` for `hv.save` whether the app uses a `ThreadPool` from the start or not.

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/hv/lib/python3.12/concurrent/futures/_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/io/state.py", line 433, in _handle_future_exception
    self._handle_exception(exception)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/io/state.py", line 440, in _handle_exception
    raise exception
  File "/home/user/miniconda3/envs/hv/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/reactive.py", line 416, in _process_bokeh_event
    self._process_event(event)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/widgets/button.py", line 247, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameters.py", line 542, in __set__
    super().__set__(obj,val)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/user/PycharmProjects/volcplume/toast.py", line 8, in save_curve
    hv.save(curve, 'curve.html')
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/holoviews/util/__init__.py", line 807, in save
    return renderer_obj.save(obj, filename, fmt=fmt, resources=resources,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/holoviews/plotting/renderer.py", line 595, in save
    plot.layout.save(basename, embed=True, resources=resources, title=title)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/viewable.py", line 985, in save
    return save(
           ^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/io/save.py", line 252, in save
    with config.set(embed=embed):
  File "/home/user/miniconda3/envs/hv/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/config.py", line 381, in set
    self.param.update(**dict(values))
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 2282, in update
    restore = self_._update(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 2315, in _update
    setattr(self_or_cls, k, v)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/config.py", line 400, in __setattr__
    validate_config(self, attr, value)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/config.py", line 59, in validate_config
    setattr(config, parameter, orig)
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/config.py", line 410, in __setattr__
    w.fn()
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/parameterized.py", line 781, in _sync_caller
    return function()
           ^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/param/depends.py", line 41, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/hv/lib/python3.12/site-packages/panel/config.py", line 351, in _set_thread_pool
    raise RuntimeError("Thread pool already running")
RuntimeError: Thread pool already running
```

**Comment by TheoMathurin** [comment]
Interestingly, the crash does not occur if you're trying to save to a `png` file.
