### ISSUE TITLE
HTTP Request Timeout

### ISSUE THREAD

**Issue by simonaay** [holoviz/panel#5992]
4 users tried to login to the webapp, but the webapp crashed upon authenticating with an **Internal Server Error**. According to the Traceback, it seemed that a timeout has been reached while fetching access token. Do you think there's a way not to put users under this traffic? Keep in mind that after a while the server regains its course for fewer users entering. That being said, the served webapp works completely find just not when several users entering together.

Traceback found below:
```
 AttributeError: 'NoneType' object has no attribute 'body'
     body = codecs.decode(response.body, 'utf-8')
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 47, in decode_response_body
     body = body or decode_response_body(response)
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 345, in _on_error
     return self._on_error(e.response)
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 194, in _fetch_access_token
     return await self._fetch_access_token(
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 129, in get_authenticated_user
     user = await self.get_authenticated_user(**params)
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 315, in get
     result = await result
   File ".../.local/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
 Traceback (most recent call last):
 During handling of the above exception, another exception occurred:
 AttributeError: 'NoneType' object has no attribute 'body'
     body = codecs.decode(response.body, 'ascii')
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 45, in decode_response_body
 Traceback (most recent call last):
 During handling of the above exception, another exception occurred:
 tornado.simple_httpclient.HTTPTimeoutError: Timeout during request
     response = await http.fetch(req)
   File ".../.local/lib/python3.10/site-packages/panel/auth.py", line 192, in _fetch_access_token
 Traceback (most recent call last):
 HTTPServerRequest(protocol='http', host='xxxx:yyyy', method='GET', uri='/login?next=%2F%3Fcode%...
 2023-11-30 07:16:46,767 Uncaught exception GET /login?next=%2F%3Fcode%...%26scope%3Dopenid%2520email%26...
 2023-11-30 07:14:49,696 Starting Bokeh server with process id: 1060
 2023-11-30 07:14:49,696 Bokeh app running at: http://localhost:5000/app

```

**Comment by Hoxbro** [comment]
More information is likely needed. Can you try to update to the latest version of Panel? If you haven't already done it.

**Comment by simonaay** [comment]
> More information is likely needed. Can you try to update to the latest version of Panel? If you haven't already done it.

Hi,
I want to but unfortunately the generic oauth provider that I am using is incompatible with the latest Panel version (v1.3.4). That is why, I am stuck testing on v1.2.0 as the login and authentication/authorization phase is working fine. Will update once the provider issue gets resolved.

**Comment by simonaay** [comment]
> Yes, this does not seem like the latest version which I know you've separately have had trouble with. Let me try to fix the other access_token issue you've reported and then cut a dev release for you to try.

that was quick. Thanks for your prompt response @philippjfr ! Disregard my previous quote reply then.
