### ISSUE TITLE
Preview with Panel does not work with async callbacks

### ISSUE THREAD

**Issue by Kramin42** [holoviz/panel#5999]
May be related to #3639

#### ALL software version info
python: 3.11.2
IPython          : 8.17.1
ipykernel        : 6.26.0
ipywidgets       : 8.1.1
jupyter_client   : 8.5.0
jupyter_core     : 5.5.0
jupyter_server   : 2.9.1
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.4.4
traitlets        : 5.13.0
bokeh: 3.3.2
panel: 1.3.4

#### Description of expected behavior and the observed behavior

Code example from https://panel.holoviz.org/how_to/callbacks/async.html works correctly in notebook, but when using "Preview with Panel" clicking the button does nothing.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import panel as pn
import asyncio

pn.extension()

button = pn.widgets.Button(name='Click me!')
text = pn.widgets.StaticText()

async def run_async(event):
    text.value = f'Running {event.new}'
    await asyncio.sleep(2)
    text.value = f'Finished {event.new}'

button.on_click(run_async)

pn.Row(button, text).servable()
```

#### Stack traceback and/or browser JavaScript console output

Error that appears in jupyter lab log when clicking the button:

```
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f717b68d650>>, <Task finished name='Task-93' coro=<async_execute.<locals>.wrapper() done, defined at /home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/server.py:177> exception=RuntimeError('_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes')>)
Traceback (most recent call last):
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/server.py", line 183, in wrapper
    state._handle_exception(e)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/state.py", line 440, in _handle_exception
    raise exception
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/server.py", line 181, in wrapper
    return await func(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cameron/Work/jupyterlab/ipynb_dashboards/panel_async_test.ipynb", line 16, in run_async
    "\n",
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 374, in _param_change
    self._apply_update(named_events, properties, model, ref)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 302, in _apply_update
    self._update_model(events, msg, root, model, doc, comm)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 623, in _update_model
    super()._update_model(events, msg, root, model, doc, comm)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 330, in _update_model
    model.update(**msg)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/has_props.py", line 481, in update
    setattr(self, k, v)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/has_props.py", line 334, in __setattr__
    return super().__setattr__(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 333, in __set__
    self._set(obj, old, value, setter=setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 621, in _set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 699, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/model/model.py", line 562, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 188, in trigger
    self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 249, in notify_change
    self.trigger_on_change(event)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 413, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 412, in invoke_callbacks
    cb(event)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 276, in <lambda>
    self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/events.py", line 353, in dispatch
    super().dispatch(receiver)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/events.py", line 219, in dispatch
    cast(DocumentPatchedMixin, receiver)._document_patched(self)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/server/session.py", line 244, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
2023-12-06 14:27:04,134 ERROR: panel.io.jupyter_server_extension - ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f717b68d650>>, <Task finished name='Task-93' coro=<async_execute.<locals>.wrapper() done, defined at /home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/server.py:177> exception=RuntimeError('_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes')>)
Traceback (most recent call last):
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/server.py", line 183, in wrapper
    state._handle_exception(e)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/state.py", line 440, in _handle_exception
    raise exception
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/io/server.py", line 181, in wrapper
    return await func(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cameron/Work/jupyterlab/ipynb_dashboards/panel_async_test.ipynb", line 16, in run_async
    "\n",
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 374, in _param_change
    self._apply_update(named_events, properties, model, ref)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 302, in _apply_update
    self._update_model(events, msg, root, model, doc, comm)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 623, in _update_model
    super()._update_model(events, msg, root, model, doc, comm)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/panel/reactive.py", line 330, in _update_model
    model.update(**msg)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/has_props.py", line 481, in update
    setattr(self, k, v)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/has_props.py", line 334, in __setattr__
    return super().__setattr__(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 333, in __set__
    self._set(obj, old, value, setter=setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 621, in _set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/core/property/descriptors.py", line 699, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/model/model.py", line 562, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 188, in trigger
    self.document.callbacks.notify_change(cast(Model, self), attr, old, new, hint, setter, invoke)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 249, in notify_change
    self.trigger_on_change(event)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 413, in trigger_on_change
    invoke_with_curdoc(doc, invoke_callbacks)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 412, in invoke_callbacks
    cb(event)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 276, in <lambda>
    self._change_callbacks[receiver] = lambda event: event.dispatch(receiver)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/events.py", line 353, in dispatch
    super().dispatch(receiver)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/document/events.py", line 219, in dispatch
    cast(DocumentPatchedMixin, receiver)._document_patched(self)
  File "/home/cameron/.venv/base/lib/python3.11/site-packages/bokeh/server/session.py", line 244, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```

**Comment by Kramin42** [comment]
Also note that using 'pn.state.execute' as descibed  in https://panel.holoviz.org/how_to/callbacks/server.html does not fix the issue.

```
import panel as pn
import asyncio
from functools import partial

pn.extension()

button = pn.widgets.Button(name='Click me!')
text = pn.widgets.StaticText()

def set_text(value):
    text.value = value

async def run_async(event):
    pn.state.execute(lambda: setattr(text, 'value', f'Running {event.new}'))
    await asyncio.sleep(2)
    pn.state.execute(lambda: setattr(text, 'value', f'Finished {event.new}'))

button.on_click(run_async)

pn.Row(button, text).servable()
```

This code produces the same "_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes" error when using "Preview with Panel".

**Comment by philippjfr** [comment]
Thank you for the detailed bug report, that's super helpful.
