### ISSUE TITLE
Document how to use .rx in f-strings

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6067]
One of the most basic use cases of reactivity is string generation. And in Python you do that with f-strings.

I cannot figure out how to configure .rx and f-strings. I cannot find any example in the param or Panel documentation. I need it to help gshotwell in https://discourse.holoviz.org/t/dynamically-creating-widgets/6610.

## Not working example

```python
import panel as pn

n_input = pn.widgets.IntSlider(name="Number of Sliders", value=3, start=1, end=20)
text = f"Slider value: {n_input.param.value.rx()}"
app = pn.Column(n_input, text)

app.servable()
```

```bash
TypeError: str returned non-string (type rx)

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/private/panel/script.py", line 4, in <module>
    text = f"Slider value: {n_input.param.value.rx()}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __str__ returned non-string (type rx)
```

**Comment by philippjfr** [comment]
Sadly f-string cannot and will never be supported with rx because Python evaluates them immediately. So in practice the best we can do right now is standard format strings:

```python
n_input = pn.widgets.IntSlider(name="Number of Sliders", value=3, start=1, end=20)
text = pn.rx("Slider value: {}").format(n_input)
```

At least in theory we could add a construct like `pn.rx.f("Slider value: {n_input}")` which inspects the parent frames scope and evaluates the format string. The problem with that is that this is implementation dependent, i.e. CPython would allow this but PyPy might not.

**Comment by MarcSkovMadsen** [comment]
I will collect some more things I would like documented because I cannot do them here

## Work with list

I've tried to use a `.append` to a list: `pn.rx([])`. But the app does not update when I run the below.

```python

import panel as pn

queue = pn.rx([])

def append(_=None):
    print("append")
    queue.append(1)

submit = pn.widgets.Button(name="Submit", on_click=append)

pn.Column(submit, queue).servable()
```

The app works when I use

```python
import panel as pn

queue = pn.rx([])

def append(_=None):
    queue.rx.value = queue.rx.value + [1]

submit = pn.widgets.Button(name="Submit", on_click=append)

pn.Column(submit, queue).servable()
```
