### ISSUE TITLE
.from_param returns layout. Not widget.

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6103]
In the example below I would expect `selector1` and `selector2` to both be `Select` widgets.  But instead `selector2` is a layout. 

I've never experienced or seen this behavior before. I believe its a bug/ regression?

```python
import param
import panel as pn

pn.extension()

class Dataset(param.Parameterized):
    uid = param.String()

datasets = [Dataset(uid="1"), Dataset(uid="2")]

class State(param.Parameterized):
    value = param.Parameter()

state = State()

selector1 = pn.widgets.Select(options=datasets)
selector2 = pn.widgets.Select.from_param(state.param.value, options=datasets)

pn.Column(selector1, selector2).servable()
```

![image](https://github.com/holoviz/panel/assets/42288570/67b0dedc-c2f4-4407-a848-c0ea2011f446)

**Comment by MarcSkovMadsen** [comment]
## Consequence

A consequence is that I cannot change the `objects` on `state.param.value` because Panel tries to update the `options` of the `Row` because it thinks its a widget.

```python
import param
import panel as pn

pn.extension()

class Dataset(param.Parameterized):
    uid = param.String()

    def __str__(self):
        return self.uid

datasets = [Dataset(uid="1"), Dataset(uid="2")]

class State(param.Parameterized):
    value = param.Selector(objects=datasets)

state = State()

selector1 = pn.widgets.Select(options=datasets, name="Catalogue")
selector2 = pn.widgets.Select.from_param(state.param.value, name="Source")

state.param.value.objects = [Dataset(uid="3"), Dataset(uid="4")]

pn.Column(selector1, selector2).servable()
```

```bash
ValueError: 'options' is not a parameter of Row

Traceback (most recent call last):
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/bokeh/application/handlers/code_runner.py", line 229, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/mt-quant-frontend/script.py", line 22, in <module>
    state.param.value.objects = [Dataset(uid="3"), Dataset(uid="4")]
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1378, in __setattr__
    self._trigger_event(attribute, old, value)
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/param/parameterized.py", line 1384, in _trigger_event
    self.owner.param._call_watcher(watcher, event)
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2486, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/panel/param.py", line 605, in link
    widget.param.update(**updates)
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2282, in update
    restore = self_._update(*args, **kwargs)
  File "/home/jovyan/repos/mt-quant-frontend/.venv/lib/python3.10/site-packages/param/parameterized.py", line 2313, in _update
    raise ValueError(f"{k!r} is not a parameter of {self_.cls.__name__}")
ValueError: 'options' is not a parameter of Row
```

![image](https://github.com/holoviz/panel/assets/42288570/fe3b660f-9d07-461f-81a3-9d1bc11a246f)
