### ISSUE TITLE
RuntimeError in multiple panel apps launch: single document model violation

### ISSUE THREAD

**Issue by droumis** [holoviz/panel#6142]
#### ALL software version info

- Panel: 1.3.6
- HoloViews: 1.18.1
- Bokeh: 3.3.2
- playwright: 1.40.0
- pytest-playwright: 0.4.3

#### Description of expected behavior and the observed behavior
When launching multiple panel apps using Playwright, I received the following 500 error:

`RuntimeError: Models must be owned by only a single document, ImportedStyleSheet(id='p1164', ...) is already in a doc
500 GET`.

I don't see such an error from multiple Bokeh served apps.

#### Complete, minimal, self-contained example code that reproduces the issue

<details> <summary> MRE </summary>

```python
from __future__ import annotations
from functools import partial
from typing import Callable
from bokeh.document import Document
from bokeh.server.server import Server
from bokeh.plotting import column, figure
from bokeh.models import ColumnDataSource
from playwright.sync_api import sync_playwright
import numpy as np
import panel as pn
import holoviews as hv

# Minimal Panel/HoloViews app
def pnapp(doc: Document, n: int):
    x = np.linspace(0, 1, n)
    y = np.random.default_rng(8343).uniform(size=n)
    doc.add_root(pn.Column(hv.Curve((x, y))).get_root())

# Minimal Bokeh app
def bkapp(doc: Document, n: int):
    x = np.arange(n)
    y = np.random.default_rng(8343).uniform(size=n)
    cds = ColumnDataSource(data=dict(x=x, y=y))
    p = figure()
    p.line(source=cds, x="x", y="y")
    doc.add_root(column(p))

class PanelHoloviewsExampleBase:
    def __init__(self):
        self._port = 5008

    def setup(self, bokeh_doc: Callable[[Document], None]):
        self._playwright_context_manager = sync_playwright()
        self._playwright = self._playwright_context_manager.__enter__()

        self._server = Server({'/': bokeh_doc}, port=self._port)
        self._server.start()

        self._browser = self._playwright.chromium.launch(headless=False)
        self._page = self._browser.new_page()
        self._page.goto(f"http://localhost:{self._port}/")

    def teardown(self):
        self._page.wait_for_timeout(1000)
        self._server.stop()
        self._browser.close()
        self._playwright_context_manager.__exit__(None, None, None)

if __name__ == "__main__":
    ns = [100, 500]

    for app in [bkapp, pnapp]:
        for n in ns:
            benchmark = PanelHoloviewsExampleBase()
            benchmark.setup(partial(app, n=n))
            benchmark.teardown()
```

</details>

#### Stack traceback and/or browser JavaScript console output

<details> <summary> Traceback </summary>

```bash
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5009', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/panel/io/server.py", line 588, in get
    session = await self.get_session()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/panel/io/server.py", line 477, in get_session
    session = await super().get_session()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/server/contexts.py", line 240, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/application/application.py", line 190, in initialize_document
    h.modify_document(doc)
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/application/handlers/function.py", line 140, in modify_document
    self._func(doc)
  File "/Users/droumis/src/neuro/benchmarks/benchmarks/mvp.py", line 17, in pnapp
    doc.add_root(pn.Column(hv.Curve((x, y)).opts(width=400, height=400)).get_root())
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/document/document.py", line 321, in add_root
    with self.models.freeze():
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/document/models.py", line 135, in freeze
    self._pop_freeze()
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/document/models.py", line 288, in _pop_freeze
    self.recompute()
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/document/models.py", line 235, in recompute
    ma._attach_document(document)
  File "/Users/droumis/opt/miniconda3/envs/hvneuro_asv2/lib/python3.12/site-packages/bokeh/model/model.py", line 575, in _attach_document
    raise RuntimeError(f"Models must be owned by only a single document, {self!r} is already in a doc")
RuntimeError: Models must be owned by only a single document, ImportedStyleSheet(id='p1163', ...) is already in a doc
500 GET / (::1) 176.85ms
```

</details>

#### Screenshots or screencasts of the bug in action

The first two windows are pure Bokeh and work fine.
The second two windows are intended to be Panel+HoloViews - the first Panel+HoloViews plot works fine but the second errors.

https://github.com/holoviz/panel/assets/6613202/cf613ddf-15b2-4295-9926-63f10c649804

**Comment by philippjfr** [comment]
You will have to pass the document that you want the Panel component to be rendered into to the `get_root` method. This is because internally it will associate various models (such as the `ImportedStylesheets`) with the document and if you don't pass one in explicitly it will simply create one for you.
