### ISSUE TITLE
Pyodide blocks not working in docs - ReactiveExpr cannot be imported

### ISSUE THREAD

**Issue by droumis** [holoviz/panel#6164]
Confirmed in chrome and firefox, in all pages of the docs tested

<img width="1019" alt="image" src="https://github.com/holoviz/panel/assets/6613202/28d35959-ad5e-457c-a965-132b6971cbee">

Console:
```javascript
Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 571, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 394, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 11, in <module>
  File "/lib/python3.11/site-packages/panel/io/pyodide.py", line 560, in pyrender
    from ..pane import (
ImportError: cannot import name 'ReactiveExpr' from 'panel.pane' (/lib/python3.11/site-packages/panel/pane/__init__.py)

    at new_error (pyodide.asm.js:9:12519)
    at pyodide.asm.wasm:0x158827
    at pyodide.asm.wasm:0x15fcd5
    at _PyCFunctionWithKeywords_TrampolineCall (pyodide.asm.js:9:123052)
    at pyodide.asm.wasm:0x1a3091
    at pyodide.asm.wasm:0x289e4d
    at pyodide.asm.wasm:0x1e3f77
    at pyodide.asm.wasm:0x1a3579
    at pyodide.asm.wasm:0x1a383a
    at pyodide.asm.wasm:0x1a38dc
    at pyodide.asm.wasm:0x2685c5
    at pyodide.asm.wasm:0x26e3d0
    at pyodide.asm.wasm:0x1a3a04
    at pyodide.asm.wasm:0x1a3694
    at pyodide.asm.wasm:0x15f45e
    at Module.callPyObjectKwargs (pyodide.asm.js:9:81732)
    at Module.callPyObject (pyodide.asm.js:9:82066)
    at wrapper (pyodide.asm.js:9:58562)
```

**Comment by philippjfr** [comment]
Duplicate https://github.com/holoviz/panel/issues/6124
