### ISSUE TITLE
Enabling disconnect notification somehow breaks hv.save with bokeh backend

### ISSUE THREAD

**Issue by TheoMathurin** [holoviz/panel#6326]
#### ALL software version info
panel 1.3.8
bokeh 3.3.4
holoviews 1.18.2
selenium 4.17.2
selenium-manager 4.17.0
firefox 122.0.1
geckodriver 0.34.0
python 3.12

I work within an apptainer container using DockerHub's official Ubuntu base image

#### Description of expected behavior and the observed behavior
This one is very weird.

In my setup, enabling the disconnect notification option (very nice feature btw!) breaks `hv.save` with bokeh backend. I get an error in selenium regarding the viewport. I use firefox with geckodriver and I don't know if it occurs with another browser/driver pair.

It took me hours to identify the culprit as to me it had nothing to do with the whole saving workflow, but clearly I was wrong. However there may still be something else in my environment that allows this to happen.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
import holoviews as hv
import panel as pn

pn.extension(notifications=True, disconnect_notification=True)


def save(_):
    button.loading = True
    hv.save(hv.Curve([1, 2, 3]), 'curve.png')
    button.loading = False


button = pn.widgets.Button(name='Save', on_click=save)
button.servable()
```

#### Stack traceback and/or browser JavaScript console output
```
2024-02-08 18:24:00,603 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1006'}]]}}}]} 
 error: JavascriptException()
Traceback (most recent call last):
  File "/env/lib/python3.12/site-packages/bokeh/server/protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/env/lib/python3.12/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/env/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/env/lib/python3.12/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/env/lib/python3.12/site-packages/bokeh/document/events.py", line 245, in handle_event
    event_cls._handle_event(doc, event)
  File "/env/lib/python3.12/site-packages/bokeh/document/events.py", line 280, in _handle_event
    cb(event.msg_data)
  File "/env/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 390, in trigger_event
    model._trigger_event(event)
  File "/env/lib/python3.12/site-packages/bokeh/util/callback_manager.py", line 113, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/env/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 260, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/env/lib/python3.12/site-packages/bokeh/document/callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "/env/lib/python3.12/site-packages/bokeh/util/callback_manager.py", line 109, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/env/lib/python3.12/site-packages/panel/reactive.py", line 494, in _server_event
    self._comm_event(doc, event)
  File "/env/lib/python3.12/site-packages/panel/reactive.py", line 481, in _comm_event
    state._handle_exception(e)
  File "/env/lib/python3.12/site-packages/panel/io/state.py", line 442, in _handle_exception
    raise exception
  File "/env/lib/python3.12/site-packages/panel/reactive.py", line 479, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/env/lib/python3.12/site-packages/panel/reactive.py", line 416, in _process_bokeh_event
    self._process_event(event)
  File "/env/lib/python3.12/site-packages/panel/widgets/button.py", line 247, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/param/parameterized.py", line 525, in _f
    instance_param.__set__(obj, val)
  File "/env/lib/python3.12/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/param/parameters.py", line 542, in __set__
    super().__set__(obj,val)
  File "/env/lib/python3.12/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/param/parameterized.py", line 1545, in __set__
    obj.param._call_watcher(watcher, event)
  File "/env/lib/python3.12/site-packages/param/parameterized.py", line 2489, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/env/lib/python3.12/site-packages/param/parameterized.py", line 2471, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/app/toast.py", line 10, in save
    hv.save(hv.Curve([1, 2, 3]), 'curve.png')
  File "/env/lib/python3.12/site-packages/holoviews/util/__init__.py", line 807, in save
    return renderer_obj.save(obj, filename, fmt=fmt, resources=resources,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/holoviews/plotting/renderer.py", line 599, in save
    rendered = self_or_cls(plot, fmt)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/holoviews/plotting/renderer.py", line 199, in __call__
    data = self._figure_data(plot, fmt, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/holoviews/plotting/bokeh/renderer.py", line 125, in _figure_data
    img = get_screenshot_as_png(plot.state, driver=state.webdriver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/bokeh/io/export.py", line 278, in get_screenshot_as_png
    [width, height, dpr] = _maximize_viewport(web_driver)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/bokeh/io/export.py", line 454, in _maximize_viewport
    viewport_size: tuple[int, int, int] = web_driver.execute_script(calculate_viewport_size)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: root_view is undefined
Stacktrace:
@file:///app/bokehv1i2p1vz.html:3:33
@file:///app/bokehv1i2p1vz.html:6:8
```

**Comment by TheoMathurin** [comment]
Cannot reproduce it on panel 1.9.3, holoviews 1.23.1, bokeh 3.9.1
