### ISSUE TITLE
Panel.chat.ChatInterface does not work with python 3.12.2

### ISSUE THREAD

**Issue by ea42gh** [holoviz/panel#6461]
#### ALL software version info
upyter-lab: 4.1.2
python: 3.12.2
panel 1.3.8
holoviews 1.18.3
param 2.0.2

#### Description of expected behavior and the observed behavior
a call to ChatInterface() does not return, and/or kills the python kernel outright.

#### Complete, minimal, self-contained example code that reproduces the issue

```
async def repeat_contents(contents, user, instance):
    yield contents

chat_interface = pn.chat.ChatInterface(
    callback = repeat_contents, widgets=[pn.widgets.TextInput()]
)
```

#### Stack traceback and/or browser JavaScript console output
None

#### Screenshots or screencasts of the bug in action
screenshots and brief discussion can be found in
https://discourse.holoviz.org/t/chatinterface-pb-does-not-return-and-or-kernel-dies/6949

**Comment by ea42gh** [comment]
with python 3.11.8, I get
```
Traceback (most recent call last):
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\pyviz_comms\__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\viewable.py", line 478, in _on_msg
    doc.unhold()
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\bokeh\document\document.py", line 776, in unhold
    self.callbacks.unhold()
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\bokeh\document\callbacks.py", line 431, in unhold
    self.trigger_on_change(event)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\bokeh\document\callbacks.py", line 408, in trigger_on_change
    invoke_with_curdoc(doc, event.callback_invoker)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\bokeh\document\callbacks.py", line 443, in invoke_with_curdoc
    return f()
           ^^^
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\bokeh\util\callback_manager.py", line 185, in invoke
    callback(attr, old, new)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\reactive.py", line 471, in _comm_change
    state._handle_exception(e)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\io\state.py", line 442, in _handle_exception
    raise exception
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\reactive.py", line 469, in _comm_change
    self._schedule_change(doc, comm)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\reactive.py", line 451, in _schedule_change
    self._change_event(doc)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\reactive.py", line 447, in _change_event
    self._process_events(events)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\reactive.py", line 385, in _process_events
    self.param.update(**self_events)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\param\parameterized.py", line 2282, in update
    restore = self_._update(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\param\parameterized.py", line 2322, in _update
    self_._batch_call_watchers()
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\param\parameterized.py", line 2506, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\param\parameterized.py", line 2468, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\chat\interface.py", line 390, in _click_send
    self.send(value=value, user=self.user, avatar=self.avatar, respond=True)
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\chat\feed.py", line 533, in send
    message = self._build_message(value, user=user, avatar=avatar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\chat\feed.py", line 338, in _build_message
    message = ChatMessage(**message_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeff\AppData\Roaming\Python\Python311\site-packages\panel\chat\message.py", line 225, in __init__
    elif state.browser_info.timezone:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'timezone'
```

**Comment by ea42gh** [comment]
I did a force-reinstall of holoviews and panel.
python 3.11.8 now works

**Comment by ahuang11** [comment]
Simple example works for me:

<img width="1338" alt="image" src="https://github.com/holoviz/panel/assets/15331990/d6f98ca3-c2af-4d29-b4f9-44e6603862dd">

```python
import panel as pn
pn.extension()

def callback(contents: str, user: str, instance: pn.chat.ChatInterface):
    return f"Echo: {contents}"

chat = pn.chat.ChatInterface(callback=callback)
chat.servable()
```

**Comment by ea42gh** [comment]
Likely something wrong with my installation,
since force-reinstall of panel with python 3.11 did the trick.

I had however force reinstalled panel with python 3.12 as well. ???
