### ISSUE TITLE
SerializationError: circular reference

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6546]
panel==1.4.0rc4, bokeh==3.4.0

I'm trying to help `contango` in https://discourse.holoviz.org/t/odd-behavior-when-combining-pn-param-parammethod-and-pn-tabs-dynamic-true/6581/5.

I can reduce his issue to the problem that using the `Debugger` in a dynamic Tab raises `bokeh.core.serialization.SerializationError: circular reference`.

```python
import logging

import panel as pn

pn.extension("terminal")

debug_info = pn.widgets.Debugger(
    name="Log",
    level=logging.DEBUG,
    sizing_mode="stretch_both",
    logger_names=["panel.app"],
)

tabs = pn.Tabs(
    ("Tab 1", "Some Param object"),
    ("Tab 2", debug_info),
    dynamic=True,
)
tabs.servable()
```

If you activate second tab and back to first tab you get

```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/tornado/ioloop.py", line 738, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/tornado/ioloop.py", line 762, in _discard_future_result
    future.result()
  File "/opt/conda/lib/python3.11/site-packages/bokeh/server/session.py", line 98, in _needs_document_lock_wrapper
    result = await result
             ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 430, in _change_coroutine
    state._handle_exception(e)
  File "/opt/conda/lib/python3.11/site-packages/panel/io/state.py", line 458, in _handle_exception
    raise exception
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 428, in _change_coroutine
    self._change_event(doc)
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 446, in _change_event
    self._process_events(events)
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 384, in _process_events
    self.param.update(**self_events)
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2318, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2351, in _update
    self_._batch_call_watchers()
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2545, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2505, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/panel/layout/tabs.py", line 140, in _update_active
    self.param.trigger('objects')
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2473, in trigger
    self_.update(dict(params, **triggers))
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2318, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2351, in _update
    self_._batch_call_watchers()
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2545, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2505, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 373, in _param_change
    self._apply_update(named_events, properties, model, ref)
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 300, in _apply_update
    with unlocked():
  File "/opt/conda/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.11/site-packages/panel/io/document.py", line 437, in unlocked
    msgs[conn] = conn.protocol.create('PATCH-DOC', remaining_events)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/protocol/__init__.py", line 131, in create
    return self._messages[msgtype].create(*args, **kwargs)  # type: ignore [attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 90, in create
    patch_json = PatchJson(events=serializer.encode(events))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 278, in _encode
    return self._encode_list(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 326, in _encode_list
    return [self.encode(item) for item in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 326, in <listcomp>
    return [self.encode(item) for item in obj]
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 262, in _encode
    return obj.to_serializable(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/document/events.py", line 369, in to_serializable
    new   = serializer.encode(self.new),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 282, in _encode
    return self._encode_dict(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 343, in _encode_dict
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 343, in <listcomp>
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
                                ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 278, in _encode
    return self._encode_list(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 326, in _encode_list
    return [self.encode(item) for item in obj]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 326, in <listcomp>
    return [self.encode(item) for item in obj]
            ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 262, in _encode
    return obj.to_serializable(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/model/model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 282, in _encode
    return self._encode_dict(obj)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 343, in _encode_dict
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 343, in <listcomp>
    entries=[(self.encode(key), self.encode(val)) for key, val in obj.items()],
                                ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 253, in encode
    return self._encode(obj)
           ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 262, in _encode
    return obj.to_serializable(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/model/model.py", line 534, in to_serializable
    super_rep = super().to_serializable(serializer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/has_props.py", line 417, in to_serializable
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/has_props.py", line 417, in <dictcomp>
    attributes = {key: serializer.encode(val) for key, val in properties.items()}
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 249, in encode
    self.error("circular reference")
  File "/opt/conda/lib/python3.11/site-packages/bokeh/core/serialization.py", line 480, in error
    raise SerializationError(message)
bokeh.core.serialization.SerializationError: circular reference
```

**Comment by philippjfr** [comment]
Appears to be fixed.
