### ISSUE TITLE
Panel tutorial Issues

### ISSUE THREAD

**Issue by Azaya89** [holoviz/panel#6611]
I have created this Issue to highlight all the issues and observations from going through the [Basic Panel Tutorial](https://holoviz-dev.github.io/panel/tutorials/basic/index.html).

#### Name                    Version                   Build  Channel
bokeh                     3.4.0              pyhd8ed1ab_0    conda-forge
colorcet                  3.1.0              pyhd8ed1ab_0    conda-forge
holoviews                 1.18.3             pyhd8ed1ab_0    conda-forge
hvplot                    0.9.2              pyhd8ed1ab_0    conda-forge
notebook                  7.0.8           py311hca03da5_0
numpy                     1.26.4          py311h7125741_0    conda-forge
pandas                    2.2.1           py311hfbe21a1_0    conda-forge
panel                     1.4.0              pyhd8ed1ab_0    conda-forge
param                     2.1.0              pyhca7485f_0    conda-forge
python                    3.11.8          hdf0ec26_0_cpython    conda-forge

**Comment by Azaya89** [comment]
#### Description of expected behavior and the observed behavior
I'm not seeing the *jupyter panel preview* icon at the top of my jupyter notebook as stated in the tutorial here https://holoviz-dev.github.io/panel/tutorials/basic/develop_notebook.html#preview-example
![image](https://github.com/holoviz/panel/assets/99359668/261de40b-77c9-41a7-bb40-17f105f8b025)


#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/99359668/11429ece-5fb8-43c1-9473-a6dc6003e94a)

**Comment by Azaya89** [comment]
The [video](https://assets.holoviz.org/panel/tutorials/jupyter_panel_preview_in_action.mp4) in this screenshot doesn't play. I don't know if it's supposed to play or if it was meant as a screenshot.

![image](https://github.com/holoviz/panel/assets/99359668/c603653d-a83e-44a1-86ab-ffabd872bf0a)

**Comment by Azaya89** [comment]
I think [here](https://holoviz-dev.github.io/panel/tutorials/basic/develop_editor.html#inspect-via-print) we're printing the `layout` object and not the `component` object?

#### Screenshot
![image](https://github.com/holoviz/panel/assets/99359668/16a5837f-4bb5-47ef-b502-12c712fb94f4)

**Comment by Azaya89** [comment]
There is a bug [here](https://holoviz-dev.github.io/panel/reference/panes/Str.html#parameters) that does not render the output of the embedded pyodide cells correctly.

#### Screencast

https://github.com/holoviz/panel/assets/99359668/eff0466a-68d4-420c-b7ac-e67d3253e745

**Comment by MarcSkovMadsen** [comment]
Thanks for all the nice feedback

## Jupyter Panel Preview

You don't see it because you use classic notebook. Preview is only supported in Jupyter lab. I will add a note to the docs.

## Video Issue

The video does not work for me at holoviz-dev. It does work for me at panel.holoviz.org though.

https://github.com/holoviz/panel/assets/42288570/9a88293b-c7ab-410f-93d4-69a5e292cc8a

We have video issues and we do not understand them. For example the videos won't play on iphone. We  don't know how to solve currently.

## Printing Layout

I will update docs

## Bug in Str reference guide

I don't see the bug. I see that the value output in the first cell is a number. This is surprising if you have not seen it before. Its not what you would expect the code to output. But its this way because it a rendered notebook that is shown and later the output cell is updated to a number. I cannot do anything about it. Would need Philipp to generally change the way reference documentation is created.

**Comment by Azaya89** [comment]
Thank you for responding!

Although I'm still going through the tutorials and may highlight some more issues as I find them.

> ## Jupyter Panel Preview
> You don't see it because you use classic notebook. Preview is only supported in Jupyter lab. I will add a note to the docs.

OK. Thanks!
> 
> ## Video Issue
> The video does not work for me at holoviz-dev. It does work for me at panel.holoviz.org though.
>  video.mp4 
> Try out https://panel.holoviz.org/tutorials/basic/develop_notebook.html

It still didn't work for me at panel.holoviz.org as well.

> ## Bug in Str reference guide
> I don't see the bug. I see that the value output in the first cell is a number. This is surprising if you have not seen it before. Its not what you would expect the code to output. But its this way because it a rendered notebook that is shown and later the output cell is updated to a number. I cannot do anything about it. Would need Philipp to generally change the way reference documentation is created.

OK. I was a bit suprised actually, cos I expected the output of the cell to be displayed below what was run in the input, not elsewhere under another input cell.

> Its probably also out of scope for this issue as its not a tutorial.

Yes, however I was led there through a reference link from the tutorial.

**Comment by Azaya89** [comment]
I have noticed that while running `panel serve app.py --autoreload` in my terminal, the WebSocket connection closes by itself after some time if left dormant. On updating the code in my IDE, I have to refresh the web browser to display the updated output. Is this the expected behaviour, even after setting `autoreload`? 

#### Terminal display
```
2024-04-01 12:36:24,764 WebSocket connection closed: code=None, reason=None
2024-04-01 13:19:29,318 WebSocket connection opened
2024-04-01 13:19:29,319 ServerConnection created
```

**Comment by MarcSkovMadsen** [comment]
> I have noticed that while running `panel serve app.py --autoreload` in my terminal, the WebSocket connection closes by itself after some time if left dormant. On updating the code in my IDE, I have to refresh the web browser to display the updated output. Is this the expected behaviour, even after setting `autoreload`?
> 
> #### Terminal display
> ```
> 2024-04-01 12:36:24,764 WebSocket connection closed: code=None, reason=None
> 2024-04-01 13:19:29,318 WebSocket connection opened
> 2024-04-01 13:19:29,319 ServerConnection created
> ```

The websocket will close after some duration. I believe you can change the duration. Its not clear from what you write if your websocket closes "earlier" than the default duration. Or if you just see the web socket closing and opening again because you save the code?

**Comment by Azaya89** [comment]
> 
> The websocket will close after some duration. I believe you can change the duration. Its not clear from what you write if your websocket closes "earlier" than the default duration. Or if you just see the web socket closing and opening again because you save the code?
> 
> The Panel autoreload is not as robust as the streamlit one. Streamlits app with autoreload will always be connected for the entire default duration. Panel autoreload might end up with a blank page, and then you have to refresh. I've not had the energy to post an issue with a reproducible example yet. But it happens to me many times every time I develop and is a major source of friction because I have to leave my keyboard and editor to refresh the browser with a mouse click.

Thank you for your response. I wasn't aware that there was a default duration. I just have the same experience you have of it closing after some time and requiring me to refresh the browse with a mouse click. 

It's clear to me now that it's not an unexpected behaviour.

**Comment by MarcSkovMadsen** [comment]
In my team we setup a disconnect notification in all our apps. These is a huge user experience improvement.

```python
pn.config.disconnect_notification = DISCONNECT_NOTIFICATION
pn.config.notifications = True
```

**Comment by philippjfr** [comment]
> Panel autoreload might end up with a blank page, and then you have to refresh.

You're still seeing this? Please do open an issue, without a reproducer is fine.

**Comment by Azaya89** [comment]
> ```python
> pn.config.disconnect_notification = DISCONNECT_NOTIFICATION
> pn.config.notifications = True
> ```

How do I set this up for myself pls?

**Comment by MarcSkovMadsen** [comment]
> ```python
> pn.config.disconnect_notification = DISCONNECT_NOTIFICATION
> ```

See https://panel.holoviz.org/how_to/callbacks/notifications.html

**Comment by Azaya89** [comment]
I think there's an error with this code snippet [here](https://holoviz-dev.github.io/panel/tutorials/basic/pn_bind.html#harnessing-throttling-for-performance)

#### Code snippet
```
import panel as pn

from time import sleep

pn.extension()

def calculate_power(wind_speed, efficiency):
    power_generation = wind_speed * efficiency
    return (
        f"Wind Speed: {wind_speed} m/s, "
        f"Efficiency: {efficiency}, "
        f"Power Generation: {power_generation:.1f} kW"
    )

wind_speed = pn.widgets.FloatSlider(
    value=5, start=0, end=20, step=1, name="Wind Speed (m/s)"
)

efficiency = 0.3

calculate_power_bnd = pn.bind(
    calculate_power, wind_speed=wind_speed.param.value_throttled, efficiency=efficiency
)

power_md = pn.pane.Markdown(power)

pn.Column(wind_speed, power_md).servable()
```

#### Output
```
NameError: name 'power' is not defined

Traceback (most recent call last):
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/io/handlers.py", line 358, in run
    exec(self._code, module.__dict__)
  File "/Users/mac/Desktop/panel_tutorial/app.py", line 25, in <module>
    power_md = pn.pane.Markdown(power)
                                ^^^^^
NameError: name 'power' is not defined
```

The `value_throttled` parameter is also not defined as far as I can tell...

**Comment by Azaya89** [comment]
In [this section](https://holoviz-dev.github.io/panel/tutorials/basic/pn_bind.html#binding-to-bound-functions), I think there is some confusion about the function names used in the code. In the first code snippet shown below: 
```
import panel as pn

pn.extension()

def calculate_power(wind_speed, efficiency):
    return wind_speed * efficiency

def format_power_gen(wind_speed, efficiency, power):
    return (
        f"Wind Speed: {wind_speed} m/s, "
        f"Efficiency: {efficiency}, "
        f"Power Generation: {power:.1f} kW"
    )

wind_speed = pn.widgets.FloatSlider(
    value=5, start=0, end=20, step=1, name="Wind Speed (m/s)"
)

efficiency = 0.3

power = pn.bind(calculate_power, wind_speed, efficiency)

power_text = pn.bind(format_power_gen, wind_speed, efficiency, power)

pn.Column(wind_speed, power, power_text).servable()
```

The first function is called `calculate_power` but just after, the instruction said: "Try changing the `power_generation` function to:
```
def power_generation(wind_speed, efficiency):
    print(wind_speed, efficiency)
    return wind_speed * efficiency
```
" 
which I believe was referring to the same function. It was confusing for me to figure out which function is to be changed.

**Comment by Azaya89** [comment]
There's a small typo [here](https://holoviz-dev.github.io/panel/tutorials/basic/pn_rx.html#reactive-expressions)

![image](https://github.com/holoviz/panel/assets/99359668/2a3c6980-9698-477c-8e08-928791363005)

**Comment by Azaya89** [comment]
This part [here](https://holoviz-dev.github.io/panel/tutorials/basic/templates.html#crafting-a-hello-world-app) feels redundant since in order to follow the tutorial, there is an earlier instruction to serve the app.

![image](https://github.com/holoviz/panel/assets/99359668/7ba1b856-fcff-4bc9-a2f1-859203607b45)

**Comment by Azaya89** [comment]
It seems the code [here](https://holoviz-dev.github.io/panel/tutorials/basic/caching.html#exercise-implement-caching) is not running at all on the site.

I tried running it locally on VScode and it's showing an error on the webpage:

#### Code
```
from datetime import datetime
from time import sleep

import panel as pn

pn.extension()

@pn.cache
def get_data():
    print("loading data ...")
    sleep(2)
    return {"last_update": str(datetime.now())}


data = get_data()

pn.pane.JSON(data).servable()
```

#### Error message
```
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Traceback (most recent call last):
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/io/handlers.py", line 358, in run
    exec(self._code, module.__dict__)
  File "/Users/mac/Desktop/panel_tutorial/app.py", line 17, in <module>
    pn.pane.JSON(data).servable()
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/viewable.py", line 395, in servable
    self.server_doc(title=title, location=location) # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/viewable.py", line 1002, in server_doc
    model = self.get_root(doc)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/pane/base.py", line 422, in get_root
    root_view, root = self._get_root_model(doc, comm, preprocess)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/pane/base.py", line 348, in _get_root_model
    root = self._get_model(doc, comm=comm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/pane/base.py", line 497, in _get_model
    model = self._bokeh_model(**self._get_properties(doc))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/reactive.py", line 585, in _get_properties
    properties = self._process_param_change(params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/pane/markup.py", line 533, in _process_param_change
    params = super()._process_param_change(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/pane/base.py", line 520, in _process_param_change
    params.update(self._transform_object(params.pop('object')))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/panel/pane/markup.py", line 523, in _transform_object
    text = json.dumps(data or {}, cls=self.encoder)
                      ^^^^^^^^^^
  File "/Users/mac/anaconda3/envs/pn_tutorial/lib/python3.11/site-packages/pandas/core/generic.py", line 1576, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by Azaya89** [comment]
Unlike other 'Build a ...' in the tutorials, the code in [Build an image classifier](https://holoviz-dev.github.io/panel/tutorials/basic/build_image_classifier.html#build-an-image-classifier) was never explained. Is this intentional? If so, it seems like a departure from the format of the others.
