### ISSUE TITLE
Panel Output Doesn't Persist In VSCode

### ISSUE THREAD

**Issue by DmitriyLeybel** [holoviz/panel#6702]
#### ALL software version info
```
jupyter_bokeh == 4.0.1
panel == 1.4.1
vscode == 1.88.0
notebook == 7.1.2
bokeh == 3.4.0

VS Code Jupyter Extension: v2024.3.0
```
#### Description of expected behavior and the observed behavior
After running notebook cells and rendering outputs, saving the file, and then reopening the file, Panel widgets and panes disappear. 
This problem doesn't exist within JupyterLab, and there are no persistence options with Bokeh plots.

#### Complete, minimal, self-contained example code that reproduces the issue
```python
import panel as pn
pn.extension()
```
```python
slider_widget = pn.widgets.FloatSlider(start=0, end=10, step=0.1, value=5, name='Slider')
slider_widget
```
```python
data = {
    "name": "John",
    "age": 30,
    "city": "New York"
}

pn.pane.JSON(data)
```

#### Stack traceback and/or browser JavaScript console output -- dev tools console log
```console
log.ts:419  INFO Started local extension host with pid 12216.
12An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
log.ts:429  WARN [mainThreadStorage] large extension state detected (extensionId: sourcegraph.cody-ai, global: true): 1654.4462890625kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.
log.ts:439   ERR Unable to read file 'c:\Users\dmley\AppData\Roaming\Code\logs\20240409T190026\window1\exthost\output_logging_20240409T190027\2-Jupyter.log' (Error: Unable to resolve nonexistent file 'c:\Users\dmley\AppData\Roaming\Code\logs\20240409T190026\window1\exthost\output_logging_20240409T190027\2-Jupyter.log'): Error: Unable to read file 'c:\Users\dmley\AppData\Roaming\Code\logs\20240409T190026\window1\exthost\output_logging_20240409T190027\2-Jupyter.log' (Error: Unable to resolve nonexistent file 'c:\Users\dmley\AppData\Roaming\Code\logs\20240409T190026\window1\exthost\output_logging_20240409T190027\2-Jupyter.log')
    at n.F (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:657:19968)
    at n.D (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:657:19763)
    at async n.C (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:657:19075)
    at async s.O (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1674:45861)
    at async vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1674:45058
console.ts:137 [Extension Host] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\dmley\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\package.nls.en-us.json'
	at C.e (c:\Users\dmley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:6084)
	at Object.readFile (c:\Users\dmley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4463)
	at async _0x9c8500 (c:\Users\dmley\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:204376)
	at async _0x4bfbb1 (c:\Users\dmley\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:203953)
	at async _0x1785d4 (c:\Users\dmley\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:313198)
	at async _0x15825a (c:\Users\dmley\.vscode\extensions\ms-python.vscode-pylance-2024.4.1\dist\extension.bundle.js:1:243047)
	at async o.n (c:\Users\dmley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:6237)
	at async o.m (c:\Users\dmley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:6200)
	at async o.l (c:\Users\dmley\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:142:5657)
log.ts:419  INFO [perf] Render performance baseline is 13ms
log.ts:429  WARN [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
log.ts:439   ERR Cannot read properties of null (reading 'domNode'): TypeError: Cannot read properties of null (reading 'domNode')
    at T.bb (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:16348)
    at T.Y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:14707)
    at T.Y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1105:50585)
    at T.updateElementHeight (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:10813)
    at f.updateElementHeight2 (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1660:50863)
    at Ee (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2700:22800)
    at Oe.layoutNotebookCell (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2700:23007)
    at u.value (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2700:11241)
    at f.y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at f.z (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:729)
    at f.fire (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:945)
    at f.fire (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:2074)
    at u.tb (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:50846)
    at u.layoutChange (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:50756)
    at set editorHeight [as editorHeight] (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:45148)
    at new f (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2564:111221)
    at m.j (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:650:1241)
    at m.createInstance (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:650:733)
    at K.renderElement (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2564:126066)
    at Q.renderElement (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:239:2141)
    at T.Z (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:15746)
    at T.U (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:12582)
    at T.splice (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:11055)
    at vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4:8585
    at Array.forEach (<anonymous>)
    at t.splice (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4:8572)
    at vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:239:7943
    at L.bufferEvents (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:3585)
    at f.splice (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:239:7919)
    at f.splice2 (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1660:41731)
    at vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1660:40486
    at Array.forEach (<anonymous>)
    at f.lb (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1660:40255)
    at u.value (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1660:39641)
    at n.y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at n.z (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:729)
    at n.fire (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:945)
    at V (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:73951)
    at u.value (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1693:74610)
    at n.y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at n.z (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:729)
    at n.fire (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:945)
    at u.value (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:19918)
    at s.y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at s.fire (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:876)
    at s.resume (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:1945)
    at u.applyEdits (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:23438)
    at h (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:2208)
    at n.runWithContext (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2564:71331)
    at n.run (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1658:47660)
    at handler (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:683:20756)
    at m.invokeFunction (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:650:326)
    at S.n (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1602:23141)
    at S.executeCommand (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1602:22729)
    at q.M (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:654:14157)
    at q.J (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:654:11833)
    at vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2237:54996
log.ts:439   ERR TreeError [BreadcrumbsOutlinePicker] Tree element not found: [object Object]: Error: TreeError [BreadcrumbsOutlinePicker] Tree element not found: [object Object]
    at T.o (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:192:29689)
    at T.expandTo (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:192:29100)
    at Y.reveal (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:626:2341)
    at z.r (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:26780)
    at z.show (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:22079)
    at Object.getAnchor (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:33840)
    at a.t (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:153:10439)
    at a.show (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:153:10220)
    at w.showContextView (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:654:23791)
    at x.E (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1896:32866)
    at n.y (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:659)
    at n.fire (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:876)
    at v.z (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:1289)
    at v.C (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:196:2433)
    at vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:192:56893
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/c:/Users/dmley/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:152:30139)
notebookWebviewPreloads.js:3 '_allOutputItems' is proposed API. DO NOT ship an extension that depends on it!
get _allOutputItems @ notebookWebviewPreloads.js:3
```

### Demo of widgets working along with VS Code Jupyter output log
![image](https://github.com/holoviz/panel/assets/6779278/bf825984-6685-45dd-8e21-431ba10d2233)

### Right after saving and reloading
![image](https://github.com/holoviz/panel/assets/6779278/69a69d95-4316-4e70-9367-ab07864f6ca4)

### VS Code Jupyter Log
```
21:00:47.401 [info] Restart requested ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:00:47.401 [info] Dispose Kernel process 39804.
21:00:47.404 [info] Process Execution: c:\WINDOWS\System32\taskkill.exe /F /T /PID 39804
21:00:47.436 [warn] Failed to get activated env vars for ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe in 31ms
21:00:47.448 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
21:00:47.460 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-12216I2CZOb4gdjKo.json
    > cwd: ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks
21:00:47.460 [info] Kernel process 35896.
21:00:48.083 [info] Restarted 4d5a8650-35b6-41d7-a6d0-3ef7f4851999
21:00:56.276 [info] Handle Execution of Cells 0 for ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:00:56.288 [info] Kernel acknowledged execution of cell 0 @ 1712721656288
21:00:56.977 [info] End cell 0 execution after 0.689s, completed @ 1712721656977, started @ 1712721656288
21:00:58.297 [info] Handle Execution of Cells 1 for ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:00:58.306 [info] Kernel acknowledged execution of cell 1 @ 1712721658306
21:00:58.314 [info] End cell 1 execution after 0.008s, completed @ 1712721658314, started @ 1712721658306
21:00:59.044 [info] Handle Execution of Cells 2 for ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:00:59.060 [info] Kernel acknowledged execution of cell 2 @ 1712721659060
21:00:59.066 [info] End cell 2 execution after 0.006s, completed @ 1712721659066, started @ 1712721659060
21:03:30.324 [info] Disposing request as the cell (0) was deleted ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:03:30.324 [info] Disposing request as the cell (0) was deleted ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:03:30.324 [info] Disposing request as the cell (1) was deleted ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:03:30.324 [info] Disposing request as the cell (1) was deleted ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:03:30.324 [info] Disposing request as the cell (2) was deleted ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:03:30.324 [info] Disposing request as the cell (2) was deleted ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb
21:03:30.324 [info] Dispose Kernel '~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb' associated with '~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb'
21:03:30.325 [info] Dispose Kernel process 35896.
21:03:30.327 [info] Process Execution: c:\WINDOWS\System32\taskkill.exe /F /T /PID 35896
21:03:34.309 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0b3216738bb8c385b7be77ab68fa791c859df305d064b88b1257e550e18285ac7.~\AppData\Local\Microsoft\WindowsApps\python3.12.exe.~\AppData\Local\Microsoft\WindowsApps\python3.12.exe.-m#ipykernel_launcher  (Python Path: ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe, Unknown, 3.12.2) for '~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks\musique_eda.ipynb' (disableUI=true)
21:03:34.341 [warn] Failed to get activated env vars for ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe in 31ms
21:03:34.353 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe -m pip list
21:03:34.353 [warn] Failed to get activated env vars for ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe in 41ms
21:03:34.364 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
21:03:34.379 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.12.exe -m ipykernel_launcher --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-12216QSZHceQ8N2ar.json
    > cwd: ~\OneDrive\Desktop\Sites\dmitriyleybel.github.io\notebooks
21:03:34.379 [info] Kernel process 15432.
21:03:35.063 [info] Registering Kernel Completion Provider from kernel Python 3.12.2 for language python
```

**Comment by BerginJay** [comment]
I got the same issue here, any suggestions?

**Comment by philippjfr** [comment]
I'm not an expert in VSCode, does this work for other `ipywidget` components? That's what's used to render Panel components inside VSCode so if it works for them we might be able to get it working too.

**Comment by DmitriyLeybel** [comment]
> I'm not an expert in VSCode, does this work for other `ipywidget` components? That's what's used to render Panel components inside VSCode so if it works for them we might be able to get it working too.

Ah, you're right, same problem with `ipywidget` components. Darn.

![image](https://github.com/holoviz/panel/assets/6779278/fd8b1f07-1bc8-4b29-90f3-ad20029e6693)

After saving and reopening:
![image](https://github.com/holoviz/panel/assets/6779278/0a2b58ea-bf41-4844-97ab-9da738096c3e)
