### ISSUE TITLE
500 internal server error with Panel 1.4.3

### ISSUE THREAD

**Issue by monodera** [holoviz/panel#6864]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
Panel 1.4.3
Python 3.11.9
Bokeh 3.4.1
Tornado 6.4
OS: AlmaLinux 8.9
nginx/1.14.1

#### Complete, minimal, self-contained example code that reproduces the issue

`test_app_servable.py`:

```
import panel as pn

pn.extension()

file_input = pn.widgets.FileInput()

pn.Column(file_input).servable()
```

Run it with the following command:

```
panel serve ./test_app_servable.py \
    --port 10080 \
    --allow-websocket-origin="example.com" \
    --use-xheaders \
    --prefix="test_app" \
    --websocket-max-message-size=104857600
```

#### Stack traceback and/or browser JavaScript console output

```
$ bash ./run_test_app_servable.bash
2024-05-24 00:51:42,369 Starting Bokeh server version 3.4.1 (running on Tornado 6.4)
2024-05-24 00:51:42,370 Torndado websocket_max_message_size set to 104857600 bytes (100.00 MB)
2024-05-24 00:51:42,370 User authentication hooks NOT provided (default user enabled)
2024-05-24 00:51:42,372 Bokeh app running at: http://localhost:10080/test_app/test_app_servable
2024-05-24 00:51:42,372 Starting Bokeh server with process id: 232069
2024-05-24 00:52:09,224 Uncaught exception GET /test_app/test_app_servable (ip_address)
HTTPServerRequest(protocol='https', host='example.com:443', method='GET', uri='/test_app/test_app_servable', version='HTTP/1.1', remote_ip='ip_address')
Traceback (most recent call last):
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/panel/io/server.py", line 508, in get
    payload = self._generate_token_payload()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/panel/io/server.py", line 452, in _generate_token_payload
    payload.update(self.application_context.application.process_request(self.request))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/panel/io/application.py", line 103, in process_request
    user = decode_signed_value(config.cookie_secret, 'user', user.value).decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/tornado/web.py", line 3589, in decode_signed_value
    return _decode_signed_value_v2(secret, name, value, max_age_days, clock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/tornado/web.py", line 3674, in _decode_signed_value_v2
    expected_sig = _create_signature_v2(secret, signed_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/monodera/test/test_app/.venv/lib/python3.11/site-packages/tornado/web.py", line 3710, in _create_signature_v2
    hash = hmac.new(utf8(secret), digestmod=hashlib.sha256)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monodera/.pyenv/versions/3.11.9/lib/python3.11/hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/monodera/.pyenv/versions/3.11.9/lib/python3.11/hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
2024-05-24 00:52:09,226 500 GET /test_app/test_app_servable (ip_address) 2.43ms
```

The browser displays "500: Internal Server Error". This error does not happen `Panel<1.4.3`.

- [x] I may be interested in making a pull request to address this, but so far I have no idea where to look at.

**Comment by monodera** [comment]
I should have added that the app is behind nginx reverse proxy. Anyway, this issue does not happen till 1.4.2.  If you need more information, I'm happy to provide them.

**Comment by monodera** [comment]
I tried again today and I couldn't reproduce the issue. I'll close it as not planned. Sorry for confusion. If it happens again, I'll report it.
