### ISSUE TITLE
panel 1.4.3 regression: `KeyError: 'content'` in jupyterlab

### ISSUE THREAD

**Issue by pmav99** [holoviz/panel#6871]
### ALL software version info
- python 3.11
- jupyterlab 4.2.1
- A virtualenv with the following packages:

<details>
<summary><b>requirements.txt</b></summary>

```
anyio==4.4.0 ; python_version >= "3.11" and python_version < "4.0"
appnope==0.1.4 ; python_version >= "3.11" and python_version < "4.0" and platform_system == "Darwin"
argon2-cffi-bindings==21.2.0 ; python_version >= "3.11" and python_version < "4.0"
argon2-cffi==23.1.0 ; python_version >= "3.11" and python_version < "4.0"
arrow==1.3.0 ; python_version >= "3.11" and python_version < "4.0"
asttokens==2.4.1 ; python_version >= "3.11" and python_version < "4.0"
async-lru==2.0.4 ; python_version >= "3.11" and python_version < "4.0"
attrs==23.2.0 ; python_version >= "3.11" and python_version < "4.0"
babel==2.15.0 ; python_version >= "3.11" and python_version < "4.0"
beautifulsoup4==4.12.3 ; python_version >= "3.11" and python_version < "4.0"
bleach==6.1.0 ; python_version >= "3.11" and python_version < "4.0"
bokeh==3.4.1 ; python_version >= "3.11" and python_version < "4.0"
certifi==2024.2.2 ; python_version >= "3.11" and python_version < "4.0"
cffi==1.16.0 ; python_version >= "3.11" and python_version < "4.0"
charset-normalizer==3.3.2 ; python_version >= "3.11" and python_version < "4.0"
colorama==0.4.6 ; python_version >= "3.11" and python_version < "4.0" and (sys_platform == "win32" or platform_system == "Windows")
comm==0.2.2 ; python_version >= "3.11" and python_version < "4.0"
contourpy==1.2.1 ; python_version >= "3.11" and python_version < "4.0"
debugpy==1.8.1 ; python_version >= "3.11" and python_version < "4.0"
decorator==5.1.1 ; python_version >= "3.11" and python_version < "4.0"
defusedxml==0.7.1 ; python_version >= "3.11" and python_version < "4.0"
executing==2.0.1 ; python_version >= "3.11" and python_version < "4.0"
fastjsonschema==2.19.1 ; python_version >= "3.11" and python_version < "4.0"
fqdn==1.5.1 ; python_version >= "3.11" and python_version < "4"
h11==0.14.0 ; python_version >= "3.11" and python_version < "4.0"
httpcore==1.0.5 ; python_version >= "3.11" and python_version < "4.0"
httpx==0.27.0 ; python_version >= "3.11" and python_version < "4.0"
idna==3.7 ; python_version >= "3.11" and python_version < "4.0"
ipykernel==6.29.4 ; python_version >= "3.11" and python_version < "4.0"
ipython==8.24.0 ; python_version >= "3.11" and python_version < "4.0"
isoduration==20.11.0 ; python_version >= "3.11" and python_version < "4.0"
jedi==0.19.1 ; python_version >= "3.11" and python_version < "4.0"
jinja2==3.1.4 ; python_version >= "3.11" and python_version < "4.0"
json5==0.9.25 ; python_version >= "3.11" and python_version < "4.0"
jsonpointer==2.4 ; python_version >= "3.11" and python_version < "4.0"
jsonschema-specifications==2023.12.1 ; python_version >= "3.11" and python_version < "4.0"
jsonschema==4.22.0 ; python_version >= "3.11" and python_version < "4.0"
jsonschema[format-nongpl]==4.22.0 ; python_version >= "3.11" and python_version < "4.0"
jupyter-client==8.6.2 ; python_version >= "3.11" and python_version < "4.0"
jupyter-core==5.7.2 ; python_version >= "3.11" and python_version < "4.0"
jupyter-events==0.10.0 ; python_version >= "3.11" and python_version < "4.0"
jupyter-lsp==2.2.5 ; python_version >= "3.11" and python_version < "4.0"
jupyter-server-terminals==0.5.3 ; python_version >= "3.11" and python_version < "4.0"
jupyter-server==2.14.0 ; python_version >= "3.11" and python_version < "4.0"
jupyterlab-pygments==0.3.0 ; python_version >= "3.11" and python_version < "4.0"
jupyterlab-server==2.27.2 ; python_version >= "3.11" and python_version < "4.0"
jupyterlab==4.2.1 ; python_version >= "3.11" and python_version < "4.0"
linkify-it-py==2.0.3 ; python_version >= "3.11" and python_version < "4.0"
markdown-it-py==3.0.0 ; python_version >= "3.11" and python_version < "4.0"
markdown==3.6 ; python_version >= "3.11" and python_version < "4.0"
markupsafe==2.1.5 ; python_version >= "3.11" and python_version < "4.0"
matplotlib-inline==0.1.7 ; python_version >= "3.11" and python_version < "4.0"
mdit-py-plugins==0.4.1 ; python_version >= "3.11" and python_version < "4.0"
mdurl==0.1.2 ; python_version >= "3.11" and python_version < "4.0"
mistune==3.0.2 ; python_version >= "3.11" and python_version < "4.0"
nbclient==0.10.0 ; python_version >= "3.11" and python_version < "4.0"
nbconvert==7.16.4 ; python_version >= "3.11" and python_version < "4.0"
nbformat==5.10.4 ; python_version >= "3.11" and python_version < "4.0"
nest-asyncio==1.6.0 ; python_version >= "3.11" and python_version < "4.0"
notebook-shim==0.2.4 ; python_version >= "3.11" and python_version < "4.0"
numpy==1.26.4 ; python_version >= "3.11" and python_version < "4.0"
overrides==7.7.0 ; python_version >= "3.11" and python_version < "4.0"
packaging==24.0 ; python_version >= "3.11" and python_version < "4.0"
pandas==2.2.2 ; python_version >= "3.11" and python_version < "4.0"
pandocfilters==1.5.1 ; python_version >= "3.11" and python_version < "4.0"
panel==1.4.3 ; python_version >= "3.11" and python_version < "4.0"
param==2.1.0 ; python_version >= "3.11" and python_version < "4.0"
parso==0.8.4 ; python_version >= "3.11" and python_version < "4.0"
pexpect==4.9.0 ; python_version >= "3.11" and python_version < "4.0" and (sys_platform != "win32" and sys_platform != "emscripten")
pillow==10.3.0 ; python_version >= "3.11" and python_version < "4.0"
platformdirs==4.2.2 ; python_version >= "3.11" and python_version < "4.0"
prometheus-client==0.20.0 ; python_version >= "3.11" and python_version < "4.0"
prompt-toolkit==3.0.45 ; python_version >= "3.11" and python_version < "4.0"
psutil==5.9.8 ; python_version >= "3.11" and python_version < "4.0"
ptyprocess==0.7.0 ; python_version >= "3.11" and python_version < "4.0" and (sys_platform != "win32" and sys_platform != "emscripten" or os_name != "nt")
pure-eval==0.2.2 ; python_version >= "3.11" and python_version < "4.0"
pycparser==2.22 ; python_version >= "3.11" and python_version < "4.0"
pygments==2.18.0 ; python_version >= "3.11" and python_version < "4.0"
python-dateutil==2.9.0.post0 ; python_version >= "3.11" and python_version < "4.0"
python-json-logger==2.0.7 ; python_version >= "3.11" and python_version < "4.0"
pytz==2024.1 ; python_version >= "3.11" and python_version < "4.0"
pyviz-comms==3.0.2 ; python_version >= "3.11" and python_version < "4.0"
pywin32==306 ; sys_platform == "win32" and platform_python_implementation != "PyPy" and python_version >= "3.11" and python_version < "4.0"
pywinpty==2.0.13 ; python_version >= "3.11" and python_version < "4.0" and os_name == "nt"
pyyaml==6.0.1 ; python_version >= "3.11" and python_version < "4.0"
pyzmq==26.0.3 ; python_version >= "3.11" and python_version < "4.0"
referencing==0.35.1 ; python_version >= "3.11" and python_version < "4.0"
requests==2.32.2 ; python_version >= "3.11" and python_version < "4.0"
rfc3339-validator==0.1.4 ; python_version >= "3.11" and python_version < "4.0"
rfc3986-validator==0.1.1 ; python_version >= "3.11" and python_version < "4.0"
rpds-py==0.18.1 ; python_version >= "3.11" and python_version < "4.0"
send2trash==1.8.3 ; python_version >= "3.11" and python_version < "4.0"
six==1.16.0 ; python_version >= "3.11" and python_version < "4.0"
sniffio==1.3.1 ; python_version >= "3.11" and python_version < "4.0"
soupsieve==2.5 ; python_version >= "3.11" and python_version < "4.0"
stack-data==0.6.3 ; python_version >= "3.11" and python_version < "4.0"
terminado==0.18.1 ; python_version >= "3.11" and python_version < "4.0"
tinycss2==1.3.0 ; python_version >= "3.11" and python_version < "4.0"
tornado==6.4 ; python_version >= "3.11" and python_version < "4.0"
tqdm==4.66.4 ; python_version >= "3.11" and python_version < "4.0"
traitlets==5.14.3 ; python_version >= "3.11" and python_version < "4.0"
types-python-dateutil==2.9.0.20240316 ; python_version >= "3.11" and python_version < "4.0"
typing-extensions==4.12.0 ; python_version >= "3.11" and python_version < "4.0"
tzdata==2024.1 ; python_version >= "3.11" and python_version < "4.0"
uc-micro-py==1.0.3 ; python_version >= "3.11" and python_version < "4.0"
uri-template==1.3.0 ; python_version >= "3.11" and python_version < "4.0"
urllib3==2.2.1 ; python_version >= "3.11" and python_version < "4.0"
wcwidth==0.2.13 ; python_version >= "3.11" and python_version < "4.0"
webcolors==1.13 ; python_version >= "3.11" and python_version < "4.0"
webencodings==0.5.1 ; python_version >= "3.11" and python_version < "4.0"
websocket-client==1.8.0 ; python_version >= "3.11" and python_version < "4.0"
xyzservices==2024.4.0 ; python_version >= "3.11" and python_version < "4.0"
```
</details>

### Description of expected behavior and the observed behavior

Executing something as simple as `pn.Column()` throws a traceback

#### Complete, minimal, self-contained example code that reproduces the issue

launch jupyterlab. Create a **new** notebook and paste the following code:
```
import panel

panel.extension()
panel.Column()
```

#### Stack traceback and/or browser JavaScript console output
```
Traceback (most recent call last):
  File "/tmp/asdf/.venv/lib/python3.11/site-packages/pyviz_comms/__init__.py", line 340, in _handle_msg
    self._on_msg(msg)
  File "/tmp/asdf/.venv/lib/python3.11/site-packages/panel/viewable.py", line 469, in _on_msg
    patch = manager.assemble(msg)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/asdf/.venv/lib/python3.11/site-packages/panel/models/comm_manager.py", line 29, in assemble
    msg_obj = cls(header, msg['metadata'], msg['content'])
                                           ~~~^^^^^^^^^^^
KeyError: 'content'
```

#### Screenshots or screencasts of the bug in action

![image](https://github.com/holoviz/panel/assets/411196/c465fe7b-637a-47c6-8c22-c5aec27f2dc4)

https://github.com/holoviz/panel/assets/411196/412c1f49-dda3-4f0b-bacc-0743c3d88970

- [x] I may be interested in making a pull request to address this

**Comment by pmav99** [comment]
This is screenshot with panel 1.4.2 (which seems to behave normally)

https://github.com/holoviz/panel/assets/411196/d0dd7222-1e1c-4080-bc7f-7c64c0a78d08

**Comment by ahuang11** [comment]
Thanks for reporting. I believe this is a duplicate of https://github.com/holoviz/panel/issues/6865

**Comment by pmav99** [comment]
Yeah, it is the same. Closing
