### ISSUE TITLE
ReactiveHTML components cannot have a String param initialized on creation

### ISSUE THREAD

**Issue by jerry-kobold** [holoviz/panel#6897]
There appears to be a bug in `ReactiveHTML` which makes it impossible to initialize string parameters with values passed into the constructor.

#### ALL software version info
`panel==1.4.4`

#### Description of expected behavior and the observed behavior

When `ReactiveHTML` is subclassed and a `param.String` is defined on the derived class, attempting to initialize that class with a value for that param results in the following error (trace truncated):

```
  File "/Users/jerry/Library/Caches/pypoetry/virtualenvs/panel-ui-extensions-BV4D3BUD-py3.12/lib/python3.12/site-packages/param/parameterized.py", line 1647, in _validate
    self._validate_value(val, self.allow_None)
  File "/Users/jerry/Library/Caches/pypoetry/virtualenvs/panel-ui-extensions-BV4D3BUD-py3.12/lib/python3.12/site-packages/param/parameterized.py", line 1641, in _validate_value
    raise ValueError(
ValueError: String parameter 'ReactiveHTMLMetaclass.text' only takes a string value, not value of <class 'panel.pane.markup.Markdown'>.
```

#### Complete, minimal, self-contained example code that reproduces the issue

The error may be reproduced using the following custom component code taken directly from the Panel website (imports added):

```python
import panel as pn
import param
from panel.reactive import ReactiveHTML


class CustomComponent(ReactiveHTML):
    """I'm a custom component"""

    text = param.String("I'm **bold**")
    color = param.Color("silver", label="Select a color", doc="""The color of the component""")

    _template = """
<p style="background:{{ color }}">Jinja literal value. {{ text }}</p>
<p id="el" style="background:${color}">Javascript template variable. ${text}</p>
"""


main = pn.Column()
component = CustomComponent(text="hello world")
main.append(component)
template = pn.template.BootstrapTemplate(main=main)
template.servable()
```

I would expect the custom component to be displayed, but instead the above error is thrown in the `__init__` method of `ReactiveHTML`.

#### Stack traceback and/or browser JavaScript console output

```
2024-06-06 20:45:22,332 Error running application handler <panel.io.handlers.ScriptHandler object at 0x12c2af520>: String parameter 'ReactiveHTMLMetaclass.text' only takes a string value, not value of <class 'panel.pane.markup.Markdown'>.
File 'parameterized.py', line 1634, in _validate_value:
raise ValueError( Traceback (most recent call last):
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/io/handlers.py", line 389, in run
    exec(self._code, module.__dict__)
  File "/Users/jerry/Development/machine-prospector/scratch/reactive_test.py", line 19, in <module>
    component = CustomComponent(text='hello world')
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/reactive.py", line 1615, in __init__
    super().__init__(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/reactive.py", line 560, in __init__
    super().__init__(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/reactive.py", line 120, in __init__
    super().__init__(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/viewable.py", line 700, in __init__
    super().__init__(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/viewable.py", line 539, in __init__
    super().__init__(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/panel/viewable.py", line 300, in __init__
    super().__init__(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 4148, in __init__
    refs, deps = self.param._setup_params(**params)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 1678, in override_initialization
    ret = fn(self_, *args, **kw)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 1971, in _setup_params
    setattr(self, name, resolved)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 527, in _f
    return f(self, obj, val)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 1490, in __set__
    self._validate(val)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 1640, in _validate
    self._validate_value(val, self.allow_None)
  File "/Users/jerry/Development/machine-prospector/venv/lib/python3.10/site-packages/param/parameterized.py", line 1634, in _validate_value
    raise ValueError(
ValueError: String parameter 'ReactiveHTMLMetaclass.text' only takes a string value, not value of <class 'panel.pane.markup.Markdown'>.
```

The direct cause of the bug appears to be the line 1614 in `panel/reactive.py`:

```
params[children_param] = panel(child_value)
```

During `__init__` this line is hit when an external value is passed to the constructor, but not otherwise. If this happens, the `child_value` (in my above example the text `"hello world"`) is turned into a `Markdown` pane, which throws a subsequent validation error as the pane is not a string. 

- [X] I may be interested in making a pull request to address this

Happy to take a swing at fixing this with some guidance about how not to break anything else and in particular, why `self._parser.children` is not populated when a default is supplied but is populated when an external value is passed in.

**Comment by jerry-kobold** [comment]
I should also add that the following works just fine:

```python
component = CustomComponent()
component.text = "hello world"
main.append(component)
template = pn.template.BootstrapTemplate(main=main)
template.servable()
```

The component is displayed as expected and the value of the text is indeed `hello world`

**Comment by jerry-kobold** [comment]
Further note: this bug appears to be triggered because `${text}` is a bound reactive parameter in the template. If I remove `${text}` entirely or change that to `{{text}}`, there is no problem. My understanding is that this is because the template is parsed to find the bidirectionally linked parameters, right?
