### ISSUE TITLE
TypeError: key: expected bytes or bytearray, but got 'NoneType'

### ISSUE THREAD

**Issue by hengaini2055** [holoviz/panel#6944]
#### ALL software version info
OS: windows11
python env: conda
python version: 3.10.11
Pip list
```
Package                                  Version           Editable project location
---------------------------------------- ----------------- -----------------------------------------------------------
absl-py                                  2.0.0
accelerate                               0.21.0
adbc-driver-manager                      0.7.0
adbc-driver-postgresql                   0.7.0
affine                                   2.4.0
agate                                    1.7.0
aiobotocore                              2.12.1
aiofiles                                 23.2.1
aiohttp                                  3.9.1
aiohttp-cors                             0.7.0
aioitertools                             0.11.0
aiosignal                                1.3.1
aiosqlite                                0.19.0
alabaster                                0.7.16
alembic                                  1.13.1
aliyun-python-sdk-core                   2.14.0
aliyun-python-sdk-kms                    2.16.2
altair                                   5.1.2
amqp                                     5.2.0
aniso8601                                9.0.1
annotated-types                          0.6.0
ansicon                                  1.89.0
antlr4-python3-runtime                   4.9.3
anyio                                    3.7.1
apache-airflow-providers-celery          3.5.1
apache-airflow-providers-common-io       1.2.0
apache-airflow-providers-common-sql      1.10.0
apache-airflow-providers-ftp             3.7.0
apache-airflow-providers-http            4.8.0
apache-airflow-providers-imap            3.5.0
apache-airflow-providers-sqlite          3.7.0
apache-superset                          3.1.1
apispec                                  6.4.0
appdirs                                  1.4.4
apprise                                  1.7.2
apsw                                     3.45.1.0
argcomplete                              3.2.1
argon2-cffi                              21.3.0
argon2-cffi-bindings                     21.2.0
arrow                                    1.2.3
asciitree                                0.3.3
asgi-lifespan                            2.1.0
asgiref                                  3.7.2
asttokens                                2.2.1
astunparse                               1.6.3
async-lru                                2.0.2
async-timeout                            4.0.3
asyncer                                  0.0.7
asyncio                                  3.4.3
asyncpg                                  0.29.0
atpublic                                 3.1.2
attrs                                    23.2.0
autogluon                                1.1.1
autogluon.common                         1.1.1
autogluon.core                           1.1.1
autogluon.features                       1.1.1
autogluon.multimodal                     1.1.1
autogluon.tabular                        1.1.1
autogluon.timeseries                     1.1.1
Babel                                    2.14.0
backcall                                 0.2.0
backoff                                  2.2.1
bcrypt                                   4.0.1
beautifulsoup4                           4.12.2
behave                                   1.2.6
bidict                                   0.22.1
billiard                                 4.2.0
binaryornot                              0.4.4
bleach                                   6.0.0
blessed                                  1.20.0
blinker                                  1.7.0
blis                                     0.7.11
blosc2                                   2.6.1
bloxs                                    1.0.2
bokeh                                    3.4.2
boto3                                    1.34.127
botocore                                 1.34.127
Bottleneck                               1.3.8
branca                                   0.7.0
Brotli                                   1.1.0
build                                    1.0.3
cachelib                                 0.9.0
cachetools                               5.3.1
Cartopy                                  0.20.2
catalogue                                2.0.10
catboost                                 1.2.2
cattrs                                   23.2.3
celery                                   5.3.6
certifi                                  2023.11.17
cffi                                     1.16.0
cfgv                                     3.4.0
cftime                                   1.6.3
chardet                                  5.2.0
charset-normalizer                       3.3.2
click                                    8.1.7
click-didyoumean                         0.3.0
click-option-group                       0.5.6
click-plugins                            1.1.1
click-repl                               0.3.0
clickclick                               20.10.2
cligj                                    0.7.2
cloudpathlib                             0.15.1
cloudpickle                              2.2.1
colorama                                 0.4.6
colorbrewer                              0.2.0
colorcet                                 3.0.1
coloredlogs                              14.0
colorful                                 0.5.5
colorlog                                 4.8.0
colour                                   0.1.5
comm                                     0.1.3
confection                               0.1.3
ConfigArgParse                           1.7
ConfigUpdater                            3.2
connectorx                               0.3.2
connexion                                2.14.2
contextily                               1.6.0
contourpy                                1.2.1
convertdate                              2.4.0
cookiecutter                             2.5.0
coolname                                 2.2.0
coverage                                 7.4.1
cramjam                                  2.6.2
crcmod                                   1.7
cron-descriptor                          1.4.0
croniter                                 2.0.1
cryptography                             41.0.7
cycler                                   0.11.0
cymem                                    2.0.8
Cython                                   0.29.36
dacite                                   1.8.1
dagster-cloud-cli                        1.3.14
dask                                     2023.7.0
dataclasses-json                         0.5.14
datasets                                 2.20.0
datashader                               0.15.1
datashape                                0.5.2
dateparser                               1.2.0
dbt-extractor                            0.4.1
debugpy                                  1.6.7
decorator                                5.1.1
defusedxml                               0.7.1
delta-spark                              2.4.0
deltalake                                0.10.0
Deprecated                               1.2.14
deprecation                              2.1.0
dill                                     0.3.8
diskcache                                5.6.3
distlib                                  0.3.7
dnspython                                2.4.2
docker                                   6.1.3
docopt                                   0.6.2
docstring-parser                         0.15
docutils                                 0.20.1
duckdb                                   0.9.2
duckdb-engine                            0.9.0
dynaconf                                 3.2.4
email-validator                          1.3.1
entrypoints                              0.4
et-xmlfile                               1.1.0
evaluate                                 0.4.2
exceptiongroup                           1.2.0
execnet                                  2.0.2
executing                                1.2.0
fastai                                   2.7.15
fastapi                                  0.100.1
fastcore                                 1.5.29
fastdownload                             0.0.7
fasteners                                0.19
fastjsonschema                           2.17.1
fastparquet                              2023.7.0
fastprogress                             1.0.3
filelock                                 3.12.2
fiona                                    1.9.6
fitparse                                 1.2.0
Flask                                    2.2.5
Flask-AppBuilder                         4.4.1
Flask-Babel                              2.0.0
Flask-BasicAuth                          0.2.0
Flask-Caching                            2.1.0
Flask-Compress                           1.14
Flask-Cors                               4.0.0
Flask-JWT-Extended                       4.6.0
Flask-Limiter                            3.5.0
Flask-Login                              0.6.3
Flask-Migrate                            3.1.0
Flask-Session                            0.5.0
Flask-SQLAlchemy                         2.5.1
flask-talisman                           1.1.0
Flask-WTF                                1.2.1
flatbuffers                              23.5.26
flower                                   2.0.1
folium                                   0.15.1
fonttools                                4.40.0
fqdn                                     1.5.1
frozendict                               2.3.10
frozenlist                               1.4.1
fsspec                                   2023.12.2
func-timeout                             4.3.5
fused                                    1.5.3
future                                   0.18.3
gast                                     0.5.4
gdown                                    4.7.1
geographiclib                            2.0
geopandas                                0.12.2
geopy                                    2.4.1
gevent                                   23.9.1
geventhttpclient                         2.0.11
ghp-import                               2.1.0
gitdb                                    4.0.11
gitdb2                                   4.0.2
gitdir                                   1.2.7
github3.py                               4.0.1
GitPython                                3.0.6
gluonts                                  0.15.1
google-api-core                          2.12.0
google-auth                              2.23.4
google-auth-oauthlib                     1.0.0
google-cloud                             0.34.0
google-cloud-bigquery                    3.13.0
google-cloud-core                        2.3.3
google-cloud-storage                     2.13.0
google-crc32c                            1.5.0
google-pasta                             0.2.0
google-re2                               1.1
google-resumable-media                   2.6.0
googleapis-common-protos                 1.62.0
gpustat                                  1.1.1
gql                                      3.4.1
graphene                                 3.2.2
graphql-core                             3.2.3
graphql-relay                            3.2.0
graphviz                                 0.20.1
greenlet                                 3.0.3
griffe                                   0.40.0
grimp                                    3.2
grpcio                                   1.60.0
grpcio-health-checking                   1.56.0
grpcio-status                            1.59.3
gunicorn                                 21.2.0
h11                                      0.14.0
h2                                       4.1.0
h5netcdf                                 1.3.0
h5py                                     3.10.0
hashids                                  1.3.1
hdfs                                     2.7.3
hijri-converter                          2.3.1
holidays                                 0.25
hologram                                 0.0.16
holoviews                                1.18.1
hpack                                    4.0.0
html5lib                                 1.1
htmlmin                                  0.1.12
httpcore                                 0.16.3
httptools                                0.6.0
httpx                                    0.23.3
huggingface-hub                          0.23.4
humanfriendly                            10.0
humanize                                 4.9.0
hvplot                                   0.8.4
hyperframe                               6.0.1
hyperopt                                 0.2.7
ibis                                     3.3.0
ibis-framework                           7.2.0
ibis-substrait                           2.29.1
identify                                 2.5.35
idna                                     3.6
igraph                                   0.11.4
ImageHash                                4.3.1
imageio                                  2.31.1
imagesize                                1.4.1
import-linter                            2.0
importlib-metadata                       6.11.0
importlib-resources                      5.13.0
inflection                               0.5.1
iniconfig                                2.0.0
intake                                   0.7.0
intake-parquet                           0.3.0
intel-openmp                             2021.4.0
ipykernel                                6.23.3
ipylab                                   1.0.0
ipysheet                                 0.7.0
ipython                                  8.14.0
ipyvue                                   1.10.1
ipyvuetify                               1.8.10
ipywidgets                               8.0.6
isodate                                  0.6.1
isoduration                              20.11.0
itsdangerous                             2.1.2
jedi                                     0.18.2
Jinja2                                   3.1.3
jinxed                                   1.2.0
jmespath                                 0.10.0
joblib                                   1.3.1
json5                                    0.9.14
jsonpatch                                1.33
jsonpointer                              2.4
jsonschema                               4.20.0
jsonschema-specifications                2023.12.1
jupyter                                  1.0.0
jupyter-bokeh                            3.0.7
jupyter_client                           8.3.0
jupyter-console                          6.6.3
jupyter_core                             5.3.1
jupyter-events                           0.6.3
jupyter-lsp                              2.2.0
jupyter-resource-usage                   1.0.0
jupyter_server                           2.7.0
jupyter_server_terminals                 0.4.4
jupyterlab                               4.0.11
jupyterlab-pygments                      0.2.2
jupyterlab_server                        2.23.0
jupyterlab-widgets                       3.0.7
kedro                                    0.19.3
kedro-datasets                           2.1.0
kedro-viz                                8.0.1
keras                                    2.15.0
kiwisolver                               1.4.4
kombu                                    5.3.5
korean-lunar-calendar                    0.3.1
kubernetes                               29.0.0
langchain                                0.0.278
langcodes                                3.3.0
langsmith                                0.0.31
lazy_loader                              0.3
lazy-object-proxy                        1.10.0
leather                                  0.3.4
libclang                                 16.0.6
lightgbm                                 3.3.5
lightning                                2.3.0
lightning-utilities                      0.9.0
limits                                   3.7.0
linkify-it-py                            2.0.2
llvmlite                                 0.40.1
local-structure                          0.1.0             e:\hengainilearning\panel\materials-python-import\structure
locket                                   1.0.0
lockfile                                 0.12.2
locust                                   2.20.1
Logbook                                  1.5.3
loguru                                   0.6.0
lumen                                    0.5.1
lxml                                     4.9.3
Mako                                     1.3.0
Markdown                                 3.5.2
markdown-it-py                           3.0.0
MarkupSafe                               2.1.3
marshmallow                              3.20.2
marshmallow-oneofschema                  3.0.1
marshmallow-sqlalchemy                   0.26.1
mashumaro                                3.6
matplotlib                               3.7.2
matplotlib-inline                        0.1.6
mdit-py-plugins                          0.4.0
mdurl                                    0.1.2
mercantile                               1.2.1
mergedeep                                1.3.4
minimal-snowplow-tracker                 0.0.2
mistune                                  0.8.2
mizani                                   0.9.3
mkdocs                                   1.5.3
mkdocs-exclude-search                    0.6.6
mkdocs-open-in-new-tab                   1.0.3
mkl                                      2021.4.0
ml-dtypes                                0.2.0
mlforecast                               0.10.0
model-index                              0.1.11
more-itertools                           10.2.0
mpmath                                   1.3.0
msgpack                                  1.0.5
multidict                                6.0.4
multimethod                              1.10
multipledispatch                         0.6.0
multiprocess                             0.70.16
multitasking                             0.0.11
murmurhash                               1.0.10
mypy                                     1.9.0
mypy-extensions                          1.0.0
myst-parser                              2.0.0
nb2xls                                   0.1.6
nbclient                                 0.5.13
nbconvert                                6.4.5
nbformat                                 5.9.0
ndindex                                  1.8
nest-asyncio                             1.5.6
netCDF4                                  1.6.5
networkit                                10.1
networkx                                 3.2.1
nh3                                      0.2.14
nlpaug                                   1.1.11
nltk                                     3.8.1
nodeenv                                  1.8.0
notebook                                 7.0.6
notebook_shim                            0.2.3
nptyping                                 2.4.1
numba                                    0.57.1
numcodecs                                0.12.1
numexpr                                  2.8.5
numpy                                    1.24.4
nvidia-ml-py                             12.535.108
nvidia-ml-py3                            7.352.0
oauthlib                                 3.2.2
omegaconf                                2.2.3
onnx                                     1.16.1
onnxruntime                              1.18.0
opencensus                               0.11.3
opencensus-context                       0.1.3
opendatalab                              0.0.10
openmim                                  0.3.9
openpyxl                                 3.1.2
opentelemetry-api                        1.22.0
opentelemetry-exporter-otlp              1.22.0
opentelemetry-exporter-otlp-proto-common 1.22.0
opentelemetry-exporter-otlp-proto-grpc   1.22.0
opentelemetry-exporter-otlp-proto-http   1.22.0
opentelemetry-proto                      1.22.0
opentelemetry-sdk                        1.22.0
opentelemetry-semantic-conventions       0.43b0
openxlab                                 0.0.11
opt-einsum                               3.3.0
optimum                                  1.18.1
ordered-set                              4.1.0
orjson                                   3.9.12
oss2                                     2.17.0
outcome                                  1.3.0.post0
overrides                                7.3.1
packaging                                23.2
pandas                                   2.0.3
pandas-stubs                             2.2.0.240218
pandoc                                   2.3
pandocfilters                            1.5.0
panel                                    1.4.4
panel-chemistry                          0.2.2
param                                    2.1.1
paramiko                                 3.3.1
parse                                    1.20.1
parse-type                               0.6.2
parsedatetime                            2.4
parso                                    0.8.3
parsy                                    2.1
partd                                    1.4.0
pathspec                                 0.12.1
pathy                                    0.10.2
patsy                                    0.5.3
pdf2image                                1.17.0
peewee                                   3.17.0
pendulum                                 3.0.0
pex                                      2.1.138
pgsanity                                 0.2.9
phik                                     0.12.3
pickleshare                              0.7.5
pillow                                   10.3.0
pins                                     0.8.4
pip                                      24.1
pipenv                                   2023.7.23
platformdirs                             4.2.0
plotly                                   5.15.0
plotnine                                 0.12.4
pluggy                                   1.3.0
plumbum                                  1.8.2
ply                                      3.11
polars                                   0.19.2
polyline                                 2.0.1
pooch                                    1.7.0
pre-commit                               3.6.2
pre-commit-hooks                         4.5.0
preshed                                  3.0.9
prettytable                              3.9.0
prison                                   0.2.1
prometheus-client                        0.19.0
prompt-toolkit                           3.0.43
proto-plus                               1.22.3
protobuf                                 4.25.2
psutil                                   5.9.7
psycopg2                                 2.9.7
psycopg2-binary                          2.9.6
pure-eval                                0.2.2
py                                       1.11.0
py-cpuinfo                               9.0.0
py-spy                                   0.3.14
py3Dmol                                  2.0.4
py4cytoscape                             1.9.0
py4j                                     0.10.9.7
pyarrow                                  16.1.0
pyarrow-hotfix                           0.5
pyasn1                                   0.5.0
pyasn1-modules                           0.3.0
pycparser                                2.21
pycryptodome                             3.19.0
pyct                                     0.5.0
pydantic                                 1.10.15
pydantic_core                            2.14.6
pydeck                                   0.8.0
pyecharts                                2.0.4
pyee                                     11.0.1
Pygments                                 2.17.2
PyJWT                                    2.8.0
pymdown-extensions                       10.3.1
PyMeeus                                  0.5.12
Pympler                                  1.0.1
pymssql                                  2.2.10
PyNaCl                                   1.5.0
pyodbc                                   5.0.1
pyparsing                                3.0.9
pyperclip                                1.8.2
pypng                                    0.20220715.0
pyproj                                   3.6.0
pyproject_hooks                          1.0.0
pyproject-toml                           0.0.10
PyQt6                                    6.6.1
PyQt6-Qt6                                6.6.3
PyQt6-sip                                13.6.0
pyreadline3                              3.4.1
pyrsistent                               0.19.3
pyshp                                    2.3.1
PySocks                                  1.7.1
pyspark                                  3.4.1
pystac                                   1.10.0
pytesseract                              0.3.10
pytest                                   7.4.0
pytest-asyncio                           0.23.3
pytest-base-url                          2.0.0
pytest-benchmark                         4.0.0
pytest-cov                               3.0.0
pytest-forked                            1.6.0
pytest-mock                              1.13.0
pytest-xdist                             2.2.1
python-daemon                            3.0.1
python-dateutil                          2.8.2
python-dotenv                            1.0.0
python-geohash                           0.8.5
python-json-logger                       2.0.7
python-nvd3                              0.15.0
python-slugify                           8.0.1
pytimeparse                              1.1.8
pytoolconfig                             1.3.1
pytorch-lightning                        2.3.0
pytorch-metric-learning                  1.7.3
pytz                                     2023.3.post1
pytzdata                                 2020.1
pyvista                                  0.41.1
pyviz-comms                              2.3.2
PyWavelets                               1.4.1
pywin32                                  306
pywinpty                                 2.0.10
PyYAML                                   6.0.1
pyyaml_env_tag                           0.1
pyzmq                                    25.1.0
qtconsole                                5.5.1
QtPy                                     2.4.1
questionary                              1.10.0
rasterio                                 1.3.7
ray                                      2.10.0
reacton                                  1.7.2
readchar                                 4.0.5
redis                                    4.6.0
referencing                              0.32.1
regex                                    2023.8.8
requests                                 2.32.3
requests-cache                           1.2.0
requests-futures                         1.0.1
requests-oauthlib                        1.3.1
requests-toolbelt                        1.0.0
responses                                0.18.0
rfc3339-validator                        0.1.4
rfc3986                                  1.5.0
rfc3986-validator                        0.1.1
rich                                     13.7.0
rich-argparse                            1.4.0
rich-click                               1.7.2
rio-stac                                 0.8.1
rioxarray                                0.14.1
rope                                     1.12.0
roundrobin                               0.0.4
rpds-py                                  0.17.1
rsa                                      4.9
rtoml                                    0.9.0
ruamel.yaml                              0.18.5
ruamel.yaml.clib                         0.2.8
ruff                                     0.1.15
s3fs                                     2024.2.0
s3transfer                               0.10.1
safetensors                              0.4.3
scikit-image                             0.19.3
scikit-learn                             1.4.0
scipy                                    1.12.0
scooby                                   0.7.2
seaborn                                  0.12.2
secure                                   0.3.0
selenium                                 4.9.1
semver                                   3.0.2
Send2Trash                               1.8.2
sentence-transformers                    2.2.2
sentencepiece                            0.1.99
seqeval                                  1.2.2
setproctitle                             1.3.3
setuptools                               69.0.3
shapely                                  2.0.3
shellingham                              1.5.0.post1
shillelagh                               1.2.17
shortid                                  0.1.2
simplejson                               3.19.2
six                                      1.16.0
sklearn                                  0.0.post7
slack-sdk                                3.26.0
smart-open                               6.4.0
smmap                                    5.0.1
sniffio                                  1.3.0
snowballstemmer                          2.2.0
snuggs                                   1.4.7
solara                                   1.22.0
sortedcontainers                         2.4.0
soupsieve                                2.4.1
spacy                                    3.7.1
spacy-legacy                             3.0.12
spacy-loggers                            1.0.5
spatial                                  0.2.0
Sphinx                                   7.2.6
sphinx_autodoc_typehints                 1.20.2
sphinx-copybutton                        0.5.2
sphinx-favicon                           1.0.1
sphinx-last-updated-by-git               0.3.6
sphinx-notfound-page                     1.0.0
sphinx-rtd-theme                         2.0.0
sphinxcontrib-applehelp                  1.0.8
sphinxcontrib-devhelp                    1.0.6
sphinxcontrib-htmlhelp                   2.0.5
sphinxcontrib-jquery                     4.1
sphinxcontrib-jsmath                     1.0.1
sphinxcontrib-qthelp                     1.0.7
sphinxcontrib-serializinghtml            1.1.10
sphinxcontrib-youtube                    1.4.1
SQLAlchemy                               1.4.51
SQLAlchemy-JSONField                     1.0.2
SQLAlchemy-Utils                         0.38.3
sqlalchemy-views                         0.3.2
sqlglot                                  20.11.0
sqlparse                                 0.4.4
srsly                                    2.4.8
sshtunnel                                0.4.0
stac_geoparquet                          0.2.1
stack-data                               0.6.2
starlette                                0.27.0
statsforecast                            1.4.0
statsmodels                              0.14.0
strawberry-graphql                       0.219.1
streamz                                  0.6.4
substrait                                0.2.1
sympy                                    1.12
tables                                   3.9.2
tabulate                                 0.8.10
tangled-up-in-unicode                    0.2.0
tbb                                      2021.12.0
tenacity                                 8.2.3
tensorboard                              2.17.0
tensorboard-data-server                  0.7.1
tensorboardX                             2.6.2.2
tensorflow-estimator                     2.15.0
tensorflow-io-gcs-filesystem             0.31.0
termcolor                                2.4.0
terminado                                0.17.1
testpath                                 0.6.0
text-unidecode                           1.3
texttable                                1.7.0
textual                                  0.41.0
textual-fastdatatable                    0.4.0
textual-textarea                         0.7.3
thinc                                    8.2.1
threadpoolctl                            3.2.0
tifffile                                 2023.7.18
tiktoken                                 0.4.0
time-machine                             2.13.0
timm                                     0.9.7
tinycss2                                 1.2.1
tokenizers                               0.15.2
toml                                     0.10.2
tomli                                    2.0.1
toolz                                    0.12.0
toposort                                 1.10
torch                                    2.3.1+cu121
torchmetrics                             1.2.1
torchvision                              0.18.1
tornado                                  6.4
tqdm                                     4.66.4
traitlets                                5.9.0
transformers                             4.39.3
trio                                     0.23.1
trio-websocket                           0.11.1
truffleHog                               2.2.1
truffleHogRegexes                        0.0.7
typeguard                                4.1.5
typer                                    0.9.0
types-cachetools                         5.3.0.7
types-pytz                               2024.1.0.20240203
types-PyYAML                             6.0.12.12
types-toml                               0.10.8.20240310
types-toposort                           1.10.0.1
typing_extensions                        4.9.0
typing-inspect                           0.9.0
tzdata                                   2023.4
tzlocal                                  5.2
uc-micro-py                              1.0.2
ujson                                    5.8.0
unicodecsv                               0.14.1
universal-pathlib                        0.1.4
uri-template                             1.3.0
uritemplate                              4.1.1
url-normalize                            1.4.3
urllib3                                  2.0.7
urlpath                                  1.2.0
utilsforecast                            0.0.10
uvicorn                                  0.27.1
vega-datasets                            0.9.0
vine                                     5.1.0
virtualenv                               20.25.0
virtualenv-clone                         0.5.7
visions                                  0.7.5
ViTables                                 3.0.3
vowpalwabbit                             9.4.0
vtk                                      9.2.6
waitress                                 2.1.2
wasabi                                   1.1.2
watchdog                                 3.0.0
watchfiles                               0.19.0
watchgod                                 0.8.2
wcwidth                                  0.2.13
weasel                                   0.3.2
webcolors                                1.13
webencodings                             0.5.1
websocket-client                         1.6.1
websockets                               11.0.3
Werkzeug                                 2.3.8
wheel                                    0.38.4
widgetsnbextension                       4.0.7
win32-setctime                           1.1.0
window-ops                               0.0.14
wordcloud                                1.9.3
wrapt                                    1.16.0
wsproto                                  1.2.0
WTForms                                  3.1.2
WTForms-JSON                             0.3.5
xarray                                   2023.6.0
xgboost                                  2.0.3
xlrd                                     2.0.1
XlsxWriter                               3.0.9
xxhash                                   3.2.0
xyzservices                              2023.5.0
yahooquery                               2.3.7
yarl                                     1.9.4
yfinance                                 0.2.33
zarr                                     2.17.2
zict                                     3.0.0
zipp                                     3.17.0
zope.event                               5.0
zope.interface                           6.1
```
#### Description of expected behavior and the observed behavior
All is ok before I pip install geoviews. After this installation, I remove two directories according prompt: ~anel and ~anel-1.3.6.dist-info from conda install directory.
When I run any panel app, get the same error as follows:
```
PS C:\Users\henga\powershell\xgboost22> panel serve app.py --autoreload
2024-06-28 05:03:27,389 W-1005 (FIXED_SIZING_MODE): 'fixed' sizing mode requires width and height to be set: Column(id='p1031', ...)
2024-06-28 05:03:27,518 Starting Bokeh server version 3.4.2 (running on Tornado 6.4)
2024-06-28 05:03:27,521 User authentication hooks NOT provided (default user enabled)
2024-06-28 05:03:27,526 Bokeh app running at: http://localhost:5006/app
2024-06-28 05:03:27,527 Starting Bokeh server with process id: 42752
2024-06-28 05:03:27,558 Uncaught exception GET /app (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/app', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\tornado\web.py", line 1790, in _execute
    result = await result
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\panel\io\server.py", line 508, in get
    payload = self._generate_token_payload()
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\panel\io\server.py", line 452, in _generate_token_payload
    payload.update(self.application_context.application.process_request(self.request))
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\panel\io\application.py", line 103, in process_request
    user = decode_signed_value(config.cookie_secret, 'user', user.value).decode('utf-8')
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\tornado\web.py", line 3589, in decode_signed_value
    return _decode_signed_value_v2(secret, name, value, max_age_days, clock)
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\tornado\web.py", line 3674, in _decode_signed_value_v2
    expected_sig = _create_signature_v2(secret, signed_string)
  File "D:\Program Files\condamini\envs\panel110\lib\site-packages\tornado\web.py", line 3710, in _create_signature_v2
    hash = hmac.new(utf8(secret), digestmod=hashlib.sha256)
  File "D:\Program Files\condamini\envs\panel110\lib\hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
  File "D:\Program Files\condamini\envs\panel110\lib\hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
2024-06-28 05:03:27,568 500 GET /app (127.0.0.1) 11.00ms
```
Now, I have uninstalled the library geoviews.

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by hengaini2055** [comment]
@ahuang11 the story comes from [your app](https://huggingface.co/spaces/ahuang11/year-vs-climatology/blob/main/app.py). When I installed geoviews, everything is wrong.

**Comment by hengaini2055** [comment]
#6864 maybe a similar issue, but I cannot find the reason.

**Comment by philippjfr** [comment]
Already fixed in https://github.com/holoviz/panel/commit/497370dc4e711460abd1d6063872d58f95007ad1

Will consider whether to backport to a 1.4.5 release or wait for 1.5.0.

**Comment by hengaini2055** [comment]
thanks your reply!
