### ISSUE TITLE
Can't use the "terminal" extension with `inline` enabled

### ISSUE THREAD

**Issue by dennisjlee** [holoviz/panel#7086]
#### ALL software version info

Computer: Mac OSX 14.5, M3 Max
Python: 3.10.14
Browser: Chrome 127.0.6533.89 arm64

Libraries:
panel 1.4.5
bokeh 3.4.2
jupyterlab 4.2.4
jupyterlab_widgets 3.0.11
notebook 7.2.1

#### Description of expected behavior and the observed behavior

Expected: should be able to load the Panel / Holoviz frontend libraries with the `"terminal"` extension enabled.

Observed: when `pn.config.inline` is true, the `<script>` tag emitted by `pn.extension("terminal")`  is invalid and causes a syntax error, which prevents Panel from working.

#### Complete, minimal, self-contained example code that reproduces the issue

In a Jupyter notebook:
```
import panel as pn

pn.config.inline = True
pn.extension("terminal")
```

```
pn.widgets.Terminal("Hello world").servable()
```

#### Stack traceback and/or browser JavaScript console output

JS console errors:

```
VM7887:1259 Uncaught SyntaxError: Invalid or unexpected token
    at w.attachWidget (911.bundle.js:1:18414)
    at w.insertWidget (911.bundle.js:1:17908)
    at x._insertOutput (7226.bundle.js:1:10481)
    at x.onModelChanged (7226.bundle.js:1:6952)
    at a (409.bundle.js:1:2625)
    at e.emit (409.bundle.js:1:2354)
    at o.emit (409.bundle.js:1:334)
    at d._onListChanged (7226.bundle.js:1:2896)
    at a (409.bundle.js:1:2625)
    at e.emit (409.bundle.js:1:2354)

Panel: ERROR: Unable to run Panel code because Bokeh or Panel library is missing
```

#### Screenshots or screencasts of the bug in action

<img width="1326" alt="image" src="https://github.com/user-attachments/assets/0679b29f-d341-4f39-885b-c8bcc2350791">

I found the script tag on the page in the outputs from the first cell, and evaluated its textContent - sure enough, there was a SyntaxError. It's not trivial to find where it is though since it's so large - I've tried a few tools and have not found an obvious issue yet.

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/6d10b3e5-8fa5-481b-9f3f-f06c875750f3">

- [ X ] I may be interested in making a pull request to address this

**Comment by dennisjlee** [comment]
I think I've isolated the bug: 

This is the contents of the script tag that Panel is generating
[simplified_panelBug.js.txt](https://github.com/user-attachments/files/16515998/simplified_panelBug.js.txt)

In the function starting at line 1258 (a minified version of xterm.js), there are line breaks in the middle of a double-quoted string at the end of a few lines.

The original version from jsdelivr is here: https://cdn.jsdelivr.net/npm/xterm@4.14.1/lib/xterm.js

The symbols that are broken (FS, GS, RS, NEL) all contain escape characters in the original xterm.js source code, so I think something is broken in the way that xterm.js is minified and included in Panel's inline bundle 

<img width="270" alt="image" src="https://github.com/user-attachments/assets/fdf3197e-da90-488b-b2cb-70bfb5503765">
