### ISSUE TITLE
Clifford example fails due to incorrect float slider

### ISSUE THREAD

**Issue by jlstevens** [holoviz/panel#714]
Running the `clifford_interact.ipynb` notebook in a new environment with latest numba, datashader and panel allows the `n` parameter to have float values:

![image](https://user-images.githubusercontent.com/890576/67042968-97224900-f0ee-11e9-81f5-577e46042d2e.png)

Which with numba 0.45.1 results in errors that break the dashboard:

<details>
<pre>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/panel/viewable.py", line 678, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/param/parameterized.py", line 1219, in inner
    return fn(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/param/parameterized.py", line 2573, in set_param
    return self_or_cls.param.set_param(*args,**kwargs)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/param/parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/param/parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/panel/interact.py", line 181, in update_pane
    new_object = self.object(**self.kwargs)
  File "/home/ubuntu/panel-examples/gallery/simple/clifford_interact.ipynb", line 37, in clifford_plot
    "    xs[0], ys[0] = x0, y0\n",
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/numba/dispatcher.py", line 376, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/numba/dispatcher.py", line 343, in error_rewrite
    reraise(type(e), e, None)
  File "/home/ubuntu/miniconda/envs/monitoring/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function zeros>) with argument(s) of type(s): (float64)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function zeros>)
[2] During: typing of call at /home/ubuntu/panel-examples/gallery/simple/clifford_interact.ipynb (26)

File "clifford_interact.ipynb", line 26:
    "This example demonstrates how to use the ``pn.interact`` function to trigger updates in an image of a Clifford [attractor](https://en.wikipedia.org/wiki/Attractor) generated using the [Datashader](https://datashader.org) library."
   ]
   ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
</pre>
</details>

**Comment by philippjfr** [comment]
Can't reproduce anymore.
