### ISSUE TITLE
AttributeError: 'function' object has no attribute 'owner'

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7203]
I'm trying to help a user in https://discourse.holoviz.org/t/facilitating-support-for-language-localization-in-panel/7576 add language support to the Select widget.

I can get the example working with `pn.bind` function (see discourse). But I cannot get it working with `@pn.depends` function because `AttributeError: 'function' object has no attribute 'owner'` is raised.

To me that is quite surprising as I believe they are both "references"?

```python
import panel as pn

pn.extension()

LANGUAGES = ["en-US", "fr-FR", "de-DE", "es-ES"]

OPTIONS = ["For", "Against"]

TRANSLATIONS = {
    "Mode:": {"en-US": "Mode:", "fr-FR": "Mode :", "de-DE": "Modus:", "es-ES": "Modo:"},
    "For": {"en-US": "For", "fr-FR": "Pour", "de-DE": "Für", "es-ES": "Para"},
    "Against": {"en-US": "Against", "fr-FR": "Contre", "de-DE": "Gegen", "es-ES": "Contra"},
}


def translate(text, language):
    if isinstance(text, list):
        return [translate(t, language) for t in text]
    return TRANSLATIONS.get(text, {}).get(language, text)


language = pn.widgets.Select(name="Language", options=LANGUAGES)


@pn.depends(language)
def get_options(language, options=OPTIONS):
    return {translate(option, language): option for option in options}


mode = pn.widgets.Select(
    name=pn.bind(translate, text="Mode:", language=language),
    options=pn.bind(get_options, language=language, options=get_options),
)

pn.Column(language, mode, mode.param.value).servable()
```

```bash
AttributeError: 'function' object has no attribute 'owner'

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/panel/io/handlers.py", line 389, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/mt-devops/script.py", line 30, in <module>
    mode = pn.widgets.Select(
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/panel/widgets/select.py", line 200, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/widgets/select.py", line 78, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/widgets/base.py", line 75, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 560, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/reactive.py", line 120, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/viewable.py", line 700, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/viewable.py", line 539, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/panel/viewable.py", line 300, in __init__
    super().__init__(**params)
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 4187, in __init__
    refs, deps = self.param._setup_params(**params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 1685, in override_initialization
    ret = fn(self_, *args, **kw)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 1970, in _setup_params
    ref, ref_deps, resolved, is_async = self_._resolve_ref(pobj, val)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 2043, in _resolve_ref
    value = resolve_value(value, recursive=pobj.nested_refs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 186, in resolve_value
    value = eval_function_with_deps(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 164, in eval_function_with_deps
    kwargs = {n: getattr(dep.owner, dep.name) for n, dep in kw_deps.items()}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/param/parameterized.py", line 164, in <dictcomp>
    kwargs = {n: getattr(dep.owner, dep.name) for n, dep in kw_deps.items()}
                         ^^^^^^^^^
AttributeError: 'function' object has no attribute 'owner'
```

**Comment by MarcSkovMadsen** [comment]
Seems I made a mistake.

**Comment by philippjfr** [comment]
What was the mistake? It reads okay to me.

**Comment by MarcSkovMadsen** [comment]
I `bind` a `depends` function.
