### ISSUE TITLE
build-docs fails because of missing xserver

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7219]
I was trying to build the docs by running `build-docs`. I get

```bash
Successfully converted examples/gallery/streaming_videostream.ipynb to pyodide-worker target and wrote output to streaming_videostream.html.
/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/pyvista/plotting/plotter.py:159: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``

  warnings.warn(
2024-09-01 04:06:18.005 (   1.726s) [    7F029815D740]vtkXOpenGLRenderWindow.:456    ERR| vtkXOpenGLRenderWindow (0x5579fc8fd490): bad X server connection. DISPLAY=
ERROR:root:bad X server connection. DISPLAY=
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/bin/panel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jovyan/repos/private/panel/panel/command/__init__.py", line 101, in main
    ret = Convert(parser).invoke(args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/command/convert.py", line 113, in invoke
    convert_apps(
  File "/home/jovyan/repos/private/panel/panel/io/convert.py", line 583, in convert_apps
    files = _convert_process_pool(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/io/convert.py", line 483, in _convert_process_pool
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

I'm running on linux inside a docker container on a JupyterHub. Probably something needs to be installed or configured? But what.

A solution or workaround for me to be able to build the docs and work with them would be highly appreciated.

**Comment by MarcSkovMadsen** [comment]
I can see it happens inside `_docs-pyodide`. As VTK cannot run in Pyodide anyways a solution would probably be to skip it from this kind of build.

```bash
 Pixi task (_docs-pyodide in docs): panel convert examples/gallery/*.ipynb doc/how_to/*/examples/*.md --to pyodide-worker --out ./builtdocs/pyodide/ --pwa --index --requirements doc/pyodide_dependencies.json
Successfully converted examples/gallery/altair_brushing.ipynb to pyodide-worker target and wrote output to altair_brushing.html.
Successfully converted examples/gallery/deckgl_game_of_life.ipynb to pyodide-worker target and wrote output to deckgl_game_of_life.html.
Successfully converted examples/gallery/gapminders.ipynb to pyodide-worker target and wrote output to gapminders.html.
Successfully converted examples/gallery/glaciers.ipynb to pyodide-worker target and wrote output to glaciers.html.
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7fe0f1e05620>, 20)
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/holoviews/core/options.py", line 77, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '20' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7fe0f1e05620>, 44)
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/holoviews/core/options.py", line 77, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '44' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
Successfully converted examples/gallery/hvplot_explorer.ipynb to pyodide-worker target and wrote output to hvplot_explorer.html.
WARNING:param.OverlayPlot00361: responsive mode could not be enabled because fixed width and height were specified.
Successfully converted examples/gallery/iris_kmeans.ipynb to pyodide-worker target and wrote output to iris_kmeans.html.
Successfully converted examples/gallery/nyc_deckgl.ipynb to pyodide-worker target and wrote output to nyc_deckgl.html.
Successfully converted examples/gallery/penguin_crossfilter.ipynb to pyodide-worker target and wrote output to penguin_crossfilter.html.
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7f956d4e9620>, 48)
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/holoviews/core/options.py", line 77, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '48' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7f956d4e9620>, 20)
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/holoviews/core/options.py", line 77, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '20' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
Exception ignored in: functools.partial(<function cleanup_custom_options at 0x7f956d4e9620>, 44)
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/holoviews/core/options.py", line 77, in cleanup_custom_options
Exception: Cleanup of custom options tree with id '44' failed with the following exception: 'NoneType' object has no attribute '_options_context', an unreferenced orphan tree may persist in memory.
Successfully converted examples/gallery/penguin_kmeans.ipynb to pyodide-worker target and wrote output to penguin_kmeans.html.
Successfully converted examples/gallery/portfolio_analyzer.ipynb to pyodide-worker target and wrote output to portfolio_analyzer.html.
Successfully converted examples/gallery/portfolio_optimizer.ipynb to pyodide-worker target and wrote output to portfolio_optimizer.html.
/home/jovyan/repos/private/panel/examples/gallery/streaming_videostream.ipynb:244: ParamFutureWarning: Parameter 'video_stream' on <class 'bokeh_app_e3723376ae184654aee683beddde93b9.VideoStreamInterface'> is being given a valid parameter reference VideoStream(design=<class 'panel.theme.materi..., format='jpeg', height=0, name='Video Stream', sizing_mode='fixed', timeout=500, visible=False, width=0) but is implicitly allow_refs=False. In future allow_refs will be enabled by default and the reference VideoStream(design=<class 'panel.theme.materi..., format='jpeg', height=0, name='Video Stream', sizing_mode='fixed', timeout=500, visible=False, width=0) will be resolved to its underlying value . Please explicitly set allow_ref on the Parameter definition to declare whether references should be resolved or not.
  "        self._layout = pn.Row(**params)\n",
WARNING:bokeh.core.validation.check:W-1002 (EMPTY_LAYOUT): Layout has no children: Row(id='p1028', ...)
Successfully converted examples/gallery/streaming_videostream.ipynb to pyodide-worker target and wrote output to streaming_videostream.html.
/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/pyvista/plotting/plotter.py:159: UserWarning: 
This system does not appear to be running an xserver.
PyVista will likely segfault when rendering.

Try starting a virtual frame buffer with xvfb, or using
  ``pyvista.start_xvfb()``

  warnings.warn(
2024-09-01 04:52:01.437 (   1.469s) [    7F472593E740]vtkXOpenGLRenderWindow.:456    ERR| vtkXOpenGLRenderWindow (0x558158cf1060): bad X server connection. DISPLAY=
ERROR:root:bad X server connection. DISPLAY=
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/bin/panel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jovyan/repos/private/panel/panel/command/__init__.py", line 101, in main
    ret = Convert(parser).invoke(args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/command/convert.py", line 113, in invoke
    convert_apps(
  File "/home/jovyan/repos/private/panel/panel/io/convert.py", line 583, in convert_apps
    files = _convert_process_pool(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/io/convert.py", line 483, in _convert_process_pool
    result = future.result()
             ^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by philippjfr** [comment]
Fixed separately by excluding VTK from `panel convert` call.
