### ISSUE TITLE
build-docs errors because of missing firefox or geckodriver

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7220]
I've followed the new developer guide. When I run `docs-build` I see

```bash
Used existing FileDownload thumbnail
getting thumbnail code for /home/jovyan/repos/private/panel/examples/reference/widgets/FileDropper.ipynb
Path exists True
Traceback (most recent call last):
  File "/tmp/tmpgivt71lq", line 67, in <module>
    from nbsite.gallery.thumbnailer import thumbnail;thumbnail(file_dropper, '/home/jovyan/repos/private/panel/doc/reference/widgets/thumbnails/FileDropper')
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/nbsite/gallery/thumbnailer.py", line 133, in thumbnail
    obj.save(basename+'.png')
  File "/home/jovyan/repos/private/panel/panel/viewable.py", line 964, in save
    return save(
           ^^^^^
  File "/home/jovyan/repos/private/panel/panel/io/save.py", line 272, in save
    return save_png(
           ^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/io/save.py", line 85, in save_png
    state.webdriver = webdriver_control.create()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/bokeh/io/webdriver.py", line 180, in create
    driver = self._create(kind, scale_factor=scale_factor)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/bokeh/io/webdriver.py", line 198, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.
FileDropper thumbnail export failed
```

I guess the workaround is to make sure all thumbnails are created. But the real solution would to have pixi install the firefox or geckodriver as a part of the docs installation?

**Comment by philippjfr** [comment]
Going to disable automatic thumbnailing.

**Comment by philippjfr** [comment]
Apparently this is already an option. Will disable in your PR.
