### ISSUE TITLE
Tabulator header_filter raises: TypeError: type.__new__() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7234]
I'm on the current `main` branch of Panel, pandas==2.2.2, numpy==1.26.4

I have a dataframe with categorical values. When I try to filter in the header to a categorical values I get `TypeError`.

I believe this is a regression as I've not experienced this before in my app I've been using for a while.

```python
import panel as pn
import pandas as pd

df = pd.DataFrame({'model': ['A', 'B', 'C', 'D', 'E']})
df['model'] = df['model'].astype('category')

pn.widgets.Tabulator(df, header_filters=True).servable()
```

```bash
Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/bokeh/server/session.py", line 98, in _needs_document_lock_wrapper
    result = await result
             ^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/reactive.py", line 509, in _change_coroutine
    state._handle_exception(e)
  File "/home/jovyan/repos/private/panel/panel/io/state.py", line 464, in _handle_exception
    raise exception
  File "/home/jovyan/repos/private/panel/panel/reactive.py", line 507, in _change_coroutine
    self._change_event(doc)
  File "/home/jovyan/repos/private/panel/panel/reactive.py", line 525, in _change_event
    self._process_events(events)
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 1317, in _process_events
    return super()._process_events(events)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/reactive.py", line 1429, in _process_events
    super(ReactiveData, self)._process_events(events)
  File "/home/jovyan/repos/private/panel/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 1651, in _update_cds
    super()._update_cds(*events)
  File "/home/jovyan/repos/private/panel/panel/util/__init__.py", line 341, in wrapped
    fn(self, *args, **kwargs)
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 329, in _update_cds
    self._processed, data = self._get_data()
                            ^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 1411, in _get_data
    return super()._get_data()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 623, in _get_data
    return self._process_df_and_convert_to_cds(self.value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 627, in _process_df_and_convert_to_cds
    df = self._filter_dataframe(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 480, in _filter_dataframe
    filters.extend(self._get_header_filters(df))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/widgets/tables.py", line 516, in _get_header_filters
    val = col.dtype.type(val)
          ^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() takes exactly 3 arguments (1 given)
```

**Comment by MarcSkovMadsen** [comment]
I tried downgrading `pandas<2.0`. Same problem.

**Comment by MarcSkovMadsen** [comment]
The **workaround** for me is to convert categorical to `object` type.
