### ISSUE TITLE
`ModuleNotFoundError` in Panel Pyodide Site under `1.5.0rc1`

### ISSUE THREAD

**Issue by michaelweinold** [holoviz/panel#7237]
#### ALL software version info

```
panel==1.5.0rc1
```

#### Description of expected behavior and the observed behavior

I was trying to see if the `1.5.0rc1` release of @philippjfr really did solve my previous issue with `panel convert`:

- https://github.com/holoviz/panel/issues/7231#event-14172571936

Unfortunately, the MWE of this issue is now stuck at `ModuleNotFoundError: No module named 'bw2io'`... but only in the "Executing Code" stage - _after_ successfully installing the `bw2io` package.

#### Complete, minimal, self-contained example code that reproduces the issue

See MWE in https://github.com/holoviz/panel/issues/7231#event-14172571936

#### Stack traceback and/or browser JavaScript console output

```
pyodide.asm.js:10 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 412, in run_async
    await coroutine
  File "<exec>", line 13, in <module>
ModuleNotFoundError: No module named 'bw2io'

    at new_error (pyodide.asm.js:10:9965)
    at pyodide.asm.wasm:0x16dc69
    at pyodide.asm.wasm:0x177492
    at _PyEM_TrampolineCall_JS (pyodide.asm.js:10:124082)
    at pyodide.asm.wasm:0x1c2c4c
    at pyodide.asm.wasm:0x2c79ac
    at pyodide.asm.wasm:0x20a621
    at pyodide.asm.wasm:0x1c3339
    at pyodide.asm.wasm:0x1c3648
    at pyodide.asm.wasm:0x1c36c6
    at pyodide.asm.wasm:0x29e6fa
    at pyodide.asm.wasm:0x2a4cf1
    at pyodide.asm.wasm:0x1c3806
    at pyodide.asm.wasm:0x1c346f
    at pyodide.asm.wasm:0x176af6
    at callPyObjectKwargs (pyodide.asm.js:10:62217)
    at Module.callPyObjectMaybePromising (pyodide.asm.js:10:63465)
    at wrapper (pyodide.asm.js:10:27093)
    at Kn.e.port1.onmessage (pyodide.asm.js:10:100342)
```

#### Screenshots or screencasts of the bug in action

<img width="1728" alt="Screenshot 2024-09-08 at 06 59 22" src="https://github.com/user-attachments/assets/c9027067-2bab-4094-98b5-705f7a5a6d3e">

- [x] I may be interested in making a pull request to address this

**Comment by michaelweinold** [comment]
...apparently the pinned version of `bw2data` in `requirements.txt` called for a different version of `bw2io` than what was also pinned.
