### ISSUE TITLE
Panel templates suppress errors shown in debugger widget

### ISSUE THREAD

**Issue by yt87** [holoviz/panel#7327]
Thanks for contacting us! Please read and follow these instructions carefully, then delete this introductory text to keep your issue easy to read. Note that the issue tracker is NOT the place for usage questions and technical assistance; post those at [Discourse](https://discourse.holoviz.org) instead. Issues without the required information below may be closed immediately.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc should be added within the dropdown below.)

<details>
    <summary>Software Version Info</summary>

```plaintext
panel                     1.5.0              pyhd8ed1ab_0    conda-forge     
```    
</details>

#### Description of expected behavior and the observed behavior

The code  in file ``Debugger.ipynb`` executes as expected. When option ``x`` is selected, causing an exception, the exception can be viewed in the debugger. When ``pn.Column`` is replaced by a template (``Debugger1.ipynb``) , the debugger no longer catches that exception.  The console traceback points to an error in ``panel/widgets/debugger.py``, see output below. I tried both ``FastListTemplate`` and ``MaterialTemplate``.

I run the code from command line:

```
panel serve --dev Debugger.ipynb
panel serve --dev --port 5007 Debugger1.ipynb
```
#### Complete, minimal, self-contained example code that reproduces the issue

```python
# Debugger.ipynb
import panel as pn

pn.extension("terminal", console_output="disable")

debug = pn.widgets.Debugger(name="Good Debugger")
selector = pn.widgets.Select(name="options", options=[0, "x", 1], value=0)


def update(value):
    return pn.pane.Str(int(value))

bf = pn.bind(update, selector)
panel_bf = pn.panel(bf)
pn.Column(selector, panel_bf, debug).servable()

# Debugger1.ipynb
import panel as pn

pn.extension("terminal", console_output="disable")

debuger = pn.widgets.Debugger(name="Bad Debugger")
selector = pn.widgets.Select(name="options", options=[0, "x", 1], value=0)


def update(value):
    return pn.pane.Str(int(value))


bf = pn.bind(update, selector)
panel_bf = pn.panel(bf)
pn.template.MaterialTemplate(
#pn.template.FastListTemplate(
    title="debugger", sidebar=[selector], main=[panel_bf, debuger]
).servable()
```

#### Stack traceback and/or browser JavaScript console output
Output from Debugger when `x` is selected:
```
2024-09-26 22:51:16,836 WebSocket connection opened
2024-09-26 22:51:16,837 ServerConnection created
2024-09-26 22:51:23,907 ERROR: panel.reactive - Callback failed for object named 'options' changing property {'value': 'x'} 
Traceback (most recent call last):
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 1106, in eval
    return eval_function_with_deps(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/reactive.py", line 594, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/projects/seaice/apps/Debugger.ipynb", line 13, in update
    "<div id='c7525e69-1313-49a6-bc32-51889cc8871f'>\n",
                    ~~~~~~~^~~
ValueError: invalid literal for int() with base 10: 'x'
2024-09-26 22:51:23,917 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7decc8d2c800>>, <Task finished name='Task-693' coro=<ServerSession.with_document_locked() done, defined at /home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/bokeh/server/session.py:77> exception=ValueError("invalid literal for int() with base 10: 'x'")>)
Traceback (most recent call last):
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/bokeh/server/session.py", line 98, in _needs_document_lock_wrapper
    result = await result
             ^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 509, in _change_coroutine
    state._handle_exception(e)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/io/state.py", line 464, in _handle_exception
    raise exception
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 507, in _change_coroutine
    self._change_event(doc)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 525, in _change_event
    self._process_events(events)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 1106, in eval
    return eval_function_with_deps(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/reactive.py", line 594, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/projects/seaice/apps/Debugger.ipynb", line 13, in update
    "<div id='c7525e69-1313-49a6-bc32-51889cc8871f'>\n",
                    ~~~~~~~^~~
ValueError: invalid literal for int() with base 10: 'x'
```

Output from Debugger1 when `x` is selected:
```
2024-09-26 23:06:02,053 WebSocket connection opened
2024-09-26 23:06:02,053 ServerConnection created
2024-09-26 23:06:11,325 ERROR: panel.reactive - Callback failed for object named 'options' changing property {'value': 'x'} 
Traceback (most recent call last):
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 1106, in eval
    return eval_function_with_deps(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/reactive.py", line 594, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/projects/seaice/apps/Debugger1.ipynb", line 13, in update
    "\n",
          
ValueError: invalid literal for int() with base 10: 'x'
2024-09-26 23:06:11,329 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7561eb03ae40>>, <Task finished name='Task-1174' coro=<ServerSession.with_document_locked() done, defined at /home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/bokeh/server/session.py:77> exception=AttributeError("'NoneType' object has no attribute 'document'")>)
Traceback (most recent call last):
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 462, in _process_events
    self.param.update(**self_params)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2319, in update
    restore = dict(self_._update(arg, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2352, in _update
    self_._batch_call_watchers()
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2546, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 2506, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/param.py", line 1106, in eval
    return eval_function_with_deps(ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/param/reactive.py", line 594, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/projects/seaice/apps/Debugger1.ipynb", line 13, in update
    "\n",
          
ValueError: invalid literal for int() with base 10: 'x'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
          ^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/bokeh/server/session.py", line 98, in _needs_document_lock_wrapper
    result = await result
             ^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 509, in _change_coroutine
    state._handle_exception(e)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/io/state.py", line 464, in _handle_exception
    raise exception
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 507, in _change_coroutine
    self._change_event(doc)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 525, in _change_event
    self._process_events(events)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/reactive.py", line 480, in _process_events
    log.exception(f'Callback failed for object named {self.name!r} {msg_end}')
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 1574, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 1568, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 1022, in handle
    rv = self.filter(record)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/logging/__init__.py", line 858, in filter
    result = f.filter(record)
             ^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/widgets/debugger.py", line 97, in filter
    widget_session_ids = set(m.document.session_context.id
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/miniforge3/envs/seaice/lib/python3.12/site-packages/panel/widgets/debugger.py", line 99, in <genexpr>
    tuple()) if m.document.session_context)
                ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'document'
```
#### Screenshots or screencasts of the bug in action

- [ ] I may be interested in making a pull request to address this

**Comment by yt87** [comment]
It seems templates are not the culprit. This works fine:
```
import panel as pn
pn.extension("terminal", console_output="disable")

def update(value):
    return pn.pane.Str(int(value))

debugger = pn.widgets.Debugger(name="Debugger")
selector = pn.widgets.Select(name="options", options=[0, "x", 1], value=0)
bf = pn.bind(update, selector)
panel_bf = pn.panel(bf)
tabs = pn.Tabs(("Panel", panel_bf), ("Debug", debugger))
pn.template.MaterialTemplate(
    title="Debugger", sidebar=[selector], main=[tabs]
).servable()
```

**Comment by yt87** [comment]
Closing this one, after more investigation, opened #7347 instead.
