### ISSUE TITLE
Preview with Panel broken with notifications turned on

### ISSUE THREAD

**Issue by MP-MaximilianLattka** [holoviz/panel#7380]
#### ALL software version info

<details>
    <summary>Software Version Info</summary>

```plaintext
Python 3.12.7
Panel 1.5.2 (still working on 1.4.5)
```
</details>

#### Description of expected behavior and the observed behavior

Using the "Preview Notebook with Panel"/"Open with Panel in New Browser Tab" feature in combination with `pn.extension(notifications=True)` is working with older panel versions such as 1.4.5, but results in an "Kernal error" using more recent versions, such as 1.5.2.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel as pn
pn.extension(notifications=True)
template = pn.template.BootstrapTemplate()
template.servable();
```

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):
  File "/home/USER/workspace/test/panel_bug/panel_bug.ipynb", line 22, in <module>
    }
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/pyviz_comms/__init__.py", line 64, in __new__
    return param.ParameterizedFunction.__new__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/param/parameterized.py", line 4468, in __new__
    return inst.__call__(*args,**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/panel/config.py", line 849, in __call__
    load_notebook(
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/panel/io/notebook.py", line 409, in load_notebook
    bundle = bundle_resources(
             ^^^^^^^^^^^^^^^^^
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/panel/io/resources.py", line 409, in bundle_resources
    css_files.extend(css_resources.css_files)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/panel/io/resources.py", line 715, in css_files
    self.extra_resources(files, '__css__')
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/panel/io/resources.py", line 645, in extra_resources
    resource = component_resource_path(model, resource_type, resource)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/workspace/test/panel_bug/.venv/lib/python3.12/site-packages/panel/io/resources.py", line 261, in component_resource_path
    rel_path = os.fspath(resolve_custom_path(component, path, relative=True)).replace(os.path.sep, '/')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

- [x] I may be interested in making a pull request to address this

**Comment by MP-MaximilianLattka** [comment]
Latest working Panel version: 1.4.5

Earliest non-working Panel version: 1.5.0

**Comment by MP-MaximilianLattka** [comment]
In `panel/io/resources.py`->`component_resource_path` there was a breaking change:
https://github.com/holoviz/panel/commit/15a8241a00ac35e883bc4aa4563d9a82b642b6f8#diff-b9e0d8d8a08aa2a99e2444fcaa4235581abf746cbd6dcc93e1b36c1be79c9cceL261-R261

`resolve_custom_path` may return `None` and it does in the minimal example above. Casting it to `str` was fine (resulting in `"None"`), but `os.fspath` is not happy with `None` and raises the Exception.
