### ISSUE TITLE
Cannot sync date and time widgets to url

### ISSUE THREAD

**Issue by electrophys** [holoviz/panel#7386]
panel 1.5.2

URL syncing does not working for date and time widgets.

```python
import datetime as dt
import panel as pn

pn.extension()

test_widget = pn.widgets.DatetimePicker(
    name='Datetime Picker', value=dt.datetime(2021, 3, 2, 12, 10)
)

pn.state.location.sync(test_widget, parameters=["value"])

pn.template.FastListTemplate(
    title="Sync a Time-based widget and the url parameters",
    main=[test_widget]
).servable()

```

Does not update the URL when the widget value changes.

```python
import datetime as dt
import panel as pn

pn.extension()

test_widget = pn.widgets.DatetimeRangeInput(
    name='Datetime Range Input',
    start=dt.datetime(2017, 1, 1), end=dt.datetime(2019, 1, 1),
    value=(dt.datetime(2017, 1, 1), dt.datetime(2018, 1, 10)),
    width=300
)

pn.state.location.sync(test_widget, parameters=["value"])

pn.template.FastListTemplate(
    title="Sync a Time-based widget and the url parameters",
    main=[test_widget]
).servable()
```

causes an exception:

```python
2024-10-09 18:28:58,404 Error running application handler <panel.io.handlers.ScriptHandler object at 0x7f94d4365350>: Object of type datetime is not JSON serializable
File 'encoder.py', line 180, in default:
raise TypeError(f'Object of type {o.__class__.__name__} ' Traceback (most recent call last):
  File "/usr/local/python/3.11.7/lib/python3.11/site-packages/panel/io/handlers.py", line 405, in run
    exec(self._code, module.__dict__)
  File "/workspaces/stratolaunch-data-eng-pipelines/ui/test.py", line 13, in <module>
    pn.state.location.sync(test_widget, parameters=["value"])
  File "/usr/local/python/3.11.7/lib/python3.11/site-packages/panel/io/location.py", line 267, in sync
    v = json.dumps(v)
        ^^^^^^^^^^^^^
  File "/usr/local/python/3.11.7/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.7/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.7/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.11.7/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

- [x] I may be interested in making a pull request to address this

**Comment by hyamanieu** [comment]
A potential solution is to serialize and do it at load:

```python
if pn.state.location:
            date_params = ["value"]
            with param.parameterized.batch_call_watchers(self):
                param_setter = {}
                for d in date_params:
                    if d in pn.state.session_args:
                        param_setter[d] = dt.datetime.fromisoformat(
                            pn.state.session_args.get(d)[0].decode()
                        ).date()
                self.param.set_param(**param_setter)
            pn.state.location.sync(
                self,
                date_params,
            )
```
Note self is in this case your widget (any child of `param.Parameterized`).
You may need to adapt how the list `date_params` is used for range as in this case it's a tuple of datetimes, not a datetime.
