### ISSUE TITLE
Panel Preview not working: KeyError

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7433]
I'm working on upgrading our jupyterhub and Panel. In our existing setup the Jupyter Panel Preview is working. But not in the new setup.

## Steps

- Log into Jupyter
- Open Notebook
- Select `base` environment
- Create notebook with widget and make it .servable(). (With just display  like `pn.panel('hello').servable()` there is no problem.)
- Click the Panel Preview button
- See that the preview does not show anything and that there is an error in the browser console.

![image](https://github.com/user-attachments/assets/8c56e28d-5d37-4742-a603-606745839551)

Check the server logs

```bash
2024-10-23 11:41:32,007 - ServerApp - ERROR - Uncaught exception GET /mt-fumo/user/masma/panel-preview/render/test.ipynb/ws (10.86.100.104)
HTTPServerRequest(protocol='https', host='mnr-jupyterhub-dev.de-prod.dk', method='GET', uri='/mt-fumo/user/masma/panel-preview/render/test.ipynb/ws', version='HTTP/1.1', remote_ip='10.86.100.104')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/tornado/websocket.py", line 940, in _accept_connection
    await open_result
  File "/opt/conda/lib/python3.11/site-packages/panel/io/jupyter_server_extension.py", line 392, in open
    kernel_info = state._kernels[self.session_id]
                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'XKRUSRxzKSS076zhAKRFPD2dUhH9z29fFg8TLcjZNv9r'
```

**Comment by philippjfr** [comment]
Reading the code I really struggle to see how this is possible UNLESS the websocket connection takes >30 seconds to open. Can you confirm how quickly this happens?

**Comment by MarcSkovMadsen** [comment]
Thanks so much for responding. The preview opens and closes the web socket almost instantanously.


https://github.com/user-attachments/assets/8f481b01-1404-4160-9527-4fc3eeab915f

**Comment by MarcSkovMadsen** [comment]
As I see it `self.close()` must have run for some unknown reason:

![image](https://github.com/user-attachments/assets/2baca037-1559-4a50-b0e9-f19b5cf86630)

**Comment by MarcSkovMadsen** [comment]
Right now my hypothesis is that token/ session_id is not valid due to the xrsf cookie issue https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3422 mentioned. I don't know if its related.

**Comment by philippjfr** [comment]
I'm fairly certain those are unrelated issues, the token is transmitted as part of the websocket headers so that seems unlikely to be affected by any cookie issues. Also the token clearly can be decoded since it doesn't error on the `get_session_id` call.

**Comment by MarcSkovMadsen** [comment]
> I'm fairly certain those are unrelated issues, the token is transmitted as part of the websocket headers so that seems unlikely to be affected by any cookie issues. Also the token clearly can be decoded since it doesn't error on the `get_session_id` call.

My understanding from reading the issue is that it is in fact a headers issue:

![image](https://github.com/user-attachments/assets/8e945a0c-8d5e-44d5-b79e-07433addb9e3)

**Comment by MarcSkovMadsen** [comment]
FYI. **It works locally**:

![image](https://github.com/user-attachments/assets/79aa6a0b-c9a6-476c-99c9-427c1a60f3b3)

**Comment by MarcSkovMadsen** [comment]
An additional comment is that we've mixed a helm chart v 3.3.8 for installing Jupyterhub App. version 4.1.6 with installing the jupyterhub 5.2.1. We will try to align these.

**Comment by MP-MaximilianLattka** [comment]
As a sidenote, keep in mind that the Preview feature is also broken with notifications turned on:

https://github.com/holoviz/panel/issues/7380

**Comment by MarcSkovMadsen** [comment]
My colleagues also mentions https://github.com/holoviz/panel/issues/7039 as something that might be related.

**Comment by MarcSkovMadsen** [comment]
Status Update on our findings:

Panel preview can show but not work fully initially. When we refresh it does not show and there is some websocket issue.

## Works

Our updated Jupyter image works with Panel preview when

- deployed locally on a docker desktop 
- deployed as a stand alone container on our kubernetes cluster

## Does not work

- When scheduled by the Jupyterhub by the proxy.

## Details

We tried both helm charts marked below

![image](https://github.com/user-attachments/assets/1e320f1a-3df6-4245-800a-261cc401211b)

from https://hub.jupyter.org/helm-chart/.

We tried the docker images `quay.io/jupyter/minimal-notebook:python-3.12`, `jupyter/minimal-notebook:python-3.11.6`, `quay.io/jupyter/minimal-notebook:ubuntu-22.04`.

We also tried our original docker image (which is also `jupyter/minimal-notebook:python-3.11.6`) and it works with the latest helm chart. The difference is that even though the base docker image has the same name, the operating system has been updated in the mean while.

**Comment by MarcSkovMadsen** [comment]
When we open the preview the web socket is connect. When we refresh the connection is lost

![image](https://github.com/user-attachments/assets/24436c1e-dd10-40c8-9863-f4aa058f4040)

When we refresh the connection is lost again with the session session id/ token. Should we see the same token @philippjfr ?

![image](https://github.com/user-attachments/assets/232b3ae5-2689-4e5a-9c3e-1afc9086d44c)

**Comment by MarcSkovMadsen** [comment]
Just tried again. I can open the preview - but not refresh. During refresh the websocket connection is lost.

https://github.com/user-attachments/assets/55fdaacf-d2fd-448e-993f-cd315beaa743
