### ISSUE TITLE
Failed to build panel extension for jupyterlab

### ISSUE THREAD

**Issue by travis23** [holoviz/panel#766]
My goal is to use panel with jupyterlab on python 3.7. I followed the installation instructions at https://panel.pyviz.org/, but the installation process did not complete the install.

Per the instructions, at an anaconda prompt I ran

`conda install -c conda-forge jupyterlab`

That completed with no problems. 

At the anaconda prompt I entered 

`jupyter labextension install @pyviz/jupyterlab_pyviz`.

The response was
`
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  C:\Users\[user]\AppData\Local\Temp\jupyterlab-debug-9s40h598.log
 `
The behavior I expected was a message indicatating that the build was successful.

OS: Windows 10
Browser: Chrome

#### Versions of possibly relevant packages
Python 3.7.4
jupyterlab 1.2.0
jupyter_client 5.3.4
jupyter_core 4.6.0
jupyterlab_server 1.0.6
panel 0.6.4
notebook 6.0.1
bokeh 1.3.4
param 1.9.2

The contents of the log file are below.

#### jupyterlab-debug-9s40h598.log

```
Yarn configuration loaded.
Node v10.13.0

> C:\Users\[user]\Anaconda3\envs\py37\npm.CMD pack @pyviz/jupyterlab_pyviz
npm notice 
npm notice package: @pyviz/jupyterlab_pyviz@0.8.0
npm notice === Tarball Contents === 
npm notice 1.3kB package.json         
npm notice 1.5kB LICENSE.txt          
npm notice 2.2kB README.md            
npm notice 64B   lib/index.d.ts       
npm notice 151B  lib/index.js         
npm notice 556B  lib/manager.d.ts     
npm notice 1.4kB lib/manager.js       
npm notice 0     lib/panel_widget.d.ts
npm notice 0     lib/panel_widget.js  
npm notice 587B  lib/plugin.d.ts      
npm notice 1.5kB lib/plugin.js        
npm notice 1.9kB lib/renderer.d.ts    
npm notice 9.5kB lib/renderer.js      
npm notice 419B  lib/widgets.d.ts     
npm notice 5.6kB lib/widgets.js       
npm notice === Tarball Details === 
npm notice name:          @pyviz/jupyterlab_pyviz                 
npm notice version:       0.8.0                                   
npm notice filename:      pyviz-jupyterlab_pyviz-0.8.0.tgz        
npm notice package size:  7.7 kB                                  
npm notice unpacked size: 26.7 kB                                 
npm notice shasum:        8422d3456e97e4ab1aa000e10b269ac5a422f336
npm notice integrity:     sha512-uSMn7zzWrTmQk[...]gMd2IWJbrb+cQ==
npm notice total files:   15                                      
npm notice 
pyviz-jupyterlab_pyviz-0.8.0.tgz

Yarn configuration loaded.
Node v10.13.0

Building jupyterlab assets (build:prod:minimize)
> node C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.55s.

> node C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\staging\yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ C:\Users\[user]\Anaconda3\envs\py37\share\jupyter\lab\staging\node_modules\.bin\yarn-deduplicate -s fewer
Done in 0.52s.

> node C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\staging\yarn.js run build:prod:minimize
yarn run v1.15.2
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
child_process.js:632
    throw err;
    ^

Error: spawnSync webpack ENOENT
    at Object.spawnSync (internal/child_process.js:982:20)
    at spawnSync (child_process.js:596:24)
    at Object.execFileSync (child_process.js:624:13)
    at Object.<anonymous> (C:\Users\[user]\Anaconda3\envs\py37\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\ensure-max-old-space.js:30:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "C:\Users\[user]\Anaconda3\envs\py37\lib\site-packages\jupyterlab\commands.py", line 669, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by ceball** [comment]
I _think_ this is unrelated to panel: see https://github.com/jupyterlab/jupyterlab/issues/7425, where there appears to be a resolution.
